### ISSUE TITLE
I am trying to build the following query using query builder:

### ISSUE THREAD

**Issue by veerareddy123** [typeorm/typeorm#1006]
My raw sql query is like this:

select user_id AS USER, sum(mins) AS MINS from attendance where user_id="J7IZ3YXX" and updated_date between '2017/09/18' and '2017/09/20';

and my querybuilder is:

const QueryBuilder :any=this.dao.createQueryBuilder("attendance");
      QueryBuilder.select("attendance.sum(mins) AS MINS, attendance.user_id AS USER")
      QueryBuilder.where("attendance.user_id =:J7IZ3YXX")
      QueryBuilder.andWhere("updated_date BETWEEN :startDate AND :endDate, {'2017/09/18', '2017/09/20'}")
     .getMany();

after seeing the rsult it is saying that userid is undefined

**Comment by daniel-lang** [comment]
You have a couple of errors in your code.
1. the alias for the table has to be inside of `SUM()` like `SUM(attendeance.mins)`
2. the parameters in your where part won't work since you don't have a parameter called `J7IZ3YXX` and at the second where the object that defines your parameters is part of the where clause and doesn't have keys
3. You can't you `getMany()` because you don't select a full entity. You have to use `getRawMany()`

Your corrected query builder code would look like this:
```typescript
const QueryBuilder = this.dao.createQueryBuilder("attendance");
QueryBuilder.select("sum(attendance.mins)", "mins")
QueryBuilder.addSelect("attendance.user_id", "user");
QueryBuilder.where("attendance.user_id = :id", {id: "J7IZ3YXX"});
QueryBuilder.andWhere("updated_date BETWEEN :startDate AND :endDate", {startDate: '2017/09/18', endDate: '2017/09/20'});
const users= await QueryBuilder.getRawMany();
```
if `this.dao` the the repository for the `attendance` table, this code will generate
```sql
SELECT
   sum(attendance.mins) AS mins,
   attendance.user_id AS user
FROM attendance attendance
WHERE attendance.user_id = ? AND updated_date BETWEEN ? AND ?
-- PARAMETERS: ["J7IZ3YXX","2017/09/18","2017/09/20"]
```
and return an array with that looks like this
```json
[
   { "user": 1, "mins": 12 },
   { "user": 2, "mins": 5 }
]
```

As a sidenote: you don't have to save the querybuilder. You code could also look like this:
```typescript
users = await this.dao.createQueryBuilder("attendance");
                      .select("sum(attendance.mins)", "mins")
                      .addSelect("attendance.user_id", "user")
                      .where("attendance.user_id = :id", {id: "J7IZ3YXX"})
                      .andWhere("updated_date BETWEEN :startDate AND :endDate", {startDate: '2017/09/18', endDate: '2017/09/20'})
                      .getRawMany();
```
or even
```typescript
users = await this.dao.createQueryBuilder("attendance");
                      .select("sum(attendance.mins) as mins, attendance.user_id as user")
                      .where("attendance.user_id = :id and updated_date BETWEEN :startDate AND :endDate", {id: "J7IZ3YXX", startDate: '2017/09/18', endDate: '2017/09/20'})
                      .getRawMany();
```

**Comment by veerareddy123** [comment]
Thanks Daniel I will try once and let me know the status

**Comment by pleerock** [comment]
@veerareddy123  any updates?

**Comment by pleerock** [comment]
Closing as no answer from reportee.
