### ISSUE TITLE
Serialization & Circular Dependencies 

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#1060]
Im trying to use the 'cerialize' library alongside TypeORM

There seems to be a circular dependency when declaring one-to-many / many-to-one relationships

Seeing as both classes will have a dependency on the other - it causes other libraries that use reflection to fail

https://github.com/weichx/cerialize/issues/22#issuecomment-223018469

The best example of this would be here:
https://github.com/typeorm/typeorm/blob/master/sample/sample3-many-to-one/entity/Post.ts
https://github.com/typeorm/typeorm/blob/master/sample/sample3-many-to-one/entity/PostAuthor.ts

Any advice on a work around?

**Comment by pleerock** [comment]
This issue is not related to typeorm. Its how javascript works and you probably cant do anything here. Thats why typeorm does not rely on reflection of property types and you HAVE to define a type, e.g. :

```ts
@ManyToOne(type => Author)
author: Author;
```

We could do simply:

```ts
@ManyToOne()
author: Author;
```

But this may bring us problems on circular references and we decided to always use "type". Your library should follow same semantics. This is implemented in class-transformer library as well.

**Comment by rightisleft** [comment]
Hard linking for future reference:
https://github.com/pleerock/class-transformer
