### ISSUE TITLE
reference models from a different project

### ISSUE THREAD

**Issue by theigor** [typeorm/typeorm#1062]
Hi,

I have a project with typeorm in typescript which has all the models in a `./models` directory. What I want to do is be able to export the model definitions so I can use it in a different peer project.

Is there a suggested way to do this?

Here's what I did
1. Add a project.json to the source directory (with the typescript files)
2. `npm install --save ..\project\models\`
3. But now vscode is telling me it can't find the module when i try to reference it like `import SomeModel from "project-models";` even though `project-models` is present in `node-modules`

What occurred to me also is that even if this were to work, I'd need to enable the experimental decorators in the main project and I am not sure what will happen? Would I need to require typeorm as well? I don't need typeorm in the main project - I just want model definitions.

Thanks!

**Comment by pleerock** [comment]
> But now vscode is telling me it can't find the module when i try to reference it like import SomeModel from "project-models"; even though project-models is present in node-modules

But do you you have typescript `d.ts` files inside "project-models"? Because you need them to make things work. If you don't then seek for solution in typescript itself. Your issue is not related to typeorm somehow. 

> even if this were to work, I'd need to enable the experimental decorators in the main project and I am not sure what will happen? Would I need to require typeorm as well? I don't need typeorm in the main project - I just want model definitions.

of course you'll have them. Its the same you would use lets say `fs.writeFile` and then complaining that you have this code in the generated model while you don't have `fs` in some other environment. But there is a solution. You can use this [shim](https://github.com/typeorm/typeorm/blob/master/extra/typeorm-model-shim.js) and configure your webpack/systemjs/typescript to map "typeorm" namespace into this file. This way you won't have compiler errors.

**Comment by theigor** [comment]
For future people, I got this working by adding a package.json to the type output in the main application and imported the types as a package in the app that has the model dependency.
