### ISSUE TITLE
When we can expect cascade remove 

### ISSUE THREAD

**Issue by harishajdarevic** [typeorm/typeorm#1093]
Hello, 

We know that cascade remove is currently removed, but we want to check do you have any information when we can expect that functionality?

**Comment by pleerock** [comment]
cascade remove will be removed completely in `0.2.0` because of:

* complexity it brings (the most complex part of orm, almost unmaintainable)
* functionality brings lot of unexpected deep bugs
* brings confusion to users between cascade remove or database-level cascades 
* can bring too much implicit magic to users

What use instead? Use database-level remove, e.g. `onDelete: "SET NULL"` or `onDelete: "CASCADE"`

**Comment by xmlking** [comment]
Please remove `remove` option for cascade = [‘insert’, ‘update’, ‘remove’] type definition
