### ISSUE TITLE
Is the repository no longer maintained?

### ISSUE THREAD

**Issue by 0x0bit** [typeorm/typeorm#10973]
Currently, the repository has more than 2,000 issues, the last update was 6 months ago, what do you use now and what do you recommend?

**Comment by bruceharrison1984** [comment]
I'm wondering as well. 

I'm currently using DrizzleORM, and while it works IMHO the DX doesn't feel as smooth as TypeORM. I was thinking of creating a D1 database driver, but if I had to make any changes the base library I feel like they'd never be merged in.

**Comment by fzn0x** [comment]
PRs even getting no reviews

**Comment by MrYbo** [comment]
> 我也很感激。
> 
> 我建议使用 DrizzleORM，虽然它可以工作，但我认为 DX 效果不如 TypeORM 流畅。我曾考虑创建一个 D1 数据库驱动程序，但如果我必须对基础库进行任何更改，我觉得它们永远不会合并。

@bruceharrison1984 It was nice to get to know [MikroORM](https://mikro-orm.io/)

**Comment by w3nl** [comment]
Looks like this package is indeed not maintained active anymore.
I also have open a [PR](https://github.com/typeorm/typeorm/pull/10802) for a long time, no responses, also no responses on the email.
I think I would also move to another package or fork this package, since there is no active maintenance and no responses from the original developers.

**Comment by giosueDelgado** [comment]
Hi guys, hope this can be a good news:
https://github.com/typeorm/typeorm/issues/3267#issuecomment-2228099642

**Comment by stim371** [comment]
Here's the announcement about this project being taken on by new maintainers: https://typeorm.io/future-of-typeorm#

If you'd like to join the effort, or have tech questions, pop into the Discord! 

https://discord.gg/cC9hkmUgNa
