### ISSUE TITLE
feat request: define the Column type with constant

### ISSUE THREAD

**Issue by axetroy** [typeorm/typeorm#1103]
```typescript
import {Entity, Column, PrimaryGeneratedColumn, Type} from "typeorm";

@Entity()
export class Photo {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({
        length: 100
    })
    name: string;

    @Column(Type.TEXT) // @Column("text")
    description: string;

    @Column()
    filename: string;

    @Column(Type.DOUBLE)  // @Column('double')
    views: number;

    @Column()
    isPublished: boolean;
}
```

**Comment by pleerock** [comment]
What is the purpose of this feature request?

**Comment by axetroy** [comment]
@pleerock 

1. save memery, no need to declarate type string many times. only reference memery
2. unified type, in case of you change the type string, it will not bring breaking change

**Comment by pleerock** [comment]
We had `ColumnTypes` before, until TypeORM started to support database-specific column types. Now when we support all database-specific types this feature request seems doubtful to me.

1. not sure if I completely understand what you mean here

2. I'll hardly change something since its a direct name of the database column type. I think I even don't check anything - just directly pass this type into the SQL query

3. Yes we could apply a string literal types instead of class with constants, however this is pointless as well. Since user can use then `shape` column type which is only supported in postgres. Or user could use `boolean` which is not supported by mysql

**Comment by pleerock** [comment]
I'll close this issue for now, let me know if you have something to add
