### ISSUE TITLE
Why does typeorm rename relation columns in database?

### ISSUE THREAD

**Issue by emorris00** [typeorm/typeorm#1108]
```javascript
@Entity()
class TestEntity {
    @PrimaryGeneratedColumn()
    id: number

    @Column()
    test_column: string

    @OneToMany(type => TestEntity2, 'test')
    test_relation: TestEntity2
}
```

In the database the test_entity table columns will be named id, test_column, and testRelationId.
It didn't change the name of the column in v0.0.11, is there a reason the behavior changed?

**Comment by shroudedcode** [comment]
@emorris00 I don't know the reason for sure, but I think it's because when you think of `TestEntity` as a class and you have an instance of it, you expect `test_relation` to return a `TestEntity2` and not a `Number` (ID). With the new behavior, this is now consistent across the actual table and the TypeORM representation.

Oh, and please:
- Name variables (or properties in this case) the "JavaScript way", `testColumn` instead of `test_column`.
- Don't put `relation` inside the name of a property with a relation. `BlogPost.authorRelation` doesn't return an `AuthorRelation`, it returns an `Author`, so calling it `author` makes more sense.
- Do not use a string for the `inverseSide` of a `OneToMany` relation, it's more error-prone.

**Comment by pleerock** [comment]
Lot of things are changed since 0.0.11. 

If it generates you a `testRelationId` name it looks like a bug. It actually should generate you `test_relationId`. But not `test_relation` anymore. Why? Because now typeorm supports working with relations which point to multiple columns, for example to `id` and `name` of the TestEntity2 entity. Thats why we now need to put referenced column name at the end of foreign column name. So, we'll have testRelationId and testRelationName columns

**Comment by emorris00** [comment]
Ah, that makes sense. Thanks.

**Comment by matejbizjak** [comment]
You can use `@JoinColumn` anotation to specify column's name in a database.

Example:
`@ManyToOne(type => Role)`
`@JoinColumn({name: "role_id"})`
`roleId: Role;`

Read more [here](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#joincolumn-options).

**Comment by lucasMarques0605** [comment]
> You can use `@JoinColumn` anotation to specify column's name in a database.
> 
> Example:
> `@ManyToOne(type => Role)`
> `@JoinColumn({name: "role_id"})`
> `roleId: Role;`
> 
> Read more [here](https://github.com/typeorm/typeorm/blob/master/docs/relations.md#joincolumn-options).

You saved me! thank u.
