### ISSUE TITLE
AfterRemove() decorator not working on removeById()

### ISSUE THREAD

**Issue by MahBoy** [typeorm/typeorm#1137]
My database currently has an image entity with just an ID and a path. To ensure the removal of the image file upon deletion from the database, I added an AfterRemove() decorator to the entity as follows:
```js
@AfterRemove()
public async afterRemove() {
    await DeleteFileIfExistsAsync(`${ImagesFolder}${this.path}`);
}
```

However, when trying to delete an image using 
```js
await this.imageRepository.deleteById(id)
```
the AfterRemove() decorator will not be called.

On the other hand, using
```js
await this.imageRepository.remove(await this.imageRepository.findOneById(id));
```
works just as wanted.

Is this the intended behaviour or am I missing some information on the decorator I failed to read?

**Comment by pleerock** [comment]
`deleteById` is primitive at the moment. This behaviour will be changed in 0.2.0 and listeners will be called on deleteById method call as well.

**Comment by pleerock** [comment]
Okay so after deeper investigation on this question I'll answer same as in #1173 :

subscribers and listeners are very tricky. Lets say we have a post model with listeners applied:

```ts
@Entity()
export class Post {
     ....
     @AfterRemove()
     afterRemove() {
           this.counter += 1;
     }
}
```

When you are calling `deleteById(id, updateMap)` by id it does roughly following:

```ts
updateById(id, updateMap) {
   return createQueryBuilder()
     .delete()
     .from(Post)
     .where({ id: id })
     .execute();
}
```

What this query builder does - it builds `DELETE post WHERE id = :id` and executes it. That's all. There is no entity which method can be called, e.g. to call this listener we need to do `post.afterRemove()` because there is no `post` instance anywhere in this method.

Those methods (delete, update, query builders) must be used when you want to execute quick query without extra checks and queries. `save` and `remove` methods do much more, and they cover all functionality typeorm has. So, you must use them instead.
