### ISSUE TITLE
Syntax error on @entity 

### ISSUE THREAD

**Issue by tamannaizap** [typeorm/typeorm#1184]
am getting this error... I installed all of the dependencies properly... plz help if you can

SyntaxError: src/entity/photo.js: Unexpected token (3:0)
  1 | import {Entity, Column, PrimaryGeneratedColumn} from "typeorm";
  2 |  
> 3 | @Entity()
    | ^
  4 | export class Photo {
  5 |  
  6 |     @PrimaryGeneratedColumn()
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trial@1.0.0 start: `babel src --out-dir dist && node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trial@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dixit/.npm/_logs/2017-11-15T10_01_19_701Z-debug.log

**Comment by pleerock** [comment]
@tamannaizap Im closing this issue because of inappropriate behaviour from your side. Please do not spam same issue you have in 10000 places even in unrelated places. Your problem is most likely with babel configuration or versions. Investigate more and try to find a solution for your issue and please don't spam everywhere anymore.
