### ISSUE TITLE
Repository.findOneById(id) resolves promise with an undefined object in case of non-existing id

### ISSUE THREAD

**Issue by szepeshazi** [typeorm/typeorm#122]
```
import {createConnection} from "typeorm";

createConnection(/*...*/).then(connection => {
	let photoRepository = connection.getRepository(Photo);
	photoRepository.findOneById(1000) // non-existent id in storage
	.then(function(photo) {
		// Promise will be resolved for the above id
		console.log(photo); // undefined
	})
	.catch(function(error) {
		// Promise does not get rejected, execution never gets here
		console.log(error);
	});
}).catch(error => console.log(error));
```

This may be so by design (not a bug, but feature :) - but I was expecting that the promise would be rejected in such cases.

**Comment by pleerock** [comment]
it is be design. Rejecting here would be inappropriate. Rejecting is like a throwing an exception. In this case there is no error, simply nothing match your request.

**Comment by hmil** [comment]
Sorry for unearthing this one but I believe this point is worth debating further. 

Consider the code below:

```typescript
@Get("/topic/:id")
async topic(@Param("id") id: string) {
    return some_view({
        topic: await this.topicRepository.findOneById(id) // Type error, undefined cannot be assigned to Topic
    });
}
```

With the current behavior of findOneById, I need boilerplate runtime type checking. For instance:

```typescript
@Get("/topic/:id")
async topic(@Param("id") id: string) {
    return topic({
        topic: await this.topicRepository.findOneById(id).then(topicOrUndef => {
            if(!topicOrUndef) {
                throw new NotFoundError();
            } else {
                return topicOrUndef
            }
        })
    })
}
```

Laravel has `findOrFail` which behaves like my hack above. It is semantically clean because indeed I was looking for something and couldn't find it, hence 404 not found. Moreover it helps keeping a code focused on the happy path, therefore you get a cleaner code. I think it's worth considering adding such feature to the API, what do you think?

**Comment by pleerock** [comment]
lets say we throw an exception, but you'll need to catch it anyway to provide a proper message to a client, aren't you?

**Comment by pleerock** [comment]
usually I do it this way:

```ts
@Get("/topic/:id")
@OnUndefined(404)
async topic(@Param("id") id: string) {
    return this.topicRepository.findOneById(id);
}
```

But your case is more complex since it requires error to be thrown in another block...

**Comment by hmil** [comment]
Indeed I see your use case now.
I'm experimenting with ways to bring typescript's type system down to the view layer (along with type safety, auto-completion and all the good stuff). In this case, having a `findOrFail` method makes lots of sense because 1. We don't want to have explicit `undefined` checks all over the view template, 2. If there is no object, then most of the time it means the view cannot be rendered and instead we will want to display a generic 404.

If you want to learn more, my work is on [this repository](https://github.com/hmil/topside). I think it would work well with the amazing work you did on typeorm, routing-controllers and typedi to provide a TypeScript alternative to Laravel, Play! and co.

Let me know if you'll consider the `findOrFail` API, I could sketch a PR for it.

**Comment by pleerock** [comment]
Okay, I think we can add it. Please name it `findOneOrFail`. Also, `findOneById` is deprecated and will be removed in next versions. Instead `findOne(id)` syntax is used now, so it means we don't need `findOneByIdOrFail` which is good.
