### ISSUE TITLE
Running migrations on MS SQL db tries to create the migrations table on every run

### ISSUE THREAD

**Issue by kenpederson** [typeorm/typeorm#1254]
I am trying to use typeorm as the orm for my node project. When I run my initial sync, all of my tables are created fine. I then create a migration and run it without issue (table updates made, migration table created, migration entry added). Now I am trying to run a second migration and I am receiving the following error:

> QueryFailedError: RequestThere is already an object named 'migrations' in the database.

Why is typeorm trying to create the migration table again if it already exists from being created during the last migration? I am guessing there is a bug in the createMigrationsTableIfNotExist function of the MigrationExecutor?

**Comment by PJCAfonso** [comment]
Hi 
TypeOrm really has helped speed up my development, you guys are doing a great job, but you that used Django up to now, are feeling some problems with migrations, because there all stuff of changes on code versus database, implement the scripts very well.
 
We are using _TYPEORM 0.2.9 and MSSQL 4.2.3_. All the changes we made over entity files, typeorm migration try all the time create a new table. Since add new column, change name of column, add new relations, etc, etc,

We are analised this and we are worry because when our platform go to market, and few month later we want to implement new feature, how can we update all update on database?

Please tell us, **"we are doing migrations wrong!"**, and we do not need to manually write all changes we do on code versus database?

Once again guys greate tool.

**Comment by havenchyk** [comment]
@PJCAfonso could you please create a new issue with some example?

**Comment by osnersanchez** [comment]
I am having this same problem when generating a second migration
