### ISSUE TITLE
Is there way to add some kind of "Hey types are not available mister" when you do not import "reflect:metadata" first when using orm?

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#1258]
It's a tricky thing I have in the back of my mind just out of the experience.
Often, working with IDE - there will be error about "undefined" column type not supported in entity (also thank you for implementing column name in this error, I was on the old version and wanted to do PR for this but it was already here in the new version!). Often problem with not importing "reflect:metadata". Why I mentioned IDE? After writing more code, IDE could auto-import something and place it above importing reflect metadata, thus making situation hard to understand - why of the sudden this error.

**Comment by pleerock** [comment]
There is a small problem. TypeORM also works in JavaScript. And when you use it with JavaScript you don't need reflect-metadata at all. If we implement this we'll force to install reflect-metadata for non-typescript users when they don't really need it. But I think we can do it.

I was also thinking to make reflect-metadata direct typeorm dependency, but Im not sure what problems this can bring since reflect-metadata is a shim, and usually people does not provide shims with their packages.

**Comment by idchlife** [comment]
Hmm... How about adding 2 pieces of information to error message? If that's possible.

Thinking of this error message I remember that there is also no clarification so far if you are using custom type for field, making it undetectable by reflection (I assume that's the problem).

Is it will be too much adding much more information to the error itself? Like tips on what caused it:
If you are on TS you may forgotten to import reflect:metadata
Also you may have custom typed column, so explicit type should be added as argument
You did not provide type so it can not be guessed

**Comment by pleerock** [comment]
Ah okay I got you. Probably we can add such error.

**Comment by pleerock** [comment]
Now `import "reflect-metadata"` is included in the typeorm and users should not include it anymore theoretically. Let's see how it will work them
