### ISSUE TITLE
[feture request] provice an cli option to ignore timestamp check on "migrations:run"

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1315]
sometimes migrations will be created by diffrent teamates or diffrent git branches.

**Comment by pleerock** [comment]
In what order they should be run then?

**Comment by xujif** [comment]
@pleerock  like [laravel eloquent ](https://github.com/illuminate/database) . it just migrate files whitch has not been migrated order by timestamp.

**Comment by xujif** [comment]
I suggest to add an option like '--force' to ignore the timestamp check.

**Comment by pleerock** [comment]
wait, if ignore will be ignored then in what order they will be run?

**Comment by xujif** [comment]
Also run the un migrated files order by timestamp.  Error is unusual when the migration created by other mates or in an other branch.

**Comment by BurtonR** [comment]
I'd expect it to run in alphabetical order of the file name. Alternatively, add an `order` property to the interface and reference that.

I'm used to naming the migration scripts manually with the date and an order number. An example would be : `remove-name-20172712-001.ts`

This way, it's quick and easy to see what happened, and when, while just looking at the file list and not having to go into the DB (that's the whole point of an orm right?)

I was able to find a workaround though. Since the timestamp check isn't really a _timestamp_ check, and just casting the last 13 characters to `int` [here](https://github.com/typeorm/typeorm/blob/117f77c55757f838d4e11ba2e0ad532fc10dcedb/src/migration/MigrationExecutor.ts#L224)
I've just named the class with the date and 5 numbers at the end: `removeName_2017271200001`

It's hacky, but it lets me and my team continue using the naming method we're accustomed to. It'd be really nice to name the migrations without the filler by passing a flag to the migration command though. 
Maybe something like `--ignore-timestamp`, or maybe `--filename-order` and have it run migrations based on either the filename or another property on the interface

I see you're using the `migrations` property in `ormconfig.js`. This means that the file names _are_ available if you chose to pass them back. This would probably be a bigger change than you're willing to make and I understand that, but I _could be_ possible to order the migrations on filename :)

I'd be willing to put together a PR for that if you'd be willing to entertain the idea

**Comment by stimms** [comment]
@pleerock If we were to submit a PR to add flags as @BurtonR suggested would that be something you'd consider merging?

**Comment by pleerock** [comment]
Migration execution order is a huge point of discussion currently, and Im still not sure what is the best design. We can add extra option like `--order=name|timestamp` as @BurtonR suggests, but does it cover all cases? 

@BurtonR also mention about `migrations` property in `ormconfig`. What if we control ordering there and disable ability to specify migrations directories, e.g.:

```ts
{
    entities: ["entity/*.js"],
    migrations: [
           FirstMigration,
           SecondMigration,
           ThirdMigration, ...
    ]
}
```

And migration executor will run migrations in the order defined in this array. What do you think?

Adding everybody who faced this particular issue, lets find best solution that is going to fit everybody: @szkumorowski @mscharley @galkowskit  @yujiahaol68 @luchillo17 @Ostrzy

**Comment by mscharley** [comment]
As far as I’m concerned it almost doesn’t matter what the ordering is as long as it’s defined and deterministic and doesn’t require things to be run strictly in order in production, though each migration run will run all available new migrations in order. This will probably require a new `run_at` column in the migrations table to keep track of when things were actually run as opposed to when they were created. 
File order seems reasonable, since the auto generated file names include a time stamp as a prefix.

**Comment by mscharley** [comment]
It would be interesting to have the migrations array processed in order and let people manually control the order explicitly via the array as an option but I don’t think it’s a good only solution.

**Comment by luchillo17** [comment]
The current system based on timestamps is not wrong, it's just not suited for team development, most of the time, if 2 people have 2 migration that collide when executing, it means it was bad task assignment since they ended up working in something that collided.

If you ask me, taking in account how teams should work (ideal case, most of the time teams don't follow this), teams should keep track of what are they changing, and ensure they're not colliding with another team member, so the way this should be managed, is that if 1 team member has a migration with a timestamp old enough, but hasn't been run yet, it should be executed, and then put in the table of executed migrations in timestamp order (even though the migration is way in the middle).

Remember that above statement is right only if the team ensures no one makes migrations that collide in the team, if they do, is the team responsibility to deal with the conflicts accordingly, so in that order of ideas, i think is ok if we execute migrations by timestamp like now, but if there's old migrations pending, just execute them (with a flag so it's not the default behavior) and include them in the migration table.

**Comment by BurtonR** [comment]
@pleerock in regards to the `migrations` property in the `ormconfig`, what I was originally referring to was the fact that the file names are available in code in that class. That would mean that it would be possible to update the rest of the downstream code to use the file name in the ordering of the migrations. 

I see your suggestion of explicitly defining the migrations order via array in the config. That could be a viable option. It would make conflicts with different branches creating migrations more definite and require the fix to be resolved with intention. I kind of like that idea, although I also fear that it may become overwhelming with long running projects where the migrations list could be massive. On the other hand, if you could reference an external file (a `.json` with the array defined), it could be manageable. 

The option @luchillo17 mentioned, with a `force` flag to run migrations regardless if there is a newer one already run could be a somewhat quick patch. I would expect that if a migration is added with a timestamp less than another already run migration, that the framework would run that new one in order, and re-execute all the migrations with a timestamp greater than that newly added one.

**Comment by luchillo17** [comment]
@BurtonR The issue with your last comment is that, to do that you require to revert all migrations that are greater than the one that lacks execution, the issue comes that such reverts could potentially erase data, for example in production environments, i think a better way to handle it is to update the not executed ones to have a new timestamp, or execute them regardless (at least for this DB) and when deployed in a new DB use the correct order, otherwise we risk unwanted reverts & data loss.

**Comment by BurtonR** [comment]
Ah, you're right! Forgot about that little fact... I agree with what you said though. Execute regardless of timestamp if there are newer migrations already run, but run in order if bringing up a new DB. Of course, this would still be behind a `--force` flag for the existing migrations to make sure that's what you want to do.

**Comment by mscharley** [comment]
So, by example:

With the migration timestamps `[1234, 2345, 3456, 4567]` in a database with `[1234, 3456]` already run, we would run `[2345, 4567]` in that order. In a fresh database, you would run them in lexical order.

That sounds fine, just wanted to reiterate that the revert order must match the run order. For example, the old database would run reverts in the order `[4567, 2345, 3456, 1234]`. Otherwise you run into weird issues like 'We just did a deployment, migration 2345 was the culprit but we can't revert it without reverting a working migration from the previous deployment.'.

**Comment by pleerock** [comment]
@mscharley thanks for the example 😆  I need confirmation from everybody that this is preferable way of how migrations shall work

**Comment by luchillo17** [comment]
Approves with thumbs up to not clutter this thread.

**Comment by pleerock** [comment]
@xujif your thoughts?

**Comment by yoz** [comment]
@pleerock: @xujif wrote above in https://github.com/typeorm/typeorm/issues/1315#issuecomment-350180804 "just migrate files whitch has not been migrated order by timestamp" which I also think makes sense.

**Comment by luchillo17** [comment]
@yoz Yeah, more or less what @BurtonR, @mscharley and i discussed in this comments in order, expanding on the idea of the migrations and how to handle them as well as reverts when requested:
- https://github.com/typeorm/typeorm/issues/1315#issuecomment-365924709
- https://github.com/typeorm/typeorm/issues/1315#issuecomment-365933332
- https://github.com/typeorm/typeorm/issues/1315#issuecomment-365936545
- https://github.com/typeorm/typeorm/issues/1315#issuecomment-366053508

**Comment by xujif** [comment]
Is there an conclusion？ @pleerock 
I found typeorm will find "last migration" from database, that will cause "when my teammate create an migration and migrated but not commit to master. I can not  undo my migration without the file."
so I suggest find "last migration" from the order of local file. just like "laravel".

**Comment by pleerock** [comment]
Fixed and released in `0.2.0-alpha.35`, try it via `npm i typeorm@next`. You'll need to drop migration table or add primary auto-generated `id` column and remove primary flag from timestamp manually to make revertion work correctly.

**Comment by pleerock** [comment]
Please test it and provide a feedback.

**Comment by yoz** [comment]
@pleerock There is a significant problem in the alpha version when trying to revert migrations in existing databases - they don't have IDs (the `migrations` table doesn't have an `id` column). `migration:revert` uses `getLatestExecutedMigration`; it attempts to sort by `migration.id`, which is NaN for every migration, and returns a completely random migration to revert.

**Comment by yoz** [comment]
@pleerock Sorry, I didn't see the comment about the id column - note that you can't just drop the migration table, because running migrations after that will attempt to re-run all previous migrations.

**Comment by pleerock** [comment]
correct, it means you need to drop migrations and remove migrations. Alternative is to manually add needed changes into the migrations table.

**Comment by mscharley** [comment]
That really isn’t a viable upgrade strategy. You can’t just remove the old migrations or new installs won’t work. And manually updating the table isn’t much of an option either. Shouldn’t the migrations system be able to upgrade its own table?

**Comment by pleerock** [comment]
Ideally it should be. Feel free to contribute on that part.

**Comment by sumeet-bansal** [comment]
@pleerock did anything come out of this discussion? Currently running into the same issue where teammates commit migrations with out-of-order timestamps.
