### ISSUE TITLE
How to auto join all of the tables?

### ISSUE THREAD

**Issue by fanzkday** [typeorm/typeorm#1354]
```
// user.js

@Entity()
class User {

  @OneToOne(type => Address)
  @JoinColumn()
  public address: Address;

  // ... many relations

  @OneToOne(type => Company)
  @JoinColumn()
  public company: Company;

}
```
I want to auto join all of tables, like this  :
```
this.rep.createQueryBuilder("user").joinAll();
```
Not like this, Because I don't know how many relations there are. This may sound strange: 
```
this.rep.createQueryBuilder("user")
  .innerJoin("user.address")
  // ...
  .innerJoin("user.company")
```
And I need to:
```
this.rep.createQueryBuilder("company").joinAll(); // can join user
```

**Comment by pleerock** [comment]
No, there is no such functionality and I'm doubtful about this functionality, because:

* joins are used to control what you want to select. Joins are expensive operations once your joined data grows, so its a good practice to control what you need when you need it. Much more expensive then separate queries for the same data

* this design does not fit well with query builder conception where you build a query and have all the flexibility, and not just use methods that do everything for you

* you can't join something with a condition or use somehow joined data because of missing aliases from your side

* there can be nested joins, for example address.street, `joinAll` sounds confusing for them and does not allow to do nested joins because you can do them only via aliases which you specify in a second parameter of `innerJoinAndSelect` function

Let's see if someone else from the community vote on this feature and maybe we will implement it.

**Comment by fanzkday** [comment]
ok, thanks.
