### ISSUE TITLE
Migration check timstamp order - possiblity to disable

### ISSUE THREAD

**Issue by szkumorowski** [typeorm/typeorm#1364]
Would be great to have possiblity to disable this error, as the execute migrations in order is not always required

` if (lastTimeExecutedMigration && migration.timestamp < lastTimeExecutedMigration.timestamp)
                throw new Error(New migration found: ${migration.name}, however this migration's timestamp is not valid. Migration's timestamp should not be older then migrations already executed in the database.);`

**Comment by mscharley** [comment]
Also running into this issue - migrations *can* be ordered by timestamp but it shouldn't be a requirement, or that requirement should be able to be disabled. This basically causes havoc in any environment with more than one stream of work because if I'm writing an update and my coworker is writing an update... what timestamps do we give each of those updates? Who will finish first?

**Comment by pleerock** [comment]
Im going to close this issue to reduce duplicates. Lets discuss everything in #1315
