### ISSUE TITLE
BUG or SUPPORT something wrong with joinable tables

### ISSUE THREAD

**Issue by cybermerlin** [typeorm/typeorm#1418]
I have `TestEntity.ts`:
```js
@Entity('test_1288');
export class TestEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column(type => JoinEntity)
    jName: JoinEntity = new JoinEntity({spec: "fffffffff"});
}
```
and joinable table `JoinEntity.ts`:
```js
@Entity("join_1288")
export class JoinEntity {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    spec: string;
}
```

and of course `test.ts`:
```js
describe("github issues > #1288 check calculated columns (sql in @Column)", () => {

    let connections: Connection[];
    before(async () => {
        return connections = await createTestingConnections({
            entities: [__dirname + "/entity/*{.js,.ts}"]
        });
    });
    beforeEach(() => {
        return reloadTestingDatabases(connections);
    });
    after(() => {
        return closeTestingConnections(connections);
    });

    it("should persist successfully and return entity", () => Promise.all(connections.map(async connection => {
        // create objects to save
        const joinEntity1 = new JoinEntity();
        joinEntity1.spec = "Entity #1 spec (for TestEntity)";

        const testEntity1 = new TestEntity();
        testEntity1.name = "Entity #1";
        testEntity1.jName.spec = "Entity #1 some spec";

        const testEntity2 = new TestEntity();
        testEntity2.name = "Entity #2";

        // persist
        await connection.manager.save([
            testEntity1,
            testEntity2
        ]);
```

but what I see in a query?:
```SQL
INSERT INTO "test_1288"("name", "jNameSpec") VALUES ($1,$2)  RETURNING "id", "jNameId"
```
any comments about this?

**Comment by pleerock** [comment]
Looks correct. What issue do you have?

**Comment by pleerock** [comment]
You are using a concept called "embedded entities". When you embed entity it merges all properties from it into your original entity. In your case result will be `test_1288` table with 4 columns:

* id
* name
* jNameId
* jNameSpec

Where `id` and `jNameSpec` are both primary columns and they are resulted in a *composite primary key*. This is how embedded entities are working. Im not sure why are you using "joinable" table terminology here, but looks like you are confusing this with concept of real relations (many-to-many, one-to-many, etc.) 

Also there are two issues with your code:

* your second entity does not need a decorator. Remove `@Entity("join_1288")` from JoinEntity.
* you have multiple primary keys and both are auto-generated columns - this is not supported (and will not be because of database-level limitations)

**Comment by cybermerlin** [comment]
I was thinking something like: 
tables: test_1288, join_1288
 and 
test_1288.jName are FK to join_1288.id 
      and if I have to get spec value then all I need is just call testEntity1.jName.spec (like in ibatis on advanced types)

**Comment by cybermerlin** [comment]
thank for waiting for my reaction (I was very busy).

**Comment by pleerock** [comment]
you need to use relations, not `@Column(() => Entity)` syntax for your purpose.

**Comment by cybermerlin** [comment]
thx.
maybe u show me some link to that helping page, it's will be helpful for me?

**Comment by pleerock** [comment]
open a documentation site and take a look on section panel, you'll see "Relations" there.
