### ISSUE TITLE
Unexpected results from find/findOne and getOne/getMany from repository and queryBuilder

### ISSUE THREAD

**Issue by umarov** [typeorm/typeorm#1450]
**OS:** Elementary OS 0.4.1 (Ubuntu 16.04.3 LTS)
**Node:** lts/carbon
**TypeORM:** 0.1.11
**Postgres:** psql (PostgreSQL) 9.5.10
**TypeScript:** 2.6.2
**ts-node:** 4.1.0

[Gist with all the files](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c)

So I have [Order](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c#file-order-ts), [Customer](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c#file-customer-ts), and [Client](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c#file-client-ts) entities.

On the [Order](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c#file-order-ts) model, you can see the different statuses and how the db fields are setup.

I am trying to query orders by different statuses, but I am getting unexpected results.
In the beginning I started using the `Repository` to query orders. I would get unexpected results. 
I tried using query builder, it would not help me that much. I have read the docs multiple times and spend hours on this already.
[Here are all the test commands I have used with the console.log values](https://gist.github.com/umarov/027d0c8df2fafa78636a7c56481a7b2c#file-more-tests-ts)
I have some other query types I have written in the gist there. 

Am I doing something wrong?
I have tried putting `printSql` on the commands. Then after running the SQL commands in pgAdmin, I would get the expected results.

**Comment by pleerock** [comment]
@umarov there are few issues I noticed. 

* first, you don't need to manually escape names most of times, ORM does it for you when it can, but you need to provide proper statements
* second, some of your statements in query builder aren't not escaped automatically because of inproper usage, for example instead of `"order"."clientId"` you need to do `order.client`, e.g. you should use property names from your model, not database column names
* another issue is here:

```ts
return getRepository(Order).findOne({
      relations: ['customer', 'client', 'orderItems'],
      clientId: client.id,
      customerId: customer.id,
      status: 'active'
    });
```

You cannot mix find options and conditions, you can use only one of them. Since you are using find options here (`relations`) your conditions should be inside `where`. Also you need to query data by their model, not database structure:

```ts
return getRepository(Order).findOne({
      relations: ['customer', 'client', 'orderItems'],
      where: {
          client: { id: client.id },
          customer: { id: customer.id },
          status: 'active'
      }
    });
```

Your queries built by query builder have only one issue I see (besides comment about escaping above):

```ts
    .select()
    .from(Order, 'order')
``` 

You do not select anything real here, you need to specify what you are selecting this way:

```ts
    .select('order')
    .from(Order, 'order')
```

Which means you are really selecting order object with all its data.

**Comment by umarov** [comment]
Thanks for the explanation and clarifications.
I eventually started using `where` in conditions in for different entities after looking more through the docs. I updated my `Order` queries to follow what you put in here and they work really well (really fast too).
One issue though,
```
return getRepository(Order).findOne({
      relations: ['customer', 'client', 'orderItems'],
      where: {
          client: { id: client.id },
          customer: { id: customer.id },
          status: 'active'
      }
    });
```
when I use this syntax. I get an error saying `QueryFailedError: invalid input syntax for integer: "{"id":1}"`. So I can go around this error by modifying the where object:
```
return getRepository(Order).findOne({
      relations: ['customer', 'client', 'orderItems'],
      where: {
          client: client.id,
          customer: customer.id,
          status: 'active'
      }
    });
```
That works perfectly and just like expected. But it's a bit unclear that the `client` key in the where object represents `clientId`. 

Other than that, query builders work nicely after adding the `select('order')`.

**Comment by pleerock** [comment]
Looks like a resolved issue. Let me know if not. Closing.
