### ISSUE TITLE
leftJoinAndSelect with subquery returns Unknown column in field list error 

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm#1476]
Using the Latest 0.1.11 version. Why does `leftJoinAndSelect` create an invalid query using the subquery function?

For example, joining a count subquery

````
         this.plansRepository
            .createQueryBuilder("b")
            .leftJoinAndSelect(subQuery=>{
                return subQuery
                    .select(`COUNT("planId")`,`total`)
                    .addSelect(`planId`)
                    .from(Items,"items")
                    .groupBy(`items.planId`)
            },"i",`i.planId = b.planId`)
            .getRawMany()
````
The query returns an SQL error because there's an redundant subquery alias `i` in front of the `FROM` clause, "i".*, **i** <<<<< FROM

````
ER_BAD_FIELD_ERROR: Unknown column 'i' in 'field list'
````

````
SELECT `b`.`planId` AS `b_planId`, `b`.`planName` AS `b_planName`,`i`.*, i FROM `plans` `b`
LEFT JOIN (SELECT COUNT(planId) AS `total`, planId 
FROM `items` `items` GROUP BY `items`.`planId`) `i` ON i.planId = `b`.`planId`

````

Even if I use a custom select in the plansRepository: 
````
 this.plansRepository
            .createQueryBuilder("b")
            .select(1)
            .leftJoinAndSelect(subQuery......
````
I still get that redundant alias in front of the FROM clause.

**Comment by daniel-lang** [comment]
I was able to generate an SQL statement that looks like this:
```sql
SELECT "b"."planId" AS "b_planId", "b"."planName" AS "b_planName", "i".*, "i" FROM "plan" "b"
LEFT JOIN (SELECT COUNT("planId") AS "total", planId FROM "item" "items" GROUP BY "items"."planId")
"i" ON i.planId = "b"."planId"
```
Which would returns something like this:
```json
[{"b_planId":1,"b_planName":"Test","total":2,"planId":1,"\"i\"":"i"}]
```

But I had modify `SelectQueryBuilder.ts` to do so. But my modification isn't quiet correct as it still selects i.
From my investigation it seems like this wrong query gets generated because "i" isn't correctly excluded in `SelectQueryBuilder::createSelectExpression()`.

@pleerock is this something that @AlexMesser is correctly working on for 0.2? Because the same wrong statement is generated on `next`. If not I can investigate some more and probably fix it.

**Comment by pleerock** [comment]
@daniel-lang no nobody is working on QueryBuilder currently.

**Comment by daniel-lang** [comment]
@stonecold123 Please take a look at #1494. As it fixes your problem but you will still need to manually escape the subquery.
The fix will be released with the next version.
