### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by pleerock** [typeorm/typeorm#148]
I'm planning to merge my efforts on [typeodm](https://github.com/pleerock/typeodm) project into typeorm. I think mongodb will fit a design of typeorm. There are several considirations that need to thought out, but overall intergration should look fine. I'm planning to work on it next month. If you are interested in this, take a look on [samples in typeodm repo](https://github.com/pleerock/typeodm/tree/master/sample) and also take a look on source code of typeodm. Please share your thoughts and considirations on this.

**Comment by joesonw** [comment]
The problem might be difference between `mysql` and `MongoDB` queries. An example approach would be `spring-data`. Instead of merging `typeodm` into `typeorm`, create a new project that abstracts the basic operations of database, e.g, save, query, find, etc.

**Comment by pleerock** [comment]
thank you for the feedback. yeah, I clearly understand the differences and know how challengeable it will be to fix both into single orm. I always was sure that they should be separate projects. However what really buys me that how easy it will be just to add additional driver to exists set of drivers - I'll only need to add driver, create mongodb version for repository and entity manager classes where I'll need to override few methods like query, transaction and createQueryBuilder and throw exception that they are not supported by mongodb. Plus add additional repository specific to mongodb and add there mongodb-specific functions. Thats really easy and really simplifies libraries maintenance.

What you suggest is conceptually correct, however right now it may cost me maintenance issues and will require more time. I would like to keep them both in the same repository until they grow and will become popular. Maybe in the future if they will be so I'll extract them into separate libraries and create common abstraction layers as you suggested. 

Thank you

**Comment by 19majkel94** [comment]
I wonder if it's possible to use generics in TypeScript to produce sth like this:

![2017-01-10 18_12_38- test ts - backend - visual studio code](https://cloud.githubusercontent.com/assets/10618781/21816447/7de2f3c2-d760-11e6-8d47-a1e73a06307d.png)

IMO it's better to have compile-time error info rather than failed at runtime ;)

**Comment by pleerock** [comment]
no, I guess it will not be possible... for mongodb Im planning to add `connection.getMongoRepository` that returns `MongoRepository` with mongo-db specific methods.

**Comment by 19majkel94** [comment]
Thanks to Typescript 2.1 and `keyof` and mapable types it's now possible! 👍 

```typescript
// define helper - type alias
type ClassType<T> = { 
    new (...args: any[]): T;
}

// define sample Entity class
class User {
    public email: string;
    public sendEmail(): boolean {
        return Math.random() > 0.5;
    }
}

// define type 1 of Repository
class MongoRepository<T> {
    public constructor(
        private EntityClass: ClassType<T>
    ) {}

    public getFromDocument(): T {
        return new this.EntityClass();
    }
}

// define type 2 of Repository
class SqlRepository<T> {
    public constructor(
        private EntityClass: ClassType<T>
    ) {}

    public getFromTable(): T {
        return new this.EntityClass();
    }
}

// key feature - define a mapable type
interface DriverMap<T> {
    "sql": SqlRepository<T>,
    "mongo": MongoRepository<T>
}

// declare a helper - string enum
class DriverTypes {
    public static readonly MONGO = "mongo";
    public static readonly SQL = "sql";
}

// now the magic :D
class Connection<K extends keyof DriverMap<any>> {
    // type K is keys of DriverMap type - "sql" | "mongo"
    public constructor(
        private driverTypeName: K
    ) {}
    
    // T is normal newable class type
    // returning DriverMap[K] means that compiler will look into DriverMap interface
    // and check the type of property with key K
    public getRepository<T>(entityClassType: ClassType<T>): DriverMap<T>[K] {
        if (this.driverTypeName === "mongo") {
            // as any, because of narrowing K bug - "MongoRepository<T> is not asignable to DriverMap<T>[K]"
            return new MongoRepository(entityClassType) as any;
        } else {
            return new SqlRepository(entityClassType) as any;
        }
    }
}
// now let's test - mongo connection and repository
const mongoCon = new Connection(DriverTypes.MONGO);
const mongoUserRepo = mongoCon.getRepository(User);
const mongoUser = mongoUserRepo.getFromDocument();
mongoUser.sendEmail();

// it's working, now sql!
const sqlCon = new Connection(DriverTypes.SQL); // new Connection("sql") works too!
const sqlUserRepo = sqlCon.getRepository(User)
const sqlUser = sqlUserRepo.getFromTable();
sqlUser.sendEmail();

// PROFIT !!!
```
Go and check it out with Typescript 2.1.6! 😉 

With this, the API is very type-safe for user, you can't call mongo method with sql connection or even Postgres specific when targeting MySQL. `as any` has to be placed sometimes only inside library but now in `RepositoryFactory` you have `any` as well so no changes for you I think.

What do you think? I know it's a lot of refactoring but it's TypeScript, if we can it should be type-safe 😉

**Comment by pleerock** [comment]
that looks really cool, however its just a hack. It will work only because of `new Connection(DriverTypes.SQL)` statement given explicitly. To make for example `getConnection()` method working you have to define it this way `getConnection<"mongodb">()` which isn't pretty same with `getRepository<"mongodb">` or decorators like `@OrmRepository<"mongodb">`

**Comment by 19majkel94** [comment]
Of course! If you get generic type from container you have to assert it's type. But with this solution, you have one generic method which return correct repository and it's type-safe:

```typescript
const conn = getConnection<"mongo">();
const repo = conn.getRepository(User);
const user = repo.getFromDocument();
repo.getFromTable(); // Property 'getFromTable' does not exist on type 'MongoRepository<User>'.
user.sendEmail();
```
So you don't have to make N functions to get N types of drivers from container.
You can also use this technique to make functions like `createConnection` more type-intelligent and return `MongoConnection` which can have `dropCollections` specific methods, etc. The type T can be key of ConnectionOptions.driver.type so no `<Type>` assertions 😉

**Comment by pleerock** [comment]
TBH Im not satisfied with `getConnection<"mongo">()` expression. For me it seems better to call `connection.getMongoRepository()` rather. Or even `getMongoConnection()` if needed. It all should be simple and intuitive. However calling `getConnection<"mongo">()` each time you need a connection is not simple or intuitive.

**Comment by 19majkel94** [comment]
You're right, `getMongoRepository` sound better but you are able to do this on sql connection loaded from container, so you'll get runtime error instead of instant type error in IDE (or during compilation).

The better solution is to have `getMongoConnection()` function, which returns `Connection<"mongo">` where `getRepository()` returns `MongoRepository`. And it could only by a wrapper for nicer names:

```typescript
function getMongoConnection() {
    return getConnection<"mongo">();
}
```

**Comment by pleerock** [comment]
the reason why `getConnection<"mongo">()` isn't good because no-one will use it this way and even know that it should be done this way. Even those who know that this is possible to do it this way will not do it this way - simply because its weird and ugly. Plus this implementation makes underlying code much more complicated.

TBH I still prefer to have one `getConnection()` instead of two connection retrieve functions and have a `getMongoRepository` method which yeah, will throw runtime exception if someone use it. Is it a problem? No, because noone gonna use it for sql, and even if they will they will end up using it very quickly on early stages. The only con is that it will be available as a suggestion by code completition. 

But I really amazed how did you find such really awesome hack to solve this problem. I love your idea and understand how many good points it has. However we need better implementation

**Comment by 19majkel94** [comment]
The whole idea about types is to minimize frequency of runtime exceptions and the need of looking at documentation instead of relying on intellisense/autocompletion and jsdoc 😉 

I know that this implementation might makes underlying code much more complicated but for now it can just use this `keyof` and `T[K]` feature in declaration and `any` type assertion inside to make API type-safe, so it's not a complete refactor for now. 

You can have this feature in mind while developing integration with MongoDB, maybe you would have new ideas which may need `MongoConnection` type, because now `Connection` has method like `syncSchema` which are not related to document database. And you may want to add methods like `dropCollection` or sth else.

And this feature can work not only with `new Connection`:
```typescript
async function createConnection<K extends keyof DriverMap<any>>(options: { driver: { type: K } }): Promise<Connection<K>> {
    return new Connection(options.driver.type);
}

const createdConn = await createConnection({ 
    driver: {
        type: "sql"
    }
});
const createdUserRepo = createdConn.getRepository(User);
const createdUser = createdUserRepo.getFromTable();
createdUser.sendEmail();
```

> because no-one will use it this way and even know that it should be done this way

With [this TypeScript PR](https://github.com/Microsoft/TypeScript/pull/13487) generic types will be able to have default type, so calling pure `getConnection()` return them normal connection but `getConnection<"mongo">()` or `getConnection<"oracle">()` will return the specific connection with specific repositories, etc. Because this syntax will allow you to implement more specific drivers and related APIs for MySQL, Oracle, etc. with more detailed `QueryBuilder` API, etc.

You  don't have to force to use `<>` syntax - just use function wrapper as aliases.
The `getMongoRepository` will also be kinda breaking change which will need to be described in readme/documentation as well.

And you can get type-safe on decorators just by exporting specific decorators in specific path will common aliases:

```typescript
import { PrimaryGeneratedColumn } from "typeorm/mongo";
```

So mongo won't have exported `TableInheritance`, etc.

**Comment by pleerock** [comment]
> The whole idea about types is to minimize frequency of runtime exceptions and the need of looking at documentation instead of relying on intellisense/autocompletion and jsdoc

right and `getConnection<"mongo">()` isnt really descriptive without docs.

> With this TypeScript PR generic types will be able to have default type

does help too much, user still needs to call weird `getConnection<"mongo">` (or `getMongoConnection doesnt matter) to get a connection.

> The getMongoRepository will also be kinda breaking change which will need to be described in readme/documentation as well.

thats not a breaking change. Its just additional method that can be used or not. Non-mongodb users wont use it at all.

> And you can get type-safe on decorators just by exporting specific decorators in specific path will common aliases

No, having two points where from to import is a bad idea.

> So mongo won't have exported TableInheritance, etc.

its not a problem, who don't want to use it simply would not use it

> You can have this feature in mind while developing integration with MongoDB, maybe you would have new ideas which may need MongoConnection type, because now Connection has method like syncSchema which are not related to document database. And you may want to add methods like dropCollection or sth else.

actually its just an iceberg surface problems. There are tons of problems of integration of mongodb or any other non-relational drivers. Like, for example what to do with `@Column()` decorator which have lot of relational-only specific options, what to do with `@Index` decorator which also has its own functionality on each platforms, what to do with query, transaction, query builder which are part of relational databases and lot of other issues.

as joesonw mentioned earlier the best if typeorm and typeodm would be separate projects, however at this point I would like to make them all-in-one to increase framework popularity and usage and to decrease maintenance cost of the library, because more libraries I have more work (and time) need to be spend to maintain them. Maybe in the future once they both reach stability and popularity I'll separate them.

Btw not sure if you already seen that (but I guess yes), but I already have created a PR which has basic implementation of mongodb driver.

**Comment by 19majkel94** [comment]
> does help too much, user still needs to call weird getConnection<"mongo"> (or `getMongoConnection doesnt matter) to get a connection.

Calling just `getConnection()` will work and return `Connection` exactly as now. If you want type-safe, you can call `getMongoConnection()` and get `MongoConnection` like "weird" `getMongoRepository()`. With only SQL Repo and Mongo it's make no sense, the generic `Connection<T>` can be use when there is a need to returning `MongoRepository<U>`, `OrientDbRepository<U>`, `Neo4JRepository<U>` or even Postrges or Oracle.

> thats not a breaking change. Its just additional method that can be used or not. Non-mongodb users wont use it at all.

Not a breaking change in the exactly meaning but TypeORM user might think that it's just another driver type so he will call `getRepository()` and have a lot of error, he has to change his code to `getMongoRepository()` to make it works.

> actually its just an iceberg surface problems. There are tons of problems of integration of mongodb or any other non-relational drivers. Like, for example what to do with @Column() decorator which have lot of relational-only specific options, what to do with @Index decorator which also has its own functionality on each platforms, what to do with query, transaction, query builder which are part of relational databases and lot of other issues.

If `@Index<"mongo">(options)` is a bad idea, I think that only the separate import path are the solution. So all in all, you need more types for the decorators options to get more compile-error rather than throwing eg. `GeneratedOnlyForPrimaryError` on run-time. It's easier to have specific classes with inheriting common base behavior rather than many if-throw code in different part of TypeORM internals.

I know that there are more important things to do now because this kind of error is easy to find (it will print on console if you don't catch it), the whole more-detailed types idea can be done in the future but you can think about it when developing a new API for new drivers.

> Btw not sure if you already seen that (but I guess yes), but I already have created a PR which has basic implementation of mongodb driver.

So I will take a look at it in a free time :wink:

**Comment by arimus** [comment]
I'd lean towards trying to have a single API with different drivers under the hood. Whether or not that's moving the odm into the orm codebase or creating a higher level mapper which exposes a common interface, is a subject for debate. But having the common stuff consistently exposed and only breaking into driver / underlying datastore specifics when it is useful / necessary is quite nice. There are some examples of this type of approach in the wild (e.g. loopback is a notable one)

There is a lot in common that can be easily mapped under the hood to do sensical, logically equivalent things (event if there is some variance). Honestly, I'd say map them all out and compare them, because there's more in common than you'd initially think. Indexes, column/property constraints, table/document relationships and join/populate mechanisms, etc.

Of course, each DB has it's own special query interfaces. In mongo you'll want to be able to do more complex map-reduce / aggregation pipeline stuff in MongoDB for instance, but that's only on the query side and then it's all just common results processing again. For a lot of it, you could probably model this querying, joining and filtering pipeline similarly for both and make most people very happy. Few folks **want** to write SQL and / or Aggregation Pipeline Queries for most of the work being done. It's just the 1% of the time you need to drop down and tweak / optimize the query side, then zoom back out.

Also, having some methods at the top level for sanity and convenience, which are not implemented in a particular database, can easily just throw a NotImplementedError. This probably isn't a problem to be concerned about, since folks aren't going to be trying to use one driver and then move to another without understanding there will be changes necessary. Most everyone understands this won't be seamless...it's rarely even seamless between two relational backends. In any case, this can be mitigated with some clear documentation. You can't worry over the fact that some users don't understand what they are doing though...that's a much, much bigger project to work on and likely out of scope ;)

@pleerock I'm willing to help hash out some of the common interface constraints and challenges, even if it's just an exercise in determining feasibility. I was excited to see the typeodm project and this thread on the possibility of bringing them together if it makes sense. And in the case they really aren't, perhaps I can help pick up some of the slack on the typeodm project.

Cheers

**Comment by pleerock** [comment]
> Not a breaking change in the exactly meaning but TypeORM user might think that it's just another driver type so he will call getRepository() and have a lot of error, he has to change his code to getMongoRepository() to make it works.

The plan is still to left default `Repository` implementation for all drivers. `getRepository()` will work for mongodb. Just some of its methods (query, transaction) wont work and will throw an exception if user will try to use them. This is already implemented.

> If @Index<"mongo">(options) is a bad idea, I think that only the separate import path are the solution.

I don't like importing from separate paths either, because it will make it complicated to use for both current and mongodb users (ide will suggest imports from two paths instead of automatically do it from first one). But yeah, the problem exist and neither of solutions are ideal.

**Comment by pleerock** [comment]
@arimus thanks for the comment on this issue.

> There is a lot in common that can be easily mapped under the hood to do sensical, logically equivalent things (event if there is some variance).

That's right, but evil is in details as usual. There are quite lot small problematic cases where its impossible to they equivalent for all drivers

> This probably isn't a problem to be concerned about, since folks aren't going to be trying to use one driver and then move to another without understanding there will be changes necessary.

thats right. TypeORM's purpose isn't to make a perfect abstraction for drivers which you can easily swap. This functionality in practice almost never needed. TypeORM's purpose is more to make sure to provide as much functionality as needed for him to solve his problems.

If someone want to contribute or see whats going on on mongodb side of the typeorm take a look on my PR for mongodb driver, checkout it and start to explore problems and challenges ;)

**Comment by 19majkel94** [comment]
> I don't like importing from separate paths either, because it will make it complicated to use for both current and mongodb users (ide will suggest imports from two paths instead of automatically do it from first one). But yeah, the problem exist and neither of solutions are ideal.

I saw that someone said that you should move the common code for both project (metadata stuffs, listeners, etc.) to separate package and just use it in TypeORM and TypeODM. You could have npm scopes for the packages, so `@typeorm/core` would have the basic stuffs which would be used by `@typeorm/mongo` and other drivers. Common decorators could be exported from core to the mongo/mysql/etc. package, so there would be one import path from one package.

**Comment by pleerock** [comment]
yeah thats actually what I was talking about:

> as joesonw mentioned earlier the best if typeorm and typeodm would be separate projects, however at this point I would like to make them all-in-one to increase framework popularity and usage and to decrease maintenance cost of the library, because more libraries I have more work (and time) need to be spend to maintain them. Maybe in the future once they both reach stability and popularity I'll separate them.

What you have suggested with separate packages is a good idea probably I'll use it in the future.
Also I'll try to use technique you were talking about once default generic types will be released with `T & U & Z` approach and measure pros and cons of this design in practice.

**Comment by 19majkel94** [comment]
By the way, I've seen that in `routing-controllers` you use this type of enum:
```typescript
export type ParamType = "body"|"query"|"header"|"file"|"files"|"body_param"|"param"|"session"|"state"|"cookie"|"request"|"response"|"custom_converter";

export class ParamTypes {
    static BODY: ParamType = "body";
    static QUERY: ParamType = "query";
    // ...
}
```

Class-based string enums need to have `readonly` keyword and no typedef to resolve to exact values 
```typescript
typeof ParamTypes.Body === "body"|"query"|"header"|"file"|"file" // ...etc. 
typeof DriverTypes.MONGO === "mongo" // not "string" or like ParamTypes
```
to be able to work with the `K extends keyof DriverMap` and `DriverMap<T>[K]`. I've done some experiments and the best solutions is this:
```typescript
// define runtime enum
class DriverTypes {
    public static readonly MONGO: "mongo";
    public static readonly SQL: "sql";
}

// define compile time (generic type check) enum
namespace DriverTypes {
    export type MONGO = "mongo";
    export type SQL = "sql";
}
```
It's a bit of repeating but this allows to:
```typescript
getConnection<DriverTypes.MONGO>();
createConnection({ driver: { type: DriverTypes.MONGO }})
```
and also in the old JS-fashioned strings form:
```typescript
getConnection<"mongo">();
createConnection({ driver: { type: "mongo" }})
```

Unfortunately  TS doesn't allow for indexer type for static class properties:
```typescript
interface DriverTypesEnum {
    static readonly [property: string]: keyof DriverMap<any>
}
```
So you need to be carefull when creating new enum entries or refactor string names.

**Comment by arimus** [comment]
@pleerock FYI, I merged in the PR locally and I'm getting the following compilation errors:

```
[16:47:39] Starting 'compile'...

198                 Cursor.prototype.toArray.call(this, (error: MongoError, results: Entity[]): void => {
                    ~~~~~~

src/repository/MongoRepository.ts(198,17): error TS2693: 'Cursor' only refers to a type, but is being used as a value here.


208                 return Cursor.prototype.toArray.call(this).then((results: Entity[]) => {
                           ~~~~~~

src/repository/MongoRepository.ts(208,24): error TS2693: 'Cursor' only refers to a type, but is being used as a value here.


216                 Cursor.prototype.next.call(this, (error: MongoError, result: CursorResult): void => {
                    ~~~~~~

src/repository/MongoRepository.ts(216,17): error TS2693: 'Cursor' only refers to a type, but is being used as a value here.


226                 return Cursor.prototype.next.call(this).then((result: Entity) => {
                           ~~~~~~

src/repository/MongoRepository.ts(226,24): error TS2693: 'Cursor' only refers to a type, but is being used as a value here.
```

**Comment by pleerock** [comment]
@arimus yeah this is something I made a PR for in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14567 . Once it gets merged we will get rid of these errors. For now made same changes in your locally installed mongodb.d.ts file (need to change Cursor's definition type from `interface` to `class`)

**Comment by pleerock** [comment]
Mongodb support is merged into master and available in latest `0.1.0-alpha` versions. Samples can be found [here](https://github.com/typeorm/typeorm/tree/master/test/functional/mongodb/basic). Later we will need to add docs.

**Comment by pairmix** [comment]
Hi there,
What about this feature?
I need queryBuilder. Is it available ?
If not, what package do i have to use instead ?

**Comment by rustamwin** [comment]
@pairmix you should use cursor (`createCursor()`, `createEntityCursor()`)

**Comment by pairmix** [comment]
I replaced all my createQueryBuilder by find/findOne with correct FindOptions.
It seems to work.
I don't see how and why i should use createCursor and createEntityCursor.

Any examples ?

**Comment by francojay** [comment]
bump
