### ISSUE TITLE
BeforeUpdate is not running

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#1483]
Adding `@BeforeUpdate()` fails to run in my model when updating the model.

A full code sample can be found here:
https://github.com/crutchcorn/PET-Template/commit/721d4bac85e6cb0e2b3d6a4e28098538c17b9fc0

**Comment by crutchcorn** [comment]
I am incredibly dumb. Ignore this issue, as it is not valid

**Comment by crutchcorn** [comment]
@pleerock I thought this was a bug as, even though I was hitting `save` to update, I was not passing any new information to the model. This should probably be documented as this is drastically different behavior than what I think most would expect

**Comment by pleerock** [comment]
before update means before actual updation in the database. If there are no changes in the model it does not to do database updation, thus listener is not being called.

**Comment by crutchcorn** [comment]
Right, but this is behavior that many might not expect. You might want to document that so that it's more explicit

**Comment by lordnynex** [comment]
I understand the underlying issue in this ticket that there is no new properties to the model so the hook is not firing. In my case, quite a few parameters are being updated but I'm not seeing the hook fire at all. The model is being updated by `repository.updateById(id, params)`. Is this expected? Our particular work flow is 'create empty entity' and then 'update the entity with actual data'.  

Unrelated, is there a way for the BeforeUpdate listener to have some context into what fields are changing? In my case, I'm attempting to perform a cryptographic operation and need to find away around performing this operation more than once on a field.

**Comment by crutchcorn** [comment]
@lordnynex 
Sounds like you should create a new bug - as that's unrelated to the behavior found here

You can use `BeforeUpdate`, query the database for the old model, and compare against `this` (`this` contains the new object). However, if you're using `select: false` (which I would suggest for crypto anything), you're more or less out of luck. Related thread here: https://github.com/typeorm/typeorm/issues/1514

**Comment by lordnynex** [comment]
@crutchcorn Thanks for getting back to me. I read it, the whole thing seems complicated and confusing. In the last hour or so I'm having much better luck with implementing a custom `ValueTransformer` on the column. Take a look at this test case example.

https://github.com/typeorm/typeorm/blob/d36ae18a887f3045e5c24f6b798e3afe13707043/test/functional/columns/value-transformer/entity/Post.ts#L6

**Comment by crutchcorn** [comment]
DM me on Twitter (@crutchcorn) and we'll take a look at your code and figure out what we can. Maybe our use-cases for BeforeUpdate are the same and we can work together, and if not I'm more than willing to help however I can

**Comment by lordnynex** [comment]
@crutchcorn I don't use twitter. If you want to reach out my email is my github username @ gmail. 

I'm guessing from your code examples it seems like you want to use these hooks for hashing password fields. Our use case is actual AES encryption on a value. Since the value is nullable, the hooks cause weird issues because the value may or may not be there. The particular issue I observed was `@BeforeUpdate()` was not actually being called when `updateById` was used to add the value to the entity.  Even if the hook were to fire as expected I was uncomfortable because there may be edge cases where an unrelated data update, could attempt to encrypt the field more than once (unless I try to somehow track encrypted status). It seemed quite brittle. 

It was then brought to my attention that I can write an `EncryptedStringTransformer` class which applies the encryption and decryption operations on the value completely transparently to the application. It's working fantastically! I'm not sure how a value transformer would work in your particular case because I don't know if a query parameter on there `WHERE` predicate would be fed through the transformer. If it is, I would highly recommend implementing your hashing logic in a `ValueTransformer` because it works so seamlessly. It essentially makes logic bugs impossible.

Here is a really contrived example

```typescript
export class EncryptedStringTransformer implements ValueTransformer {
  constructor(private encryptionKey: string) {}

  static default(): EncryptedStringTransformer {
    const key = getYourEncryptionKey()
    return new EncryptedStringTransformer(key)
  }

  to(value?: string) {
    if (!value) {
      return undefined
    }
    return encryptTheString(this.encryptionKey, value)
  }

  from(encryptedValue?: string) {
    if (!encryptedValue) {
      return undefined
    }
    return decryptTheString(this.encryptionKey, encryptedValue)
  }
}

@Entity()
export class Person {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  username: string;

  @Column({
    transformer: EncryptedStringTransformer.default(),
    type: 'varchar',
    nullable: true,
  })
  secretField?: string
}
```

I am not sure how this would work in something like an authentication call where you want to take a user password from POST, hash it, and query for an exact string match. In the above example though, you could just fetch records on the login username (or email if you use that), and compare the fields. Anyways, theres ways to deal with it but I'm making a lot of assumptions about your use case.

**Comment by pleerock** [comment]
> The model is being updated by repository.updateById(id, params). Is this expected?

@lordnynex can you try on `next` version? Its called simply repository.update(id, params) btw
