### ISSUE TITLE
Undefined does not affect model objects

### ISSUE THREAD

**Issue by crutchcorn** [typeorm/typeorm#1490]
When trying to update a user, I mistakenly ran the following commands:
```
      user.resetPasswordToken = undefined;
      user.resetPasswordExpires = undefined;
      userRepo.save(user)
```

But I noticed that it wasn't doing anything to the user object. However, when I changed this to:
```
      user.resetPasswordToken = null;
      user.resetPasswordExpires = null;
      userRepo.save(user)
```

It had the expected behavior. This could be different from most people's expectations (even if this is expected behavior from the project), and should be clearly documented

**Comment by pleerock** [comment]
Its by design and allows partial updations. You can lets say do `userRepo.save({ id: 1, middleName: "Lalala" })` without being worried that other data will be removed. Also setting properties to `null` is actually making column values null in the database as well, so logically everything fit good.

and btw you always can contribute in documentation, its quite easy to do and will help others to solve issues you faced.

**Comment by crutchcorn** [comment]
I understand and think it's a great design choice. 

I know I can contribute, and do plan to, but often find these bugs in the middle of a code session and just need to log them out. I'll try getting a PR in with doc additions here soon.

**Comment by pleerock** [comment]
nice!
