### ISSUE TITLE
Postgres pg_trgm type of index

### ISSUE THREAD

**Issue by pratham2003** [typeorm/typeorm#1519]
**Issue type:**
question

**Database system/driver:**
postgres

How do i add a custom index like following one using TypeORM?
`CREATE INDEX symbol_idx ON public.some_table USING GIN(symbol gin_trgm_ops);`
I added it using a query directly but the synchronize feature in TypeORM deletes it.

**Comment by pleerock** [comment]
Custom index types are not supported yet, most probably because they are different in all databases. We are planning to think about their design and implement this functionality.

Its strange that synchronize removes it. Looks like an issue and to fix it I think you can only disable schema sync for particular entity with this index.

**Comment by pratham2003** [comment]
I see, thanks :)
But how do we disable sync for a single entity? I could only find a way to disable sync globally in TypeORM.

**Comment by pleerock** [comment]
its hidden inside `@Entity` decorator: `@Entity({ synchronize: false })`

**Comment by pratham2003** [comment]
I see, thanks a lot!

**Comment by AlexMesser** [comment]
This feature won't be implemented (at least in the near visible future), because of lot of different database specifics and multiple issues with getting information about exist database indices and synchronizing them automatically.

You should create index manually (for example in the migrations) with any index signature you want. To make TypeOrm ignore these indices during synchronization use following syntax:

```ts
@Entity()
@Index("ignored_index", { synchronize: false })
export class Post {
```
avaliable from `typeorm@0.2.0-alpha.27`

**Comment by kukoo1** [comment]
Just for information, if this feature will be implemented.
This is how sequelize index API is
[](https://sequelize.org/master/manual/models-definition.html#indexes)
```javascript
{
  fields: ['data'],
  using: 'gin',
  operator: 'jsonb_path_ops'
}
```

**Comment by Pasukaru** [comment]
Please also consider cases where fields are expressions.
Currently, typeorm will throw an error `Index contains column that is missing in the entity` for cases like this:

`CREATE INDEX "idx" ON "tbl" (LOWER(TRIM("col")))`

**Comment by simplenotezy** [comment]
I need to define an index like so:

    CREATE INDEX ON profiles USING GIST (location);
    
Is there a workaround to do this?

**Comment by w3llcod3** [comment]
How to add an index trigram to an entity?

It should match this query in the migration
```Typescript
await queryRunner.query('CREATE INDEX ids_requests_address_trigram ON requests USING GIN (address gin_trgm_ops)')
```

When trying 
```Typescript
  @Index({ fulltext: true })
  @Column({ type: 'text', nullable: true, default: null })
    address: string
```

it gets dropped in db by `migration:generate` as typeorm generates DROP command 

I guess this still an issue in typeorm for not being able to add trigram index
