### ISSUE TITLE
set default value of @UpdateDateColumn to null

### ISSUE THREAD

**Issue by ali-web** [typeorm/typeorm#1528]
**Issue type:** feature request
At the moment apparently there's no way to set the default value of `@UpdateDateColumn` to `null`, but I think it would be nice to have this option.

Furthermore, it might not be a bad idea to have that as the default behaviour as when you just insert an item, it hasn't been updated yet and that enables one to easily query for items that haven't been updated yet (though I know it's subjective), but I guess that would raise some backward compatibility issues, but I would be interested to know what's your thoughts on that.

**Comment by pleerock** [comment]
no, this not a goal of `@UpdateDateColumn` decorator. If you want to customize and implement such behaviour, its better if you use your own update date property with `@Column` decorator and implement logic in listeners.

**Comment by benjaminhera** [comment]
@pleerock can you explain what is the goal of the `@UpdateDateColumn` decorator then? I think it would make much more sense to be able to customise the decorator as I wish, or at least disable the `default` option property for the decorator because it is misleading, that I have that option when it does nothing.
