### ISSUE TITLE
Invalid SQL being generated by updateById when using postgres array inside embedded

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#1569]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

PR with failing test case coming.

**Comment by pleerock** [comment]
This cannot be fixed in the current master because fix will lead to a breaking change. This issue because only postgres and mssql supports arrays and array can go as a single parameter in query builder, while others use arrays as multiple parameters. Breaking change is going to break for users all their query builder expressions where arrays are used, for example `WHERE IN (:param)` statement. Im skipping your test and going to fix it on the `next` branch.

**Comment by pleerock** [comment]
This was fixed in `0.2.0-alpha.19`.
