### ISSUE TITLE
Changing Schemas dynamically based on logged in user 

### ISSUE THREAD

**Issue by Seshagiri25** [typeorm/typeorm#1577]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,
  I am working on a SAAS based multi-tenant application. We are using schema per tenant architecture. Coming from .Net platform, TypeORM looks very familiar to EF and would like to use in our project. But the constraint I am facing is to change schema depending on the user/tenant logged in. We are using sub-domain technique and I can get current tenant from the sub-domain. 

Coming to the question of changing schemas, I saw two options in TypeORM
1. Using Schema as in Entity({schema:'something'})
2. passing in Schema in Connection Options. (We are using postgres as our database)

We will have same model name for each of the schema. For Ex. Products. This model will be available in all the schemas. Schemas will be created when a user is registered and models will be created in schema on the fly. In this case I cannot go with Scenario 1.  

I can use scenario 2, but I have to create single connection for each of the tenant to same database. Say If I have 100 tenants, then I have to create 100 connections. My question is, Is this prudent way to do it? I read somewhere that more connections to single database will slowdown postgres performance. 
Or can you suggest any other option? 

Any help will be appreciated...

**Comment by pleerock** [comment]
> I read somewhere that more connections to single database will slowdown postgres performance.

When we are talking about "typeorm connection, e.g. createConnection" its not real postgres connection, its a orm's connection with pooling established. Real connections are created on different operations, and more operations and users you have more connections you'll have, you cannot avoid it since its how system should work when you have multiple users (connections are blocking). So, you probably read something wrong or something that cant be avoided.

Let me confirm something - do you want to have same entity in *different schemas*?  If yes then you can use solution 2 but it has its own limitation, or probably better if you use two entities for each schema, but reduce duplications using inheritance. 

Im not aware of the architecture you are using, but probably solutions can be found on database-level, not in programmatic usage? It will be definitely better.

**Comment by Seshagiri25** [comment]
Hi ,
Yes, What I am trying to do is create postgres schema and its tables dynamically when a user is registered online. So it will be same schema and same data structure but different client. Before you point out, I cannot use same table for multiple clients(separating with client_id) due to requirements which are beyond the scope of this discussion. 
I am trying to go with solution 2, as it offers me to change schema at connection level, which I can handle with `createConnection()`. But there is a limitation with running migrations, which I will tackle it in another way. 

Maybe I am wrong with connections. But thanks for clarification and reply.

**Comment by pleerock** [comment]
Did I answer your question? Can this issue be closed?

**Comment by Seshagiri25** [comment]
Yeah sure thanks...

**Comment by syabro** [comment]
@pleerock is it possible to set provide `schema` as an argument to `getManager` or to `getRepository`?

@Seshagiri25 have you figured out how to deal with migrations in different schemas?
