### ISSUE TITLE
Sort order for indices

### ISSUE THREAD

**Issue by yhpark** [typeorm/typeorm#1594]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[?] `cordova`
[ ] `mongodb`
[x] `mssql`
[x] `mysql` / `mariadb`
[x] `oracle`
[x] `postgres`
[x] `sqlite`
[?] `sqljs`
[?] `websql`

(applicable to all RDBMS)

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Most RDBs support specifying sort order for each column when defining indices. For composite index, this could make a query much efficient since it may eliminate the need of `order by` clause from select query. I believe this is one of the features that are widely used yet not supported by this project, so please consider supporting the feature.

**Comment by yhpark** [comment]
https://stackoverflow.com/questions/2292662/how-important-is-the-order-of-columns-in-indexes

**Comment by yhpark** [comment]
https://stackoverflow.com/q/743858

**Comment by pleerock** [comment]
Thanks for the report, we are planning to support this feature in the next version.

**Comment by AlexMesser** [comment]
This feature won't be implemented (at least in the near visible future), because of lot of different database specifics and multiple issues with getting information about exist database indices and synchronizing them automatically.

You should create index manually (for example in the migrations) with any index signature you want. To make TypeOrm ignore these indices during synchronization use following syntax:

```ts
@Entity()
@Index("ignored_index", { synchronize: false })
export class Post {
```
avaliable from `typeorm@0.2.0-alpha.27`
