### ISSUE TITLE
Cannot create connection with entities at all

### ISSUE THREAD

**Issue by eyelidlessness** [typeorm/typeorm#1679]
**Issue type:**

 [ ] question
 [x] bug report
 [ ] feature request
 [ ] documentation issue

**Database system/driver:**

 [ ] `cordova`
 [ ] `mongodb`
 [ ] `mssql`
 [ ] `mysql` / `mariadb`
 [ ] `oracle`
 [x] `postgres`
 [ ] `sqlite`
 [ ] `sqljs`
 [ ] `websql`

**TypeORM version:**

 [x] `latest`
 [ ] `@next`
 [ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I created a repo isolating and reproducing the issue [here](https://github.com/eyelidlessness/typeorm-bug). This repo includes:

- tsconfig.json which correctly enables `emitDecoratorMetadata`
- src/index.ts which attempts to connect three different ways, and includes their respective errors as comments:
    - Reference source TS files by glob
    - Reference compiled JS files by glob
    - Directly require model
- dist/* which shows that the compiled model does in fact include the type metadata for decorated columns

It's not clear to me how this is supposed to work, but I cannot accomplish anything at all with TypeORM currently.

**Comment by pleerock** [comment]
If you are new to typeorm its better to start with this [example repo](https://github.com/typeorm/typescript-example). Simply clone and start working. 

Your problem is here:

```ts
        entities: [
            // Try to load the model from source
            '**/*.model.ts',
        ],
```

First problem you need to specify a "dirname", like this: `entities: [ __dirname + "/**/*.model.ts" ]`

Second problem are files.

If you are running your app via ts-node (which does compilation on-the-fly then you can use .ts files in your "entities" section.

If you are running your app from "dist" directory then you need to specify files in there: `entities: [ __dirname + "/dist/**/*.model.js" ]` and those files should be `js` files since you are running js app, not ts app like in ts-node case.

**Comment by eyelidlessness** [comment]
Hi,

I've updated my issue reproduction repository to reflect your feedback, in the following ways:

1. I eliminated the attempt to use .ts files, because I don't intend to use ts-node.
2. I updated the .js file glob to use `__dirname`, but I had to correct it because running from "dist", that is already included in the `__dirname` value (I included a log demonstrating this).
3. I left the direct load case intact. It does not refer to any files, only the model directly.

I get the exact same errors for the two remaining cases:

```
{ DataTypeNotSupportedError: Data type "undefined" in "Foo.bar" is not supported by "postgres" database.
    at new DataTypeNotSupportedError (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/error/DataTypeNotSupportedError.js:16:28)
    at /Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:68:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:65:36)
    at /Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:36:74
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/metadata-builder/EntityMetadataValidator.js:36:25)
    at Connection.buildMetadatas (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/connection/Connection.js:503:33)
    at Connection.<anonymous> (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/connection/Connection.js:157:30)
    at step (/Users/gnosis/Projects/typeorm-bug/node_modules/typeorm/connection/Connection.js:32:23)
name: 'DataTypeNotSupportedError',
message: 'Data type "undefined" in "Foo.bar" is not supported by "postgres" database.' }
```

Please look at [the compiled model](https://github.com/eyelidlessness/typeorm-bug/blob/master/dist/Foo.model.js) to see that the type metadata is being correctly generated, but it is being treated as if the type is undefined.

**Comment by pleerock** [comment]
you need to import reflect-metadata before everything else in your index file

**Comment by eyelidlessness** [comment]
1. This is not covered anywhere in the documentation. Would you consider updating it?
2. As a quick experiment, I added the import to node_modules/typeorm/index.js and it solved the problem just the same as if I had included it in my own file. Would you consider importing it in TypeORM so that users don't need to do so?

**Comment by pleerock** [comment]
> This is not covered anywhere in the documentation. Would you consider updating it?

Its covered [here](https://github.com/typeorm/typeorm#installation). Please read docs before attacking me.

> As a quick experiment, I added the import to node_modules/typeorm/index.js and it solved the problem just the same as if I had included it in my own file. Would you consider importing it in TypeORM so that users don't need to do so?

This will really simplify things. I remember i had that import years ago, but I don't remember what problem caused me to remove this thing later. Probably I'll need to return things back and see what happen.

**Comment by eyelidlessness** [comment]
> Its covered here.

Ah so it is, my mistake. I had pulled down the repo and searched the /docs/ directory, but somehow missed this. Mea culpa.

> Please read docs before attacking me.

A misstatement of fact about the documentation is not the same as a statement about the qualifications of a person. Please don't do this, it's petty.

> This will really simplify things. I remember i had that import years ago, but I don't remember what problem caused me to remove this thing later. Probably I'll need to return things back and see what happen.

Thanks for looking into that. In the meantime, I have got it working now. Thanks for your help.

**Comment by hi2u** [comment]
@pleerock 

> > This is not covered anywhere in the documentation. Would you consider updating it?
> 
> Its covered [here](https://github.com/typeorm/typeorm#installation). 

My issue is probably not exactly the same.  

But it seems that the `entities` setting in ormconfig.json is relative to the current working directory of the shell that node is run in, rather than the location of the ormconfig.json file / project root?  

I've been getting errors such as `RepositoryNotFoundError` related to this.

I couldn't find anything in the docs about this.  Maybe it's in there somewhere?  But I couldn't find anything in 3 days of searching for what my problem could have been, or even now, when I know what to look for.

1. Is there a reason that it's relative to the shell's working directory, rather than the ormconfig.json file / project root?

2. I think maybe this should be made more obvious somehow, especially given that so many of the getting-started examples shown don't include `__dirname` (and I guess they can't in JSON anyway?).  

I've been tearing my project apart for 3 days trying to figure out why typeorm completely stopped working, but only some of the time, and regardless of whether I was changing my code or not.

I greatly appreciate your work & this library in general, so I hope this doesn't sound like whinging.  I just wanted to clearly explain why I think it's important to make it easier for people to get started with the library.  It seems quite a few people are being tripped up by some of these initial issues when getting started.  I was close to giving up on using typeorm altogether.


3. If I want to contribute to the documentation, is it just a matter of editing the markdown files in this main `typeorm/typeorm` project?
