### ISSUE TITLE
TypeORM in the wild?

### ISSUE THREAD

**Issue by dbkaplun** [typeorm/typeorm#1759]
Hello,

Are there any examples of TypeORM in the wild? It would be great to see a list of projects that use TypeORM in some way, to see how much it can scale and who's using it.

Thanks for reading!

**Comment by pleerock** [comment]
Not sure if people are watching for such issues and will be able to answer this question. Personally I don't know since noone is usually talking from what company they are using it. People usually simply report issues if they have, and if they don't they simply use it silently.

Closing as non-issue.
