### ISSUE TITLE
transaction connection problem?

### ISSUE THREAD

**Issue by xujif** [typeorm/typeorm#1946]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `websql`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I found that transaction will createQueryRunner on an exist connection ,but not create a new session or monopolize one.
so that other queries which is out of transaction will run in the same connection,it will cause a parallel problem ?

**Comment by pleerock** [comment]
its not clear what you mean. Explain what is your purpose and what you are trying to do

**Comment by xujif** [comment]
sorry for my english.
I have some problem with concurrency request. It is easily cause deadlock when start transaction at same time
I found that typeorm keep database conncection is singleton , even in the transaction, diffrent transactions  cross  each other.
I review the source code, when begin a transaction, typeorm just new a "QueryRunner", but not create a new connection or  make the current connection monopolize.

**Comment by pleerock** [comment]
each new QueryRunner is a separate database connection. TypeORM's `Connection` is actually connection pool.

**Comment by ameinhardt** [comment]
@pleerock: in Sqlite-, ReactNative-, Expo-, Nativescript-, Cordova- and SqlJs-Driver, `createQueryRunner` doesn't create a new `QueryRunner` instance. In Oracle-, Mysql-, Postgres-, SqlServer-, Cockroach-Driver it returns the one existing already.
So unfortunately, in the former, this will result in an `TransactionAlreadyStartedError`:
```
const connection   = getConnection(),
      queryRunner1 = connection.createQueryRunner(),
      queryRunner2 = connection.createQueryRunner();
await queryRunner1.startTransaction();
await queryRunner2.startTransaction();
await queryRunner2.release();
await queryRunner1.release();
```

And more importantly, it can lead to unexpected conditions in save(), because even if no queryRunner is provided to save/EntityPersistExecutor, it always uses the singleton and might inject into an existing transaction.
