### ISSUE TITLE
queryRunner.renameTable should just rename.

### ISSUE THREAD

**Issue by fwh1990** [typeorm/typeorm#1965]
**Issue type:**

[ ] bug report

**Database system/driver:**

[ ] `mysql`

**TypeORM version:**

[ ] `@next`

**Steps to reproduce or a small repository showing the problem:**

Why using  `queryRunner.renameTable` can change table index name? You just drop my normal index and unique index, and then rebuild them with hash name like `IDX_4baa50847ec3f6d1ac94904be9`

Is any problem or side effect when I rename my table?

So, I don't want my index name be changed, because it's hard to write migration file later. I means something may out of control when I want to drop my table index. Program may return to me: `The index _x_x_x_ doesn't exist`.

If is't a bug, can you fix that and release a new version as soon as possible? Thank you.

**Comment by pleerock** [comment]
its not a bug, its by design. Index names are being generated using table name, and ORM needs a proper index name to make a proper schema synchronization. Even if you rename table manually using SQL query, next time you run synchronization it will drop and create indices anyway.

**Comment by fwh1990** [comment]
How about keep the index name if the name is now named as hashcode? I never synchronize db schema, just use migration file.

**Comment by pleerock** [comment]
you basically don't use half of functionality TypeORM provides. There won't be a feature you are talking about in this issue, as I explained we need to recreate renamed indices. Consider using `queryRunner.query` method and execute raw queries.

**Comment by ahilke** [comment]
Hi @pleerock, I found this thread, because I am facing a similar issue.

I have a migration that renames a table using `queryRunner.renameTable()`, which recreates my unique index. I defined the index with name in my entity, but the migration uses the auto-generated name (I guess it would be hard to find the related entity at this point). Is the only way to fix this to then afterwards drop and recreate the index myself again? Sadly, that is confusing if you don't know about this behaviour of `renameTable()`. Maybe an option could be added to `renameTable()`? I guess I could also use raw SQL for renaming tables, but I generally prefer the `queryRunner` methods, since I need to support multiple database vendors.
