### ISSUE TITLE
Startup schema synchronization deletes data automatically - expected behavior?

### ISSUE THREAD

**Issue by welkie** [typeorm/typeorm#1984]
**Issue type:**

I wanted to get some clarification on behavior I witnessed. I was pleasantly surprised to see TypeORM able to automatically create and apply a migration to add a column to my table if I add a property to a model. I thought to myself that if that same behavior works in reverse, it would be safe for TypeORM to throw an error if there was data in that column and it were to be removed from the model. I was wrong though, I noticed that it just deletes the column along with any data in it when you start the app again.

I was wondering, is this intended behavior? Is synchronization considered dangerous, and should we be using manual migrations instead?

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[*] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[*] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

* Have a table's schema include a nullable column
* Add data to at least one row in that table for that column
* Remove the property from the class definition for that model
* Start app with synchronization enabled

**Comment by pleerock** [comment]
>  it would be safe for TypeORM to throw an error if there was data in that column and it were to be removed from the model.

no, it won't. If you remove column from the model it means you want to remove it and all its data, otherwise why did you remove it. (for the cases when you want to rename a column you need to make single-change migrations, this is the only way orm can determine if you renamed column and not added a new one and removed old one, there are other requirements as well, but this one is the most basic, JFYI)

>  Is synchronization considered dangerous, and should we be using manual migrations instead?

any migration considered dangerous, working with data is always a serious thing and you have to confirm before executing it. On production the flow can be:

* you generate a migration
* you check if it won't break your data by analyzing generated queries
* you append additional logic if you want to change something
* you run the migration
