### ISSUE TITLE
Closure Table Implementation is different than standard?

### ISSUE THREAD

**Issue by awwong1** [typeorm/typeorm#2076]
**Issue type:**

  [X] question
 [X] documentation issue

**Database system/driver:**

  [X] `postgres`

**TypeORM version:**

  [X] `latest`
  [X] `0.2.4`

**Question**

I notice in the main documentation that your project advertises:

> supports closure table pattern

I'm not sure if it's currently properly implemented. When running the closure table tests in ORM, I see that postgres runs the following queries:

```sql
CREATE TABLE "category" (
  "id" SERIAL NOT NULL,
  "name" character varying NOT NULL,
  "parentCategoryId" integer,
  CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id")
)
CREATE TABLE "category_closure" (
  "id_ancestor" integer NOT NULL,
  "id_descendant" integer NOT NULL,
  CONSTRAINT "PK_8da8666fc72217687e9b4f4c7e9" PRIMARY KEY ("id_ancestor", "id_descendant")
)
ALTER TABLE "category" ADD CONSTRAINT "FK_9e5435ba76dbc1f1a0705d4db43" FOREIGN KEY ("parentCategoryId") REFERENCES "category"("id")
ALTER TABLE "category_closure" ADD CONSTRAINT "FK_4aa1348fc4b7da9bef0fae8ff48" FOREIGN KEY ("id_ancestor") REFERENCES "category"("id")
ALTER TABLE "category_closure" ADD CONSTRAINT "FK_6a22002acac4976977b1efd114a" FOREIGN KEY ("id_descendant") REFERENCES "category"("id")
```

Shouldn't the closure table implementation have the depth of the ancestor/descendant relationship in the closure table to eliminate the sub query for immediate children/parents?
- If you add the depth field to the closure table, you can eliminate the foreign key `parentCategoryId` in the entity table and just keep `id`

Seems also a bit misleading to say closure tables are supported when deletes or moves are not implemented https://github.com/typeorm/typeorm/issues/193 

I'd like to help contribute for this feature, but I'm not sure how to do so in a backwards compatible way with users that have already implemented closures (db migration is non trivial). I also see that this is getting more attention in [0.3.0 milestone](https://github.com/typeorm/typeorm/milestone/2)?  Is a redesign/rewrite already planned?

**Comment by pleerock** [comment]
TypeORM does support closure table pattern, but its not necessary to support all possible features working with closure table. I have seen different implementations of closures with and without level (depth) column, with and without foreign key column.

Feel free to contribute!

I would like to keep foreign key column because it provides some useful features. Feel free to support a depth/level column. It won't be a breaking change since it should be optional. There is a `@TreeLevelColumn` decorator that you can use to implement this behaviour. If user adds a column with this decorator - the level column is added, if no, then its not - just like it is right now. So we only need to implement the underlying behaviour.

Same about moving and deleting, it will be great if you can help on this topics as well!

**Comment by awwong1** [comment]
I'm closing this and moving discussion to https://github.com/typeorm/typeorm/issues/193.
