### ISSUE TITLE
Migrations vs schema sync

### ISSUE THREAD

**Issue by ph55** [typeorm/typeorm#2090]
**Issue type:**
[V] question

**Database system/driver:**
[V] `mysql` / `mariadb`

**TypeORM version:**
[V] `latest`

I try to combine `schema:sync` in development with `migration` in production with no success. 

The easiest way to work in development with `synchronize: true`.
After some milestone there is a need to generate migration of your changes for safe run in production.

The problem is when you either `synchronize: true` or run `schema:sync` manually - `migration:generate` won't give you any result.

So you can only combine  `synchronize: true` with manual sync in production ?
And if you want to use migrations - you should use it both in development and production ?

**Comment by pleerock** [comment]
> migration:generate won't give you any result.

it won't give you result since your schema is up to date when you run it with `synchronize: true or  schema:sync`. Why do you need a migration when you already have a schema in sync?

Simply use `synchronize: true or  schema:sync` until in both development and production you need a migration. Generated migration is exactly what synchronize: true generates you, the only reason why you might need migration over it is if you want to change something in a migration.

**Comment by ph55** [comment]
> the only reason why you might need migration over it is if you want to change something in a migration

Migrations are more safe for production also because of option to revert/rollback.
You deploy your version, run migration and if breaking change detected - you rollback your code and also rollback migration.

In this way you have full control of your version release.
With schema sync you have no rollback option. 
If you release version with breaking change - you can't rollback easily because there is no `schema:revert`.

---

And now I will answer to myself.
After rollback your code - `schema:sync` will rollback db changes to previous state.
