### ISSUE TITLE
Use an existing pg.Client connection

### ISSUE THREAD

**Issue by benny-medflyt** [typeorm/typeorm#210]
How can I get a typeorm `Connection` (or `EntityManager`) from an existing connection created with the `pg` library?

<https://github.com/brianc/node-postgres/wiki/Client>

For example, I want to do something like:

```typescript
import * as pg from 'pg';

const client = new pg.Client('postgres://brian:mypassword@localhost:5432/dev');
client.connect(async () => {
    // Do some SQL queries with client...
    await insertPhotosSql(client);

    // Now I want to do some typeorm queries using same connection:
    const connection = ???(client);
    let allPhotos = await connection.entityManager.find(Photo);
});
```

**Comment by pleerock** [comment]
why do you need this?

**Comment by benny-medflyt** [comment]
I need to execute some custom SQL, and may also need to use LISTEN/NOTIFY. but i would also like to use typeorm for some queries

**Comment by pleerock** [comment]
You can get access to `ng` via typeorm this way:

`connection.driver.nativeInterface` will return you object with `pg` instance inside. But normally you wont need it. If you want to execute raw sql query you can use `connection.entityManager.query()` method

**Comment by pleerock** [comment]
did I answer your question?

**Comment by benny-medflyt** [comment]
Yes, using `nativeInterface` works in the meantime. thanks!

**Comment by hurrvinek** [comment]
seems that ``native interface`` has been removed. Is there still a way to pass the connection to a new pg.Client?

**Comment by pleerock** [comment]
depend on database, for postgres its `connection.driver.postgres`

**Comment by JohannesRu** [comment]
> why do you need this?

Hey @pleerock, the idea is that I can get better insights in my app performance. I want to provide pg.Client as I am monitoring that instance using zipkin and jaeger. https://www.npmjs.com/package/zipkin-instrumentation-postgres

**Comment by leighman** [comment]
> I want to provide pg.Client as I am monitoring that instance using zipkin and jaeger.

Hi @pleerock, would also be interested in this. Thanks.

**Comment by sagidM** [comment]
@pleerock Hi Umed.
I want to make another argument about existing connection.
I work in a big tech company which, as many other such ones, uses a lot of inner libraries.
Right now we try to move little by little to TypeORM, but in an existing project, there are many functions that work with DB.

For example, say we have functions like (without TypeORM)
```ts
someTransaction(() => {
  createEntity1(params: Entity1Params)
  createEntity2(params: Entity2Params)
})
```
Then we created `Entity1` via TypeORM but not `Entity2`.
So as we want to make a smooth transition to the framework, we can't just use TypeORM in that case because they are 2 different drivers (e.g. pg Client/Pool).

I can do a PR with passing in the existing client, at least for `pg`, but not sure whether the core team is open for such changes. Is it?
