### ISSUE TITLE
Timezone question

### ISSUE THREAD

**Issue by nikitaulshin** [typeorm/typeorm#2124]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello!

I have a small question about ```@CreateDateColumn``` functionality.
Is it possible to somehow configure the ORM so that the generated dates are saved in a 0 timezone (i.e. '2018-05-11T09:04:32+00:00')?

Thank you!

**Comment by pleerock** [comment]
I think you just have to set database timezone to UTC, am I right @chriskalmar ? (create/update dates are generated using CURRENT_TIMESTAMP)

**Comment by nikitaulshin** [comment]
This solution helped, thanks.

**Comment by chriskalmar** [comment]
Well, it's not that easy. 
`@CreateDateColumn` and `@UpdateDateColumn` are using `now()` (which returns a `timestamp with time zone`) for generating timestamps.
Unfortunately the automatically generated table columns are based on `timestamp`, which (since postgres 7.3) is based on `timestamp without time zone`. This is fine according to the current SQL standard but a problem for this use case.

So you have a timestamp column that doesn't hold the timezone information but you still would like to have UTC timing stored. 
Setting the server to `UTC` might be helpful in your case but you need to understand that the returned timestamp is not in `UTC` but in a local timezone (which would be the server's timezone).

I'm working on a GraphQL framework that heavily relies on typeorm. The reason why I never ran into this problem is that I build custom create/update columns and control the timestamp generation on the framework level.

There is currently no way in typeorm to change the column type of `@CreateDateColumn` and `@UpdateDateColumn` (I think this is something worth improving @pleerock). Maybe changing the column type to `timestamp with time zone` would be a better option to begin with.

So for now I would suggest to try setting the server to `UTC` (but carefully examining the effects on read). 
Another option is to generate your own timestamp columns for the relevant entities and to have a simple wrapper around the point where you persist data via typeorm to inject the desired timestamps.

**Comment by pleerock** [comment]
> There is currently no way in typeorm to change the column type of @CreateDateColumn and @UpdateDateColumn (I think this is something worth improving @pleerock).

there is. You are able to provide type in decorator column options

**Comment by chriskalmar** [comment]
I know and I tried it before but couldn't turn the column into another data type.
This is what I tried:
```
  @UpdateDateColumn({
    type: 'time with time zone'
  })
```

Looking at the relevant code I assumed that the data type is fixed for create/update date columns:
https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L190-L198

What am I missing?

**Comment by pleerock** [comment]
"before" when? In >= 0.2.0 ? it shall work (@AlexMesser was working on it)

> https://github.com/typeorm/typeorm/blob/master/src/driver/postgres/PostgresDriver.ts#L190-L198

those are just defaults I believe

**Comment by chriskalmar** [comment]
sorry, my bad. 😅
found this here:
https://github.com/typeorm/typeorm/blob/master/src/metadata/ColumnMetadata.ts#L371-L373

I was having an outdated typeorm where I was testing it. 
All good now, thanks.
