### ISSUE TITLE
How to resolve type conflict in ConnectionOptions?

### ISSUE THREAD

**Issue by g-borgulya** [typeorm/typeorm#2144]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Trying to use typeorm configuration with our CI system.

We use docker and ENV variables. Different configurations for development and production environment. I understand that typeorm can read its settings from different sources, but I don't exactly understand how it could be done with ENV vars.

If I try to do something like this:

```ts
import {ConnectionOptions} from 'typeorm';

const ormOptions: ConnectionOptions = {
  type: process.env.TYPEORM_CONNECTION || 'mysql',
  host: process.env.TYPEORM_HOST || 'localhost',
  port: parseInt(process.env.TYPEORM_PORT || '3306', 10),
  username: process.env.TYPEORM_USERNAME || 'user',
  password: process.env.TYPEORM_PASSWORD || null,
  database: process.env.TYPEORM_DATABASE || 'test',
  logging: process.env.TYPEORM_LOGGING || 'true',
  synchronize: !!process.env.TYPEORM_SYNCHRONIZE,
};
```

Then it immediately fails with:

```bash
error TS2345: Argument of type '{ type: string; host: string; port: number; username: string; password: string | null; database: ...' is not assignable to parameter of type 'ConnectionOptions'.
  Type '{ type: string; host: string; port: number; username: string; password: string | null; database: ...' is not assignable to type 'ReactNativeConnectionOptions'.
    Property 'location' is missing in type '{ type: string; host: string; port: number; username: string; password: string | null; database: ...'.
```

I have the following questions:
- Is this a bug of typeorm?
- If this is intentional then how am I supposed to use ConnectionOptions?
- Or is there any other best practice to configure typeorm with ENV variables?

**Comment by pleerock** [comment]
its not a bug, its how `ConnectionOptions` type is implemented. It uses union type and each type contains its own properties, for example in the case of `sqlite` there is no host, port or username and it won't allow you to pass such options, but you do! (since your type is dynamic).

Easiest way for you is to use `any` instead of `ConnectionOptions` otherwise logic to handle your dynamic connection type can be quite complex.

Best practice is not to have a dynamic type since in practice you most probably won't have it or won't be able to achieve multi-database setup at least because you'll use different column types specific to database.

**Comment by g-borgulya** [comment]
Thank you, it works fine with `any` .
