### ISSUE TITLE
Unable to run migrations without a database

### ISSUE THREAD

**Issue by dkfiresky** [typeorm/typeorm#2181]
**Issue type:**

[ ] question
[x] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
1. Create a new migration which creates a database for you.
2. Create a default ormconfig.json without the database option.
3. Run migrations.

**Expected behavior:**
All the migrations run successfully.

**Current behavior:**
Migration failed with error: `ER_NO_DB_ERROR: No database selected`

**Possible solution:**
Run this query:
```sql
CREATE TABLE `migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB
```
after first migration was complete.

**Comment by dkfiresky** [comment]
Another option would be using a JSON file for storing the completed migrations (as Sequelize does).

**Comment by pleerock** [comment]
I don't recommend you to "not specify database in your connection options". Although its technically possible in mysql, typeorm rely a lot on a selected database.

Better solution might be to create a separate script that runs database creation logic.

**Comment by dkfiresky** [comment]
There are no limitations on `ConnectionOptions` in the code that require explicitly defined database option. Which means that it should be possible to run the migration before the database even exists.

Why there should be a separate script, when there are migrations already?

https://github.com/typeorm/typeorm/blob/master/src/driver/mysql/MysqlConnectionCredentialsOptions.ts#L36

https://github.com/typeorm/typeorm/blob/master/src/driver/sqlserver/SqlServerConnectionCredentialsOptions.ts#L34

```ts
/**
 * Database name to connect to.
 */
readonly database?: string;
```

**Comment by pleerock** [comment]
> There are no limitations on ConnectionOptions in the code that require explicitly defined database option.

yes it means you can do a connection and execute queries, but most of functionality won't work. That's why I tell you its not recommend you not to do so if you need functionality more then simply setuping a connection and executing a query. Even if you make database in the migrations you'll still  need to have database in connection configuration set if you want to have all typeorm features to work properly. Again, I don't recommend you to use migrations for database creation purpose. 

If you want, you can try use cli to execute your query before you run a migration, kinda:

```
typeorm query "CREATE DATABASE x IF NOT EXIST" && typeorm migrations:run
```

**Comment by dkfiresky** [comment]
I solved issue for myself. You can reopen it if you like. Thanks for help.

**Comment by btxtiger** [comment]
@pleerock This kind of solution does not work, since typeorm checks if the configured database exists before running any query. Currently there is no way to create the database with typeorm-cli. If you like to run migrations before the application starts, the database needs to already exist.

```sh
`npx ts-node ./node_modules/.bin/typeorm query "CREATE SCHEMA IF NOT EXISTS `my_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"`
@xyz.com-err npm ERR! Exit status 1
...
sh: 1: my_database: not found
{ Error: ER_BAD_DB_ERROR: Unknown database 'my_database'
```
Even creating a second config file and not setting the database name fails with message "database name missing in config".

**Comment by havenchyk** [comment]
@btxtiger could you please create a new issue with the proper description?
