### ISSUE TITLE
How to make filtering by ManyToMany relation

### ISSUE THREAD

**Issue by VLZH** [typeorm/typeorm#2225]
**Issue type:**
[x] question

**Database system/driver:**
[x] `postgres`

**TypeORM version:**
[x] `0.2.0` (or put your version here)

Hello everyone! Sorry for my English

I am trying to make select query by using Repository, but do not understand how to filter by m2m relationship
I found only one solution, it is to stay my previous method for building FindOptions and set it to a QueryBuilder through FindOptionsUtils.applyOptionsToQueryBuilder. Then make filtering by leftJoinAndSelect. What do you think about this? Or maybe there is exist another way to do this?

**Comment by mike-zenith** [comment]
I basically created the same solution for filtering relations. It works the same way as you mentioned, instead of using `repository.find`, it accepts `SelectQueryBuilder` instance and returns a new one with applied filters using either `leftJoinAndSelect` or `innerJoinAndSelect`.

If you are working on apis, I would consider using a similar approach as it gives another control layer in front of the orm / repository while keeping its flexibility.
https://martinfowler.com/eaaCatalog/queryObject.html

**Comment by VLZH** [comment]
My final decision is to use only QueryBuilder. I will do refactoring soon and maybe it will be the good lib for creating API from "Models".

**Comment by pleerock** [comment]
yes you need to use QueryBuilder. In 0.3.0 we are planning to extend find options functionality. See more information in #2100
