### ISSUE TITLE
Unexpected behavior when passing duplicate entities to repository.save()

### ISSUE THREAD

**Issue by elthrasher** [typeorm/typeorm#2251]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I noticed this problem while upgrading from typeorm 0.1.11 to 0.2.6. For better or for worse (okay, for worse), my team has a UI that sometimes passes duplicate entities to the server to be saved. For example, a payload might look like:
```
[ { id: 1, description: "test1a" },
  { id: 2, description: "test2a" },
  { id: 1, description: "test1a" },
  { id: 2, description: "test2a" }]
```
Under typeorm 0.1.11 the behavior here was be that four update statements are generated. After upgrading to 0.2.6, we observed that we get two update and two insert statements (which will likely fail).

It might be good to throw some kind of error or warning because it's clearly not my intent to update the same row twice, however the behavior under 0.1.11 was working for my app while it's now broken under 0.2.6.

In the interest of preserving backward compatibility I will quickly submit a PR that allows the above save to work, generating four update statements (two of them useless). If the maintainers of this library wish to deprecate this behavior and instead throw warnings or errors, I'm happy to contribute there as well.

**Comment by pleerock** [comment]
okay so we have to choose the right design. Options are:

1. throw an error if there is a duplication
2. "UPDATE" duplication
3. merge all values into a single result and perform a single update

Not sure if `#1` is a good solution since there can be situations like this:

```ts
user {
    avatarPhoto: {
       id: 1,
       name: "changed name"
    },
    photos: [{
       id: 1,
       description: "changed name"
    }]
}
```

(assuming partial updates and cascades) it won't update you anything and instead throw you an error. Maybe its good to throw an error in such complicated cases, Im not really sure.

`#2` produces multiple queries which is bad, but it is explicit which is important and users can find and understand the issue quickly.

`#3` is opposite side of `#2` and makes implicit and hard to understand what is happening. Plus if some properties are overlapped its not clear which one to choose.

Looks like in your PR you did `#2` and probably its something I would go for now.
