### ISSUE TITLE
Feature Request: Select Event subscribers 

### ISSUE THREAD

**Issue by mikemcguire** [typeorm/typeorm#2266]
**Issue type: Feature request**

Having a subscriber that triggers before/after a query/find event. In my current implementation the existing "before" subscribers are interacting with my Permissions class to enforce multi-tenant data separation, attaching the tenant ID to the data set for specific roles. It would also be useful to enforce this on get requests. Having this functionality in these hooks provides the ability for me to keep this logic in an area of the app that doesn't see a lot of maintenance, important to maintain the stability of our multitenant implementation, while also providing a DRY enforcement for all requests. This seems like an ideal use-case for the subscribers, but without some type of select/find/query event the functionality is incomplete.

That being said I'm new to Typeorm and may not be seeing the bigger picture, there may very well have been a good reason to avoid adding an event like this.

**Comment by pleerock** [comment]
there is an `afterLoad` listener which you can use in your event subscribers. I don't see a reason to have a `beforeLoad` listener. If you think there is, please provide a real world examples where it can be needed.

**Comment by mikemcguire** [comment]
Hmm maybe what Im trying to accomplish isn't the best use case for these hooks. 
But what I'd like to do is to apply a where clause to the query, before it executes, the clause would ensure that a user can only query data that belonged to their tenant_id

I was hoping this approach would save me a lot of code duplication, as Im using a subscriber that subscribes to every entity in my app. As well keeping any code specific to enforcing my multitenant data structure out of locations which receive a lot of maintenance.

**Comment by mikemcguire** [comment]
Mostly for simplicity and maintenance. Adding another  abstraction layer + additional dependencies just makes the whole thing a lot more complex for only needing to add a single where clause in a specific situation. 

But there are other ways to solve and doesn't sound like I'll get far with this request though. Thanks for all the help.

**Comment by Dabada** [comment]
> Mostly for simplicity and maintenance. Adding another abstraction layer + additional dependencies just makes the whole thing a lot more complex for only needing to add a single where clause in a specific situation.
> 
> But there are other ways to solve and doesn't sound like I'll get far with this request though. Thanks for all the help.

@mikemcguire how do you solve this issue without "BeforeUpdate" or a generic repository ?

**Comment by ishwar-kshirsagar** [comment]
"I don't see a reason to have a beforeLoad listener. If you think there is, please provide a real world examples where it can be needed."

Let me present my case. I am encrypting data before it goes to database and decrypting 
it after fetching. So in short database will have encrypted values and services in my node application  will have decrypted values. For select queries, afterLoad works fine for non-encrypted fields.
However it doesn't work for encrypted fields. 
e.g.  find({ where: { email: 'abc@gmail.com' }}). So for querying, I need to encrypt the where clause parameters. In this case, I need to encrypt the 'abc@gmail.com' in order to get result since database have encrypted values.
So this is clear case about why this feature is necessary. Hoping to see it in next version.

**Comment by vany0114** [comment]
@pleerock any workaround to do the beforeload? what we need to do is a generic way to implement perf counters, for example how long it takes to run a query.

**Comment by cojack** [comment]
@pleerock why this request is closed?
