### ISSUE TITLE
More verbose message instead of "Unable to connect to the database" when something is wrong

### ISSUE THREAD

**Issue by basvdijk** [typeorm/typeorm#2304]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've created a project with https://github.com/nestjs/nest Now when something is wrong with a credential or when I have an error in my entity file I got the error 'Unable to connect to the database.' instead of an error pointing to what is really wrong e.g. wrong credential, error in relationship between entities etc.

My suggestion is to make this more verbose so you know what is wrong. Now I literally have no clue where to look beside I know it has something to do with a many-to-one relationship

**Comment by pleerock** [comment]
Can you please provide more information what code produces what error (full error with trace logs)

**Comment by pleerock** [comment]
Probably nest has some wrappers that does such error. Try to setup typeorm without nest and check if you'll have the same error, or different one.

**Comment by basvdijk** [comment]
I tried around a bit and it looks like you're right. When I use typeORM separately I see the errors, guess there is a bug with nestjs which does not show the errors of the plugin underneath.

**Comment by pleerock** [comment]
btw you can set different types of logging inside typeorm connection options, for example `logging: ["error"]` to see only errors or `logging: true` to see all logs.

I guess this issue can be closed.

**Comment by nicolae536** [comment]
I have the same issue did you manage to fix it ?

**Comment by Maxcorp** [comment]
I also have the same problem. With npm run start it's works fine for me, but with npm run start:dev i have error https://prnt.sc/o3l5dp.

**Comment by ferdiebirdie** [comment]
> I also have the same problem. With npm run start it's works fine for me, but with npm run start:dev i have error https://prnt.sc/o3l5dp.

In your configuration, try changing src to dist:

`"entities": ["dist/**/*.entity.js"]`

**Comment by bmoe24x** [comment]
I had the same exact issue as @Maxcorp. Following @ferdiebirdie's advice, switching to "dist" worked.

**Comment by silent528** [comment]
> > 我也有同样的问题。使用npm run start对我来说很好，但是使用npm run start：dev我有错误https://prnt.sc/o3l5dp。
> 
> 我从此[链接](https://codeburst.io/typeorm-by-example-part-1-6d6da04f9f23)找到了解决方案。在您的配置中，尝试将src更改为dist：
> 
> `"entities": ["dist/**/*.entity.js"]`

thank you! it's running

**Comment by sashiksu** [comment]
nestJs normally shows **Unable to connect to the database** message and it's small info to dig into find problem. So to start fix this issue, try to connect to db via CLI. In my case I went to the postgres bin folder and perform following command.
`psql -h localhost -p 5432 -u postgres`

_psql -h <host>-p <portNumber>-u <username>_
and it asks to enter password. So in this step enter password which you given to the **ormConfig** file.
if it is let you in double check config file's other parameters.
Sometimes even you enter the correct password it won't let you in the db in CLI mode same time you are allowing in GUI. This happens when you install postgres tools separately. (_Still you could find the solutions to resolve this if you google it, such as **changing ph_hba.config file** and later **restarting postgresSql** service_) It's easy to just uninstall all components and install whole postgres package.
