### ISSUE TITLE
TypeORM Angular 6 sample/seed application or a how-to setup

### ISSUE THREAD

**Issue by codessentials** [typeorm/typeorm#2309]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[x] `sqljs`
[ ] `react-native`
[x] `webSql`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Is it possible to provide an Angular 6 sample/seed application or a how-to to get such application setup?
It seems Angular CLI 6 is different than before (you cannot eject webpack anymore?!) so it would be great to use that (newest) version.

**Comment by pleerock** [comment]
I have already provided you information via email. Typeorm is not frontend-specific and does not care what framework you use. If you use typeorm in the browser but still need webpack config to change then ask solution from angular team how to use custom webpack config (I think there are hacky ways?)

**Comment by aammfe** [comment]
> I have already provided you information via email. Typeorm is not frontend-specific and does not care what framework you use. If you use typeorm in the browser but still need webpack config to change then ask solution from angular team how to use custom webpack config (I think there are hacky ways?)

Please tell us what information you have provided in email. bcs I m having same issue. 

Thanx

**Comment by ZiadJ** [comment]
Angular is one of the most popular frameworks out there that are based on Typescript on the frontend yet TypeORM which is also based on it doesn't care to provide a working example on how to integrate with it? I'm not sure I can get that.

**Comment by pleerock** [comment]
@ZiadJ right, angular is popular, and following your logic we shall also create samples for react/vue/preact and something else? And even if we do so, the most important is that even we create such sample, shall we create it with shared models or not? Because its architecture-level decision and some prefer having models shared and some not. Which one we should choose? And if we choose to share models, its going to mean for people that we recommend to do same when using angular+typeorm. However I can't recommend this approach to anyone.

**Comment by ZiadJ** [comment]
Those alternative frameworks are not based on Typescript so they're not really within scope here I guess, at least not if resources are lacking to consider them all.
