### ISSUE TITLE
breaking changes to NamingStrategy

### ISSUE THREAD

**Issue by vance** [typeorm/typeorm#2345]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.2.0` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

we have a custom naming strategy for a project, and we are updating from 0.1.x to 0.2.x

currently we have:

```
  public foreignKeyName(
    tableName: string,
    columnNames: string[],
     referencedTableName: string,
     referencedColumnNames: string[],
  ): string {
    return [tableName]
      .concat(columnNames)
       .concat([`_${referencedTableName}`])
       .concat(referencedColumnNames)
      .join('_');
  }

// result: 
// local_table_local_column__remote_table_target_column

```

but the last two params are removed. Can we assume param 1 and 2 are now the "referenced" table? 
is there control over the linking character between original and fk, or is `_` assumed?

we also had indexName with 3 Params, but param 1 is now removed in 0.2.0:

```
  public indexName(
    customName: string | undefined,
    tableName: string,
    columns: string[],
  ): string {
    return (
      customName ||
      [tableName]
        .concat(columns)
        .concat(['fkey'])
        .join('_')
    );
  }
```
i think this was due to bug with generated join tables... maybe `custom || tableName...` not needed anymore? 
clarification much appreciated!

**Comment by pleerock** [comment]
Those changes were made by @AlexMesser . As he told me, first change was made because those parameters were not used anymore - he removed them. Second change was made because check for "customName" was extract out of the naming strategy.

Naming strategy is something we have in future plans to completely revisit and refactor thats why it still lefts undocumented functionality. Feel free to contribute and add missing options if you need them.

**Comment by vance** [comment]
Hm. It seems that removing the parameters from the interfaces of these method blocks upgrade from 1.x. 

For instance we overrode many of these methods to use non-sha, human readable names. Without the missing parameters, we are unable to define names in the same way that our current database uses. 

We also used the pattern for unique constraints etc, which also do not provide enough options. I could submit a PR that adds them back, but it seems if it is due to refactor, that those changes may be lost. 

**what was the intent in refactoring the naming strategy?** 

Knowing that may be helpful if I undertake that. I'm a little nervous as each method has dozens of references throughout the app.

```
    foreignKeyName(tableName: string, columnNames: string[], referencedTableName: string, referencedColumnNames: string[]): string {
        const key = `${tableName}_${columnNames.join("_")}_${referencedTableName}_${referencedColumnNames.join("_")}`;
        return "fk_" + RandomGenerator.sha1(key).substr(0, 27); // todo: use crypto instead?
    }
```

**Comment by vance** [comment]
May be able to contribute. Gathering minimum requirements to allow for Postgres community standards for naming. I think it would be similar to adding back the parameters used in the 0.1.x implementations, but keeping the new defaults provided in 0.2.x

**Comment by pleerock** [comment]
I remember only few people who told they are using naming strategy stuff. Its not documented feature, you know. And as I told its not documented because its not complete yet. If you want to contribute on some options we can add them but in the future we may change them once we finish naming strategy refactoring. 

What I can also suggest is to take owning on this feature, implement everything user might need, document everything and make this functionality stable, finally.

So, feel free to contribute!
