### ISSUE TITLE
repository insert does not return auto-generated id if @Column decorator used

### ISSUE THREAD

**Issue by hiyelbaz** [typeorm/typeorm#2364]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```
...
var myclass = new MyClass();
await repository.insert(myclass);
console.log(myclass.id);
```

Returns auto-generated id if  "PrimaryGeneratedColumn" used:
```
class MyClass {
    @PrimaryGeneratedColumn()
    id: number;
}
```

Does not return auto-generated id if "Column" used:
```
class MyClass {
    @Column("integer", {
        generated: true,
        nullable: false,
        primary: true,
        name: "id"
    })
    id: number;
}
```

**Comment by pleerock** [comment]
thanks for the report, maybe second one even do not create a generation strategy.

**Comment by SimantoR** [comment]
I wanted to report on this as well:

typeorm: 0.2.22
database: sqlite3

schema:
```
@Entity('transactions')
export class Transaction {
  @PrimaryGeneratedColumn('rowid')
  id: number;

  @Column({ type: 'real', precision: 3, nullable: false })
  price: number

  @Column({ type: 'real', precision: 3, nullable: false })
  paid: number;

  @Column('datetime')
  timestamp: Date;

  @Column({ enum: PaymentMethod })
  paymentMethod: PaymentMethod;
}
```
and execution code:
```
const transaction = database.create(Transaction, {
  paid: value,
  timestamp: new Date(),
  price: subTotal + hst_gst,
  paymentMethod: PaymentMethod.credit
});
database.save<Transaction>(transaction)
  .then(t => console.log(t))
  .catch((err: Error) => console.warn(err.message));
```

when the value is logged:
![image](https://user-images.githubusercontent.com/34289663/74096016-b7c64280-4ad3-11ea-84db-d8d34452c7e6.png)

**Comment by twigs67** [comment]
Any update on this?

**Comment by dremie** [comment]
Can confirm for MySQL using `repository.save`. [This workaround](https://github.com/typeorm/typeorm/issues/2364#issuecomment-398430948) is not ideal since there's a difference in semantics and table schema between `@PrimaryGeneratedColumn` and `@Generated + @Column`. Imo you shouldn't have to make the field a primary key just to get the  `.save` or `.insert` methods to return the field in the result set, e.g. when you're using (a) different field(s) as PK.

In the latter case, you can still follow the suggestion above and alter your table such that the previously primary key(s) are now "just" unique keys (https://typeorm.io/#decorator-reference/unique).
