### ISSUE TITLE
Eager load relations?

### ISSUE THREAD

**Issue by TylerDev6** [typeorm/typeorm#24]
Hey pleerock, been exploring your library for a bit now and can't seem to figure out how to have an entity's relations returned alongside it, at least, generically at any rate. my entityManager.findOne() is returning the entity without even a reference to the relation.

**Comment by TylerDev6** [comment]
Hibernate handled this with FetchType.EAGER and FetchType.LAZY

**Comment by pleerock** [comment]
personally Im not a big fan of eager loading, which is convenient, but mostly feature that dramatically decrease your app's performance. However I added experimental support of eager loading in typeorm. I can't guarantee you that everything will work perfectly because its an experimental feature. Also in node.js its not as easy to make lazy relations as in java because of its asynchronous nature. Take a look into [these samples and try them](https://github.com/typeorm/typeorm/tree/master/sample/sample18-lazy-relations)

**Comment by pleerock** [comment]
note that you must work with promises in make lazy relations to work - you need to define property's type as promise, write to property a promise, and get it as a promise

**Comment by TylerDev6** [comment]
I'd be fine with lazy loading if it would at least return me something....

my relationship is described as follows:

@OneToOne(type => Person, { cascadeInsert: true, cascadeUpdate: true, onDelete: "CASCADE"})
	@JoinColumn()
	@JsonMember({ type: Person })
	public person: Person;

But my instance doesn't actually contain a "person" property. It's not fulfilled whatsoever.

**Comment by TylerDev6** [comment]
ideally I'd prefer public person: Person|number; where number is the id. This wouldn't require a join either.

**Comment by pleerock** [comment]
i recommend you to use query builder and join the data you need. Its most efficient way to do things

**Comment by TylerDev6** [comment]
that's true, but can't be done generically. The class of the join needs to be known. :(

**Comment by pleerock** [comment]
btw if you only need a person id, there is no need to join a relation. You can use `@RelationId` decorator, see example [here](https://github.com/typeorm/typeorm/blob/master/test/functional/decorators/relation-id/entity/Post.ts#L23)

**Comment by TylerDev6** [comment]
Ok, that's helpful, thanks.

**Comment by 19majkel94** [comment]
> However I added experimental support of lazy loading in typeorm.

Could this be implemented by setters and getter like in Hibernate?

```typescript
@OneToMany(type => Post, post => post.author, {
    cascadeInsert: true,
    cascadeUpdate: true
})
private _posts: Promise<Post[]>;

getPosts(): Promise<Post[]> {
    return this._posts;
}

set posts(posts: Post[]) {
    this._posts = Promise.resolve(posts);
}
```

Unfortunately, in TS `'get' and 'set' accessor must have the same type` :disappointed:

**Comment by pleerock** [comment]
In TypeScript there is no need to defined a private property and getters and setters for it until you really need it like in Java, because getter and setters are supported on the language level and it resolves all the problems that Java trying to resolve by conventing us to create getter and setter methods for each property. 

If you are interested in lazy relations take a look at [this sample](https://github.com/typeorm/typeorm/tree/master/sample/sample18-lazy-relations)

**Comment by 19majkel94** [comment]
I have analized this sample and I don't like this part:
```typescript 
post.author = author.asPromise();
post.author = Promise.resolve(author);
   
for (category of await post.categories) {
    ...
}
```

It's hard to read and think that property is a promise and you need to wrap object to promise to store/assign.
It would be much more readable by using explicit function which returns the promise:
```typescript
post.author = author;

for (category of await post.getCategories()) {
    ...
}
```
I know I have to implement setter and getter - like now I have to remember to implement the helper `asPromise()` (or naming it `toPromise()`).

**Comment by pleerock** [comment]
For me `await post.categories` is already good, and I don't see any reason to create a method for it. But if you want you should be able to do it without problems. For your example:

```typescript
set posts(posts: Post[]) {
    this._posts = Promise.resolve(posts);
}
```

You can't do like this, this is a logically correct limitation of the language. You need to define your method like this:


```typescript
set posts(postsPromise: Promise<Post[]>) {
    this._posts = postsPromise;
}
```

**Comment by 19majkel94** [comment]
The best reason why getter shouldn't return `Promise` is that you can't use `async` keyword there, as in the constructor. It's confusing where you have to await for property or have `object.property.then()` syntax.

For me is better to have explicit function which return a Promise for I'm awaiting (the tsc marks this code as a valid code so I can do this):
```typescript
@ManyToOne(type => Author, author => author.posts, {
    cascadeInsert: true,
    cascadeRemove: true,
    onDelete: "SET NULL"
})
_author: Promise<Author|null>;

getAuthor() {
    return this._author;
}

set author(author: Author) {
    this._author = Promise.resolve(author);
}
```
Usage:
```typescript
post.author = author;
post.getAuthor().then(author => {
    if (author) {
        author.name = "19majkel94";
    }
});
```

But it's a bad idea because it let you to use `let author: Author = post.author` even if you haven't implemented `get author()`. You can only do it contrariwise - implement `get author()` and when try to set you will get error that `author` is readonly.

So it looks like we has to stick with implicit `Promise` property or explicit implement `setAuthor` and `getAuthor` methods until typescript will be able to do this kind of trick :wink:
