### ISSUE TITLE
ManyToMany with cascadeRemove?

### ISSUE THREAD

**Issue by Tobias4872** [typeorm/typeorm#243]
Hi,

I have stumbled upon a couple of examples where a ManyToMany decorator can also hold options with "cascadeRemove" property. But in 0.0.8 which I am using right now, the only options I can put to a ManyToMany decorator are "cascadeInsert" and "cascadeUpdate".

How would I setup a ManyToMany relation correctly, so that the entries in the relation table are removed when one of the related entities is removed?

Thanks,
   Tobias.

**Comment by pleerock** [comment]
Hi,

There is a huge pain with `cascadeRemove` option. Its one of the most complex feature in terms of implementation in ORM and source of lot of issues and bugs.

One of the problem is when user sets cascadeRemove from both sides it causes circular removes, sometimes unexpected. Probably I'll return this option back, maybe with some new changes, I'll need to think more about cascades and reimplement some of its parts, and this takes really LOT OF TIME, because as I said cascades are the MOST complex part of ORM. Unfortunately. 

Feel free to go deeper into problems with cascades inside the code, if you want, I totally need some help with managing that complexity. 

But for now I'll recommend to iterate and manually remove all cascade objects.

Thanks,
Umed

**Comment by Tobias4872** [comment]
Hi,

thanks for your answer. I completely understand the problem here. I am afraid I don't have the abilities to help you on this, though. Will use the manual clean-up for now.

This is good to close.

Tobias.

**Comment by pleerock** [comment]
Cascades remove concept was completely removed from the ORM and won't be available from 0.2.0. Use `onDelete` property of the relation to set a database-level cascade removes.
