### ISSUE TITLE
How can I create 'IS NULL' in my SQL statement by QueryBuilder?

### ISSUE THREAD

**Issue by JeongJun-Lee** [typeorm/typeorm#2525]
**Issue type:**

[*] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[*] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[*] `0.2.3` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

For example, the SQL statement will be made as being intended by Repository
```
await productsRepository.find({
  relations: ['productDetails'],
  where: {isInactive: null}
});
```
```
WHERE "Products"."isInactive" IS NULL
```

But, the SQL statement will not be made as being intended by QueryBuilder
```
await productsRepository.createQueryBuilder('Products')
        .innerJoin("Products.productDetails", "ProductDetails")
        .where("Products.isInactive = :isInactive", {isInactive: null})
        .getMany();
```
```
WHERE "Products"."isInactive" = ? -- PARAMETERS: [null]
```
In result, I cannot get my wanted values by this wrong SQL statement.

**Comment by JeongJun-Lee** [comment]
But I think the consistency is needed as same behavior of both Repository and QueryBuilder.

**Comment by imnotjames** [comment]
The consistency isn't quite there because you're explicitly writing it as equals in the query builder where as in the find it's some find options.  This is working as intended.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
