### ISSUE TITLE
generated primary key will be deleted first and then created

### ISSUE THREAD

**Issue by JingMo** [typeorm/typeorm#2537]
**Issue type:**

[ ] question

**Database system/driver:**

[ ] `mysql` 

**TypeORM version:**

[ ] `0.2.0` 

**Steps to reproduce or a small repository showing the problem:**

Hi, I have a question:
  first: I get enties by using  typeorm-model-generator;
  second: When starting a program and when data already exists in the database table and when connecting to the database, the generated primary key in the source table will be deleted first and then created. Is that the process? How to avoid it. (synchronize: true)
  
  has try:
    dropSchma: fase ->invalid

  and other error:
    @Column('timestamp', {
        nullable: true,
        default: 'CURRENT_TIMESTAMP',
        name: 'LastModifyTime',
     })
     LastModifyTime: Date;

    this is exported by using typeorm-model-generator, but connect error because this colum

**Comment by pleerock** [comment]
Maybe its better to create issue in the typeorm-model-generator repository?

I don't know if it follows typeorm's requirements on column properties such as primary key names, foreign key names, etc. Because those names are important, and if lets say your primary key constraint name in your database is different from what typeorm expects, typeorm can try to re-create this constraint name, but to do so it needs to drop your primary key because you can't change constraint name without dropping primary key. Maybe its not the case, I just provided you information that typeorm requires some specific naming in your database.

**Comment by pleerock** [comment]
Looks like you didn't read my message.
