### ISSUE TITLE
[Migration] One to One: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by cjackson234** [typeorm/typeorm#2539]
**Issue type:**

[ x ] question
[ x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have two entities with bi-directional one to one relationships (as shown in the documentation here: http://typeorm.io/#/one-to-one-relations)

When I generate a new migration adding a property on 'Profile' it works. However, if I have data on the 'User' with a foreign key to 'Profile' running the migration fails. 

> QueryFailedError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

**Comment by pleerock** [comment]
its not an issue, its a behaviour lead by your changes, try to figure out a logical reason why sql gives you such error.

**Comment by pleerock** [comment]
I don't know why it gives you such error. Can you explain?

**Comment by cjackson234** [comment]
Is there anything else I can provide details wise?

**Comment by pleerock** [comment]
If you already have a data inside RDBMS will give you such error, because you asked him to add a non-nullable column, but if he add this column all values for exist data for this column can't be null, and he simply doesn't know what value it should set. 

Its not something that typeorm can handle - its all about your data, and only you know how to properly fill the gaps in this data. In such case you either need to add column with `nullable: true` or set default value so it get know what value should go by default.
