### ISSUE TITLE
Order by joined column

### ISSUE THREAD

**Issue by martinsura** [typeorm/typeorm#2570]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hello, is possible order query by joined column?

```
const [dbUsers, total] = await getManager().findAndCount(DbUser, {
  skip: skip(input.page),
  take: input.page.pageSize,
  order: { "profile.name" },
  relations: ["profile"]
 });
```
In my project i am getting "profile.name column was not found in the DbUser entity."

Any ideas?

Thanks

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by pleerock** [comment]
You can do it, however you need to use QueryBuilder instead of find method.

In `next` (npm i typeorm@next) you can do it via find options, example is [here](https://github.com/pleerock/typeorm/blob/abd4212f0c5207b3829e0a01b820058f1c9bad0f/test/functional/find-options/basic-usage/find-options-order.ts#L142).

**Comment by martinsura** [comment]
Thanks!
