### ISSUE TITLE
Cannot read property 'joinColumns' of undefined

### ISSUE THREAD

**Issue by locuraskyline** [typeorm/typeorm#2603]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7`

**Steps to reproduce or a small repository showing the problem:**
```javascript
@Entity()
export class Cuota {
    @PrimaryGeneratedColumn()
    id:number;

    @ManyToOne(type => CuotaEstado, estado => estado.id)
    @JoinColumn()
    estado:CuotaEstado;

    @Column({ nullable: true })
    fecha_pago:Date;

    @OneToMany(type => ItemCuota, item => item.Cuota)
    items:ItemCuota[];
}

@Entity()
export class ItemCuota {
    @PrimaryGeneratedColumn()
    id:number;
    
    @Column()
    monto:number;
    
    @ManyToOne(type => Concepto, concepto => concepto.id)
    concepto:Concepto;

    @ManyToOne(type => Cuota, cuota => cuota.items)
    Cuota: number;
}

exports.get = async function(req:Request,res:Response){
    const userRepository = getManager().getRepository(Cuota);
    const cuota = await userRepository.findOne(1, { relations:["estado", "items"] });
    console.log(cuota);

    res.status(200).send(cuota);
}
```

**Output**
TypeError: Cannot read property 'joinColumns' of undefined
    at C:\....\src\query-builder\SelectQueryBuilder.ts:1446:61
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (C:\....\src\query-builder\SelectQueryBuilder.ts:1416:57)
    at SelectQueryBuilder.getQuery (C:\....\src\query-builder\SelectQueryBuilder.ts:51:21)
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (C:\....\src\query-builder\QueryBuilder.ts:386:28)
    at SelectQueryBuilder.<anonymous> (C:\....\src\query-builder\SelectQueryBuilder.ts:1885:40)
    at step (C:\....\node_modules\typeorm\query-builder\SelectQueryBuilder.js:42:23)
    at Object.next (C:\....\node_modules\typeorm\query-builder\SelectQueryBuilder.js:23:53)
    at C:\....\node_modules\typeorm\query-builder\SelectQueryBuilder.js:17:71
    at new Promise (<anonymous>)

**Comment by marmiha** [comment]
same problem here

**Comment by marmiha** [comment]
```
@ManyToOne(type => Cuota, cuota => cuota.items)
    Cuota: number;
```
Should be:

```
@ManyToOne(type => Cuota, cuota => cuota.id)
@JoinColumn({name: "$column_name"})
    Cuota: number;
```

Where `$column_name` is the name of the column, that stores the foreign key of the `Cuota table` (the column, that has a relation to the other `Cuota table` for example `couta_id`).

That is because, you don't relations to `couta.items` but `cuota.id`, because `cuota.items` is not the actual nor it exists as a column in `Cuota table` (`cuota.items` is a relation, for TypeOrm, but in items table you have to specify to which column in that table, the relation is connected to ).

Sorry, this isn't my mother language. Hope i helped 👍

**Comment by marmiha** [comment]
Try this too:
```
@ManyToOne(type => Cuota)
@JoinColumn({name: "$column_name})
    Cuota: number;
```

**Comment by marmiha** [comment]
Actually i might be completley wrong => check this: https://github.com/typeorm/typeorm/issues/2016

**Comment by Kononnable** [comment]
@locuraskyline 
Did you resolve your issue?

**Comment by SylvainEstevez** [comment]
Same error here, although my entities are declared differently.

```typescript
import { Column, createConnection, Entity, JoinColumn, ManyToOne, OneToMany } from 'typeorm';
import { entityId } from './packages/common/src/utils/typed-object-id';
import { DatabaseConfig } from './packages/old-orchestrator/src/config/database';
import { SnakeNamingStrategy } from './packages/typeorm/snake-naming-strategy';

@Entity({ name: 'cart' })
class Cart {
  @Column({ type: 'varchar', primary: true, name: 'id', nullable: false })
  private _id: string;

  @Column({ type: 'varchar', nullable: false, name: 'title' })
  private _customer_id: string;

  @OneToMany(() => Item, item => item.cart, {
    eager: true, // I've tried a manual query instead of eager loaing, same error
    cascade: true
  })
  private _items: Item[];

  public get id() {
    return this._id;
  }

  public get customer_id() {
    return this._customer_id;
  }

  public get items() {
    return this._items;
  }

  public constructor(attributes?: { id: string, customer_id: string, items: Item[] }) {
    if (attributes) {
      this._id = attributes.id;
      this._customer_id = attributes.customer_id;
      this._items = attributes.items;
    }
  }
}

@Entity({ name: 'item' })
class Item {
  @Column({ type: 'varchar', primary: true, name: 'id', nullable: false })
  private _id: string;

  @Column({ type: 'varchar', nullable: false, name: 'description' })
  private _description: string;

  @Column({ type: 'varchar', name: 'cart_id', nullable: false })
  private _cart_id: string;

  @ManyToOne(() => Cart, cart => cart.items)
  @JoinColumn()
  private _cart?: Cart;

  public get id() {
    return this._id;
  }

  public get description() {
    return this._description;
  }

  public get cart_id() {
    return this._cart_id;
  }

  public get cart() {
    return this._cart;
  }

  public constructor(attributes?: { id: string, description: string, cart_id: string, cart?: Cart }) {
    if (attributes) {
      this._id = attributes.id;
      this._description = attributes.description;
      this._cart_id = attributes.cart_id;
      this._cart = attributes.cart;
    }
  }
}

createConnection({
  type: 'postgres',
  username: DatabaseConfig.username,
  password: DatabaseConfig.password,
  host: DatabaseConfig.host,
  database: DatabaseConfig.database,
  schema: DatabaseConfig.schema,
  entities: [Cart, Item],
  namingStrategy: new SnakeNamingStrategy(),
  name: DatabaseConfig.database,
  logging: true
}).then(async connection => {
  const cartId = entityId();
  
  const cart = new Cart({
    id: cartId,
    customer_id: 'john',
    items: [new Item({
      id: entityId(),
      cart_id: cartId,
      description: 'something'
    })]
  });

  await connection.getRepository(Cart).save(cart); // Works fine

  await connection.getRepository(Cart).findOne(cartId); // Throws

  process.exit(0);
}).catch(err => {
  console.error(err);
  process.exit(1);
});
```

Logs:

```
query: SELECT "Cart"."id" AS "Cart_id", "Cart"."title" AS "Cart_title" FROM "public"."cart" "Cart" WHERE "Cart"."id" IN ($1) -- PARAMETERS: ["5c61b8bda664ba657e3de574"]
query: SELECT "Item"."id" AS "Item_id", "Item"."description" AS "Item_description", "Item"."cart_id" AS "Item_cart_id" FROM "public"."item" "Item" WHERE "Item"."id" IN ($1) -- PARAMETERS: ["5c61b8bda664ba657e3de575"]
query: START TRANSACTION
query: INSERT INTO "public"."cart"("id", "title") VALUES ($1, $2) -- PARAMETERS: ["5c61b8bda664ba657e3de574","john"]
query: INSERT INTO "public"."item"("id", "description", "cart_id") VALUES ($1, $2, $3) -- PARAMETERS: ["5c61b8bda664ba657e3de575","something","5c61b8bda664ba657e3de574"]
query: COMMIT
TypeError: Cannot read property 'joinColumns' of undefined
    at /Users/sestevez/Documents/Projects/Volvo/laas/src/query-builder/SelectQueryBuilder.ts:1447:60
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (/Users/sestevez/Documents/Projects/Volvo/laas/src/query-builder/SelectQueryBuilder.ts:1417:57)
    at SelectQueryBuilder.getQuery (/Users/sestevez/Documents/Projects/Volvo/laas/src/query-builder/SelectQueryBuilder.ts:52:21)
    at SelectQueryBuilder.<anonymous> (/Users/sestevez/Documents/Projects/Volvo/laas/src/query-builder/SelectQueryBuilder.ts:1794:50)
    at step (/Users/sestevez/Documents/Projects/Volvo/laas/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/sestevez/Documents/Projects/Volvo/laas/node_modules/tslib/tslib.js:114:57)
    at /Users/sestevez/Documents/Projects/Volvo/laas/node_modules/tslib/tslib.js:107:75
    at Promise (<anonymous>)
    at Object.__awaiter (/Users/sestevez/Documents/Projects/Volvo/laas/node_modules/tslib/tslib.js:103:16)

Process finished with exit code 1
```

Am I doing something wrong here @Kononnable @pleerock?

**Comment by OwenCalvin** [comment]
@pleerock Same issue here

**Comment by OwenCalvin** [comment]
Okay with the debugger I found the issue from here:
https://github.com/typeorm/typeorm/blob/23137768141c211f0c35276ea4d531c61e2fe7c2/src/metadata-builder/EntityMetadataBuilder.ts#L654
With getter and setters, the decorators cannot resolve the reversePropertyPath...

**Comment by beautyfree** [comment]
Perhaps such an example will help someone solve the problem:
```
  @Field(() => Int)
  @Column({ name: "userId", type: "bigint" })
  @ManyToOne(() => User, { onDelete: "CASCADE" })
  @JoinColumn({ name: "userId", referencedColumnName: "id" })
  user: User
```

**Comment by pratham2003** [comment]
I observed that removing `eager: true` stops the error in my case.

**Comment by imnotjames** [comment]
By adding the join columns to the first response here I cannot replicate.

Can someone provide a reproducible example?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
