### ISSUE TITLE
Expose a method to add subscribers dynamically

### ISSUE THREAD

**Issue by LeoMartinDev** [typeorm/typeorm#2630]
**Issue type:**

[ ] question
[ ] bug report
[ * ] feature request
[ ] documentation issue

**TypeORM version:**

[ * ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Based on this __nestjs__ issue https://github.com/nestjs/typeorm/pull/27 - 
it would be great to be able to add subscribers using a public TypeORM method.

Our current solution (hack) is to mutate `connection.subscriber` :
```
      Object.assign(connection, {
        subscribers: [].concat(connection.subscribers).concat([instance]), // instance is a Subscriber instance
      });
```

Even if it works with current TypeORM release, it might be broken in next release.

**Comment by frozenex** [comment]
+1

**Comment by dilame** [comment]
+1

**Comment by pleerock** [comment]
Can you please explain me why you can't simply do `connection.subscribers.push()` ?

**Comment by dilame** [comment]
Because it is not convenient, this feature is not documented and used by TypeORM team under the hood, kinda private, and coud be changed in any minor release.

**Comment by pleerock** [comment]
so, you are confirming that we can use `connection.subscribers.push(instance)`? If yes, then I'm going to close this issue.

> this feature is not documented and used by TypeORM

every detail can't be documented, some details aren't worth documentation since they can complicate simple docs. This feature request is a bit specific, so I think for somebody who is searching, he can find this api easily. Also, its convenient, I don't find why not. Also, anything can be changed, really... so just use it in the case if fits your purpose, and be flexible on reacting to changes. Particularly this api shouldn't be changed in minor releases for sure.

**Comment by pleerock** [comment]
but probably we can add this to docs, to subscriber section. Feel free to PR.

**Comment by pleerock** [comment]
I'll close this one, please let me know if provided solution doesn't work for you
