### ISSUE TITLE
createQueryBuilder relation remove works only if using ID

### ISSUE THREAD

**Issue by Kalhama** [typeorm/typeorm#2632]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest` (0.2.0)
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm working with a backend where one organisation could have multiple admins (we call them coordinators). One user could be coordinating multiple organisations, so relation between is Many-to-many -relation.

I'm using queryBuilder to delete relations in a following way
```typescript
const removeCoordinatorFromOrganisation = async (organisationId, userId) => {
  // userId means coordinator
  const organisation = await getConnection.getRepository(Organisation).findOneOrFail(organisationId)

  await this.organisation
    .createQueryBuilder()
    .relation('coordinators')
    .of(organisation)
    .remove(userId)

  const org = await this.organisation.findOneOrFail({
    where: { id: organisationId },
    relations: ['coordinators']
  })

  return org.coordinators
}
```

This doesn't remove relation unless I change the queryBuilder to use organisationId instead of organisation entity.

**Comment by leojkwan** [comment]
ran into the same problem!

**Comment by iMobs** [comment]
I'm seeing this happen on many to many relationships when there is a mix of id and object with id given. For example:
```typescript
        await connection
            .createQueryBuilder()
            .relation(Post, "images")
            .of({ id: 3 }) // object with id
            .remove(3); // just the id
```

This is happening because in RelationRemover it is only checking whether the `firstColumnVal` is an instance of an object [for both the first and second column](https://github.com/typeorm/typeorm/blob/7808bba416c0b1cf9850194499e8c8d3502657b7/src/query-builder/RelationRemover.ts#L93). I'll work on a fix for this later.
