### ISSUE TITLE
Repeatable migrations

### ISSUE THREAD

**Issue by gintsgints** [typeorm/typeorm#2678]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I am thinking on implementing repeatable migrations like there - https://flywaydb.org/getstarted/repeatable

They are very useful for procedure&function like code in database. Migration system is able to detect changes in procedure source and apply procedure/function changes accordingly.

Before implementing this, things we have to discuss is:

* what would be file/class naming for repeatable migrations
* what way to keep track version of procedures in database (mdsum of migration files is first idea)

**Comment by Bessonov** [comment]
-1. This makes migrations unstable. I'm wonder why flyway supports that in the first place, because they didn't supported downgrades for long time because of possible side effects. See [this answer](https://stackoverflow.com/a/4959332/926620) on SO.

**Comment by gintsgints** [comment]
@Bessonov would like to know how repeatable migration makes migrations unstable.

**Comment by Bessonov** [comment]
@gintsgints because of side effects. Imagine:

1. Repeatable migration (for example a view), run everytime
2. Migration, which is relies on repeatable migration (use the view), run once

Now, break contract between 1 and 2 (because repeatable scripts are not immutable). Result: In best case you notice it only if you apply migrations from scratch. In worst case you don't notice it at all and shred you data.

Compare to current way:

1. Non-Repeatable migration (for example a view), run once
2. Migration, which is relies on repeatable migration (use the view), run once
3. Migration, wich changes 1. (change the view), run once

Now, you can be sure that at least 1 and 2 works as before in mostly deterministic way. Sure, this is just a simple example. But in real word you have complicated or even complex scenarios. You don't want to make things harder.

**Comment by gintsgints** [comment]
How about we think on some solution in between. I just need way to do branching/versioning procedures/functions:

- one thing is, - repeatable migration is not run _everytime_ it is run only when changes are detected.
- other, solution of scripts versioned/stored in different file & migrations applied in normal/manual way.
- another way to go I think of, is implement Procedure annotation. And then do it's migrations semiautomatical way.

**Comment by roffelsaurus** [comment]
I don't understand the point of that feature in flyway. What is wrong with copy pasting your original migration file containing the view/function/procedure "create or replace"  script, then treat is a new migration? source control and file names is better versioning than only source control. -1

**Comment by gintsgints** [comment]
@roffelsaurus do you suggest to copy over whole procedure and then probably commit it to source just to update one line?

**Comment by gintsgints** [comment]
> I don't understand the point of that feature in flyway. What is wrong with copy pasting your original migration file containing the view/function/procedure "create or replace" script, then treat is a new migration? source control and file names is better versioning than only source control. -1

Do you see what's changed in procedure in this way?
