### ISSUE TITLE
Is it possible to flush schema metadata?

### ISSUE THREAD

**Issue by stevefan1999-personal** [typeorm/typeorm#2688]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Following up on https://github.com/typeorm/typeorm/issues/2687, I was able to get a GraphQL server to run on Razzle. However, it seems like the schemas will be duplicated during hot reload, so, is there anyway I can update/flush the old schema? 

I tried to delete the metadata storage:
```ts
  if ((global as any).typeormMetadataArgsStorage) {
    delete (global as any).typeormMetadataArgsStorage
  }
```
But it does no help since the metadata are binded at import time so the repo will not be re-created.

**Comment by Zn4rK** [comment]
Many issues with HMR (and serverless-offline) is due to the fact that the metadata storage is a global variable. I wonder if the storage couldn't be local to the module instead? 

I tried the scenarios written here: https://github.com/typeorm/typeorm/blob/25c00324e974f82f8f3e32bb3ea7a4b65e275bf9/src/index.ts#L168-L175
And it works just fine by doing like this instead:
```ts
const typeormMetadataArgsStorage = new MetadataArgsStorage();

export function getMetadataArgsStorage(): MetadataArgsStorage {
    return typeormMetadataArgsStorage;
}
```

What am I missing?

As a workaround for right now, @stevefan1999-personal, you could use something like:
https://github.com/adierkens/webpack-inject-plugin

```js
if (offline) {
  offlinePlugins.push(
      new InjectPlugin(() => (`global.TypeGraphQLMetadataStorage = undefined;`),
  );
}
```

It's a bit hacky, but it should work...

**Comment by imnotjames** [comment]
We could make some of the storage local to connections - but it would require a whole lot of rewriting of how we manage decorators, entities, etc - I think it'd be a good idea but difficult to get started and get momentum on.

At this time, flushign the metadata isn't supported as you'd not be able to reload the metadata again.

If you'd like to talk through workarounds to get this working please reach out through our support channels.

For general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
