### ISSUE TITLE
Column with transformer is not normalized for update

### ISSUE THREAD

**Issue by andreasrueedlinger** [typeorm/typeorm#2703]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[x] all

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
If you add a transformer to a column which serializes the property value to the desired format, this transformation is not considered in `SubjectChangedColumnsComputer` and the column is always marked as changed if you are working with a complex object type for the column which is serialized to string for example.

```ts
export interface MyComplexType {
  foo: string;
  bar: number;
  xy: Date;
}

export const myTransformer: ValueTransformer = {
  from: dbValue => {
    const parsed = (dbValue || '').split(',');
    return { foo: parsed[0], bar: +parsed[1] || undefined };
  },
  to: entityValue => `${entityValue.foo},${entityValue.bar}`
};

@Entity('foo')
export class Foo {
  @PrimaryGeneratedColumn({ type: 'int' })
  readonly id: number;

  @Column('text', { transformer: myTransformer })
  transformed: MyComplexType;
}
```

Why is `column.getEntityValue()` not called with the transform flag to true in `computeDiffColumns` of `SubjectChangedColumnsComputer`?

**Comment by andreasrueedlinger** [comment]
Just noticed another bug:
https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/persistence/SubjectChangedColumnsComputer.ts#L85
Should be `"simple-array"` and not `"sample-array"`!

**Comment by PachowStudios** [comment]
Any update on this?

Because we transform our numeric columns to BigNumber types, this causes all our numeric columns to always be detected as changed.

If there is a good reason for not calling `getEntityValue` with the transform flag, can you please at least provide an option to either force it to pass the transform flag, or provide a custom equality comparison? (The latter would probably be the best long term solution).
