### ISSUE TITLE
@UpdateDateColumn updates the column value without precision

### ISSUE THREAD

**Issue by d-yokoi** [typeorm/typeorm#2718]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

- Create an entity class which has a column decorated with `@UpdateDateColumn`
```
import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

@Entity('sample')
export class Sample {
  @PrimaryGeneratedColumn({ name: 'id', unsigned: true })
  id?: string;

  @Column('varchar', { name: 'name' })
  name: string;

  @CreateDateColumn({ name: 'created_at', precision: 3 })
  readonly createdAt?: Date;

  @UpdateDateColumn({ name: 'updated_at', precision: 3 })
  readonly updatedAt?: Date;
}
```
- Create an entity object and insert to the database
- Find the same entity object, modify some columns and update with the save method
- The column with `@UpdateDateColumn` is updated with `CURRENT_TIMESTAMP` without precision

I think it would work if it uses MySQL's `ON UPDATE` like `ON UPDATE CURRENT_TIMESTAMP(3)`.
But the wrong expression is hard coded below.
https://github.com/typeorm/typeorm/blob/master/src/query-builder/UpdateQueryBuilder.ts#L417

Is there any workaround ?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by gregwym** [comment]
👍 We have the same issue. Would be great to take the advantage of timestamp(6). Looks like its on their todo, but not further discussed. 

https://github.com/typeorm/typeorm/blob/master/src/query-builder/UpdateQueryBuilder.ts#L430
```
            if (metadata.updateDateColumn)
                updateColumnAndValues.push(this.escape(metadata.updateDateColumn.databaseName) + " = CURRENT_TIMESTAMP"); // todo: fix issue with CURRENT_TIMESTAMP(6) being used, can "DEFAULT" be used?!
```

**Comment by tigersoftdev** [comment]
I can confirm that issue still exists. As a workaround I have following snippet in my entity:
```
@BeforeUpdate()
setUpdateDate(): void {
  this.updateDate = new Date();
}
```
This provides milliseconds to update date, but it should be handled by the framework.

**Comment by felipe-fator3** [comment]
This issue should be reopened. #7517 does not fix the precision problem.

As mentioned by @gregwym , the following still exists in the source code and CURRENT_TIMESTAMP is being used instead of CURRENT_TIMESTAMP(6), because CURRENT_TIMESTAMP is hard-coded:

https://github.com/typeorm/typeorm/blob/26581d0264268045496b43f7a0f338eb9f2b70cc/src/query-builder/UpdateQueryBuilder.ts#L448-L449

I can see two possible ways to fix the issue:
- Within the same if, check whether `metadata.updateDateColumn.onUpdate` is set; if true, there is no need to set a hard-coded CURRENT_TIMESTAMP, since the database will handle that by itself:
```javascript
if (metadata.updateDateColumn && updatedColumns.indexOf(metadata.updateDateColumn) === -1 && !metadata.updateDateColumn.onUpdate)
    updateColumnAndValues.push(this.escape(metadata.updateDateColumn.databaseName) + " = CURRENT_TIMESTAMP");
```
- Include the information about precision (`metadata.updateDateColumn.precision`) to the hard-coded CURRENT_TIMESTAMP:
```javascript
if (metadata.updateDateColumn && updatedColumns.indexOf(metadata.updateDateColumn) === -1)
    updateColumnAndValues.push(this.escape(metadata.updateDateColumn.databaseName) + " = CURRENT_TIMESTAMP" + (metadata.updateDateColumn.precision ? `(${metadata.updateDateColumn.precision})` : ""));
```

There could also be a mixed solution, using the value of `metadata.updateDateColumn.onUpdate` instead of a hard-coded CURRENT_TIMESTAMP or something like that.

One should note that I simplified the answer by not checking the database type. I proposed the answers based on MariaDB only.

**Comment by hwooo** [comment]
In TypeORM v0.3 still the issue exists.

**Comment by ScumbagMark** [comment]
Not sure why this was closed.  There are still the same comments in the code.
```ts
updateColumnAndValues.push(this.escape(metadata.updateDateColumn.databaseName) +
    " = CURRENT_TIMESTAMP"); // todo: fix issue with CURRENT_TIMESTAMP(6) being used, can "DEFAULT" be used?!
```

Inserting new records in the database does use the correct precision - it is inserting with the value DEFAULT.

**Comment by andberto** [comment]
The issue still occur in typeorm 0.3.20.

**Comment by alumni** [comment]
@andberto You can follow PR #11258, seems to go into the right direction, but needs to be fixed before merging
