### ISSUE TITLE
MySQLDriver findChangedColumns (fields: width, precision)

### ISSUE THREAD

**Issue by alangatti** [typeorm/typeorm#2737]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.7` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

MySQL version: 5.7
Typescript version: 3.0.1

Everytime schema:sync is called, typeorm drops all fk and re-create them. It also performs alter table change column to timestamp columns. The problem is when findChangedColumns is called.
[Line](https://github.com/typeorm/typeorm/blob/a4dec02cc59d3219a29c7be0322af2253e1452dc/src/driver/mysql/MysqlDriver.ts#L623)

```ts
console.log("width:", tableColumn.width, columnMetadata.width);
console.log("precision:", tableColumn.precision, columnMetadata.precision);
```

output:

for fk:
```ts
width: 10 undefined
```

for timestamp:
```ts
precision: 0 null
```

Example entity:

```ts
@Entity('assignments')
export class Assignment {

  @PrimaryGeneratedColumn({unsigned: true})
  id: number;

  @CreateDateColumn({precision: null, type: 'timestamp', default: () => 'CURRENT_TIMESTAMP'})
  from: Date;

  @Column({precision: null, type: 'timestamp', default: () => null, nullable: true})
  to: Date;
```

**Comment by alangatti** [comment]
Any news on this?

**Comment by jeremija** [comment]
It my case the comparison of default values fails because of case difference. The `MysqlDriver#compareDefaultValues` ends up comparing the following values:

```javascript
"CURRENT_TIMESTAMP(6)" === "current_timestamp(6)"
```

Running:

- `typeorm@0.2.19` (`@latest`)
- `mariadb  5.5.5-10.3.13-MariaDB-1:10.3.13+maria~bionic mariadb.org binary distribution`
   docker image: `mariadb:10`
   sha256: `e93652b8b80d422415a7771c0cd281d4b9922e1fcbc7f775cf5d3b162b8dc81d`) 

Notice the case difference of the default value in `mysql` CLI utility when executing `CREATE TABLE` and `SHOW CREATE TABLE`:

```mysql
mysql> CREATE TABLE test(created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6));
Query OK, 0 rows affected (0.02 sec)

mysql> SHOW CREATE TABLE test;
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test  | CREATE TABLE `test` (
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

The `MysqlDriver#mappedDataTypes.createDateDefault` and `MysqlDriver#mappedDataTypes.updateDateDefault` are both set to `CURRENT_TIMESTAMP(6)`.

I'm not sure if all versions of MariaDB and/or MySQL behave the same, but I guess the comparison here should be case-insensitive.
