### ISSUE TITLE
CLI freezes on migration:generate command (TS, postgres, Win10)

### ISSUE THREAD

**Issue by nikitaulshin** [typeorm/typeorm#2791]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/nikitaulshin/typeorm-ts-bug

Hello!

I'm using typescript and postgres. When I call migration:generate using ts-node, the process hangs and nothing happens. 

Reproducible on Windows 10.

Thanks!

**Comment by nikitaulshin** [comment]
Any updates on this?

**Comment by savchenkoto** [comment]
I have the same issue.

**Comment by jappyjan** [comment]
same here

**Comment by savchenkoto** [comment]
@jappyjan
I had this problem because I specified absolute path in `ormconfig`:
```
const config: ConnectionOptions  = {
  ...
  cli: {
    migrationsDir: path.resolve(rootPath, 'src/migrations'),
  }
  ...
}
```
I dig into the source code a bit and found out that migration:generate do the following to resolve the location it's supposed to put created migrations.
`path = process.cwd() + "/" + (directory ? (directory + "/") : "") + filename;`

So for me the solution was to change the line in `ormconfig` to this:
`migrationsDir: 'src/migrations'`

**Comment by imnotjames** [comment]
If it's the same problem in all of these, this should be fixed in the next release.
