### ISSUE TITLE
Undefined entity - in subscribers after and before update events

### ISSUE THREAD

**Issue by darekf77** [typeorm/typeorm#2809]
**Issue type:**

[x ] bug report
**Database system/driver:**

[x] `sqlite`

**TypeORM version:**

[ x] `0.2.7 

**Steps to reproduce or a small repository showing the problem:**

Simple example here:  https://github.com/darekf77/typeorm-sqlite-error-example

**Comment by ChangJoo-Park** [comment]
+1 here
same environment.

**Comment by VinceOPS** [comment]
Same here - PostgreSQL & TypeORM 0.2.8 - looks like this is "by design"... The `UpdateQueryBuilder` is not passing any argument for `entity` dans `databaseEntity` to the method responsible for broadcasting Events... 

Btw I think there is a mistake in the definition of `UpdateEvent` as `entity` and `databaseEntity` should be optional (`entity?: <type>` instead of `entity: <type>`)

Related to https://github.com/typeorm/typeorm/issues/2246 (contains answers from Pleerock).
What could be possible is to pass the "valuesSet" from UpdateQueryBuilder, but this isn't the **entity**, properly speaking.

**Comment by pleerock** [comment]
its not a bug. I told it probably hundred of times probably that people should use `save` if they want to have all orm functionality. `update` was supposed as "just execute update query and thats it" - limited functionality with maximal performance. Maximal performance means no additional selects, no additional selects means no `databaseEntity` set in subscriber event.

@VinceOPS yes we can update signature. Feel free to pr ;)

**Comment by dhammma** [comment]
This behavior very not obvious for me

**Comment by rskvazh** [comment]
This is definitely a bug that event.entity typed as always not undefined, but SOMETIMES its undefined. 
Why you are calling subscribers/listeners for this situations at all? I've a bug because this is not obvious.
