### ISSUE TITLE
When I get a QueryFailedError:"invalid input syntax for integer

### ISSUE THREAD

**Issue by dudduss** [typeorm/typeorm#2812]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by bennyn** [comment]
The "invalid input syntax for integer" can occur when you defined a property of your entity as `number` and you try to save a floating point number (like "1385.48549945"). 

For JavaScript a floating point number and an integer are the same (JS only has one `number` type) but for Postgres these are different things so it crashes when trying to save a floating point to a number (integer) field.

Changing from:

```ts
@Column()
myNumber: number;
```

To:

```ts
@Column({type: 'real'})
myNumber: string;
```

might solve the issue.

**Comment by franzos** [comment]
This is now, an actual issue:

```
@Column({
   type: 'real',
   default: 0,
})
something: string;
```

Results in the following error:

```
[Nest] 33094   - 08/08/2019, 2:32 AM   [ExceptionsHandler] invalid input syntax for integer: "28.6" +16566ms
[0] QueryFailedError: invalid input syntax for integer: "28.6"
```

_TypeORM_ v0.2.18; Someone else has the same issue: [Stackoverflow.com](https://stackoverflow.com/questions/57391545/queryfailederror-invalid-input-syntax-for-integer-when-querying-on-type-floa)

**Comment by hussainwali74** [comment]
has anyone solved this?

**Comment by JStuve** [comment]
> has anyone solved this?

I just had this issue and for me is was re-ordering my route definitions. 

`@Get([‘:id’])` was before `@Get([‘type’])’

Switching the order fixed it.

**Comment by imnotjames** [comment]
If you have experienced something similar & can create a reproducible example please open a new issue.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
