### ISSUE TITLE
angular and typeorm 

### ISSUE THREAD

**Issue by aammfe** [typeorm/typeorm#2884]
**Issue type:**

[ X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ x] `sqlite`
[ x] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello!!

I m trying to integrate typeorm in angular but unable due to ngcli limitation.
I have followed [this](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack) documentation but could not make it work with typeorm.

still getting 
![image](https://user-images.githubusercontent.com/11896817/46380251-121eea00-c6bb-11e8-88ed-fdbb90085190.png)

errors 

[repo](https://github.com/aammfe/Angular-6-with-Typeorm-not-working) where you can see issue.
this is [webconfig](https://github.com/aammfe/Angular-6-with-Typeorm-not-working/blob/master/webpack.config.js) and this is [angular.json](https://github.com/aammfe/Angular-6-with-Typeorm-not-working/blob/master/angular.json) 

please help.

**Comment by sagerobert** [comment]
I'm using TypeORM with NestJS as server and Angular 6 as client, too.
I've made a 'client' and a 'server' dir under 'src' and starting 'server/index.ts' via nodemon and angular the normal way with 'ng serve', htis works finde so far.
I've no idea how to handle this on the web server after uploading, but until now it's fine :-:

**Comment by MetaiR** [comment]
is there any solution on this one?

**Comment by pleerock** [comment]
This question is off-topic. Its like using typeorm+react or using typeorm+android application. Angular is a separate library and its client-side library and I guess you are using typeorm on the server.

**Comment by ZiadJ** [comment]
Turns out TypeORM doesn't really care about integration with other frameworks. I paid the price for it a year ago after all my work based on it went down the drain after an update broke compatibility with Angular. I'd suggest you move onto something else like Loopback 4 which doesn't consider itself as completely separate from the typescript ecosystem.

**Comment by vlapo** [comment]
@ZiadJ I am really sorry you have such experience with typeorm but as you can see our "team" is heavily undersized (lot of features are waiting, 550+ issues unresolved long time). It is not in our power to handle all possible integrations with typescript based frameworks. I have to say it again and again. We are just ordinary people and do everything in our free time.

I also have to say we are focused on nodejs support as backend is mostly place where majority of developers handle DB operations. As Angular developer I would like to see better support of angular in future. But right now I do not have so much time to handle it. So if you are interested clone typeorm repo and check source code. If you have any ideas how to bring back angular support I will help you as much as possible.

Contributing is welcome every time.

**Comment by dalu** [comment]
Is anyone aware of a client side ORM except normalizr, which isn't really an ORM...
What I'm looking for is ...
Every entity has a repository service
E.g. user user service /api/users
Post post service /api/posts
Etc
What I'm looking for, for Angular is something where I define relationships,  fetch the data from the services, combine the data, and provide a way of querying the data that was stored client side, optionally fetching current data from the http endpoints. And all that without the complexity and boilerplate of ngrx. In fact I don't want to use state management at all.

So, any ormish client anyone is aware of?

**Comment by aammfe** [comment]
> Is anyone aware of a client side ORM except normalizr, which isn't really an ORM...
> What I'm looking for is ...
> Every entity has a repository service
> E.g. user user service /api/users
> Post post service /api/posts
> Etc
> What I'm looking for, for Angular is something where I define relationships, fetch the data from the services, combine the data, and provide a way of querying the data that was stored client side, optionally fetching current data from the http endpoints. And all that without the complexity and boilerplate of ngrx. In fact I don't want to use state management at all.
> 
> So, any ormish client anyone is aware of?

Hello!!
good idea !!!
but how u are going to mange inconsistency bw client and server db?

**Comment by dalu** [comment]
Hi aammfe,

sorry for going off-topic, first :)

For syncing inconsistencies, that depends on the server side on the database used.
MongoDB has https://docs.mongodb.com/manual/changeStreams/
Postgresql you can define triggers and listeners
Updating the client could be done either via websocket or EventSource (I wrote a blog entry about Go and EventSource, there are some pitfalls https://blog.icod.de/2018/12/17/angular-eventsource-go-and-wasted-lifetime/ )
MySQL I'm not aware of it having such a feature, you'd have to notify some kind of notification service in the repository's method find, update, insert etc.

as for "the other thing" this is the same. you need a manager (ORM) for the services (services in angular are essentially repositories, classes with list, find etc methods. In those methods are http calls that return observables). In Angular or rather rxjs you have Subjects and can create Observable from Subjects. Passing data to Subjects is done with the `next()` method and subscribers should use the .AsObservable() method in the components.

So your client subscribes to changes, IMHO the EventSource ( https://developer.mozilla.org/en-US/docs/Web/API/EventSource ) solution should be preferred over websocket because it's "native" HTTP.
Whenever something changes the client receives an update, that could look like
```json
{
  "table": "users",
  "method": "update", // ['insert', 'update', 'delete']
  "id": "some_id"
}
```
Then this id could be queried for up to date data. Why only id? To not cause unnecessary traffic. Not all updates are interesting. But if you're trying to stay in sync probably all are actually interesting, so data could be passed along every time.

Somewhere else I wrote about a manager service.
The manager (Object Relationship Manager)
uses the services (let's call them DataServices e.g. UserDataService PostDataService), their list find findOne update updateAll remove removeAll methods.
Grabs data from the services, and is responsible for gluing the objects that have relationships together.
Who listens to updates? A special DataUpdateListenerService, which the manager subscribes to.
Depending on update type the manager queries the data services and updates the client side data.
The manager passes observables and has ways to query the complete set, return either 1 entity or entites with relationships.
e.g.
`this.orm.query(params: object, entityName: string, related: Array<string>|| null) // pseudocode`
would trigger a (this is in the manager)
`this.entityStream.next(query_result)`
You me we would probably want multiple entity streams ( which are Subjects.AsObservable()). Even in the user/post/comment example you'd probably want either of those streams independently, regardless, for whatever reason (post with tags and a separate distinct tag list come to mind)
So yeah the manager could provide a map<string, BehaviorSubject> ( https://www.learnrxjs.io/subjects/behaviorsubject.html )
example usage: `this.manager.subjects.get('user').AsObservable()`
or... you predefine what subjects should update what data
e.g. subjects.get('user+post')

It's all still quite raw in my mind.
normalizr could probably help there, when it comes to querying single entities by id. But maybe let's not complicate things.

You're only every watching 1 version of the data (view)

I kind of want to build a blog solution to see if theory meets praxis.
