### ISSUE TITLE
leftJoinAndSelect does not always return the same result

### ISSUE THREAD

**Issue by michaelchiche** [typeorm/typeorm#2887]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/michaelchiche/typeorm-apollo-examples

in the repository above, in the file https://github.com/michaelchiche/typeorm-apollo-examples/blob/master/src/index.ts#L104, you can see a leftJoinAndSelect, which uses the Post model.
And on the line above, the same query using strings.

They both generate the same query,
But in the string one, the result has the Posts nested automatically, in the model one, it does not
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by csuich2** [comment]
I actually came across this recently as well and have been looking in to the root cause and potential fixes.

@pleerock What I've found so far is that I believe the issue is stemming from line 127 of ```JoinAttribute.ts```
https://github.com/typeorm/typeorm/blob/805b554e4ff0359f60a9ee98e45e3b827a981a75/src/query-builder/JoinAttribute.ts#L126-L145

When ```entityOrProperty``` is a class/function, the first line of the ```relation``` property bails out by returning undefined, so the rest of the code doesn't have access to the relation.

**Comment by imnotjames** [comment]
This is intentionalc.

One join (with the entity class) is doing an arbitrary join with the metadata defining tables and columns.

The other, with the string, is referencing the relation.

Only the latter SHOULD set the relation in joinattribute and get joined as the relation.

This is by design.
