### ISSUE TITLE
first class support for custom (un)marshallers

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#289]
So i want to use momentjs instead of Date for my records and this is how I was able to get it typeorm to work:

```typescript
    @BeforeInsert() _setDt() {this.date = this.date.toDate() as any}
    @BeforeUpdate() _setDt1() {this.date = this.date.toDate() as any}
    @AfterLoad() _setDt2() {this.date = moment(this.date)}
    @Column({ type: "date", nullable: false }) date: moment.Moment
```

it would be great if there was a first class column option for setting up our own marshalling and unmarshalling so we didn't have to break types with `as any`

```typescript
@Column({ 
    type: "date", 
    nullable: false, 
    marshaller: {
        toDb: d => d.toDate(), 
        fromDb: d => moment(d)
    }
}) date: moment.Moment

```

**Comment by pleerock** [comment]
yes, probably needed feature, I'll think about it more. Right now you can use `class-transfromer` library to do what you want.

**Comment by dcworldwide** [comment]
If we go this route IMO I prefer transform: {to, from}. It's more terse and semantically less java like.

**Comment by pleerock** [comment]
yeah if we talk about naming then it should be even better

**Comment by maxcan** [comment]
I agree with @dcworldwide on `to from`

**Comment by pleerock** [comment]
TBH I don't like both names. @19majkel94 you are a class-transformer and routing-controllers pro, what do you think about this feature and whats your own suggestion on the naming things?
This can be something like this:

```typescript
@Column({ 
    type: "date", 
    nullable: false, 
    transform: {
        to: d => d.toDate(), 
        from: d => moment(d)
    }
}) 
```

or if `to` and `from` names aren't descriptive (and I think it is, because its not really clear which of them what do) it can be:

```typescript
@Column({ 
    type: "date", 
    nullable: false, 
    transform: {
        rawToEntity: d => d.toDate(), 
        entityToRaw: d => moment(d)
    }
}) 
```

or maybe something better? Also we can extract transform into separate decorator like this:

```typescript
@Column({ 
    type: "date", 
    nullable: false
}) 
@ColumnValueTransformer({
    rawToEntity: d => d.toDate(), 
    entityToRaw: d => moment(d)
})
```

or just:

```typescript
@Column({ 
    type: "date", 
    nullable: false
}) 
@ColumnValueTransformer(d => d.toDate(), d => moment(d))
```

But the question is do we really need it, or shall we make it part of column decorator?

**Comment by 19majkel94** [comment]
```
@ColumnValueTransformer(d => d.toDate(), d => moment(d))
```
It's not intuitive, I don't know which one (to/from) is first, so it's bad for me.

I like the flexibility and I would like to see both `rawToEntity/entityToRaw` and `to/from` in TypeORM!
So Java pros `canUseLongNameInsteadOfShortMnemonic` and JS geeks can use `to` and `from` 😉 

I also like type-safe, so there is a snippet:
```typescript
type TransformerFunction = (entity: any) => void;

interface ColumnValueTransformerOptionsDescriptive {
    rawToEntity?: TransformerFunction;
    entityToRaw?: TransformerFunction;
}

interface ColumnValueTransformerOptionsShort {
    from?: TransformerFunction;
    to?: TransformerFunction;
}

type ColumnValueTransformerOptions = ColumnValueTransformerOptionsDescriptive | ColumnValueTransformerOptionsShort;

function optionsTest(options: ColumnValueTransformerOptionsShort): void;
function optionsTest(options: ColumnValueTransformerOptionsDescriptive): void;
function optionsTest(options: ColumnValueTransformerOptions): void {
    return void 0;
}

optionsTest({
    rawToEntity: (user: User) => user.email,
    entityToRaw: (user: User) => user.email,
    // from: (user: User) => user.email,
    to: (user: User) => user.email, // Object literal may only specify known properties, and 'to' does not exist in type 'ColumnValueTransformerOptionsDescriptive'.
});
```
So no danger that user create an `ColumnValueTransformerOptions` with both `rawToEntity` and `to` properties.

If `@ColumnValueTransformer` decorator can't be used without `@Column` decorator, I would stick to `transform` property in `@Column` decorator.

**Comment by dcworldwide** [comment]
Agree with @19majkel94 comment's about 

`@ColumnValueTransformer(d => d.toDate(), d => moment(d))`

I also like the idea of not introducing too many decorators into the api.  Also I think semantically this feature fits within the scope of the column decorator.

**Comment by pleerock** [comment]
I agree that we should not add a new decorator for this case. However I don't like the idea that we will have dual behaviour with `rawToEntity + entityToRaw` and `from + to`. Yeah its cool that we can do such things with TypeScript however its not good to do things so. For this task (transformation) there should be only one way to do this and having dual way will just confuse users. So we need to choose either `rawToEntity + entityToRaw` or `from + to` or suggest something better

**Comment by pleerock** [comment]
> How the TransformerFunction should work? The d from examples is entity property, can your metadata stuffs associate the decorator function with property on which the decorator is applied?

it should be two parameters at least: `(value: any, entity: User) => any`

**Comment by maxcan** [comment]
> So we need to choose either `rawToEntity + entityToRaw` or `from + to` or suggest something better

How about `toEntity` and `fromEntity` a bit more concise but still clear meaning

**Comment by maxcan** [comment]
So I just spent the better part of a morning figuring out that the pg driver will unmarshall columns with a decimal type into javascript strings to avoid dataloss from JS's sketchy handling of numeric types. https://github.com/brianc/node-postgres/pull/353

This gives this feature a bit more urgency for me.  

@pleerock if you point me in the right direction for where to start in the code and any examples to follow, I could take a stab at a PR

**Comment by slavafomin** [comment]
Hello everyone!

Just stumbled upon this issue today, when implementing data layer in our application.

I have this class:

```typescript
export class ConfirmationRequestType {

  static SIGN_UP = new ConfirmationRequestType('SIGN_UP');
  static CHANGE_EMAIL = new ConfirmationRequestType('CHANGE_EMAIL_1');
  /** … */

  constructor (private value: string) {
  }

  toString () {
    return this.value;
  }

}
```

I'm using it as a "smart enum" which capable of casting itself to string when needed and at the same time support typing.

I've tried to define my model this way:

```typescript
@Entity()
export class ConfirmationRequest {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column(ColumnTypes.STRING)
  type: ConfirmationRequestType;
}
```

However, when data is persisted to the database, the column has `{"value":"SIGN_UP"}` value. It looks like TypeORM is ignoring the `toString()` method. Shouldn't it call it when transforming unknown object to string?

Something like:

```typescript
if ('object' === typeof value && 'function' === typeof value.toString) {
  value = value.toString();
}
```

So, in order to mitigate this problem I have to use this workaround:

```typescript
@Entity()
export class ConfirmationRequest {

  @PrimaryGeneratedColumn()
  id?: number;

  @Column(ColumnTypes.STRING)
  type: ConfirmationRequestType | string;


  @BeforeInsert()
  @BeforeUpdate()
  typeToString () {
    this.type = this.type.toString();
  }

  @AfterInsert()
  @AfterUpdate()
  @AfterLoad()
  typeFromString () {
    this.type = new ConfirmationRequestType(this.type as string);
  }

}
```

Specifically I'm defining type property as `ConfirmationRequestType | string` and manually casting it to string before persisting and back to object after it. This solution works, but looks pretty ugly and cumbersome.

---

So, my questions/ideas:

1. Shouldn't TypeORM use `toString()` method when casting objects to string? This looks like a reasonable and even expected behavior, because `toString()` can be considered like "magic method". However, this would solve only a first part of my specific case.

2. Generally, I think that TypeORM should support custom column types, this is a pretty basic and probably desired feature for every non-trivial project. I like the idea of using value transformers.

Please, let me propose the following API:

# Example I — Value Transformer Interface with Annotations

You will need to define a class implementing ValueTransformer interface provided by TypeORM. Then this class should be referenced in column annotation:

```typescript
class MomentValueTransformer implements ValueTransformer<moment, Date> {
  transformTo (value: moment): Date {
    return value.toDate();
  }
  transformFrom (value: Date): moment {
    return moment(value);
  }
}
```

```typescript
@Entity()
export class MyEntity {
  @Column(ColumnTypes.DATE, { valueTransformer: MomentValueTransformer })
  type: moment;
}
```

# Example II — Value Transformer Interface without Annotation

Or alternatively the `MomentValueTransformer` class could be registered with TypeORM globally (like subscribers for example) and then value could be transformed automatically without the need for special annotations:

```typescript
class MomentValueTransformer implements ValueTransformer<moment, Date> {
  getToType () {
    return moment;
  }
  getFromType () {
    return Date;
  }
  transformTo (value: moment): Date {
    return value.toDate();
  }
  transformFrom (value: Date): moment {
    return moment(value);
  }
}
```

And then simply:

```typescript
@Entity()
export class MyEntity {
  @Column(ColumnTypes.DATE)
  type: moment;
}
```

During value transformer registration the TypeORM could call it's `getToType` and `getFromType` methods to actually inquire the types supported by transformer.

Then when it needs to actually transform the value it could looks for suitable transformer in the list of registered transformers according to the actual type of the value and the destination type. In this implementation column will have two types: the runtime type and persist type, i.e.: `@Column(PersistType) type: RuntimeType;`.

What do you think? Thanks!

**Comment by dropdevcoding** [comment]
This would be very helpful in general - no matter how it is implemented in the end - for ValueObjects when using DDD

**Comment by pleerock** [comment]
Thanks to @iRath96 for implementation of this feature. It will be released in next version this week.

**Comment by slavafomin** [comment]
Oh, that's great, thanks! Are there any docs yet?

**Comment by iRath96** [comment]
@slavafomin There is! [docs/entities.md](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#column-options)

Also take a look at [test/functional/columns/value-transformer/entity/Post.ts](https://github.com/typeorm/typeorm/blob/8968397bf24d900a8f3101370553278b4127be24/test/functional/columns/value-transformer/entity/Post.ts#L27) for an example implementation. Note that you can also do

```javascript
transformer: {
  from(value) {
    return …;
  },
  to(value) {
    return …;
  }
}
```

instead.

Hope this helps!

**Comment by nicklaros** [comment]
Hi, I try to use transformer on `mongodb` but it is just ignored. Does it support mongodb connection or did I do something wrong?

**Comment by nicklaros** [comment]
here is the code
```
  @Column({
    type: String,
    transformer: {
      to: (value: string): Moment.Moment => Moment(value, 'YYYY-MM-DD'),
      from: (value: Moment.Moment): string => value.format('YYYY-MM-DD'),
    },
  })
  public startsAt?: Moment.Moment;
```

**Comment by sillykelvin** [comment]
@nicklaros Seems it should be the other way around: `to` is to **convert entity value to database value** and `from` is to **convert database value to entity value**, so you have to exchange the definition of `to` and `from`.

**Comment by nicklaros** [comment]
@sillykelvin aahh I see. Great thanks.

**Comment by danielsetreus** [comment]
How to use this with a MongoDB DBRef field? 

```typescript
@Column({
      transformer: {
        to: (value: any) => {
          console.log('Transform to', value);
          return value;
        },
        from: (value: any) => {
          console.log('Transform from', value);
          return value;
        }
      }
})
public authors: Author[];
```
Gives no console output... 

`entity.author` gives:
```javascript
[ DBRef {
    _bsontype: 'DBRef',
    namespace: 'author',
    oid: xyz,
    db: undefined } ]
```
which is the raw data from the db.

**Comment by moltar** [comment]
Relevant: https://github.com/typeorm/typeorm/issues/4179
