### ISSUE TITLE
How to filter objects with OR query

### ISSUE THREAD

**Issue by copsbehindme** [typeorm/typeorm#2929]
**Issue type:**
[ ✓ ] question
[ ✓  ] feature request
[ ✓  ] documentation issue

**Database system/driver:**
[ ✓ ] `postgres`

**TypeORM version:**
[ ✓ ] `latest`

I want find results in my repo where firstname is like 'john' **OR** lastname is like 'doe'
but findOptions where clause treat it as **AND**.

What I tried :

```
let results = await userRepo.find({
  where : {
    firstname : Like('%John%'),
    lastname : Like('%Doe%'),
  }
});
```

What I expect of this :

```
let results = await userRepo.find({
  where : {
    firstname : Like('%John%'),
    lastname : Or(Like('%Doe%')),
  }
});
```
Any help on how can I use 'OR' within **where** object?

**Comment by gintsgints** [comment]
Bit hacky, but may be this works for you:

```
        const results = await connection.manager.find(User, { where: { firstName: Raw(`
        "firstName" AND ("firstName" LIKE '%John%' OR "lastName" LIKE '%Doe%')
        `) } });
```

**Comment by pleerock** [comment]
Let's not forget that SQL is a very high level language and very dynamic, so we can express in our plain js object only basic queries. Suggested syntax is weird IMO and covers such case, that can be easily extended to hundred other cases that aren't covered by this syntax.

So, lets remember, in case if complex SQL queries we have to fallback to raw or query builder.

In this particular case we can already do following:


```ts
await userRepo.find({
  where : [{
    firstname : Like('%John%'),
  }, {
    lastname : Or(Like('%Doe%')),
  }]
```

**Comment by phil294** [comment]
As far as I  can see, OP suggestion is not an optimal idea because until now, all [operators](https://github.com/typeorm/typeorm/tree/master/src/find-options/operator) are applied to one key only (to the `key` in `where: { key: OP(...) }`) and @copsbehindme suggests that a new `Or()` operator that affects multiple `key`s.

The suggested solution looks good, however [docs](https://github.com/typeorm/typeorm/blob/master/docs/find-options.md) dont mention any `where: Array<...>` syntax..(?)

However, `Or()` would make sense when filtering for multiple values on the same key:
```ts
let results = await userRepo.find({
  where : {
    firstname : Or(Like('%John%'), Like('%AnotherJohn%'))
  }
});
```
If I am not mistaken, such syntax is currently not possible (only with QueryBuilder).

The same applies to an `And()` operator. The regarding issue #2396 was closed, however !2100 does not implement this functionality, only `If()`. Will this be possible with 0.3.0?

Could you please clear this up @pleerock ? Would love to know if I can make use of this or have to switch to another orm. Thanks

**Comment by pleerock** [comment]
@phil294 its something that isn't possible via find options yet, you need to use query builder instead.

**Comment by rustamwin** [comment]
I think this issue can be closed since there is no answer from author

**Comment by lugavin** [comment]
``` ts
let results = await userRepo.find({
  where : [
      {firstname : Like('%John%')},
      {lastname : Like('%Doe%')}
  ]
});
```

will execute following query:

``` sql
SELECT * FROM user WHERE (firstname LIKE %John%) OR (lastname LIKE %Doe%)
```
