### ISSUE TITLE
[Very Minor] Migrations list should exclude classes that do not implement MigrationInterface

### ISSUE THREAD

**Issue by dcworldwide** [typeorm/typeorm#295]
In my ts build, I had a migrations folder which contained some classes that didn't implement MigrationInterface. The logic that loads migrations from disk doesn't discriminate such files. This lead to issues running migrations. The loader should do an interface check.

**Comment by pleerock** [comment]
How do you think "do an interface check" should work?

**Comment by dcworldwide** [comment]
Is this the logic in question? 

https://github.com/typeorm/typeorm/blob/95164dcbbdb8b23b7e4399d92dd13affa4f6d8ac/src/util/DirectoryExportedClassesLoader.ts

**Comment by pleerock** [comment]
what do you mean by "interface"?

**Comment by dcworldwide** [comment]
I mean export class FirstReleaseChanges1481283582 implements **MigrationInterface**

**Comment by pleerock** [comment]
first there is no way to NOT TO LOAD THE FILE if you want to check `implements MigrationInterface`, because first you load it, then you check it.

second there is no way to check if some class implements some interface or not. There is only possibility to check if some class instanceof some another only if its `extends` this class, not implements (because interfaces are omit in runtime).

**Comment by dcworldwide** [comment]
Point 1, yes.

Point 2. This I wasn't sure about. Coming for .net I made an assumption. 

Ultimately this is very minor. This issue was created primarily to raise awareness for others. For that it's served it's purpose. I wouldn't waste any more time on it.
