### ISSUE TITLE
CLI generating entity template

### ISSUE THREAD

**Issue by Spoki4** [typeorm/typeorm#298]
When I generate entity, this generates with deprecation annotations:
```typescript
import {Table} from "typeorm";

@Table()
export class Visible {

}
```

**Comment by pleerock** [comment]
No, it [should not](https://github.com/typeorm/typeorm/blob/master/src/commands/EntityCreateCommand.ts)... I don't remember in which version it was fixed. What typeorm version you have? Make sure to update your globally installed typeorm version too because you may have old version there, `npm i typeorm -g`

**Comment by Spoki4** [comment]
hm... But I have a last version
```
typeorm -v
0.0.8

```
