### ISSUE TITLE
Can not get WHERE...IN to work

### ISSUE THREAD

**Issue by btxtiger** [typeorm/typeorm#2999]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
```ts
const usersModifiedStrings = [
  '1_2018-10-23T20:53:35.000Z',
  '2_2018-10-23T20:53:35.000Z',
  '3_2018-10-23T20:53:35.000Z',
]

getRepository(User)
    .createQueryBuilder('user')
    .select([
        'user.userId',
        'user.username',
        'user.lastModified'
    ])
    .where("CONCAT(user.userId, '_', user.lastModified) NOT IN (:...values)", {
        values: usersModifiedStrings
    })
    .getMany()
````

I'd like to filter the rows by these unique identifiers `userId_lastModifiedDate`. It works inside MySQL Workbench, but when using the query builder, the strings will never match.
Example:
- User table has 20 users
- with these 3 filter values, 17 rows should be returned. But it will be always 20 rows returned when using the query builder. The query looks correct, so it must be an issue of bind param.

```sql
SELECT
       user.user_id AS user_user_id,
       user.username AS user_username,
       user.last_modified AS user_last_modified
FROM user user
WHERE CONCAT(user.user_id, '_', user.last_modified) NOT IN (?) 
-- PARAMETERS: [["9_2018-10-23T20:53:35.000Z","43_2018-10-23T20:53:35.000Z","98_2018-10-23T20:53:35.000Z"]]
```

**Comment by btxtiger** [comment]
The issue seem to be caused by date to UTC conversion. I saw some issues on that topic. But I still do not understand why this happens.

**Comment by NShadyy** [comment]
Facing similar issue - 

Database - PostgreSQL 11.6
TypeORM - 0.2.22 

#### TypeORM -

```typescript
this.createQueryBuilder('packet')
  .where('packet."packetId" IN (:...packetIds)', { packetIds })
  .getMany()
```

#### Generated Query -

```sql
SELECT
  "packet"."id" AS "packet_id",
  "packet"."packetId" AS "packet_packetId",
  "packet"."consignmentId" AS "packet_consignmentId"
FROM
  "packet" "packet"
WHERE
  packet."packetId" IN ($1) -- PARAMETERS: ["abcd"]
```

#### Field Details -

```typescript
@Column({ type: 'text', nullable: false })
packetId: string;
```

I have a database row matching this condition, but not getting the data from TypeORM.

The query is working fine in pgAdmin with `packetId` = 'abcd' but getting error while keeping `packetId` as "abcd". Not sure if the problem is because of double quotes.

**Comment by imnotjames** [comment]
The in clause works in our tests.  If you're finding there's an actual issue please create a new issue with a Reproducible example.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
