### ISSUE TITLE
Add nullable option for embedded tables

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#300]
Unless I'm missing something, its impossible for an embedded table to be nullable.

I know I could just make the fields of the embedded table optional but in some cases, I need to make the embedded table required and when it is optional it should be all or none.

Is there a way to do this that I'm missing?

**Comment by pleerock** [comment]
I think your requirement is too specific. What if in some cases you'll need to do two columns of your embeddable entity optional, and in another case you want to do just one of them? You probably need to create better abstractions and maybe different embeddables if you have such dynamic logic. 

I've added some tests and looks like setting all nullable columns works as expected.

**Comment by maxcan** [comment]
I'm surprised that you think its too specific because its a pretty common situation to have a type like:

```typescript
interface Foo {
    name: string
    metadata?: FooMetadata
}
interface FooMetadata {
    bar: number
    caz: number
}
```

basically you want to express that a `Foo` may have metadata, but if it does, it's all or none. It can be done with relations, but sometimes it may be more performant to use the embedded tables.

Anyway, worst case I can work around it.

**Comment by pleerock** [comment]
you are talking about interfaces which are a bit different scenario. Talk about classes and their relation on tables. What you are describing can simply be done this way:

```typescript
class Foo {
    @Column()
    name: string
    @Embedded(type => FooMetadata)
    metadata?: FooMetadata
}
class FooMetadata {
    @Column({ nullable: true })
    bar: number

    @Column({ nullable: true })
    caz: number
}
```

That's it. Im not sure if its a good idea to override the whole configuration of nullabality of columns from the parent entity. This way you may want to override just some of columns in one case and some of them in another case. Or even more you may want to override types or something else. That's why I call it specific use case. If you have specific cases for you embeddable entities then maybe its better to have a separate embeddable entities?

**Comment by maxcan** [comment]
yeah, I used interfaces just to show the types, classes would have been clearer.  The problem with your approach is that you still can't enforce all-or-nothing on the embedded fields.  The goal would be something like: 

```typescript
class Foo {
    @Column()
    name: string
    @Embedded(type => FooMetadata)
    metadata?: FooMetadata
}
class FooMetadata {
    @Column({ nullable: false })
    bar: number

    @Column({ nullable: false })
    caz: number
}
```

however, I definitely see your point about not wanting to override the embedded table with the parent table.

**Comment by biels** [comment]
+1 for this feature. @pleerock think of it like the DeepPartial<T> you created for typescript. It may not fit all use cases, but it is certainly a not too specific feature. Copying entities to freeze them for future reference is very common. Thanks!

**Comment by greghart** [comment]
Came here after running into this use case myself, thanks for the existing discussion!

After reading through, I think I understand the issue. While in the type system it could be helpful to enforce the "all or nothing" constraint, there would be no corresponding database schema that enforces this (_using embedded entities at least_). 

Ie. the output of embedded entities is just inline columns. So `bar` and `caz` are either nullable columns or not in the schema. If you make them nullable, you violate `FooMetadata` constraints, if you make them non-nullable, you violate `Foo` constraints. Since there's no clear cut answer to which is more correct, marking an embedded as optional is left as a no-op.

If you want to get actual enforcement of these constraints, just a normal one-to-one relationship handles the use case.

**Comment by Matgsan** [comment]
@pleerock  No chance to implement a decorator in the parent that can make all the child columns nullable?

**Comment by romuloctba** [comment]
Just wanted to give a suggestion to anyone facing this...
In my case it was bad design:
One cannot have *embed _entities_* as nullable.

The way to do it is by using relations.
This way you can create the parent entity without having the child one defined

**Comment by jon1010hill** [comment]
There are sometimes compromises that have to be made to fit a domain model to a relational database. Sometimes this means that you might end up storing a entity in your database that is really just a value in your domain. Your application code is what counts when expressing the model.
