### ISSUE TITLE
Error: RepositoryNotFoundError: No repository for [Enitity] was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by NachtmahrEDM** [typeorm/typeorm#3017]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.8` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

1. Create my entity:
import {Entity, PrimaryColumn, Column, BaseEntity} from "typeorm";

```
@Entity("Payload")
export class Payload extends BaseEntity{

    constructor(payloadHash: string) {
        super();
        this.payloadHash = payloadHash;
    }

    @PrimaryColumn()
    payloadHash: string;

    @Column({nullable: true})
    serviceName?: string;
}
```

2. Create my method:
```
import {createConnection, getConnection, ConnectionOptions} from "typeorm";
import {Payload} from "./Entities/PayloadEntry";

export const mysql_config : ConnectionOptions = {
    type: "mysql",
    host: process.env.MYSQL_HOST,
    port: 3306,
    username: process.env.MYSQL_USERNAME,
    password: process.env.MYSQL_PWD,
    database: "my_database",
    entities: [Payload],
    synchronize: true,
    logging: false
};

createConnection(mysql_config).then(res => {
    console.log("Config created!");
});

export module DatabaseAccess {
    export async function createPayload(payload : Payload) {
        try {
            let connection = await getConnection();
            let repo = connection.getRepository(Payload);
            return await repo.save(payload);
        } catch (e) {
            console.error("Error: " + e);
        }
    }
}
```
3. Test with: `mocha --require ts-node/register './**/*.test.ts' --recursive`

Then, it throws that error. But also, it occurs not every time. Sometimes, the code can run well three or four times and then throw that bug next time. I don't really know what the cause is as I took that code from another of my projects in which it was and is working just fine.

**Comment by emirhg** [comment]
I got the same problem, how was it fixed?

**Comment by traccia87** [comment]
The same here.. support please?

**Comment by liangzai92** [comment]
me too, why? who can help me?

**Comment by tageecc** [comment]
any updates？

**Comment by Tanumay92** [comment]
Same issue in my app. Please someone help me on this.

**Comment by eit** [comment]
Same as this

**Comment by vlapo** [comment]
`RepositoryNotFoundError` is throw in case your entity isnt properly registered in connections. This could be caused wrong path (glob pattern) in `entities` connection option. Please check your `entities` property and try to change it. Maybe it will help.

**Comment by Tanumay92** [comment]
@vlapo , Thanks for your reply. Can you share some examples if possible??

**Comment by vlapo** [comment]
https://typeorm.io/#/connection-options/common-connection-options
```ts
{
    host: "localhost",
    port: 3306,
    username: "test",
    password: "test",
    database: "test",
    entities: [
        "entity/*.js" // <============= check if this is correct and our entities are on this path
    ],
}
```

**Comment by Tanumay92** [comment]
import "reflect-metadata";
import { ConnectionOptions } from "typeorm";

export let dbOptions : ConnectionOptions = {
    type : "mysql",
    host : "127.0.0.1",
    port : 3306,
    username : "root",
    password : "123456",
    database : "typeorm_schema",
    entities : [
        "entities/*.js"
   ]
    // synchronize : true 
}

This is my app-config.js file.

**Comment by Tanumay92** [comment]
![Screenshot from 2019-06-12 17:15:29](https://user-images.githubusercontent.com/30310134/59348823-bfabc800-8d35-11e9-8212-b40038cade93.png)

**Comment by Tanumay92** [comment]
My folder structure. 
@vlapo

**Comment by vlapo** [comment]
Try change it into `'./entities/**/*.js'` or `__dirname + '/entities/**/*.js''`

**Comment by Tanumay92** [comment]
Thanks @vlapo . __dirname + '/entities/**/*.js' This one working like a charm for me.

**Comment by SOHELAHMED7** [comment]
If you have files in only one extension for e.g. ts or js, then in `entities` and in case of ts put only `entities: [__dirname + '/**/*.entity.ts'],`

**Comment by abinhho** [comment]
Same issue. It's worked in  development mode but production mode.
Tried:
```
path.join(__dirname, "**/*.entity{.ts,.js}")
```
```
path.join(__dirname, "../**/*.entity{.ts,.js}")
```
```
**/*.entity{.ts,.js}
```
```
dist/**/*.entity{.ts,.js}
```
```
dist/src/**/*.entity{.ts,.js}
```
```
src/**/*.entity{.ts,.js}
```
... but not luck.

**Comment by faridfedora** [comment]
it depends where is stored your index.js file
 The entities address must be set relative to index.js
if entity folder is stored beside of index.js, you should write : 
`"entities": ["entity/**/*.js"]`

You can also add entity address relative to index.ts file to the array bracket in order to work properly in debug mode too.

**Comment by EndersonPro** [comment]
My solution for this case was to check what environment it was running in and just do that 

`const entities: string[] = process.env.NODE_ENV === 'development' ? ["./dist/**/*.entity.js"] : ["./**/*.entity.js"];`

For now it worked for me, is there a better way to solve this?

**Comment by tareqdayya** [comment]
this is what i do:
`entities: [
    process.env.NODE_ENV === 'test' ? './src/entity/*.ts' : './prod/entity/*.js',
  ],`

Only jest tests need ts files in my case, dev and production require the js, otherwise i get "Cannot use import statement outside of a module" in dev and production, and "Looks like this entity is not registered in current "default" connection" for tests.

**Comment by KeerthanaMary** [comment]
i've tried but coouldnt able to solve the error

**Comment by slalbertojesus** [comment]
This may be a little late, but to whomever is still looking for an answer, i actually was able to make the connection possible **by doing the connection without the ormconfig.json**
const main = async () => {
    await createConnection({
      type: "postgres",
      host: "postgres",
      port: 5432,
      entities: [__dirname + "/**/*.*"],   
  }).catch((error) =>
    console.log("Error found while trying to connect to postgres : ", error)
  );
I declared var __dirname at the start of my connection file, you can also print the content of var __dirname to help you out to debug. (i have in the entities *.* because i want my compiler to use javascript files at production).

**Comment by virgenherrera** [comment]
Same here basically still stuck, even trying any solution on this thread, still getting the same...

but curius thing is that, in first instance it appearas to be found:
![image](https://user-images.githubusercontent.com/13859670/83347191-e2d5db80-a2e8-11ea-8b7b-4d9244138b05.png)

basically is says that: OKAY, on load, I found these entities, but later when loading the Users module it sais: "no entities found". !!!

some additional tech data:
Framework: @nestjs/core 7.0.0
ORM Version: 0.2.24

**Comment by sotnasaj** [comment]
In my case the solution was to check the path `__dirname`, in conclusion it no depends where is stored your main.js or index.js , it depends on the config file path... in my case for example, i was using a config file for Typerorm under `src/config/files` (instead of an `ormconfig` file in root) and my entities on `src/api/user/user.entity.ts` ... so to get the entities i have to go back two dirs , something like `[__dirname, '../../api/**/*.entity{.ts,.js}]`.

**Comment by tacnoman** [comment]
I'm making a electron vue software and I have the same problem, but the worst part is, if i run with `vue-cli-service electron:serve`I receive this error, but if I run with `ts-node` works like a charm. But the Vue doesnt work anymore :/

Someone have any idea how to fix this?

**Comment by virgenherrera** [comment]
Hi, community,

first of all, I apologize for abandoning this (Question)[https://github.com/typeorm/typeorm/issues/3017#issuecomment-636436057], since I was not able to remember to tell you, how I was able to continue.

In my case (remember that I'm running over NestJs), I just forgot to add the `@Entity` decorator in my entity class.

**Comment by joekendal** [comment]
This worked in my case
```typescript
 entities: [__dirname + '/entity/*.js'],
```

**Comment by rahbal** [comment]
> This worked in my case
> 
> ```ts
>  entities: [__dirname + '/entity/*.js'],
> ```

This worked for me too.

**Comment by joekendal** [comment]
@rahbal Google Cloud Functions environment in that instance

**Comment by sgClaudia98** [comment]
In my case this worked
Adding the config `autoLoadEntities = true`
And this is what I have on the `import` in my UsersModule of my NestJs app
`TypeOrmModule.forFeature([Users])`

In my case Users was my Entity, replace it with yours

**Comment by pavansanthoshh** [comment]
> I got the same problem, how was it fixed?

in entity repository whatever class u have defined the same class should be given in typeormconfig in entities=[users] and inusersmodule TypeOrmModule.forFeature([Users])

**Comment by Lucheti** [comment]
I had the same issue and the solution i found was that in my Dockerfile i was running the index.js like:
`CMD [ "node", "dist/index.js" ]`
that means that the `__dirname` was local to the dist folder
since i was creating the connection like:
`  const conn = await createConnection({
    type: "postgres",
    url: process.env.DATABASE_URL,
    logging: true,
    entities: [__dirname + "/entity/**/*.ts"],
    migrations: [__dirname + "/migrations/**/*.ts"],
  })`

it could not find any files... obviousely because all files in the dist folder are js files compiled from the src/**.ts files

Hope it helped somebody!

**Comment by alete89** [comment]
As everyone here I was getting:
```RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?```
But the file was in the same folder as every other. and `@Entity` was present.

In my case, it was that this rule:
```  entities: ['src/model/*{.ts, .js}'] ```
didn't catch one single file that started with a capital letter:
- src/model/
    - User.ts (only this failed)
    - company.ts
    - expense.ts

I really can't find a reason, but it was it. Renaming it solved the issue.

**Comment by MarquisAlexander** [comment]
> `RepositoryNotFoundError`é lançado caso sua entidade não esteja devidamente registrada nas conexões. Isso pode ser causado pelo caminho errado (padrão glob) na `entities`opção de conexão. Verifique sua `entities`propriedade e tente alterá-la. Talvez ajude.

i verify my file of configuration orm, really my way was wrong, thaks men!! :)

**Comment by rednebmas** [comment]
I came here from google, and in my case, I forgot to add the `@Entity()` decorator to my class.

**Comment by jviala-ekino** [comment]
I had the same error but no matter the suggested solutions I tried from this issue and StackOverflow, this error would still display.

Then I ran `npm run build`, restarted the Nest app, and the true error popped into my terminal :

```
Error: Cannot find module '/code/api/dist/main'
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
  at Function.Module._load (node:internal/modules/cjs/loader:763:27)
  at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
  at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Turned out that Nest could find the `main.js` file on start. 😅 The reason is a bit specific to my setup but could help others so here's how I solved it.

My Nest application is a "package" inside a kind of monorepo architecture : 
```
my-app/
  api/          <--- (Nest App)
  frontend/
  shared/
```

Inside an entity file from `api/` folder I was importing a TypeScript enum from `shared/` folder. This caused TS to build the `api/dist/` folder with the following structure : 
```
my-app/
  api/
    dist/
      api/
      shared/
```

The `main.js` file that Nest was looking for wasn't located in `api/dist/main.js` anymore but `api/dist/api/main.js`.
I temporarily solved this by commenting the imports lines from "shared" folder, ran `npm run build` and started the app again and the error vanished.

**Comment by reselbob** [comment]
Help? Here is my ormconfig.json
```
{
   "cli": {
      "entitiesDir": "src/mariadb/entity",
      "migrationsDir": "src/mariadb/migration",
      "subscribersDir": "src/mariadb/subscriber"
   },
   "database": "simplecqrs",
   "entities": [
      "src/mariadb/entity/**/*{.ts,.js}"
   ],
   "host": "127.0.0.1",
   "logging": false,
   "migrations": [
      "src/mariadb/migration/**/*{.ts,.js}"
   ],
   "password": "password",
   "port": 3306,
   "subscribers": [
      "src/mariadb/subscriber/**/*{.ts,.js}"
   ],
   "synchronize": true,
   "type": "mysql",
   "username": "root"
}

```
My issue that I can't use `__dirname` in the file because I get all sorts of Bad JSON errors.

And of course, I get the repository not found error. Any help thanks!

**Comment by MohammedALREAI** [comment]
that same for me so i just add the js beside the ts
`  entities: [__dirname + '/**/entities/*.entity.{ts,js}'],
`

**Comment by matheusPinheiroP** [comment]
> As everyone here I was getting:
> `RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?`
> But the file was in the same folder as every other. and `@Entity` was present.
> 
> In my case, it was that this rule:
> ` entities: ['src/model/*{.ts, .js}']`
> didn't catch one single file that started with a capital letter:
> 
> * src/model/
>   
>   * User.ts (only this failed)
>   * company.ts
>   * expense.ts
> 
> I really can't find a reason, but it was it. Renaming it solved the issue.

Yeaah! That work! Thank you dude!

**Comment by MeMeMax** [comment]
For me autoLoadEntities: true did the trick. Cheers!

**Comment by jovanialferez** [comment]
i had fixed my case by making sure entities includes `*.js` while i am using typescript as the resulting build is already in `.js` anyway. :)

**Comment by FlxAlbroscheit** [comment]
As I was using a regular .env file on top of my monorepo, "__dirname + '...'" did not become resolved in any way. I fixed this by adding to my index.ts (in one of the consuming packages):
```
import path from 'path';
// ... dotenv.config({...})
process.env.TYPEORM_ENTITIES = path.resolve(__dirname, `../../common/${process.env.TYPEORM_ENTITIES}`);
```
A bit verbose, but doing the job well.

**Comment by zellkon** [comment]
check your import 
ex : import { Supplier } from '../entities/object';
replace with:  import { Supplier } from '../entities/Object';

**Comment by kevinmelo** [comment]
In my case, i configure the connection with `.env` file on **production** and the problem was he was getting the .env in root directory, not the inside on dist.

AND In the the .env needed to be configurated as `TYPEORM_ENTITIES=entity/**/*.js` and not `TYPEORM_ENTITIES=dist/entity/**/*.js` why? i don't know...
