### ISSUE TITLE
[Documentation] Default relationship handling in queries is very unclear.

### ISSUE THREAD

**Issue by estaub** [typeorm/typeorm#310]
I'm very reluctant to use the relationship support in TypeORM because I'm totally in the dark about its impact on performance.  For example, I can't find doc or sample that indicates whether, in a one-to-many relation, the "many" side is fetched on a `find` of the "one".  I suspect (maybe!) that TypeORM emulates some other ORM that you're very familiar with, so "of course it works that way".  If so, can you say what it is?

**Comment by D4edalus** [comment]
if you are wondering about the generated sql statement you can always use getGeneratedQuery() on the query builder. 

but more docs would be nice on it 👍

**Comment by estaub** [comment]
@D4edalus I'm asking about `Repository.find()`, which afaict has no `getGeneratedQuery`.  I'm fine with the querybuilder - it obviously only fetches what you tell it to, via `select`

**Comment by pleerock** [comment]
`Repository.find()` uses query builder internally, so it just delegates params you send to query builder. I understand what you are asking for, however thats a small details of documentation which currently lack because of no priority on it (and because of lack of time and help from community). I'll return back to this once more priority features will be implemented and I'll go deeper with documentation. Feel free to jump deeper in typeorm code and write documentation on your own if you can!
