### ISSUE TITLE
Can't insert rows inside migrations

### ISSUE THREAD

**Issue by marines** [typeorm/typeorm#3100]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

[repo](https://github.com/marines/typeorm-test/tree/migration-failed)

Creating a table in one migration and inserting data to that table in another migration fails with `QueryFailedError: relation "user" does not exist`. It works fine for SQLite tho. The same behavior exists on 0.2.6 too.

**Comment by zhenwenc** [comment]
Not a database nor typeorm expert, but I suspect that it's caused by the transaction.

If you look at the log when executing `migration:run`, you will see that before the transaction of `InitialSchema1542061700507` is committed, there is another transaction has been started by `AddUser1542061700508`.

To verify the assumption (__not a solution__), manually commit the `Initial` transaction by adding the following line [here](https://github.com/marines/typeorm-test/blob/migration-failed/src/migration/1542061700507-InitialSchema.ts#L6) 
```
await queryRunner.commitTransaction();
```
the migration will work.

Hope that help investigating the issue.

**Comment by marines** [comment]
Yes, it works.

**Comment by Kononnable** [comment]
Looks like issue was resolved.

**Comment by marines** [comment]
Which commit fixes it?
