### ISSUE TITLE
Extending MetaDataStorage with custom validation metadata for adding entity validation

### ISSUE THREAD

**Issue by kristianmandrup** [typeorm/typeorm#3135]
**Issue type:**

[ x ] feature request

I'd like to extend the ability to automatically create entities based on another model/schema source such as a GraphQL type def schema, using a tool such as [graphql-typeorm-generator](https://github.com/jjwtay/graphGenTypeorm/)

This library uses the (undocumented?) typeorm backdoor ability, to load entity schemas from a JS nested object. I'd like the ability to transfer my validation `@constraints` options to the Entities, using a library such as [class-validator](https://github.com/typestack/class-validator) as described on the [typeorm validation](https://github.com/typeorm/typeorm/blob/master/docs/validation.md) page.

My core idea is outlined in this [issue](https://github.com/jjwtay/graphGenTypeorm/issues/1)

I can see that the metadata is stored in `EntityMetaData` and `MetadataArgsStorage`, and built in `EntityMetadataBuilder` by the `build` method.

Not sure what would be the best way to go about this. Are the classes somehow even exposed when loaded directly from `createConnection` via `entities` or `entitySchema` entries?

This part of typeorm is not well documented and the system seems to lack good hooks for custom extensions. Would love to get your thoughts and any remedy that would allow for easier extension using the current infrastructure or some better documentation. 

Thanks!

**Comment by Kononnable** [comment]
Similar to https://github.com/typeorm/typeorm/issues/3141
Still don't really know what you want to achieve. Please elaborate and tell what is the difference between these two issues.
Typeorm is evolving pretty well so some parts of core code isn't documented for a reason. It is not a public api so it can change in time - you can use it directly if you want, but your functionality can be broken by other changes.

**Comment by pleerock** [comment]
You wrote lot of stuff, and provided lot of links, not sure if I have complete picture of what you want to do, but for this particular feature:

```ts
type Author @Entity {
    id: Int! @PrimaryGeneratedColumn
    name: String! @Column({type: "varchar"})
    books: [Book] @ManyToMany(inverseSide: "authors") @JoinColumn
}
```

I would like to have it as officially supported way of schema definition. Just like we currently have decorators and entity schemas, I would like to support graphql-based definition as well. If you are interested you can contribute and make it official.

Regarding to validation, its not part of this library and should be implemented same way, but as another library.

Regarding to your question, yes, you are on the right way - solution are entity metadatas. Just explore code and see how data is converted from decorators and entity schemas into entity metadata. You'll need to do same.

I'm sorry but I don't think we will be ever able to document those areas because there are so many other endless tasks to do. The only source of docs is a code itself. If you can't contribute to our codebase by your own, feel free to support us [other way](https://github.com/typeorm/typeorm/issues/3267) :)

**Comment by kristianmandrup** [comment]
Hi Umed, thanks for responding. 
I understand you don't have time. Huge library already. So much to do with limited resources as always ;)
I've created various libs to better integrate with GraphQL and validation. Prefer to keep a modular approach than integrate directly.
Hope at some point someone documents part of this core entity "gateway" API at least at a high conceptual level and the data flow/timing.
Cheers!

**Comment by pleerock** [comment]
@kristianmandrup thank you! Hope we will. Do you want to close this issue or do you have other questions?

**Comment by kristianmandrup** [comment]
Sure. Cheers ;)
