### ISSUE TITLE
Implement locking

### ISSUE THREAD

**Issue by Johnix1337** [typeorm/typeorm#316]
Hello,

it seems to me that this ORM doens't have any locking functionality, which is required in many applications where race conditions could be fatal.

A implementation of this should be pretty simple.

Locks can only be used in transactions.
In MySQL, the last expression in a SELECT Query can be used to define locking behaviour.
https://dev.mysql.com/doc/refman/5.7/en/select.html

So technically, just appending `FOR UPDATE` or `LOCK IN SHARE MODE` the the query is enough.

PostgreSQL has a different syntax though. PostgreSQL  uses `FOR UPDATE` and `FOR SHARE` to mimic MySQLs behaviour.
https://www.postgresql.org/docs/9.0/static/sql-select.html

PostgreSQL 9.3 and upward support two more options: `FOR NO KEY UPDATE`, `FOR KEY SHARE`.
https://www.postgresql.org/docs/9.3/static/sql-select.html

Locking is a vital feature and many people can't use this library without it, because they risk race conditions which can cause damages.

**Comment by pleerock** [comment]
Right. I see two places where we need to implement locking. First is to add locking option to `QueryBuilder` to allow users to perform selects using locking. Second is to append `FOR UPDATE` / `LOCK IN SHARE MODE` where needed in selects of `Repository#persist` method

**Comment by petermetz** [comment]
@pleerock Slightly off-topic: Locking would be nice to be part of the migration runner as well in my opinion. Currently if I'm doing a multi-server deployment in parallel (PostgreSQL), the deployments get into a race condition and the migrations go bust (occasionally).

Probably not all supported database engines can do it, but the ones that can should lock on the migrations table so that other nodes trying to execute the same migrations will be forced to wait for whoever got there first.

**Comment by pleerock** [comment]
Locking was implemented as part of QueryBuilder a long time ago. [Documentation is here](http://typeorm.io/#/select-query-builder/set-locking). I'll close this issue, let me know if somebody need something else.

**Comment by Diluka** [comment]
@pleerock can you add `lock` options to `find*` methods?

**Comment by Diluka** [comment]
@pleerock Why there hasn't `setLock` on `RelationQueryBuilder`?

**Comment by copsbehindme** [comment]
@pleerock Since most of us are using the find-options and not the query-builder in basic queries, I would like to ask if there anything we can do about this using repository api.

for my personal problem, I was looking for a solution like : 
```
let trialUsers = await userRepo.find({
  trialEnd : LessThan(todaysDate)
})
.setLock("pessimistic_read")
```
As I'm my app is running in cluster where all three instances of the app pickup same rows in db. How do setup a lock using repository api?

**Comment by PachowStudios** [comment]
FYI @copsbehindme and anyone like myself who comes across this via Google, locking via the repository API was added a few months ago.

**Comment by amkCha** [comment]
@rshea0 Thanks for adding this comment ! Do you know where I can find more info on locking via repository API ?

**Comment by quezak** [comment]
> Do you know where I can find more info on locking via repository API ?

for @amkCha and anyone else who lands here from google like me 😄 It's done via the `lock` property of the repository's `FindOptions` param: https://typeorm.io/#/find-options/basic-options

**Comment by ArielPrevu3D** [comment]
Why is there no `updateOne` on the repository with a locking option? Do we still have to use query builder for writing?
