### ISSUE TITLE
Select Query Builder does not return any results on PostgreSQL

### ISSUE THREAD

**Issue by draoncc** [typeorm/typeorm#3235]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Simply try the below code: 

```typescript
import { createConnection, Entity, PrimaryGeneratedColumn } from 'typeorm'

@Entity()
class Example {
  @PrimaryGeneratedColumn()
  id!: number
}

async function main() {
  const connection = await createConnection({ ... })
  console.log(
    await connection.manager
      .createQueryBuilder()
      .select()
      .from(Example, 'alias')
      .getOne(),
  )
}

main()
```

Assuming an Example entity has already been inserted, I'd expect to see the entity printed to the console. Instead I see `undefined`. Using `getMany()` instead returns an empty array (`[]`).

Am I missing something?

**Comment by vlapo** [comment]
Hi @draoncc,

Yeah you are missing one small detail. You have to define what do you want select in `select` method. Now you define you want all but what all? You want all from alias `alias`. This is (I suppose) because of query builder complexity.

Corrected source:
```typescript
await connection.manager
      .createQueryBuilder()
      .select('alias')
      .from(Example, 'alias')
      .getOne();
```

Alternative to your select is something like:
```typescript
connection.manager
            .getRepository(Example)
            .createQueryBuilder("alias")
            .select()
            .getQuery();
```
And from http://typeorm.io/#/select-query-builder/what-are-aliases-for you see:
`createQueryBuilder("user")` is equivalent to:

```typescript
createQueryBuilder()
    .select("user")
    .from(User, "user")
```
Hope this help :)
