### ISSUE TITLE
Allow functions in CREATE INDEX such as lower

### ISSUE THREAD

**Issue by maxcan** [typeorm/typeorm#327]
So, in the `createIndex` function, is it was possible to pass in an options argument so that you could create, for example, a lower case index on a string column?  The SQL for this is described here:  http://stackoverflow.com/questions/3980050/how-do-i-create-an-index-in-postgresql-based-on-lowercase-only

```sql
CREATE INDEX lower_case_username ON users ((lower(username)));
```

The motivation for this is that it allows for case-insensitive queries to run against the index whereas just using a case-insensitive search will break indexing in many cases.

**Comment by maxcan** [comment]
relevant code at: https://github.com/typeorm/typeorm/blob/c12dc0002c84737b21fd2a1437e61fe9d3ed91fe/src/driver/postgres/PostgresQueryRunner.ts#L720

```typescript
async createIndex(tableName: string, index: IndexSchema): Promise<void> {
        if (this.isReleased)
            throw new QueryRunnerAlreadyReleasedError();

        const columnNames = index.columnNames.map(columnName => `"${columnName}"`).join(",");
        const sql = `CREATE ${index.isUnique ? "UNIQUE " : ""}INDEX "${index.name}" ON "${tableName}"(${columnNames})`;
        await this.query(sql);
    }
```
the change would look something like:

```typescript

async createIndex(tableName: string, index: IndexSchema, opts?: transformOpts): Promise<void> {
        if (this.isReleased)
            throw new QueryRunnerAlreadyReleasedError();

        const columnNames = index.columnNames.map(columnName => `"(${opts[columnName] ? opts[columnName] : ""}${columnName}")`).join(",");
        const sql = `CREATE ${index.isUnique ? "UNIQUE " : ""}INDEX "${index.name}" ON "${tableName}"(${columnNames})`;
        await this.query(sql);
    }
```
that way you could apply the options to individual columns.

**Comment by pleerock** [comment]
adding indices expert @iz-iznogood

**Comment by AlexMesser** [comment]
This feature won't be implemented (at least in the near visible future), because of lot of different database specifics and multiple issues with getting information about exist database indices and synchronizing them automatically.

You should create index manually (for example in the migrations) with any index signature you want. To make TypeOrm ignore these indices during synchronization use following syntax:

```ts
@Entity()
@Index("ignored_index", { synchronize: false })
export class Post {
```
avaliable from `typeorm@0.2.0-alpha.27`

**Comment by goktugyil** [comment]
What is the reason to ignore these indexes during synchronization? What happens is we don't ignore them during sync?

**Comment by drtyh2o** [comment]
> What is the reason to ignore these indexes during synchronization? What happens is we don't ignore them during sync?

If they are not ignored, TypeORM will assume you deleted them and will add `DROP INDEX` commands to the next migration.

**Comment by falahati** [comment]
@AlexMesser, please reconsider this position. index on string values like email and username without case insensitive uniqueness is next to useless. This is a very useful feature and can be implemented just by converting the `unique` field of `IndexOptions` to text allowing to specify a function like `lower` or `upper`.

**Comment by faridanthony** [comment]
@AlexMesser, what about exposing an option to allow passing in an expression similar to the `@Check()`? 

This might allow us to create a case-insensitive index like this ``@Unique(`LOWER(email)`)`` and result in: `ALTER TABLE "schema"."table" ADD CONSTRAINT "CHK_56adf8c25aca73e8d94d068ff7" UNIQUE (LOWER(name));`

**Comment by Canopix** [comment]
Any update on this?

**Comment by thatguyintech** [comment]
I'd love support for this as well! 

I want to add something like:

```
@Index("uq_email", ["LOWER(email)"], { unique: true })
```

to generate this postgresql index creation:

```
await queryRunner.query(
  `CREATE UNIQUE INDEX uq_email ON user (LOWER("email"));`,
);
```

and have TypeORM track it correctly.

**Comment by Troyx21** [comment]
This feature is definitely needed. Please reopen the issue.

**Comment by jensmith-work** [comment]
I am here because i need this feature as well. (Postgres DB)

**Comment by jensmith-work** [comment]
synchronize: false (to keep typeORM from later dropping your index when you generate migrations from your model) works on 0.3.x but you have to ONLY pass the synchronize false and the index name, nothing else.  There are several different signatures for the @Index annotation

if you use this one: 

```
@Index(
  'users_lowercase_username_index',
  {
    synchronize: false,
  })
```

only then you can pass synchronize: false as an option

I was trying to use: 

```
@Index(
'users_lowercase_username_index',
['username'],
{
synchronize: false,
})
```
and 
```
@Index(
'users_lowercase_username_index',
{
concurrent: true,
synchronize: false,
})
```

neither of which compile.

I would suggest a documentation update to https://typeorm.io/docs/advanced-topics/indices#disabling-synchronization because although the example shows this, it does not mention that you can't pass any other options when passing this one.
