### ISSUE TITLE
No data returned due to case sensitivity in sql to entity transformer (RawSqlResultsToEntityTransformer)

### ISSUE THREAD

**Issue by lexwebb** [typeorm/typeorm#3319]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So i've been puzzling for a number of days as to why im having no results returned from a simple .find() when using this library and a simple pg table.

It turns out that there seems to be a bug with the class `RawSqlResultsToEntityTransformer` and the way it maps results back to entities.

The issue i'm encountering is that the internal alias the typeorm seems to be using for grouping returned data back to entities is the class name, in my case, and the example below is `Subscription`. 

The uppercase 'S' at the beginning is being maintained as the table alias all the way through a request.

This is directly conflicting with what is returned form the database, which is all lower case. In my case, what is being returned for my primary key is `subscription_subscription_id`. 

Now, when the method `RawSqlResultsToEntityTransformer.group` is run, an object index is done to return the table id for the table, and it is comparing the still uppercase alias to the lowercase version returned in the query.

My entity:
```ts
@Entity({ schema: 'dpretailer', name: 'dfo_subscription' })
export class Subscription {
  @PrimaryColumn({ name: 'subscription_id' })
  id!: number;

  @Column({ name: 'subscription_name' })
  name!: string;

  @Column('timestamptz', { name: 'subscription_start_date' })
  startDate!: string;

  @Column('integer', { name: 'subscription_frequency' })
  frequency!: number;

  @Column('integer', { name: 'number_of_releases' })
  numberOfReleases!: number;

  @Column('timestamptz', { name: 'created_on' })
  createdOn!: string;

  @Column({ name: 'created_by' })
  createdBy!: string;

  @Column('timestamptz', { name: 'deleted_on' })
  deletedOn?: string;

  @Column({ name: 'created_by' })
  deletedBy?: string;
}
```

The offending code in `RawSqlResultsToEntityTransformer`
```ts
protected group(rawResults: any[], alias: Alias): Map<string, any[]> {
        const map = new Map();
        const keys = alias.metadata.primaryColumns.map(column => this.buildColumnAlias(alias.name, column.databaseName));
        rawResults.forEach(rawResult => {
            // ---> case sensitive object index on returned sql
            const id = keys.map(key => rawResult[key]).join("_"); // todo: check partial
            if (!id) return;

            const items = map.get(id);
            if (!items) {
                map.set(id, [rawResult]);
            } else {
                items.push(rawResult);
            }
        });
        return map;
    }
```

Here is an image of a debug session showing the issue:
[Image](https://i.ibb.co/8dP29Cb/Raw-Sql-Results-To-Entity-Transformer-ts-web-ui.png)

**Comment by lexwebb** [comment]
I've done a bit more reading and it looks like this is a Postgress thing? and the database is forcing all returned values to lower case, i find it hard to believe that no-one has encountered this before. What am i doing wrong?

**Comment by lexwebb** [comment]
@pleerock I've debugged what's being returned from the ORM when it runs Sql and it's exactly what I expect. The only thing that is different is the casing of the returned columns

**Comment by pleerock** [comment]
Sorry but I still can't understand what is the issue. Can you please create a PR with a minimal reproduction failing test?

**Comment by lexwebb** [comment]
And example of the above in what SQL is generated for a simple type.
```
@Entity()
class Post {
  @PrimaryGeneratedColumn({ name: 'post_id' })
  id: number;
}
```

Generated SQL
```
SELECT "Post"."post_id" AS "Post_post_id" FROM "Post" "Post"
```

Returned from the database:
```
+--------------+
| post_post_id |
+--------------+
|            1 |
|            2 |
|            3 |
+--------------+
```

The conflict comes when the code pointed to in the snippet does an object index into the returned results, looking for the key `Post_post_id`, but cannot find a match as it is returned from the database in lowercase.

**Comment by derek-baker** [comment]
> I've done a bit more reading and it looks like this is a Postgress thing? and the database is forcing all returned values to lower case, i find it hard to believe that no-one has encountered this before. What am i doing wrong?

>Maybe you'll try to execute raw sql query on your postgres instance and check if you have expected results?

I can reproduce the same issue while using raw sql.

**Comment by nquinn721** [comment]
Did this ever get fixed? I'm running into a similar issue.
Here's my class
`
@Entity("user")
export class User extends BaseEntity {
`
Code: `User.find()` 
SQL Created: `query: SELECT `User`.`id` AS `User_id`, `User`.`username` AS `User_username`, `User`.`cellNumber` AS `User_cellNumber`, `User`.`phoneNumber` AS `User_phoneNumber`, `User`.`firstName` AS `User_firstName`, `User`.`lastName` AS `User_lastName`, `User`.`middleInitial` AS `User_middleInitial`, `User`.`sipAddress` AS `User_sipAddress`, `User`.`admin` AS `User_admin`, `User`.`super` AS `User_super`, `User`.`password` AS `User_password`, `User`.`createdAt` AS `User_createdAt`, `User`.`updatedAt` AS `User_updatedAt`, `User`.`settingsId` AS `User_settingsId`, `User`.`medicalSystemId` AS `User_medicalSystemId` FROM `user` `User``

So even though the names of the table is "user" we are getting capitalized User when finding. However if I do this

Code: `const user = await getConnection()
      .getRepository(User)
      .createQueryBuilder("user")
      .where("user.id = :id", { id: 1 })
      .getOne();`
SQL Created: `query: SELECT `user`.`id` AS `user_id`, `user`.`username` AS `user_username`, `user`.`cellNumber` AS `user_cellNumber`, `user`.`phoneNumber` AS `user_phoneNumber`, `user`.`firstName` AS `user_firstName`, `user`.`lastName` AS `user_lastName`, `user`.`middleInitial` AS `user_middleInitial`, `user`.`sipAddress` AS `user_sipAddress`, `user`.`admin` AS `user_admin`, `user`.`super` AS `user_super`, `user`.`password` AS `user_password`, `user`.`createdAt` AS `user_createdAt`, `user`.`updatedAt` AS `user_updatedAt`, `user`.`settingsId` AS `user_settingsId`, `user`.`medicalSystemId` AS `user_medicalSystemId` FROM `user` `user` WHERE `user`.`id` = ? -- PARAMETERS: [1]`

Also when I hit an endpoint it often double quotes the where clause, which in sql forces case sensitivity
` WHERE ("User"."id" = ?) -- PARAMETERS: [1]`

Now this doesn't cause any issues when I hit my local mysql. There's a couple reasons this might be true, one is 'lower_case_table_names' flag in my local is set to 2 which means I can have capital letters in table names. So even though the `where` clause is the wrong case my local db obviously doesn't care. However the 'lower_case_table_names' flag on my microsoft azure db is set to 1 which means you cannot have uppercase letters in table names. I still haven't figured out how to solve the azure uppercase issue, but either way typeorm should follow the db name when creating sql instead of the class name.

**Comment by tr1stan** [comment]
I've run into a similar issue when generating migrations, My MySQL tables are PascalCase and I'm defining them as such in TypeOrm `@Entity('PascalCase')` but the migrations don't recognise that the table already exists and tries to generate a `CREATE TABLE PascalCase ...` command. If I @Entity('pascalcase') the decorator, it sees that it exists and ignores it. My lower_case_table_names is set to `2`.

**Comment by imnotjames** [comment]
I use postgres day to day with typeorm and cannot replicate any of the issues you're purporting.

> I've run into a similar issue when generating migrations, My MySQL tables are PascalCase and I'm defining them as such in TypeOrm `@Entity('PascalCase')` but the migrations don't recognise that the table already exists and tries to generate a `CREATE TABLE PascalCase ...` command. If I @entity('pascalcase') the decorator, it sees that it exists and ignores it. My lower_case_table_names is set to `2` because I'm on MacOS.

This is completely unrelated.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
The test you made was missing an `await` before the save.  After adding that and rebasing the tests passed.  As such it seems like this is no longer an issue.
