### ISSUE TITLE
Migrations are not detected after schema drop

### ISSUE THREAD

**Issue by deweve** [typeorm/typeorm#3331]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.3.0-alpha.22` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I have wanted to clean my database, so I have run : 
`typeorm schema:drop` 
then generate new migrations, but the cli has writen :
`No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command`
So I've tried to recreate my database, but the problem is still here
`module.exports = {
  "type": "postgres",
  "host": process.env.DATABASE_HOST || "localhost",
  "port": process.env.DATABASE_PORT || 5432,
  "username": process.env.DATABASE_USERNAME || "test",
  "password": process.env.DATABASE_PASSWORD || "test",
  "database": process.env.DATABASE_DATABASE || "syntrophi-test",
  "schema": process.env.DATABASE_SCHEMA || "public",
  "synchronize": false,
  "logging": true,
  "entities": [
    "build/src/server/model/entities/**/*.js"
  ],
  "migrations": [
    "build/src/server/model/migrations/**/*.js"
  ],
  "cli": {
    "entitiesDir": "src/server/model/entities",
    "migrationsDir": "src/server/model/migrations"
  }
};
`

**Comment by pleerock** [comment]
can you please provide a reproduction repo? (use sqlite database and commit exist database)

**Comment by deweve** [comment]
https://github.com/deweve/typeorm_issue

I've tried to recreate just a simple project with typeorm and I cannot generate any migrations

**Comment by havenchyk** [comment]
@deweve what do you mean by 

> I've tried to recreate just a simple project with typeorm and I cannot generate any migrations

did you get any error?

**Comment by havenchyk** [comment]
@deweve could you please add instructions, how did you run migrations generating?

**Comment by deweve** [comment]
When I tried to generate migrations with the command : 
`typeorm migration:generate -n Test`
I have `No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command`

**Comment by deweve** [comment]
I'm really intrigued because I have tried with a new project and I have the same error

**Comment by havenchyk** [comment]
@deweve just to clarify, do you have your tables set in db? Or are you trying to generate migrations on an empty db?

**Comment by deweve** [comment]
I don't have any tables in my database in the db maybe just the migrations tables which was generated by the cli

**Comment by deweve** [comment]
So I am really sorry, I've made a mistake in my ormconfig file, I was confused with my branches and the changes.

Thanks for your help.

You're doing a great job with typeorm

**Comment by havenchyk** [comment]
@deweve but what was the mistake, could you please share?

**Comment by deweve** [comment]
So I have just reorganized my repository, and the ormconfig file was incorrect. The path for the migrations was `build/src/models/...` but the real path was `build/model`
I've realized this error when I've checkout in the repository. so the `schema:drop` wasn't the problem.

**Comment by havenchyk** [comment]
@deweve would you like maybe to raise an exception for this case?

**Comment by akosasante** [comment]
+1 I also just now ran into this after cloning my repo to the production server. Would be nice if the error message more clearly indicated that it simply couldn't find any files at that path. Otherwise, it currently was a bit misleading as it seemed like it found files, but that the migration wasn't needed. I can take a look at creating a PR to raise an exception/improve the message output if you don't mind pointing me to the right place?

**Comment by deweve** [comment]
It would be clearer if the message said: 'the migrations files are missing' or 'No migration files'. I remember when I've init a typeorm project, I've spent times figuring it out, I needed to first compile the migrations to run them

**Comment by nicogreenarry** [comment]
In case someone else ends up here because they're getting a "No migrations are pending" message (despite there being new migrations), and the comments above don't help, here's what solved the problem for me.

I've never been able to get typeorm's migration generation to work well for me, I created my recent migration file from another existing migration file.

The reason I wasn't able to create a migration using that new file was that I had neglected to update the name of the migration class, and apparently typeorm uses the class name to decide if the migration already exists in your migrations table. Once I changed that class name in my new migration file, the migration worked as expected.

**Comment by Malvolio** [comment]
For future reference:  I had the same error message, because my `ormconfig.json` said 
```
  "entities": [
	"src/entity/**/*.ts"
    ],
```
But all the actual entities were in `src/entities`.

So yes, a better error message would have been helpful.

**Comment by saturnavt** [comment]
Make shure you ormconfig.json and the app.module.ts connection is the same.

**Comment by matgott** [comment]
I'm having similar issue. I add two relations to one of my entities and when I run migration:generate no changes were found.

My config is fine because other modifications to the entities are detected.
