### ISSUE TITLE
How to get mongo driver instance

### ISSUE THREAD

**Issue by thonythony** [typeorm/typeorm#3491]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ x ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Hello,

I need to save some files in mongodb. It offers GridFs for this use case (http://mongodb.github.io/node-mongodb-native/api-articles/nodekoarticle2.html). I don't know how to get mongodb instance from typeorm.

I get driver instance with following snippet : 

```typescript
import { getConnection } from 'typeorm';
import { MongoDriver } from 'typeorm/driver/mongodb/MongoDriver';

const connection = getConnection();
const isMongo = connection.options.type === 'mongodb';

if (isMongo === true) {
  const driver = connection.driver as MongoDriver;
}
```

But when I read the code, I see the mongodb is protected : https://github.com/typeorm/typeorm/blob/60a99772e0ca990f2abcf1ac4c65d2d7054e4e9a/src/driver/mongodb/MongoDriver.ts#L117

Moreover, `MongoDriver` is not exported in root, I need to pass full path for import it, is it normal ?

Can you help me to get mongodb instance please ?

Thanks

**Comment by webleaf** [comment]
try this workaround :)
```typescript
const mongodb = (connection.driver as any).mongodb;
```

**Comment by pleerock** [comment]
if you want to make it public feel free to PR.

**Comment by rustamwin** [comment]
Why need need? explain please

**Comment by thonythony** [comment]
I need this because some features related to mongodb are missing in typeorm and getting mongodb driver instance should be useful for doing some advanced stuff related to mongodb

**Comment by vlapo** [comment]
I think in case of mongodb we can expose mongo client as public. Mongo support is not perfect in typeorm and it would be nice to get users some way to workaround.

**Comment by rustamwin** [comment]
Yeah. By design should be public as other drivers

**Comment by chengjia0807** [comment]
question..
Why all the function names in the native driver are Pascal case?

**Comment by chriszrc** [comment]
I just went through this process trying to get to the underlying Sqlite connection, and I can attest that this is not very well documented in typeorm, and is confusing. 

The docs only briefly mention what to do here (under the entry for driver):

https://typeorm.io/#/connection-api/connection-api

And even then, it's not clear if you're supposed to casting the driver to some sort of native driver class or typeorm class. Reading the source, I realized it's directing you to cast to a typeorm driver wrapper, but when you do this:

```
let sqlite3Conn = getConnection().driver as SqliteDriver;
```

The SqliteDriver is not exported by default, so unless you explicitly include a reference to the file in the import:

```
import {SqliteDriver} from "typeorm/driver/sqlite/SqliteDriver";
```

Typescript won't even let you do it. I think getting to the underlying database connection is an important step for people, and this section in docs should be expanded. For me, with sqlite, I needed to get to this because for node-sqlite3, you need to use the built in database methods for adding extensions-

**Comment by rustamwin** [comment]
@chriszrc Feel free to submit PR :)
