### ISSUE TITLE
Migrations not working

### ISSUE THREAD

**Issue by jdelobel** [typeorm/typeorm#350]
When i run:

`>typeorm migrations:create -n ActivateUUID (file is created)`

then

`>typeorm migrations:run
`
i have the fallowing message:

> No migrations are pending

**Comment by pleerock** [comment]
This sounds strange. Can you create a simple git repo with reproduction of this issue?

**Comment by jdelobel** [comment]
Hi,

I just created the repo for you. Thanks in advance.

https://github.com/jdelobel/typeorm-migrations

**Comment by icewind** [comment]
I had similar issue just because a wrong config. Migrations are running from js files and before running `migrations:run` you have to compile your migrations and models

**Comment by pleerock** [comment]
you have wrong configuration. You are outputting compiled sources into `build` directory. However in your config you are loading migrations from `src/migration/*.js`. You simply don't have such files in your `src/migration` directory. Instead they are in the `build/migration` directory. Thats why you need to change your configuration this way:

```json
[
  {
    "name": "default",
    "driver": {
      "type": "postgres",
      "host": "localhost",
      "port": 5432,
      "username": "admin",
      "password": "admin",
      "database": "admin"
    },
    "migrations": [
      "build/migration/*.js"
    ],
    "cli": {
        "migrationsDir":  "build/migration"
    },
    "autoSchemaSync": true
  }
]
```

And you'll see your migrations executed:

```
0 migrations are already loaded in the database.
1 migrations were found in the source code.
1 migrations are new migrations that needs to be executed.
Migration ActivateUUID1489616541690 has been executed successfully.
```

**Comment by cfgj** [comment]
I've some different problem. When I changed my entities, eg. removing or adding properties, and then I executed `migrations:generate`, I've got empty migration and message `No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migrations:create" command`. I expected migration with sql needed to update schema in database. `schema:sync` works perfect but `migrations:generate`, unfortunately, doesn't. I use typeorm@0.1.0-alpha.32 and TypeScript.

Here is my ormconfig.js
```js
    {
        name: 'workoutastic_cfgj-computer',
        type: 'postgres',
        host: '...',
        port: 5432,
        username: '...',
        password: '...',
        database: '...',
        autoSchemaSync: false,
        autoMigrationsRun: true,
        entities: [
            './dist/data/entites/**/*.js'
        ],
        migrations: [
            './dist/data/migrations/*.js'
        ],
        cli: {
            migrationsDir: './src/data/migrations'
        }
    }
```

**Comment by pleerock** [comment]
`migrations:generate` is only supported on mysql at the moment. In a near future it will support other databases as well.

**Comment by darkbasic** [comment]
> migrations:generate is only supported on mysql at the moment

@pleerock does it work with postgresql right now?

**Comment by pleerock** [comment]
@darkbasic partially, expect complete support in 0.2.0

**Comment by nicogreenarry** [comment]
In case someone else ends up here because they're getting a "No migrations are pending" message (despite there being new migrations), and the comments above don't help, here's what solved the problem for me.

I've never been able to get typeorm's migration generation to work well for me, I created my recent migration file from another existing migration file.

The reason I wasn't able to create a migration using that new file was that I had neglected to update the name of the migration class, and apparently typeorm uses the class name to decide if the migration already exists in your migrations table. Once I changed that class name in my new migration file, the migration worked as expected.

**Comment by vngrv** [comment]
> Hi,
> 
> I just created the repo for you. Thanks in advance.
> 
> https://github.com/jdelobel/typeorm-migrations

 Empty link :(

**Comment by arturhun** [comment]
Should anyone find this ticket searching for help with "no pending migrations" issue:

The most beloved answer in this issue (16 Mar 2017 by @pleerock) has the clue piece of info that should be better emphasized in [the docs example](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md#creating-a-new-migration) where the migration-related  

```
    "migrations": [
      "dist/migration/*.js"
    ],
```

In my case, since NestJS builds a **`dist`** folder, the migrations need to be sought in there.

My ormconfig.json looks as follows:

```
[
  {
    "name": "default",
    "type": "postgres",
    "host": "localhost",
    "port": 5432,
    "username": "postgres",
    "password": "postgres",
    "database": "bookstore",
    "migrations": [
      "dist/migration/*.js"
    ],
    "migrationsRun": true,
    "entities": [
      "dist/**/*.entity.js"
    ],
    "synchronize": false,
    "logging": true,
    "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
    }
  }
]

```

HTH someone. Feel free to comment on this config. I am still a newbie to it.

**Comment by Diego-Mike** [comment]
Hi, this is my first time using typeORM and i really don't know what to do with this problem, i've tried too many things, nothing has worked so far, the problem is migrations, it gives me the error

`No changes in database schema were found - cannot generate a migration. To create a new empty migration use "typeorm migration:create" command`

This is my ormconfig

`
{
  "type": "postgres",
  "host": "localhost",
  "port": 5432,
  "username": "postgres",
  "password": "diegoelmono",
  "database": "redit",
  "synchronize": true,
  "logging": true,
  "entities": ["src/entities/**/*.js"],
  "migrations": ["src/migrations/**/*.js"],
  "subscribers": ["src/subscribers/**/*.js"],
  "cli": {
    "entitiesDir": "src/entities",
    "migrationsDir": "src/migrations",
    "subscribersDir": "src/subscribers"
  }
}

`

This is my  package.json

`
{
  "name": "new-typeorm-project",
  "version": "0.0.1",
  "description": "Awesome project developed with TypeORM.",
  "devDependencies": {
    "@types/bcrypt": "^5.0.0",
    "@types/cookie": "^0.4.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/express": "^4.17.11",
    "@types/jsonwebtoken": "^8.5.1",
    "@types/morgan": "^1.9.2",
    "@types/node": "^15.0.2",
    "morgan": "^1.10.0",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "bcrypt": "^5.0.1",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "cookie": "^0.4.1",
    "cookie-parser": "^1.4.5",
    "dotenv": "^9.0.1",
    "express": "^4.17.1",
    "jsonwebtoken": "^8.5.1",
    "pg": "^8.4.0",
    "reflect-metadata": "^0.1.10",
    "typeorm": "0.2.32"
  },
  "scripts": {
    "start": "ts-node src/server.ts",
    "dev": "nodemon --exec ts-node src/server.ts",
    "typeorm": "ts-node ./node_modules/typeorm/cli.js"
  }
}

`

This is the schema i want to update in my postgres DB

`
import {
  Entity as TOEntity,
  Column,
  Index,
  BeforeInsert,
  OneToMany
} from "typeorm";
import bcrypt from "bcrypt";
import { IsEmail, Length } from "class-validator";
import { Exclude } from "class-transformer";

import Entity from "./Entity";
// import Post from "./Post";

@TOEntity("users")
export default class User extends Entity {
  constructor(user: Partial<User>) {
    super();
    Object.assign(this, user);
  }

  @Index()
  @IsEmail()
  @Column({ unique: true })
  email: string;

  @Index()
  @Length(3, 200)
  @Column({ unique: true })
  username: string;

  @Exclude()
  @Length(6, 200)
  @Column()
  password: string;

  // @OneToMany(() => Post, post => post.user)
  // posts: Post[];

  @BeforeInsert()
  async hashedPassword() {
    this.password = await bcrypt.hash(this.password, 6);
  }
}

`

And this is the command

`
import {
  Entity as TOEntity,
  Column,
  Index,
  BeforeInsert,
  OneToMany
} from "typeorm";
import bcrypt from "bcrypt";
import { IsEmail, Length } from "class-validator";
import { Exclude } from "class-transformer";

import Entity from "./Entity";
// import Post from "./Post";

@TOEntity("users")
export default class User extends Entity {
  constructor(user: Partial<User>) {
    super();
    Object.assign(this, user);
  }

  @Index()
  @IsEmail()
  @Column({ unique: true })
  email: string;

  @Index()
  @Length(3, 200)
  @Column({ unique: true })
  username: string;

  @Exclude()
  @Length(6, 200)
  @Column()
  password: string;

  // @OneToMany(() => Post, post => post.user)
  // posts: Post[];

  @BeforeInsert()
  async hashedPassword() {
    this.password = await bcrypt.hash(this.password, 6);
  }
}

`

As i already said, i've spent hours looking for asnwers, but nothing has worked, can someone help me with this?

**Comment by SLAYER-CODE** [comment]
What happens if I use tsc-node and I don't have the dist folder? did i need to switch to tsc?
