### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by yulintianxia** [typeorm/typeorm#3500]
Cannot create a new connection named "default", because connection with such name already exist and it now has an active connection session.
        |     at new AlreadyHasActiveConnectionError

**Comment by vlapo** [comment]
@yulintianxia again. We are using English to communicate in this project. Also we have a issue template to gather as much as possible information to help you. Why are you ignoring this template? Do you speak English?

This error is because you are creating two connections with "default" name. use `name` property in connection options. http://typeorm.io/#/connection-options

> name - Connection name. You'll use it to get connection you need using getConnection(name: string) or ConnectionManager.get(name: string). Connection names for different connections cannot be same - they all must be unique. If connection name is not given then it will be called "default".

**Comment by rustamwin** [comment]
@pleerock that too
