### ISSUE TITLE
Enhancement: Enable Case Insensitive Uniqueness 

### ISSUE THREAD

**Issue by rightisleft** [typeorm/typeorm#356]
Enhancement: Enable Case Insensitive Uniqueness 

  @Column(ColumnTypes.TEXT, {nullable: true, unique: true})
  @autoserialize email: string;

This will not catch jack@rightisleft.com vs JACK@rightisleft.com

Suggestion: Add a case insensitive check

**Comment by pleerock** [comment]
can you provide what code and where orm should generate in this case?

**Comment by zh99998** [comment]
https://github.com/typeorm/typeorm/issues/327

like this

**Comment by pleerock** [comment]
is case sensitive/insensitive is the only thing used on indices?

**Comment by pleerock** [comment]
adding indices expert @iz-iznogood

**Comment by AlexMesser** [comment]
This feature won't be implemented (at least in the near visible future), because of lot of different database specifics and multiple issues with getting information about exist database indices and synchronizing them automatically.

You should create index manually (for example in the migrations) with any index signature you want. To make TypeOrm ignore these indices during synchronization use following syntax:

```ts
@Entity()
@Index("ignored_index", { synchronize: false })
export class Post {
```
avaliable from `typeorm@0.2.0-alpha.27`
