### ISSUE TITLE
Add `browser: browser/index.js`, `main: index.js` to package.json

### ISSUE THREAD

**Issue by danielmhanover** [typeorm/typeorm#3583]
This would allow re-use of the same source files across both server and client environments in Webpack, as Webpack will intelligently choose the right TypeORM build based on the dev environment.

**Comment by vlapo** [comment]
Does it mean that this webpack config will be no more necessary ? 

http://typeorm.io/#/supported-platforms/browser

**Comment by danielmhanover** [comment]
that is correct

**Comment by chriswep** [comment]
@danielmhanover I was looking for the same thing. Since this is a small change, i created a pull request: https://github.com/typeorm/typeorm/pull/3623

I additionally added dummy classes to replace backend-only drivers in browser builds via the same configuration option in `package.json`. Using my fork of typeorm i could successfully import typeorm in webpack builds with zero additional configuration and bundle size reduced by one third (@vlapo)

@pleerock what do you think about the approach with the dummy classes? I think it's safe to assume that people don't use mysql/oracle in a browser/mobile environment? It would bring a significant advantage to browser builds by default. However i can understand if you don't like this approach. From the few places i looked into the code, i feel there would be some refactoring needed to have a more "solid" option to disable drivers. Do you see any other areas where we can save on bundle size in browsers? I would be interested to look into this.

**Comment by pleerock** [comment]
I would really like to see some better approach to prevent having multiple instances of the same classes, this is going to be annoying in IDE because it will suggest you multiple instances of classes

**Comment by chriswep** [comment]
ya, the IDE issue also came to my mind. i don't have enough insight in the code to determine if there is another simple way to achieve a similar result (hints?). from my perspective (and use case) the benefit would outweigh the IDE issue - but for sure there are other valid perspectives on this. Would it help if i add jsdoc comments to the classes like "DO NOT USE THIS CLASS"? :-) 

i think the same effect can be achieved via webpack configuration, however i think a smaller default bundle size would make using typeorm in the browser less painful. don't know how many people use it in this environment though.

**Comment by alfaproject** [comment]
People that develop in serverless environments also want small bundles to save costs on storage and execution time as well. That's a back-end environment but would also benefit from this kind of optimizations.

**Comment by chriswep** [comment]
since this is fixed in https://github.com/typeorm/typeorm/pull/3623, i think this issue can be closed @pleerock  @danielmhanover

**Comment by vlapo** [comment]
Close as merged in https://github.com/typeorm/typeorm/pull/3623
