### ISSUE TITLE
Why doesnt repository .save use DeepPartial like preload?

### ISSUE THREAD

**Issue by onionhammer** [typeorm/typeorm#3687]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`
[x] `all`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've started using 'preload' to help build objects because it gives intellisense, and then switching to '.save' before saving the file; why doesnt .save simply use the DeepPartial type that .preload uses?

**Comment by nmeyering** [comment]
I stumbled upon this myself but I think that's more of a failure of the IDE in this case? Not a Typescript expert, but my guess is it's necessary to include the extra `T` to be able to refer to the same type twice: in the parameter and the return type.

**Comment by imnotjames** [comment]
`save` has to be persisted to the database so if a field is not nullable or undefinable it cannot be included.  Deep partial does not provide those consistencies.

It uses `T extends Entity` because of single-table-inheritance.  We cannot chnage that part.

To discuss it further, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
