### ISSUE TITLE
Does an ORM provide protection from SQL injection?

### ISSUE THREAD

**Issue by Rick-Kirkham** [typeorm/typeorm#3696]
**Issue type:**

[ x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Apologies if this is the wrong place to ask this. 
Wikipedia's article on [SQL Injection](https://en.wikipedia.org/wiki/SQL_injection#Mitigation) says that an ORM provides protection against SQL injection. The exact words are: "Using object-relational mapping libraries avoids the need to write SQL code. The ORM library in effect will generate parameterized SQL statements from object-oriented code." 

This seems to be saying that it is inherent to any ORM that it generates "parameterized SQL statements", and thus protects against SQL injection. 

But this puzzles me because as far as I can tell none of the TypeScript or JavaScript ORMs, including this one, make this claim for themselves; and I would think that they would if it were true. So, my questions are: "Is what Wikipedia says true of ORMs in general?" and "Is what it says true of typeorm in particular?"

**Comment by feather-jmalone** [comment]
i would say it is a baseline expectation for any ORM, yes. which is likely why it's not mentioned in docs -- it's assumed, so long as you as use the ORM's core API or query builder.

and that's where the caveat is... ORMs provide many ways to construct a database query, but they also give you the option/flexibility to write 'raw,' do-it-yourself queries as a string... or they allow you to write some part of a generated query as a raw string. obviously you want to avoid doing this, as it kinda defeats the purpose of using an ORM... but there is a case for it every now and again.

in that scenario, where you're simply injecting user input variables into a string query (instead of using the ORM's core API / query builder functions), i would absolutely not expect it to protect you from such attacks.

**Comment by Rick-Kirkham** [comment]
Great answer! Thanks!
