### ISSUE TITLE
Support for PostGIS data types

### ISSUE THREAD

**Issue by smitalm** [typeorm/typeorm#370]
Do you plan to support [PostGIS](http://postgis.net/docs/reference.html) geography data types?

**Comment by pleerock** [comment]
Maybe after #344 we can support external extensions? By having for example `typeorm-postgres-postgis` module which will declaration merging for `ColumnPostgresType` ?

**Comment by 19majkel94** [comment]
If it's only about placing custom types in SQL DDL, you can do something like this:
```typescript
interface ColumnOptions {
    primary?: boolean;
}
type columnType = "number"|"text";

function DecoratorTest(type: columnType, options?: ColumnOptions);
function DecoratorTest(type: string, options: ColumnOptions & { customType: true });
function DecoratorTest(type: string, options?: ColumnOptions) {
     return function (object: Object, propertyName: string) {
     }
}

class Test {

    @DecoratorTest("long_number", { customType: true }
    customTypeProperty: number;

    @DecoratorTest("text")
    normalProperty: string;

}
```
Normal user would have type-safe for standard postgres functionality and if someone install 3rd party plugins to database, it can use `customType` option and provide his own type name.

But it has to have support in switch-case in typeorm or sth - I don't know how the support for column types works 😜

**Comment by pleerock** [comment]
Custom column data types are landed in `0.1.0-alpha.10`. Now you can use any datatype postgres has. Feel free to test them!

**Comment by RDeluxe** [comment]
Where are we on that ? Despite point & other type being supported, Postgis itself is not. What amount of work would be required to make postgis and typeorm work together ?

**Comment by pleerock** [comment]
Adding new types support is easy to implement feature.

**Comment by RDeluxe** [comment]
Well, I'm not quite sure about that.

Yes, adding new supported types in ColumnTypes and Postgres driver is quite easy. I managed rapidly to add the `GEOMETRY(POINT, 4386)` type.

However, to working with Postgis means using Postgis sql functions quite often. To insert a new geographical point in a `GEOMETRY(POINT, 4386)` column for example :  `ST_SetSRID(ST_MakePoint(lat, long), 4326)`. 

I talked on Gitter about this issue : the `transformer` option can solve the INSERT issue, as I discovered (after digging in the code) that it could take a function as a parameter, and in such case it will be considered as a SQL function.

So this works : 
``` typescript
  to(coordinates: ICoordinates): any {
    return function () { return "ST_SetSRID(ST_MakePoint(" + coordinates.lat + ", " + coordinates.long + "), 4326)" }
  }
```

However, to fetch the data the transformer will only be applied *after* the rawsql query has been executed. Making it impossible to easily execute a function to fetch the data. I could definitely use a RAW SQL query, like I did before, but I think that every type which need it should have an INSERT and SELECT sql_transform, used to create the SQL query. By creating this layer of abstraction we would have an easy to extend system, in which end-user / extension creators could create new types easily without modifying typeorm directly.

**Comment by pleerock** [comment]
Sorry I haven't worked with geo types and don't know all their specifics. Why can't we just select columns and have results, isn't postgres supposed to handle such logic on its own?

**Comment by RDeluxe** [comment]
Nope, there are a lot of ways to work with geographic data with postgis, the system is really fast because it's optimizing everything (that's how you can get all the points of interest in a certain radius for example). So inserting and selecting geographic data always go through some postgis functions.

**Comment by RDeluxe** [comment]
I may have some time during my weekends and late nights to work on this, if you want to clarify the abstraction layer /  good way to make typeorm extensions (such as `@typeorm/postgis`) I could start something

**Comment by theigor** [comment]
@RDeluxe , regarding
> as I discovered (after digging in the code) that it could take a function as a parameter, and in such case it will be considered as a SQL function.

Can you point me to where you discovered this? I can't find it nor get it to work. I am trying to insert a point with the mysql driver. Making the `to` return a function like you suggest:
```ts
  import { Point } from 'geojson';
  ...

  @Column("blob", {
    transformer: {
      to: (v: Point) => {
        return function () { return `ST_GeomFromGeoJSON(${JSON.stringify(v)})` }
      }
    }
  })
  location: Point;
```

ends up with this sql sent to the db:
```
  sql: 'INSERT INTO `table`(`location`) VALUES (\'function () { return `ST_GeomFromGeoJSON(${JSON.stringify(v)})`; }\')
```

Same thing if I do `to: (v: Point) => () => `ST_GeomFromGeoJSON(${JSON.stringify(v)})`,` - I get `\'() => `ST_GeomFromGeoJSON(${JSON.stringify(v)})`\'`

If I do it without a function, like so:
```ts
  @Column("blob", {
    transformer: {
      to: (v: Point) => `ST_GeomFromGeoJSON(${JSON.stringify(v)})`
    }
  })
  location: Point;
```
I get this sent to mysql:
```
  sql: 'INSERT INTO `table`(`location`) VALUES (\'ST_GeomFromGeoJSON({\\"type\\":\\"Point\\",\\"coordinates\\":[42.3600825,-71.05888010000001]})\')
```

I think I just need some way to unescape the value for this column so the mysql function is treated as a function. Any ideas?

**Comment by theigor** [comment]
Also, just for reference, I am able to get geometry _out_ of mysql as geojson with this `from` transformer:
```ts
@Column("blob", {
    transformer: {
      to: (v: Point) => eval(`ST_GeomFromGeoJSON(${JSON.stringify(v)})`),
      from: (v: any) => { return {type: "Point", coordinates: [ v.x, v.y ] } as Point }
    }
  })
  location: Point;
```
when I do `console.log(v)` inside the `from` function, I get an object like this:
```json
{ x: 42.3600825, y: -71.05888010000001 }
```

**Comment by RDeluxe** [comment]
Not quite sure, in the Postgres driver if I remember correctly. It may be line 386, in `escapeQueryWithParameters` method.

**Comment by RDeluxe** [comment]
I have been digging quickly in Sequelize, and I see they have an abstraction layer allowing user to create types.

I did not use Sequelize recently, but that's more or less what I advised earlier.
[Example](https://github.com/sequelize/sequelize/blob/fe06b45caa8577a8c57c5baf16daf5ad088c400c/lib/dialects/postgres/data-types.js) (you can see here the GEOGRAPHY type).

I'm wondering how hard this could be for TypeORM. Instead of using the type directly as a string, we would use a Class with a toSQL() method to create the SQL type string. This can already be done with transformer, but they are not a good solution for extending the framework.

Pay attention to 
``` javascript
 GEOGRAPHY.prototype._stringify = function _stringify(value, options) {
    return 'ST_GeomFromGeoJSON(' + options.escape(JSON.stringify(value)) + ')';
  };
``` 
This piece of code is what is missing right now in TypeORM, allowing users to use SQL functions while selecting

**Comment by RDeluxe** [comment]
Hello there.

Where are we on that ? I started a fork a while ago (but considering the repo evolution speed I fear to be already outdated) to put some kind of sequelize like system in place.

**Comment by RDeluxe** [comment]
Just as a note, @theigor you are talking about Geometry types, native types for postgresql, while I'm talking about Geography types, specific to the Postgis extension.

**Comment by AlexMesser** [comment]
@RDeluxe I am currently working on GIS types implementation. I have not yet started working on PostGIS, but I faced the problem with SqlServer geography type. I see that you are good at geography types and I have a question:

I have a table with geography type column and I try to insert same values in different ways:
```sql
INSERT INTO test VALUES ('POINT(47.65100 -12.34900 4326)')
INSERT INTO test VALUES (geography::Point(47.65100, -12.34900, 4326))
INSERT INTO test VALUES (geography::STGeomFromText('POINT(47.65100 -12.34900)', 4326))
```
result: 

![image](https://user-images.githubusercontent.com/17142628/38140733-874492c6-344e-11e8-95a3-566e73895a09.png)

They all give different results. I've never worked with GIS and I don't know which of them is right correct. Can you help me with this ?

**Comment by RDeluxe** [comment]
Hello Alex,

I have no experience with SqlServer. But : 

* You won't use POINT directly, POINT is a geometry type and not a GEOGRAPHY type, even in SQLServer as far as I can see
* From the sqlserver doc the correct way to save a geography point is your 2nd [solution](https://docs.microsoft.com/fr-fr/sql/t-sql/spatial-geography/point-geography-data-type)
* I checked the third solution, seems good too

Question is: what's the type of your column ? Is it `geography` ?

I suggest reading this answer which clarifies the difference between Geography types and Geometry types : https://gis.stackexchange.com/questions/223487/what-is-the-purpose-of-postgis-on-postgresql

PostGIS saves the data in a non readable format, so we can't just `SELECT` it (that's actually the reason of this issue).
Like explained [here](https://www.dataiku.com/learn/guide/other/geo/convert-coordinates-with-PostGIS.html) we can however use `SELECT ST_AsText(geom) as points FROM list_geom` or `SELECT ST_X(geom) as longitude, ST_Y(geom) as latitude FROM list_geom` to get the information in the WKT format.

**Comment by AlexMesser** [comment]
Hello @RDeluxe, currently I'm busy at my main job and unfortunately I can't spend lot of time to TypeORM. I will proceed to this task as soon as I have free time. Meanwhile this task is opened for contributions.

**Comment by theigor** [comment]
Hey @RDeluxe - sorry for the delayed response. Didn't notice you had a question for me.
So, admittedly, I am not an expert on PostGIS but I have some experience with it and with OpenLayers and here are a couple of interesting things to notice:
1. While we typically think of lat and long in that order, OpenLayers actually uses long, lat. Here's the explanation - https://openlayers.org/en/latest/doc/faq.html#why-is-the-order-of-a-coordinate-lon-lat-and-not-lat-lon-. Because of this, there seems to be some validity to the second approach above.
2. The first approach is definitely wrong - it seems it just inserted it as a varchar (although... not quite because it added more precision :/).
3. I have POINTs working outside of typeorm in MySQL.
    * The datatype is POINT, it looks like this when I select * in Workbench:
![image](https://user-images.githubusercontent.com/6673707/40578001-c88965aa-60da-11e8-9393-d5314a9a505e.png)
    * And if I right click and open value in editor, I am able to see this when viewing it as text. Note that this is _the same field_ that I am viewing as text or geojson that mysql lets me do because the datatype is POINT.
![image](https://user-images.githubusercontent.com/6673707/40578034-1610edd4-60db-11e8-80af-d7b0dddadc0b.png)
![image](https://user-images.githubusercontent.com/6673707/40578040-25a60f68-60db-11e8-9fd8-af0ae6a14d6a.png)
4. However, I have a whole other project where my geo_json field is simply TEXT and I transform it on the way in and out. The point that I am making is I think the data types are just sugar and it's all text underneath. But like I said, I am not close to an expert on this.

Not sure if that helps at all...

**Comment by mojodna** [comment]
After spending a bit of time looking at this recently, it looks like there are 2 approaches. The less intrusive approach is to bypass the rudimentary spatial type support that exists for MySQL and MS SQL and use a `ValueTransformer`:

First, register `geometry` and `geography` to the list of supported data types (is there a way to do this from client code without patching the library?):

https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L87-L149

Then, register a column with a custom transformer that uses [`wkx`](https://github.com/cschwarz/wkx) to convert to/from WKB (well-known binary, e.g. `0101000020E610000000000000008046400000000000804640`) / GeoJSON / WKT (well-known text, e.g. `POINT(45 45)`):

```javascript
import { Geometry } from "geojson";
import {
  Column,
  Entity,
  PrimaryGeneratedColumn
} from "typeorm";
import { ValueTransformer } from "typeorm/decorator/options/ValueTransformer";
import * as wkx from "wkx";

class GeometryTransformer implements ValueTransformer {
  to(geojson: Geometry) {
    return wkx.Geometry.parseGeoJSON(geojson).toWkt();
  }

  from(wkb: any) {
    return wkx.Geometry.parse(new Buffer(wkb, "hex")).toGeoJSON();
  }
}

@Entity()
class GeocodedThing {
  @PrimaryGeneratedColumn() id: number;

  @Column("geometry", {
    transformer: new GeometryTransformer()
  })
  geom: Geometry;
}
```

At this point, any code that works with entities will use GeoJSON to represent geometries. It doesn't enforce types, so you'll be able to switch between `Point`, `LineString`, `Polygon`, etc. without constraints.

The other, more intrusive, approach is to add `geometry` and `geography` types to the [driver's `spatialTypes`](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L154) and expand the special handling for [`SELECT`s](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/query-builder/SelectQueryBuilder.ts#L1660-L1666) and [`INSERT`s](https://github.com/typeorm/typeorm/blob/d6fde58c03d94b7f7dce7a0f4b3c04130e97465e/src/query-builder/InsertQueryBuilder.ts#L419-L423).

The existing implementation (`AsText` / `GeomFromText` for MySQL) uses WKT (well-known text) as the intermediate representation, which is perhaps less useful, as it still needs to be parsed into something to support easier manipulation and operation. If one were to go down that path, the equivalent PostGIS functions as `ST_AsText` and `ST_GeomFromText` (the `ST` prefix refers to "spatial type" in the [SQL/MM Spatial standard](http://doesen0.informatik.uni-leipzig.de/proceedings/paper/68.pdf). `ST_AsGeoJSON` and `ST_GeomFromGeoJSON` are the SQL/MM (read: PostGIS / MySQL / MariaDB) functions for conversion, which would obviate the need for a custom transformer (it would be treated as a `json` column instead and parsed/stringified as necessary).

An additional nicety would be to sniff to spatial columns in use (similar to [checking for `hstore`, etc.](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L276-L318)) and attempt to register the `postgis` extension.

PostGIS types are a bit different than generalized types in that they're often parameterized. They work without parameters (`geometry` allows a column to store any type of geometry (point, line, polygon, geometry collection, etc.) without constraints on the SRID (spatial reference id; essentially the coordinate system in use--lat/lon is `4326` and is in degrees, web mercator (slippy maps around the web) is `3857` and units are "meters" (the length of a "meter" varies by latitude because earth is a spheroid; http://lyzidiamond.com/posts/4326-vs-3857 is a fantastic resource for understanding this and geographic coordinate systems in general better)). They can also restrict what's store in a column, e.g. `geometry(POINT, 4326)` will prevent non-points in coordinate systems other than lat/lon from being saved. `typeorm` doesn't look like it currently supports type parameterization, so this could be more of a long-term improvement that's not necessarily for immediate usefulness.

(`geography` is less commonly used in PostGIS, but has the benefit of allowing measurement calculations to occur in meters rather than degrees to produce human-readable output (what's the distance of 1º? it depends...))

As a relatively long-time JS and spatial dev, my preference would be to use GeoJSON as an internal representation rather than WKT (many other libraries, including [Turf](https://github.com/Turfjs/turf), support GeoJSON natively). This does represent a semver-major change though. I don't have time to put together a proper PR, but am happy to code review (just @ me on the PR).

**Comment by mojodna** [comment]
Oh, I also wanted to mention that it's helpful to think of anything spatial as being generalized to existing within a coordinate system. Since we usually think of our Cartesian coordinate systems as `(x, y)`, it makes sense (for anything machine-readable) to remain consistent when using lat/lon, which means `(lon, lat)` (which _is_ `(x, y)`.

**Comment by tomasoak** [comment]
Hey guys. I read everything but I couldn't figure out how to solve this simple problem:
Any can help me?

I already have a GeoJson data, storage at PostgreSQL as jsonb. 
I'm trying unsuccessfully this ways:

![image](https://user-images.githubusercontent.com/25818342/82354911-db086400-99d7-11ea-81d7-f8675d0e5b0c.png)

**Comment by lamuertepeluda** [comment]
@tomasoak sorry I didn't get it exactly, but geography and jsonb are different quite types on PostGIS. Ensure you have PostGIS installed with Postgresql first. Then, perhaps you should try migrating your data to geography type.

**Comment by tomasoak** [comment]
@lamuertepeluda thanks for answering and sorry by not being clear enough. I already have a Postgresql / Postgis database runny on.

This is what I have on database, a single-line jsonb object:
![image](https://user-images.githubusercontent.com/25818342/82382596-9e9e2d80-9a02-11ea-91e0-51e82e4ba3c7.png)
With de following value-structure (a FeatureCollection with several MultiPolygons):
`{"type": "FeatureCollection", "features": [{"id": "inputs.id_prod", "type": "Feature", "geometry": {"type": "MultiPolygon", "coordinates": [[[[-54.8766190000221, -1.46802399999992], [-54.8765140000221, -1.4685549999999], [-54.8770950000221, -1.46874899999991], [-54.8772950000221, -1.46827799999992], [-54.8766190000221, -1.46802399999992]]]]}, "properties": {"area_ha".......:`

But, when I put the decorator as 'geography' and geojson (column name) as string (I don't know what to assign here, I tried different thinks, unsuccessfully) I get this error message from graphql playground:
`"message": "function st_asgeojson(jsonb) does not exist",`

What do you suggest to fetch this single-line FeatureCollection data? What is the best way to assign its type?

**Comment by lamuertepeluda** [comment]
@tomasoak if you want to exploit PostGIS cool features such as indexes and manipulators for geography and geometry type, you should **migrate your column type** to "geography" type (or "geometry" type if your case fits, i.e. small areas or different SRID than 4326).

Then you can use @Coulmn('geography') without problem. 

Geography is a different type from json/jsonb and data can be converted to/from GeoJSON using operators such as https://postgis.net/docs/ST_AsGeoJSON.html

You can migrate to geography using https://postgis.net/docs/ST_GeomFromGeoJSON.html

Typeorm has a fair support for migrations of this type.

Of course you can stick to jsonb if this is your use case, but then your feature will behave just like a regular json object.

**Comment by kukuandroid** [comment]
Hi, how to use query builder to query this type of column ?

**Comment by kallol24** [comment]
@kukuandroid 

const query = connection.getRepository(Basic).createQueryBuilder('basic');

const response = await query.where('basic.verified2 @> :verified', {verified: {dob: false}}).getMany();

**Comment by hussainwali74** [comment]
> After spending a bit of time looking at this recently, it looks like there are 2 approaches. The less intrusive approach is to bypass the rudimentary spatial type support that exists for MySQL and MS SQL and use a `ValueTransformer`:
> 
> First, register `geometry` and `geography` to the list of supported data types (is there a way to do this from client code without patching the library?):
> 
> https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L87-L149
> 
> Then, register a column with a custom transformer that uses [`wkx`](https://github.com/cschwarz/wkx) to convert to/from WKB (well-known binary, e.g. `0101000020E610000000000000008046400000000000804640`) / GeoJSON / WKT (well-known text, e.g. `POINT(45 45)`):
> 
> ```js
> import { Geometry } from "geojson";
> import {
>   Column,
>   Entity,
>   PrimaryGeneratedColumn
> } from "typeorm";
> import { ValueTransformer } from "typeorm/decorator/options/ValueTransformer";
> import * as wkx from "wkx";
> 
> class GeometryTransformer implements ValueTransformer {
>   to(geojson: Geometry) {
>     return wkx.Geometry.parseGeoJSON(geojson).toWkt();
>   }
> 
>   from(wkb: any) {
>     return wkx.Geometry.parse(new Buffer(wkb, "hex")).toGeoJSON();
>   }
> }
> 
> @Entity()
> class GeocodedThing {
>   @PrimaryGeneratedColumn() id: number;
> 
>   @Column("geometry", {
>     transformer: new GeometryTransformer()
>   })
>   geom: Geometry;
> }
> ```
> 
> At this point, any code that works with entities will use GeoJSON to represent geometries. It doesn't enforce types, so you'll be able to switch between `Point`, `LineString`, `Polygon`, etc. without constraints.
> 
> The other, more intrusive, approach is to add `geometry` and `geography` types to the [driver's `spatialTypes`](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L154) and expand the special handling for [`SELECT`s](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/query-builder/SelectQueryBuilder.ts#L1660-L1666) and [`INSERT`s](https://github.com/typeorm/typeorm/blob/d6fde58c03d94b7f7dce7a0f4b3c04130e97465e/src/query-builder/InsertQueryBuilder.ts#L419-L423).
> 
> The existing implementation (`AsText` / `GeomFromText` for MySQL) uses WKT (well-known text) as the intermediate representation, which is perhaps less useful, as it still needs to be parsed into something to support easier manipulation and operation. If one were to go down that path, the equivalent PostGIS functions as `ST_AsText` and `ST_GeomFromText` (the `ST` prefix refers to "spatial type" in the [SQL/MM Spatial standard](http://doesen0.informatik.uni-leipzig.de/proceedings/paper/68.pdf). `ST_AsGeoJSON` and `ST_GeomFromGeoJSON` are the SQL/MM (read: PostGIS / MySQL / MariaDB) functions for conversion, which would obviate the need for a custom transformer (it would be treated as a `json` column instead and parsed/stringified as necessary).
> 
> An additional nicety would be to sniff to spatial columns in use (similar to [checking for `hstore`, etc.](https://github.com/typeorm/typeorm/blob/1fe884e1a1814b4de92fcad0cc20cdab3fd83a17/src/driver/postgres/PostgresDriver.ts#L276-L318)) and attempt to register the `postgis` extension.
> 
> PostGIS types are a bit different than generalized types in that they're often parameterized. They work without parameters (`geometry` allows a column to store any type of geometry (point, line, polygon, geometry collection, etc.) without constraints on the SRID (spatial reference id; essentially the coordinate system in use--lat/lon is `4326` and is in degrees, web mercator (slippy maps around the web) is `3857` and units are "meters" (the length of a "meter" varies by latitude because earth is a spheroid; http://lyzidiamond.com/posts/4326-vs-3857 is a fantastic resource for understanding this and geographic coordinate systems in general better)). They can also restrict what's store in a column, e.g. `geometry(POINT, 4326)` will prevent non-points in coordinate systems other than lat/lon from being saved. `typeorm` doesn't look like it currently supports type parameterization, so this could be more of a long-term improvement that's not necessarily for immediate usefulness.
> 
> (`geography` is less commonly used in PostGIS, but has the benefit of allowing measurement calculations to occur in meters rather than degrees to produce human-readable output (what's the distance of 1º? it depends...))
> 
> As a relatively long-time JS and spatial dev, my preference would be to use GeoJSON as an internal representation rather than WKT (many other libraries, including [Turf](https://github.com/Turfjs/turf), support GeoJSON natively). This does represent a semver-major change though. I don't have time to put together a proper PR, but am happy to code review (just @ me on the PR).

I just want a simple example please:
how to insert lat-long point dataa into postgres, find distance between 2 points??

I have this column:
 ```
 @Index({ spatial: true })
  @Column({
    type: 'geometry',
    srid: 4326,
    nullable: true,
    spatialFeatureType: 'Point',
    transformer: {
      to: (v: Point) => {
        console.log(v);
        console.log(JSON.stringify(v));
        return eval(
          `ST_GeomFromGeoJSON('{"type":"Point","coordinates":[39.807222,-76.984722]}')`,
        );
      },
      from: (v: any) => {
        return v;
      },
    },
  })
  current_location: string;


```

when I try to insert data:
  "current_location": "{\"type\":\"Point\",\"coordinates\":[39.807222,-76.984722]}",

it says ST_GeomFromGeoJSON is not defined. Please help

**Comment by hussainwali74** [comment]
> Hi, how to use query builder to query this type of column ?

@tomasoak  sir ?

**Comment by PradeepNooney** [comment]
@hussainwali74 
https://stackoverflow.com/questions/67435650/storing-geojson-points-and-finding-points-within-a-given-distance-radius-nodej/67557083#67557083
