### ISSUE TITLE
Please clarify: Is lazy-loading with promises supported or not?

### ISSUE THREAD

**Issue by 720degreeLotus** [typeorm/typeorm#3703]
There are numerous comments by @pleerock in PR pull-requests (some from the end of 2018, https://github.com/typeorm/typeorm/pull/2902#issuecomment-433624122) that tell us, that the whole promise-thing was very experimental and will most likely be abandoned in the future.
I myself have bugs in using the promis-mechanic, but i think i cannot hope for a fix now.

Please clarify if promises are still an official and supported way to go or if we should switch to other mechanics.
The docs should be adjusted then for sure.

Thanks in advance.

**Comment by 720degreeLotus** [comment]
Also, i am not sure if there is any other way to achieve the same goal with TypeORM.
When i do NOT write reference-attribute as `Promise`, then it's triggering eager loading and all referenced entities will be loaded EVERY time i load the "parent" entity.
So when i want to lazy load, i must use `Promise`, is this correct?

**Comment by pleerock** [comment]
Its a hard question to answer because deprecating and abandoning them is just a plan for now. But when this is going to happen if it will isn't clear. Also since there is no elegant api to replace it at the moment I can't recommend you anything. If you need them too much - use it. Once new api will be released you'll be able to migrate over.

**Comment by 720degreeLotus** [comment]
@pleerock really appreciate your time to answer me. From my perspective the usage of promises is fine and logical. It's just that some logical things regarding this mechanism need to be rethought.
Maybe you can help me in answering if there is another way to achieve lazyloading without promises?
I really love TypeORM and i think it has hughe potential. Maybe you should try to get some sponsoring to get monthly money-support for maybe hiring devs fulltime.

**Comment by Kononnable** [comment]
@720degreeLotus 
What exactly do you mean by 'lazyloading'? Answer to your question depends on it.

Unless relation is set as eager it's data won't be fetched from the server - so some might say it's lazyloading enough.

**Comment by 720degreeLotus** [comment]
@Kononnable i meant the lazy-loading using Promises.
At this point in time, Promises in TypeORM are the only way to get lazy-loading (loading values separately and on demand after the first query). And since the way of doing this is not planned to be continued (and it's error-prone as many said), we have no "stable" way of lazyload. This is what i meant :/

**Comment by Kononnable** [comment]
Yes, there are plans to change it a lot, so it's better not to use it for now(unless you're already using it and migrating might get costly).

Question was answered so I guess we can close it.

As for documentation - I think it's marked as experimental, so no need to change anything there. Unless we want to make it more clear for users that it is experimental - in that case propose PR with info about that in place which will be easier to find.

**Comment by MartinFreire** [comment]
Sorry if it's not appropriate, but I have to strongly disagree.
The docs on the page have half a page about Lazy loading with promises and in direct comparison with eager relations. And in the last sentence 

> This is non-standard technique and considered experimental in TypeORM

The docs doesn't give an alternative to something that resembles lazy loading besides query (wich sometimes it's not a useful option)
I invested a couple of weeks of work until I realised this was not a first class citizen. 
So please, if you plan on going forward with removing it, put it on the first line

If I may suggest a way, maybe a class method to load the relation.
```
const model = userRepository.findOne(userId)
const photos = await model.getRelation('Photos');
```
I worked on PHP and know that it doesn't look so nice, but working only with Javascript for more than 3 years this is not a issue at all, furthermore it looks like many other libraries of other types.

I just want to give an opinion, the library is awesome, your work is great, but this point is still a huge problem I'm facing right now and could be avoided if a knew in advance to not rely on relational loading.

Thanks for everything

**Comment by glentakahashi** [comment]
Is there a project/issue tracking the potential rework ideas for lazy-loading like you mentioned @pleerock  or @Kononnable ? Would be interested in helping out with any work there, as lazy loading is extremely convenient when pairing TypeORM with TypeGraphQL

**Comment by didac-wh** [comment]
It may be out of place to say here, but in case someone (just like me) reaches this issue and wants to know a different (cleaner IMO) way to do this, you can use the find() parameter options:

`await MyRepository.find({ myField: myValue, relations: ['Photos'] });`

**Comment by MartinFreire** [comment]
> `await MyRepository.find({ myField: myValue, relations: ['Photos'] });`

That's also a good way to read low related tables, be careful that if you have set { eager: true } in the object, then it will load them even if you haven't set them in the relations array. If you want to avoid this you have to set { loadEagerRelations: false }, next to relations.

The problem I have encountered with this method is that I had a table with 6 or 7 relations and try to query 500 records at a time. It literally kill the app, node got out of memory because of the parsing of the object after the query

If you encounter such an issue, then you should consider restructure to the QueryBuilder API, it's really efficient.

**Comment by didac-wh** [comment]
@MartinFreire I see, thats good information.

Wouldn't it happen too in a normal eager relation fetch? (I mean, the object parse must be done anyway right?). I assume it's one of the downsides of using an ORM and letting it handle the complex fetches.

Also interesting: with lazy relations, I see that using the "relations[]" option won't load sub-relations. Instead, to load the nested relations I have to use, e.g.:
`{ relations: ['Photos', 'Photos.category'] }`

**Comment by MartinFreire** [comment]
@didac-wh 
> Wouldn't it happen too in a normal eager relation fetch? (I mean, the object parse must be done anyway right?).

For what I understand, no. QueryBuilder API builds the query in a different way and it's much more efficient. In my experience, simply changing from one to another solve the problem querying the exact same data.

A plus side from using QueryBuilder, is that you can use select and pass an array of the values you want in the query (even related ones!!)

`.select(['user.name', 'user.age', 'post.status'])`

This for me has been awesome, because even if you have to manually create the query (well, not that manually, but...) you query only what you want, get the same structure, everything as classes, with intellisense and all the goodness of the ORM, a really great experience.

**Comment by mhombach** [comment]
@MartinFreire Hey, i am the initial issue-creator, just switched to another account after all those years (old account is deleted).
I agree to your first comment here.
Using promises for lazy-loading is, in my opinion, still an extremely helpful and easy way but if it's not stable and not supported, it should be much more clear to the dev and also have some plan B for achieving the same goals.
I haven't had time to keep track of TypeORM for the last months, because i mostly used MongoDB and even if there IS support in TypeORM, it seems, that TypeORM is very strong in relational databases but lacks the same strength in non-relational databases like mongoDB.
For mongoDB i am using "mongoose" as ORM, but there i have to create interfaces for the exact same mongoose-definitions. So... double the work and double the error-chance.
It would be really awesome to have something like TypeORM that works for all those database-systems and supports the modern async/await for lazyloading in an stable way :/

**Comment by martinsik** [comment]
I'm using lazy-loading in a typegraphql app and it works great. I think it's pretty straight forward but still I'd appritiate more detailed documentation. For example how to use lazy-loading with `relations` parameter in `find*()`? Does it load relations even when they're marked as lazyloaded? Then when I use eg. `await question.categories` is it making another DB query or the Promise is already resolved from by `find*`?

Another issue I have is how to create new entities wilh relations. What's mentioned in the [docs is very brief](https://github.com/typeorm/typeorm/blob/master/docs/eager-and-lazy-relations.md#lazy-relations) and doesn't help much. For example:
```
const category1 = new Category();
category1.name = "animals";
// `user` is lazy loaded field `user: Promise<User>`
category1.user = connection.getRepository(User).findOne(userId);
await connection.manager.save(category1);
```

Lazy loaded field has to be typed as `Promise<T>` so I have to assign `user` to a Promise even when I don't need to fetch the user from DB only for that when I have `userId`. So is there any other easier way to do that without making another DB query.

**Comment by mattcoker** [comment]
Dropping this here since its working well for me at the moment as a stop-gap, and hope this can save other people some time.
I took a cue from #7485 and implemented a static method for loading relations. I'm definitely open to suggestions of ways to improve this. I literally just implemented it, so I haven't actually used anything other than the "one-to-many" relationship with this. I would recommend extending the BaseEntity with this method and then extending all relevant entities off of that CustomBaseEntity.

Used like so:
```js
const books = await Author.loadRelation(currentAuthor, "books");
return books;
```

```js
export class Author extends BaseEntity {
  // define all your fields

  @OneToMany(() => Book, (book) => book.author, { eager: false, lazy: false })
  books: Book[];

  static async loadRelation(parentModel, relationName: string) {
    const { name: modelName } = this;
    const { relations } = getConnection().getMetadata(modelName);

    const relationData = relations.find((o) => o.propertyName === relationName);
    if (!relationData)
      throw new Error(
        `Relation "${relationName}" could not be found on ${modelName}.`,
      );

    const { relationType } = relationData;

    const qb = getManager()
      .createQueryBuilder()
      .relation(this, relationName)
      .of(parentModel);

    if (["one-to-one", "many-to-one"].includes(relationType))
      return qb.loadOne();

    if (["one-to-many", "many-to-many"].includes(relationType))
      return qb.loadMany();

    throw new Error(
      `Error on relation "${relationName}" of entity "${modelName}": Unknown relation type "${relationType}`,
    );
  }
}
```

**Comment by iksaku** [comment]
@mattcoker Thanks for your comment!

I went and tried to further improve your code, but based on my use case.

In my case, I'm more biased towards Laravel's Eloquent conventions, and looked for a way for relationships to be loaded on demand.

In this case, nested relationship loading is not supported (yet), but may be worth for somebody else to look at it further down the line.

In the mean time, I wanted to have a class-bound `load` method, which takes the current class as the parent model and connects the dots with the requested relationships.

Here's my implementation:

```ts
class Model extends BaseEntity {
  async load(relations: string|string[]): Promise<this> {
    const model = this.constructor.name
    const connection = getConnection()
    const { relations: availableRelations } = connection.getMetadata(model)

    if (! Array.isArray(relations)) {
      relations = [relations]
    }

    for (const relation of relations) {
      const relationData = availableRelations.find((o: RelationMetadata) => o.propertyName === relation)

      if (! relationData) {
        throw new Error(`Relationship '${relation}' could not be found on relation '${model}'.`)
      }

      const { relationType } = relationData

      const queryBuilder = connection.manager
        .createQueryBuilder()
        .relation(model, relation)
        .of(this)

      if (['one-to-one', 'many-to-one'].includes(relationType)) {
        this[relation] = await queryBuilder.loadOne()
        continue
      }

      if (['one-to-many', 'many-to-many'].includes(relationType)) {
        this[relation] = await queryBuilder.loadMany()
        continue;
      }

      throw new Error(`Unknown relationship type '${relationType}' on '${model}.${relation}'.`)
    }

    return this
  }
}
```

And it could be used like:
```ts
const author = Author.findOne(...)
console.log(author.books) // undefined
await author.load('books')
console.log(author.books) // Array [ ... ]
```

Hope somebody finds this useful 🙌

**Comment by mellster2012** [comment]
We're using lazy loading as well, and aside from the quirks wrt persisting (values aren't saved to the DB) it's working well. One way to work-around (which we have implemented) this limitation for now and fully support promises on persist/update is to overwrite the save/update/upsert/create methods using en extended base entity or mixin, and loop through the lazy relations and promisify all the raw values (if not Promise already) after create/merge and before the final save for save/update, or after preload for preload. This logic could be easily embedded into typeorm to automate auto-boxing of values into promises on persist, or to allow a dual type on the lazy properties/relations, the raw value for persisting, and the promisified value for reading. TLDR I don't think this feature needs to be scrapped or fully rewritten/redesigned, a few tweaks should do it. Thanks!
