### ISSUE TITLE
Non-null column default should default value even if incoming value is "null"

### ISSUE THREAD

**Issue by IRCraziestTaxi** [typeorm/typeorm#3738]
**Issue type:**

[ ] question
[ X ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ X ] `postgres`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ X ] `0.2.13` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an entity with a column `updated` which defaults to the current UTC timestamp.

```ts
@Entity()
export class MyEntity {
    @Column({ nullable: false, default: () => "timezone('utc', now())" })
    public updated: Date;
}
```

I have always been explicit in setting values in my client applications; that is, I always set to `null` explicitly if an incoming value does not exist. For instance:

```ts
export class MyEntityDTO {
    public updated: Date;

    public constructor(myEntity?: MyEntityDTO) {
        this.updated = myEntity
            && myEntity.updated
            && new Date(myEntity.updated)
            || null;
    }
}
```

Personal preference, I suppose. I feel like the explicit value of `null` is preferable to the awkward nonexistence of `undefined`.

The issue came in when I try to create that entity on the back end. I get an error saying (sorry, cannot remember the exact wording) that the value `null` cannot be used for the non-null column `updated`.

Doing this in the client app fixed it:

```ts
export class MyEntityDTO {
    public updated: Date;

    public constructor(myEntity?: MyEntityDTO) {
        // TypeORM cannot handle a value of null, so do not explicitly set to null if it does not exist.
        if (myEntity && myEntity.updated) {
            this.updated = new Date(myEntity.updated);
        }
    }
}
```

Then, when the DTO is sent to the back end for creation by the repository, it works.

However, it took me a while to chase that down and that is just awkward to me. If the ORM knows that the value should not be null and has a default value, why not convert `null` to that default value instead of only explicitly `undefined`?

**Comment by johannesschobel** [comment]
Hey there..

this may **not** be a general solution for the issue, however, when it comes to the `updated` field, you can also use the `@UpdateDateColumn()` decorator (see https://typeorm.io/#/decorator-reference/updatedatecolumn ), which does everything automatically for you ;)

So your entity would look like this:
```ts
@Entity()
export class MyEntity {
    // ... a lot of attributes here
    @UpdateDateColumn() // nothing more needed
    public updated: Date;
}
```

Nice, isn't it? :+1: Note that there is also a `@CreateDateColumn()`.. 

-----

regarding the general nature of the issue you are describing..
You explicitly defined the value as `NOT NULL` - so you are telling the database that you **do not allow `null` values** and still you are setting a `null` value here.. Of course, this is an error - typeorm handles this correctly..

You are then suggesting, that - if the column is defined as `not null` but still `null` is passed, it should be converted to the `default` value.. Which is **not** an expected behaviour, i think.. This would create so many questions on the developer side, i think - and would consider this as a bad practice, for the following reasons:
* in SQL `null` is a specific type; SQL treats `undefined` and `null` differently. For `undefined / not set`, the `default` value is inserted..
* your described behaviour is completely against the SQL standard
* what happens, if there is no `default` value defined?
* why?!

All the best

**Comment by IRCraziestTaxi** [comment]
@johannesschobel Good point. I was thinking of this from an ORM (code) standpoint, not a SQL standpoint. I will close the issue and just be more careful from now on, I suppose.

Also thanks for pointing out the `@UpdateDateColumn()` and `@CreateDateColumn()` decorators - those will really come in handy rather than having to hardcode the default value based on my database type.

**Comment by johannesschobel** [comment]
Dear @IRCraziestTaxi ,
glad i could help you with this issue / problem.

The main objective of the ORM is to abstract from technical specifications of the underlying storage engine - whether it is a relational database, a single text-file or whatever.. Your suggestion, would, at least in my opinion, work against the SQL standard. Further, SQL already provides sophisticated mechanisms to achieve the latter.

For your specific problem.. You could also try using the `@beforeInsert()` and `@beforeUpdate()` methods (or decorators - depending on your programming style!) to convert `null` values..

All the best
