### ISSUE TITLE
QueryBuilder Oracle skip sql doesn't work for old versions

### ISSUE THREAD

**Issue by Thihup** [typeorm/typeorm#3926]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The current LIMIT and OFFSET for Oracle only works in Oracle >= 12.1, but old versions doesn't support the syntax.

Commit that removed support: 
https://github.com/typeorm/typeorm/commit/af71371562967d068988ac40b9c5bf41c2ccdae2

https://stackoverflow.com/questions/470542/how-do-i-limit-the-number-of-rows-returned-by-an-oracle-query-after-ordering

**Comment by vlapo** [comment]
Adding @AlexMesser as author of commit.

**Comment by AlexMesser** [comment]
Hi @Thihup. TypeORM does not support Oracle versions below 12.1. This is because since 12.1 Oracle introduced at least 2 important features: limit-offset functionality and `IDENTITY` columns. Implementation of this functionality in TypeORM without using these features would be very difficult or even impossible
