### ISSUE TITLE
Massive RAM consumption (NodeJS, Docker)

### ISSUE THREAD

**Issue by murbanowicz** [typeorm/typeorm#3927]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi,
I am using TypeORM with NestJS.
Just turning it on with just one entity adds 70-80mb to the memory consumption which is massive. Any other NestJS module use that much. With e.g. mongoose or Typegoose it is just 2-3mb of RAM.
Any idea why and how to solve it?

**Comment by Kononnable** [comment]
Can you provide simple reproduction repo? Even potentially small change can introduce big difference in RAM utilization. That's why it would be much easier to investigate it on actual example.
Also usage of ts-node is very important - for simple project with ts-node it took 100.59 MB RAM, while only 25.12 MB with precompiled js files.
