### ISSUE TITLE
How to set custom variables in typeorm ?

### ISSUE THREAD

**Issue by SunshowerC** [typeorm/typeorm#3970]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[x] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

How to achieve the following sql by typeorm?
```sql
SELECT  @a:=@a+1 serial_number, 
        marks 
FROM    student_marks,
        (SELECT @a:= 0) AS a;
```
OR
```sql
SET @count:=0;
SELECT  (@count:=@count+1) AS serial_number, 
        marks 
FROM    student_marks
```

Yes, I just want to know how to set custom variable. 
Or I just need to execute raw sql by `manager.query()` ?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
I think you can only achieve it by using raw query. You also have to remember about variables lifetime - you can use it only in the same batch.

**Comment by imnotjames** [comment]
Hope this answered, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
