### ISSUE TITLE
typeorm schema:sync does not exit

### ISSUE THREAD

**Issue by hannupekka** [typeorm/typeorm#3985]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.2.13`

**Steps to reproduce or a small repository showing the problem:**
* Run `npx typeorm schema:sync` on terminal
* Get output `Schema syncronization finished successfully.` but the process does not exit

On local machine I can always `CTRL+C` to stop it but this does not work for example in Heroku. No changes has been made to code that should cause this - in fact previous commits from our project that did work do not work anymore.

Same behaviour also with `npx typeorm schema:log` and `npx typeorm schema:drop`

Any idea what could cause something like this?

**Comment by Kononnable** [comment]
Try updating postgress driver to latest one. I think there were some problems there with connections not always closing as expected.
If upgrading doesn't help try npm module like `why-is-node-running`. I'm unable to reproduce issue myself, but that module should be able to show what is keeping node alive.
`npx why-is-node-running ./node_modules/.bin/typeorm schema:log` and if it hangs kill it with provided command(instead of ctrl+c).

**Comment by hannupekka** [comment]
Thanks! `why-is-node-running` pointed be to a right direction.
