### ISSUE TITLE
Is there a road map for this project?

### ISSUE THREAD

**Issue by vidhu** [typeorm/typeorm#3992]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

I've come accross 
https://github.com/typeorm/typeorm/milestones
https://github.com/typeorm/typeorm/blob/master/docs/roadmap.md

But they haven't been updated in a year. Just wondering if this is tracked someplace else

**Comment by pleerock** [comment]
No, due to lack of resources at the moment we freeze new feature development and only maintaining current issues and pull requests.

**Comment by Kononnable** [comment]
There is more 'internal' list of things we consider to change/implement in version 0.4.0. But there are no final decisions (since we didn't publish 0.3.0 yet).

**Comment by jshearer** [comment]
> No, due to lack of resources at the moment we freeze new feature development and only maintaining current issues and pull requests.

What does that mean for the future of TypeORM? Should I be concerned about the project shutting down?

**Comment by Kononnable** [comment]
I think  we're safe. It's very unlikely that TypeORM will be shutting down soon. However currently no one is developing typeorm full-time and maintaining project of such size takes a lot of time(fixing issues, answering questions, reviewing and merging features implemented by the community).
That's why 'core-developers' currently don't have the time to implement new features, and we cannot make any roadmap on what will be implemented soon(we don't know what will be in the next PR from the community).

Related issue which might shed some light on the future https://github.com/typeorm/typeorm/issues/3267#issuecomment-489450860

Original question was answered so we can close this issue, but if you've got related questions please do ask(here, in related issue or on slack channel).
