### ISSUE TITLE
Can't insert into postgres "schema"."table"

### ISSUE THREAD

**Issue by stlasalle** [typeorm/typeorm#4039]
**Issue type:**
[x] bug report

**Database system/driver:**
[x] `postgres`

**TypeORM version:**

[x] `latest`

**Steps to reproduce or a small repository showing the problem:**
I am using typeorm on a lambda to write to a postgres database. I have an entity called Click, with the following decorator:
`@Entity('click')`

Writes using this lambda work, and can be seen in the logs with an 'InsertResult' console log (I have set `logging: 'all'`)

Now I would instead like to write to a 'click' table in a schema called 'prod', both of which already exist. I've changed the entity decorator to:
`@Entity({ name: 'click', schema: 'prod' })`

This lambda now times out at 30s (the default lambda runtime), after doing no inserts but a series of 'SELECT's from the information schema about 5 times. I believe the lambda is running multiple times due to the timeout. I have attached the log files:
[lambda-log.txt](https://github.com/typeorm/typeorm/files/3110213/lambda-log.txt)

Could someone please explain what's going on? Is there another way that I can write to "schema"."table" using typeORM?

Thanks

**Comment by stlasalle** [comment]
After increasing the timeout of the lambda to 10 minutes to test this, the logs are stopping at the following SQL query:
`SELECT "con"."conname" AS "constraint_name", "con"."nspname" AS "table_schema", "con"."relname" AS "table_name", "att2"."attname" AS "column_name", "ns"."nspname" AS "referenced_table_schema", "cl"."relname" AS "referenced_table_name", "att"."attname" AS "referenced_column_name", "con"."confdeltype" AS "on_delete", "con"."confupdtype" AS "on_update" FROM ( SELECT UNNEST ("con1"."conkey") AS "parent", UNNEST ("con1"."confkey") AS "child", "con1"."confrelid", "con1"."conrelid", "con1"."conname", "con1"."contype", "ns"."nspname", "cl"."relname", CASE "con1"."confdeltype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confdeltype", CASE "con1"."confupdtype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confupdtype" FROM "pg_class" "cl" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_constraint" "con1" ON "con1"."conrelid" = "cl"."oid" WHERE "con1"."contype" = 'f' AND (("ns"."nspname" = 'linktree_prod' AND "cl"."relname" = 'linktree_click')) ) "con" INNER JOIN "pg_attribute" "att" ON "att"."attrelid" = "con"."confrelid" AND "att"."attnum" = "con"."child" INNER JOIN "pg_class" "cl" ON "cl"."oid" = "con"."confrelid" INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid" INNER JOIN "pg_attribute" "att2" ON "att2"."attrelid" = "con"."conrelid" AND "att2"."attnum" = "con"."parent"`

(note - these queries don't seem to run when I just use a 'table' decorator, only when the schema is there as well. And they run at the start of the lambda invocation, before I have reached the createQueryBuilder code).

When I enter that SQL statement into the database directly, using a GUI such as Postico, I get '0 rows'. Perhaps TypeORM is waiting for some sort of rows but not getting any, which is leading to it hanging until the lambda times out?

**Comment by Kononnable** [comment]
Can you reproduce the issue with another environment?
This query is one of many run during loading database model from db. Unfortunately it isn't enough to say what is not working as expected.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
