### ISSUE TITLE
Inject custom repository

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#404]
Hello!

Is it possible to automatically inject custom repository?

I have the following controller in my application:

```ts
@Service()
export class UsersController implements Controller {

  private userRepository: UserRepository;

  constructor (private database: Connection) {
    this.userRepository = database.getCustomRepository(UserRepository);
  }
}
```

Right now, I have to manually call `database.getCustomRepository(UserRepository)`, is it possible to configure Container/ORM to inject it automatically?

**Comment by pleerock** [comment]
Hi,
there is a way to do this, however don't do it this way. 

First I thought it would be great if repositories will be services, however there are few problems. First, it wont work with multiple connections since it don't know to which connection custom repository should belong. Second and the most important they wont work in transactions. In transactions you should use special provided instance of entityManager, and all your db operations should be executed via that entityManager. But if you will use global repository service it won't know about transactional entity manager and wont work in transactions properly.

**Comment by slavafomin** [comment]
@pleerock Thank you for an explanation. It means that I shouldn't inject the connection either? Do I have to manually pass the connection retrieved in controller to the service layer and all services interested in making queries?

**Comment by pleerock** [comment]
do you use `typeorm-typedi-extensions`? You can use `@OrmConnection` decorator to inject connection object. Or you can use `@OrmEntityManager` or `@OrmRepository` to inject entity manager or repository but this won't work inside transactions. Without those decorators you could simply do `getConnection()`, but handle injection on your own

**Comment by slavafomin** [comment]
@pleerock Thanks, `typeorm-typedi-extensions` looks like a very useful module!

Please, confirm if I understood correctly. I can use injection to inject any of this services (connection, entity-manager, repository) to my services, but in order to use transactions I will need to manually pass a repository instance returned by `Repository.transaction()` call to all services participating in my transaction? 

Are you using unit of work pattern or something similar to track changes and prevent data duplication in the entities tree? If I want to apply all changes to the entities tree in one go, do I have to create transaction manually (and pass it to all services manually)?

**Comment by pleerock** [comment]
No there is no direct "unit of work" however there is something very similar. And there is no identity map, so each entity you are loading is different instances so be aware of it (there are pros and cons of both approaches).

To do simple transaction you can do following:

```ts
@JsonController()
export class UserController {

   @Transaction()
   @Post("/users")
    save(@TransactionEntityManager() entityManager: EntityManager, @EntityFromBody() user: User) {
          return entityManager.persist(user);
    }

}
```

This sample is build by using typedi, typeorm, routing-controllers and all typeorm extensions. This is the way transactions be created at this moment. And yes, if you need to do some database stuff in your services you should pass given entity manager to those services and execute your operations using that entity manager. There are technical reasons for this behaviour.

**Comment by slavafomin** [comment]
@pleerock thank you for explanation. I can see the technical limitations, but such approach makes working with transactions extremely unwieldy and I believe that probably everything in a single request should be done in a single transaction to prevent half-completed processes due to unexpected errors. In Doctrine it's handled almost automatically: you just need to change your entities tree and call `$entityManager->flush()` to apply all changes to the database in a single implicit transaction.

To achieve the same functionality I will have to start transaction in each controller action and to pass transaction's entity manager along every call to my service layer. I'm I correct? Do you see any alternatives to such cumbersome approach?

**Comment by pleerock** [comment]
Yes you are correct. In php its different because each script runs on each request and everything you have in that script runs once and cleaned up. So every service is created per request and cleaned up after execution. Here in node we have a single running process and services are always in memory. Thats why its impossible to make "global transaction", because it will affect all user requests. I don't think its possible to do something better here, its already quite good approach. Just treat it as a pattern.

**Comment by slavafomin** [comment]
Yes, I understand, but, making every service method to accept entity manager as argument is not quite good approach in my opinion.

What about [CLS](https://github.com/othiym23/node-continuation-local-storage) approach? Sequelize actually uses it for transactions.

**Comment by pleerock** [comment]
I understand why you don't want to pass entity manager around. Fortunately this inconvenience is only for save/remove operation. I would like to get known more on how you see CLS should work with typescript, typeorm and dependency inject. Can you start with proposal?

**Comment by slavafomin** [comment]
I'm afraid I just have not enough time to work on this at the moment.

**Comment by 19majkel94** [comment]
Link to V4 docs when the API is described:
http://docs.sequelizejs.com/manual/tutorial/transactions.html

The CLS-based API looks promising and it shouldn't be too hard to implement it. It still needs the transaction callback (or `@Transcation` method decorator) but the benefits would be that we can use normal, "global" API like `connection.getRepository()` which would look for connection/entitymanager from CLS which `.transaction()` would replace with the value. So all TypeDI decorators that rely on this functions would be able to work with no problem. However, from the other sides it doesn't solve too much problems as we still need to inject repository/EM per route action, not once in constructor. So I'm not sure about this.

**Comment by kuloed** [comment]
@pleerock ```There are technical reasons for this behaviour.```
Can you explain to me what the reason is? I still don't understand why we cannot inject our custom repository in constructor.
I'm kind of new in node js environment, but i know how doctrine works (i'm coming from php world).
thank you for your great work.

**Comment by pleerock** [comment]
Actually you can, but be careful with this practice because it can confuse you and your team when working with transactions.

**Comment by kuloed** [comment]
Thank your for your reply.
Can you tell me why this will confuse us when working with transactions? Or can you direct me to some reference for this behaviour?

**Comment by pleerock** [comment]
This code tries to explain the problem:

```ts
await connection.transaction(async manager => {
    // in transactions you MUST use manager instance provided by a transaction,
    // you cannot use global managers, repositories or custom repositories
    // because this manager is exclusive and transactional
    // and if let's say we would do custom repository as a service
    // it has a "manager" property which should be unique instance of EntityManager
    // but there is no global EntityManager instance and cannot be
    // thats why custom managers are specific to each EntityManager and cannot be services.
    // this also opens opportunity to use custom repositories in transactions without any issues:

    const userRepository = manager.getCustomRepository(UserRepository); // DONT USE GLOBAL getCustomRepository here!
    await userRepository.createAndSave("Timber", "Saw");
    const timber = await userRepository.findByName("Timber", "Saw");
});
```

Now, when you make your custom repository global service, you cannot use it via `manager.getCustomRepository` function because if its global it'll use its own entity manager. But in transactions you MUST use entity manager provided by a transaction and only that.

**Comment by kuloed** [comment]
ahh, thank you for your kind explanation. 
i get it now, so it's because the nature way of "node js" right.

**Comment by michaelwayman** [comment]
I agree with @slavafomin that transaction CLI support should be added.
For my project we have multiple layers for our database and without doing a major rewrite we cannot switch away from Sequelize because of typeorm transaction issues.

What would be ideal is when you 
```
import {getManager} from "typeorm";

async function doThingInTransaction() {
    await connection.transaction(async manager => {
        // do stuff with manager
        await callFunction1();
    });
}

async function callFunction1() {
    // entityManager uses the transaction from doThingInTransaction
    const entityManager = getManager();
    // do stuff with entity manager
    await callFunction4();
}

async function callFunction4() {
    // entityManager uses the transaction from doThingInTransaction
    const entityManager = getManager();
    // do stuff with entityManager
}
```

All this should be pretty easily achieved using CLI the same way sequelize does.
Like I said, I have a lot of layers to my database functionality, but I have the highest exposed layer wrapped in a `@transaction` decorator that puts the transaction into the CLS namespace. Then all the calls from my decorated function, and all of those sub-call's subsequent calls, will all share and use the same transaction, all easily achieved with CLI.

**Comment by slavafomin** [comment]
After working some time with transaction management in Node.js, I'm not sure anymore that implicit transaction access is a good thing. Transaction management is hard already, adding more magic to it could make it even harder, especially, when you need to debug some issue.

**Comment by pleerock** [comment]
Yeah I have same thoughts

**Comment by pdeszynski** [comment]
@pleerock is it taken into consideration to use mechanisms like`CLS` in typeorm for transactions? As said here - yes it adds some magic/complexity but also it greatly simplifies for people using Java's Hibernate / PHP's doctrine or moving from Sequelize.

When dividing code into layers of application/domain/infrastructure and hiding implementation details (like Typeorm) it makes somewhat harder to implement it. For e.g. in application services instead of injecting repositories directly I have to define repository factory and then inject it like:

```typescript
// using inversify.js
bind<interfaces.Factory<ISomeCustomRepository>>(repositories.SomeCustomRepositoryFactory)
    .toFactory<ISomeCustomRepository>(
      (context: interfaces.Context) =>
        (transactionManager?: EntityManager) => !transactionManager
          ? getCustomRepository(SomeCustomRepositoryTypeORM)
          : transactionManager.getCustomRepository(SomeCustomRepositoryTypeORM),
```

```typescript
import IRepositoryFactory from './domain/..';
import ISomeCustomRepository from './domain/..';

@injectable()
export default class MyCustomService {

  private myCustomRepositoryFactory: IRepositoryFactory<ISomeCustomRepository>;

  public constructor(
    @inject(repositories.SomeCustomRepositoryFactory)
    myCustomRepositoryFactory: IRepositoryFactory<ISomeCustomRepository>,
  ) {
    this.myCustomRepositoryFactory = myCustomRepositoryFactory;
  }

  @Transaction()
  public add(
            @TransactionManager() manager: EntityManager,
            otherParam: any
            ) {
    const myCustomTransactionalRepository =  this.myCustomRepositoryFactory(manager);
    //...
    const myModel.dispatchEvents();
    myCustomTransactionalRepository.save(myModel);
  }
}
```

Whether I think that solution is acceptable, then I do not have an idea how to access a transaction manager outside of a method if I would like to implement domain events. For example I would like to have a `changeEmail` method on a model and if called send an email on infrastructure's level to user that email was changed by listening to a domain event (but if I'm not successful with email being sent I would like to rollback and show user an error). Is it possible right now, or how would you approach it using Typeorm?

**Comment by nicomouss** [comment]
@pdeszynski have look at #1895 
That would definitely simplify your code
