### ISSUE TITLE
Caching by foreign keys 

### ISSUE THREAD

**Issue by mishelen** [typeorm/typeorm#4045]
**Issue type:**

- [x] question
- [ ] bug report
- [ ] feature request
- [ ] documentation issue

**TypeORM version:**

- [x] `latest`
- [ ] `@next`
- [ ] `0.x.x` (or put your version here)

**QUestion:**

Imagine we have a model of 20 columns which are foreign keys. They lead to simple tables, each of which has 10 rows on average. These simple tables will not be updated frequently. Maybe once a week, maybe once a year. Those. I would like to use `eager` option somehow and cache their contents at the same time.

As I understand it, none of the options with typeorm provided caching is not suitable?

Thanks

**Comment by mishelen** [comment]
I have 2 ideas:
create `customRepository` where to redefine findById with handmade in-memory cache implementation

But not sure that `eager` assumes that under hood will be called `findById`

Transform this tables to `BaseEntity` where redifine `findById`. Probably it's the almost same as previous, but not sure.

**Comment by Kononnable** [comment]
There is cache support in Typeorm, but you probably should think if you really want to use this data as entities all the time. By the way you described your problem it might be more useful to get that data in your application logic, transform it the way which it will be easier to use them and treat them as standard JS objects.

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
