### ISSUE TITLE
ReferenceError on migration:generate

### ISSUE THREAD

**Issue by Knaackee** [typeorm/typeorm#4052]
Putting the following inside a single file throws

```
Error during migration generation:
ReferenceError: Person is not defined
```
on migration:generate

```
import {
  Column,
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn
} from "typeorm";

@Entity()
export class Car {
  @PrimaryGeneratedColumn()
  id?: number;

  @ManyToOne(() => Person, Person => Person.cars)
  owner?: Person;
}

@Entity()
export class Person {
  @PrimaryGeneratedColumn()
  id?: number;

  @Column({ type: "varchar" })
  name?: string;

  @OneToMany(() => Car, Car => Car.owner)
  cars?: Array<Car>;
}

```

If I change the order of the classes the error disappears. 
Why does this matter? Typescript can compile it without a problem.

**Comment by d0p3t** [comment]
I'm experiencing the same issue.

This prevents me from defining entities that have relationships in different files. The order of defining entities in the connection options does not matter.

I'm using `postgres`.

**Comment by Kononnable** [comment]
Unfortunately this is an issue we can't really do much about. Typescript compiles such code, but then when we try to run it we will have a ReferenceError. 
This happens because of how `emitDecoratorMetadata` option works. It requires a type(a variable with class) but in this case it isn't defined yet(in case of newer ES versions). If you change `target` to ES3 it will run correctly(compiled code uses var instead of let and there is a hoisting).

**Comment by MatteoGioioso** [comment]
Same error by changing the target to ES3
