### ISSUE TITLE
Naming Strategy Issue

### ISSUE THREAD

**Issue by Tochemey** [typeorm/typeorm#4093]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Casing in embedded entity columns is not respected. It seems that typeorm only use its naming convention meanwhile the `column` decorator has made room to specify column name. I wish those column names be respected with their cases.

This issue has been here and it seems that it is not too important to address. Kindly address it because some of us made the choice to use typeorm and are bound by naming conventions by our organisations. 

References: 

- [Issue 4047](https://github.com/typeorm/typeorm/issues/4047)

- [Issue 2599](https://github.com/typeorm/typeorm/issues/2599)

**Comment by kferrone** [comment]
You can control the naming, simply disable the prefixing of the embedded entity like so:

```ts
@Column(
        () => EmbeddedEntity,
        {
            prefix: false
        }
)
public thing: EmbeddedEntity; 
```

```ts
export default class EmbeddedEntity  {
    @Column({
        name: 'embedded_foo'
    })
    public foo: string;
}
```

Then specify name of each column in the embedded entity.

**Comment by Tochemey** [comment]
Thank you so much. It works

**Comment by alminde** [comment]
I wish this was in [the docs](https://github.com/typeorm/typeorm/blob/master/docs/embedded-entities.md).

**Comment by piotrgomola** [comment]
Unfortunately, @kferrone solution does not work in cases when we want to save the prefix and the original cases in  EmbeddedEntity. So in case I have an EmbeddedEntity like below:
```
export default class EmbeddedEntity  {
    @Column()
    public exampleColumn: string;
}
```

and an entity that reuse it for some reason twice (or more):
```
@Column(() => EmbeddedEntity)
public foo: EmbeddedEntity; 

@Column(() => EmbeddedEntity)
public bar: EmbeddedEntity; 
```

the intuition (and the documentation) says that I should receive columns like `fooExampleColumn` and `barExampleColumn`. But instead I'm receiving `fooExamplecolumn` and `barExamplecolumn`.

**Comment by venzersiz** [comment]
@piotrgomola Hi, I just realized that there is the same problem you said. Did you find a solution? I looked into codes in DefaultNamingStrategy's columnName method, but I can't find related codes.

**Comment by lucaswxp** [comment]
Any workarounds? It's weird typeorm doesn't follow the same naming conventions for embedded columns: It just capitalize the first letter and lower cases the rest, why?

**Comment by MunyuShizumi** [comment]
_Disclaimer: Don't treat this as production-ready code, this is just a 5-minute ad hoc fix that works for me currently, I'll probably look into custom naming strategies in more detail later._

As stated already, the above solution is only partial, i.e. it works only if you want to entirely disable prefixing. However, you can always write your own naming strategy to construct DB column names however you prefer. Ex. in my case I had something along the lines of:
```ts
class EmbedExample {
  @Column({ type: 'text' })
  barBaz: string;
}

@Entity()
export class EntityExample {
  @Column(() => EmbedExample)
  foo: EmbedExample;
}
```

The default naming strategy will produce `fooBarbaz` instead of `fooBarBaz`. You can override this specific behavior by extending `DefaultNamingStrategy` and overriding the `columnName` method:
```ts
import { DefaultNamingStrategy, NamingStrategyInterface } from 'typeorm';

export class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {
  columnName(propertyName: string, customName: string, embeddedPrefixes: string[]): string {
    return embeddedPrefixes
      .concat(propertyName)
      .map((s, i) => i > 0 ? s.replace(/^(.)/, c => c.toUpperCase()) : s)
      .join('');
  }
}
```

This will capitalize the first letter of each property (except the first one) and leave everything else untouched. Implement by adding `namingStrategy: new CustomNamingStrategy()` to your connection options (as described [here](https://typeorm.io/#/connection) or [here if you use ormconfig](https://typeorm.io/#/using-ormconfig/overriding-options-defined-in-ormconfig)).

[This project](https://github.com/tonivj5/typeorm-naming-strategies/blob/master/src/snake-naming.strategy.ts) might be a useful quick reference for other methods (documentation doesn't seem to cover this and states it may be subject to change?).
