### ISSUE TITLE
ManyToMany relation table extra column information

### ISSUE THREAD

**Issue by nevodavid** [typeorm/typeorm#410]
lets say I have user table, event table, and a relation table like so
users:
id | name

events:
id | name

users_events: 
user | event | status

is there any way to get the "status" from the users_events table(in the annotation).
thank you :)

**Comment by pleerock** [comment]
no such functionality won't be possible. Simply create `UserEvent` entity add status column there and setup proper relations between it, user and event.

**Comment by gmurayama** [comment]
@pleerock if the entity UserEvent is created, a primary key is required, otherwise TypeORM would throw an error. But a ManyToMany relation requires only the foreign key from both tables (in this case, the users and events). How could I achieve an entity without a primary key, only with foreign?

Thanks in advance!

**Comment by pleerock** [comment]
You can make a foreign key as a primary key as well, for example: `@ManyToOne(type => User, { primary: true }) user: User`

**Comment by gmurayama** [comment]
Worked just fine! Thanks!
