### ISSUE TITLE
ArangoDB Support

### ISSUE THREAD

**Issue by iyobo** [typeorm/typeorm#4117]
I see mongodb is supported in TypeORM.
I would like to suggest the support of an ArangoDB adapter on here as well.
https://www.arangodb.com/

I also would not mind submitting a PR if I can somehow get some pointers as to the overall architecture of TypeORM and how to go about creating an adapter.

**Comment by RienNeVaPlus** [comment]
I'm interested in support for ArangoDB as well. However I'm not really sure whether typeorm can make use of ArangoDBs Foxx services, because their environment has some limitations when it comes to promises / asynchronous functions. Using arangojs is possible, but IMHO less interessting because of the overhead in comparison to "implementing the logic directly into the database". 

Please tell me I'm wrong, I'd very much appreciate a ArangoDB driver for typeorm and I'm pretty sure my employer would be able to become a sponsor of typeorm.

**Comment by iyobo** [comment]
@RienNeVaPlus Might I suggest then that your company put out a bounty for it?
ArangoDB is new and still doesn't seem to have the kind of ppularity to trigger strong community interest. But cold hard cash will generate interest for sure.

**Comment by RienNeVaPlus** [comment]
@iyobo I cannot put out a bounty until the concerns of my previous comment are sorted out. But as I said, in case I was wrong and typeorm can be implemented into a Foxx service, my employer has suggested to become a [sponsor](https://opencollective.com/typeorm), otherwise typeorm might not be the right choice for ArangoDB.

Another reason for the above is type-arango. Right now our ressources are being invested into our [own solution](https://github.com/RienNeVaPlus/type-arango) - but don't get your hopes up, it's far from being even compareable to typeorm, although it sits directly inside a foxx service. Of course everyone is very much welcome to contribute.

**Comment by pleerock** [comment]
Right now we do not plan to integrate new database drivers, so I wouldn't expect it in a near future. If your company wants to support development, please contact me directly.

**Comment by OKNoah** [comment]
@RienNeVaPlus @pleerock I did some [Arango ORM](https://github.com/OKNoah/final/tree/master/packages/arangolize) work as well as [Type ORM](https://github.com/mojodna/typeorm/pull/1) stuff. I doubt it's of much use. Hope winds change and ArangoDB can enter the family. :)

**Comment by iyobo** [comment]
@RienNeVaPlus could you speak more on the issues you said Foxx environment has? Or link to more information.

**Comment by RienNeVaPlus** [comment]
@iyobo ArangoDB can be accessed in different ways:
- [ArangoJS](https://github.com/arangodb/arangojs) is a driver for accessing a the database from JavaScript anywhere outside of the database. This should work with GraphQL as well. But there are also:
- [ArangoDB Foxx Microservices](https://www.arangodb.com/docs/stable/foxx.html) - these run directly inside the database and thus are not only faster in most scenarios but come with additional features:

> ArangoDB allows application developers to write their data access and domain logic as microservices running directly within the database with native access to in-memory data. The Foxx microservice framework makes it easy to extend ArangoDB’s own REST API with custom HTTP endpoints using modern JavaScript running on the same V8 engine you know from Node.js and the Google Chrome web browser.

_They are a blessing I wouldn't want to miss._  However:
> Unlike JavaScript in browsers or Node.js, the JavaScript environment in ArangoDB is synchronous. This means any code that depends on asynchronous behavior like promises or setTimeout will not behave correctly in ArangoDB or Foxx.

That being said, developing a GraphQL driver is possible using ArangoJS, but it would not be able to take advantage of ArangoDBs full potential, because GraphQL depends on promises which are technically not needed in a Microservice.

**Comment by cardimajs** [comment]
Will be awesome to have support to ArangoDB

**Comment by jamangile** [comment]
Hi @iyobo and @RienNeVaPlus , 

I'm also interested in getting support for ArangoDB. 
Happy to contribute to the PR for the feature. 

I read along your thread and here are my thoughts on the topic:

I think there are conflicting objectives for the two technologies (ArangoDB Foxx services and TypeORM).
* Foxx services is really a technology to extend functionality within the ArangoDB V8 virtual environment.
* TypeORM is meant to be agnostic to database technology and runs it's own "virtual database"

Unfortunately, this means that one is going to run inside the`db` V8 environment, which should not be mistaken for the `nodejs` V8 environment. This is where I think your requirements conflict. 

@RienNeVaPlus, I think your are looking for is an extension to this deprecated 😞 [lib](https://github.com/arangodb/aqbjs). It broke my heart to this not moving forward anymore.

@iyobo, do you have an active pull request against this? I'd like to contribute. Otherwise I'll pop in against and share my pull request so that there is one open traceable branch against this.

Please let me know 😉

**Comment by iyobo** [comment]
@jamangile very correct.
@RienNeVaPlus and I have different targets.

I have absolutely no interest in Foxx.
Considerations for Foxx actually have no place in the context of TypeORM.
What I want is to be able to use ArangoDB like one would any other relational DB that TypeORM currently supports.

It's very possible, but I have not started with this yet though as time on my end has been quite constrained.

**Comment by jamangile** [comment]
Okay, this is great news... seems like we are aligning 🥳

@RienNeVaPlus... again, I'm sorry about the [aqbjs](https://github.com/arangodb/aqbjs) support. I worked on the [typescript support](https://www.npmjs.com/package/@types/aqb) of the lib which I still use for a client project. I see that you are also a big fan of the stack. If you'd like to fork and revive the project please reach out to me. I have used the lib a few times so I'm happy to share my experiences with it.

@iyobo this is what I propose. We used the official  [arangojs](https://github.com/arangodb/arangojs) driver as the driver of choice. I read through the package and I see @pleerock recently did SAP Hana support, so I propose we read through this [commit list](https://github.com/typeorm/typeorm/pull/5246) to understand the inner workings of how to add new driver support.

I think we should start with just the document store component of ArangoDB first. We can then do some planning on how we address Edges, If we choose to do so at all. What do you think of this?

If we are aligned, then I'll start a PR and share the link here for traceability.

Happy coding all ❤️

**Comment by iyobo** [comment]
@jamangile that is exactly the intent. Base (+ relational) document storage capabilities using arangojs.
Actual graphing would be a secondary concern.

**Comment by TimNZ** [comment]
Anyone working on this?
I think you just clone the Mongodb driver as starting base.

**Comment by jamangile** [comment]
Hi @TimNZ 

I forked the project [here](https://github.com/jamangile/typeorm) to get started. 
I got a bit distracted so I haven't made the pull request yet for everyone to contribute.

Looks like everyone here is keen to get this running 👟  and I'm the bottleneck 🙈 . I'll create a pull request with an abstract class clone of Mongodb and share, we can take it from there.

**Comment by natejgardner** [comment]
It would be nice to integrate Arango's graph capabilities as well. Arango functions best when edges are used to  explicitly define relationships. If TypeORM's relational features could be mapped onto ArangoDB graphs, that would really take the best advantage of ArangoDB's capabilities.

**Comment by qwathi-ai** [comment]
@imnotjames ,

Thanks for the support in tagging the pull request ❤️ .

**Comment by anonymousThey** [comment]
Hey @qwathi-ai! Thanks for getting a start on this. I wanted to support so I added a $50 bounty. Excited to see this worked on some more.

**Comment by iyobo** [comment]
I have not tested it but it looks like @qwathi-ai merged his PR that enabled ArangoDB as a driver:
https://github.com/qwathi-ai/typeorm/pull/1

Maybe this can be closed?
