### ISSUE TITLE
How to generate MongoDB ODM entities ?

### ISSUE THREAD

**Issue by davidquintard** [typeorm/typeorm#4127]
Hi there,
I'd like to know how to generate mondodb odm entities?
"typeorm-model-generator" does not support mongodb.
"mongoid" is for ruby framework (https://docs.mongodb.com/mongoid/current/)

David

**Comment by imnotjames** [comment]
Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
