### ISSUE TITLE
Types should correctly display "null" or "undefined" on nullable: true or select: false

### ISSUE THREAD

**Issue by jvandenaardweg** [typeorm/typeorm#4139]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.17`

**Steps to reproduce or a small repository showing the problem:**

First of all: thank you so much for this package. It's really easy to work with!

Lately, I stumbled upon the problem below:

Just a simple example:

```typescript
// Article entity
@Column({ nullable: true })
title: string;
```

```typescript
const article = await articleRepository.findOne(articleId);
```

Title:
`(Property) Article.title: string`

But it could also be `null`, not only a `string`.

Another example:
```typescript
// Article entity
@Column('text', { nullable: true, select: false })
text: string;
```
`(Property) Article.text: string`

But it could also be: `null` and `undefined`.

Is there any way to get more correct types? Because Typescript does not pick these things up correctly, where you would expect to be notified by possible `null` and `undefined` values.

I've tried:
```typescript
// Article entity
@Column({ nullable: true })
title: string | null;
```

But then i get an error: `Data type "Object" in "Article.title" is not supported by "postgres" database`. Probably because `typeof null` is `object`. 

The library should correctly look for any `nullable` property on the `Column` in this case. Or `nullable: true` should just be removed, and just use the types: `title: string | null` to determine a nullable column. This way it already fixes the problem I describe.

**Comment by Kononnable** [comment]
>But it could also be null, not only a string.
Any yet you wrote it yourself, that it can only be a string. We can't change typings of your code - you should use `string | null` instead.
As for an error with not recognized type - reflect-metadata can store only basic type information - and if something is nullable it always sees it as an object. Because of it typeorm doesn't get enough information to guess column type - you need to pass a `type` option to column decorator.

As for undefined - It would be very hard(if it's even possible) to pass correct type from typeorm in case `select:false` is used - types have to be known on compilation while this information is very logic dependent.

**Comment by jvandenaardweg** [comment]
> As for undefined - It would be very hard(if it's even possible) to pass correct type from typeorm in case select:false is used - types have to be known on compilation while this information is very logic dependent.

But what if you just allow to pass in: `string | undefined`? in context it’s exactly the same as giving `select: false`. Then TS just warns you you should always check if its defined if you want to use it.

**Comment by Kononnable** [comment]
You would then have to always check every column if it's value is `undefined` before using it. It would make a tremendous amount of end user code invalid(typescipt would scream about possible undefined) and will make using ORM painful.
I would very much like typeorm to be fully compatible with strict flags, but with current state of affairs I don't see this coming soon. Implementing that on it's own is pretty complex but there are tons of more important bugs to be fixed and not so much time to do that(since no one is working full-time on typeorm).

**Comment by jvandenaardweg** [comment]
> You would then have to always check every column if it's value is undefined before using it. It would make a tremendous amount of end user code invalid(typescipt would scream about possible undefined) and will make using ORM painful.

Not every column. Just the ones where you have `select: false`. Now the code just assumes its there, which is actually a bug. Implementing this change would actually warn the user of its (bad) code.

Or am i missing something here? :-)

I understand other priorities, again, thanks for the library and the time you and other contributors put in!

**Comment by Kononnable** [comment]
>Not every column. Just the ones where you have `select: false`.
If you set this option in entity definition you can declare variable as `| undefined`. It will have very similar user experience.

As for setting it for every column: It will be hard(or even impossible) to determine which columns should have `| undefined`. This is very orm-logic dependent. You pass this information to column decorator, but you need to use it in completely different place. Underneath decorator just saves metadata about config - it's saves a JS object. But type system doesn't have access to it, because it's run during compilation, before JS objects with metadata exists. To make it work we would probably have two different types - one for `select:true`, one for `select:false`. It probably is possible to implement, but it would be really hard to do it properly.

**Comment by cdeutsch** [comment]
> Any yet you wrote it yourself, that it can only be a string. We can't change typings of your code - you should use `string | null` instead.

`string | null` doesn't work with Postgres.

I get the error:

> Data type "Object" in "User.username" is not supported by "postgres" database.

Same error as @jvandenaardweg reported.

> You would then have to always check every column if it's value is undefined before using it. It would make a tremendous amount of end user code invalid(typescipt would scream about possible undefined) and will make using ORM painful.

Right now, I don't think `typeorm` works well for TypeScript, because instead of checking for just `undefined`, I have to also worry about `null`. 

Would love to see a configuration option to just treat `undefined` as `null`.

**Comment by jvandenaardweg** [comment]
I've changed the title, because...

```typescript
@Column({ select: false })
title: string | undefined;
```

...seems to work fine.

It's just about the nullable values:

```typescript
@Column({ nullable: true })
title: string | null;
```

Results in `Data type "Object" in "Article.title" is not supported by "postgres" `

**Comment by kav2k** [comment]
The only workaround that I found is this:
```ts
@Column({ nullable: true, type: "varchar" })
title: string | null;
```
i.e. manually specifying the type. Otherwise, TypeORM can't guess that type correctly (assumes Object).

It would be nice if TypeORM could correctly deduce a `nullable: true` column type from `T | null` (or `T | null | undefined`).
