### ISSUE TITLE
It seems that main website is somewhat misleading on relations. posts: Post[] does not work, but posts: Promise<Post[]> works.

### ISSUE THREAD

**Issue by idchlife** [typeorm/typeorm#417]
When loading entity from database property post: Posts[] won't even be populated, but post: Promise<Post[]> will be.

Found about promise in samples folder of repository.

Also that leads to type errors, there is no more possibility to use posts as array, but as promise.
Digging more I discovered that when finding entity through entity manage there should be also join options, so collection will be populated. There aren't any options to relation to make this happen everytime? lazy: false option does not populate collection everytime.

**Comment by pleerock** [comment]
having "lazy relations" is very specific - you have to operate with promises everywhere. This cant be done other way because all load operations are async.

so, the standard way is to leftJoinAndSelect everything you need by your own (better using query builder). This has its own benefit - granule control of what you need in different cases. I highly recommend this pattern.

one another way which is not implemented is what you are suggesting - to have `eager: true` and it will load relations all the time. This feature is for the future implementation. But I have to say it will work only in simple use cases and once you model will become complex it won't be efficient to use this option.

**Comment by idchlife** [comment]
Thanks! Waiting for eager passionately! Very useful in Doctrine and many many small simple entities with small collections. But anyway, all can be hidden is some service, with hidden implementation (all join options), as it is right now.
