### ISSUE TITLE
How to use "in" in findAndCount method

### ISSUE THREAD

**Issue by kirning** [typeorm/typeorm#4184]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I want to use "in".  e.g.:
```sql
select * from t_order where status in (0,1)
```
The document say use “In”
![image](https://user-images.githubusercontent.com/7327933/58314485-2aa66500-7e42-11e9-8db1-c49eeb850f4b.png)
But When I use it.

```ts
getRepository(Batch).findAndCount({
            where: {
                status: In([EBatchStatus.init, EBatchStatus.noPass])
            },
            skip: pageIndex * pageSize,
            take: pageSize,
        });
```

typeorm log:
```sql
SELECT "Batch"."id" AS "Batch_id" FROM "batch" "Batch" WHERE "Batch"."status" = ? LIMIT 15
-- PARAMETERS: [{"_type":"in","_value":[0,3],"_useParameter":true,"_multipleParameters":true}]
```

I can't get data what i want to obtain;

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by imnotjames** [comment]
I can't replicate this in the latest version of TypeORM.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.  If this is still a problem, please open a new issue for it.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
