### ISSUE TITLE
Provide a way to specify path to CLI config file globally

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#419]
Right now, CLI will look for a file called `ormconfig.json` in the root of the project, however, I would like to store it in some other way, e.g.: `src/config/typeorm.json`. However, in order to do this I would have to pass this path to all CLI commands, e.g.: `typeorm migrations:create -n Foo --config src/config/typeorm.json`. This quickly becomes unwieldy.

I would suggest to add an alternative way to specify default arguments for CLI in the project.

1). We could use a file called `.typeormrc` in the root directory with some pre-configured arguments for CLI, e.g.:

```json
{
  "config": "src/config/typeorm.json"
}
```

2). We could add it to a `package.json` directly:

```json
{
  "name": "project-name",
  "...": "...",
  "typeOrmConfig": {
    "config": "src/config/typeorm.json"
  }
}
```

---

Sequelize uses the first approach, in my project I have the following file `.sequelizerc`:

```js
module.exports = {
  config: './database/config.js',
  'migrations-path': './database/migrations'
};
```

And it seems to work great. I can use the same database config for both application and Sequelize CLI.

**Comment by NoNameProvided** [comment]
We can just add a CLI option to specify a custom path for the config not? The drawback is that you have to type it everytime, but it can be easily done via npm scripts. I think this is better than adding a different file. 

Also this is sightly related to #391 as I was thinking of creating a `--config` option to specify custom configs.

**Comment by slavafomin** [comment]
I think it's a general practice of allowing such RC-files in the root of the project. I know for sure that Bower and Sequelize both do this to provide additional settings. Creating an npm script for each CLI call will be extraneous work.

**Comment by pleerock** [comment]
Its general practice to have config file in root of the project. Its quite convenient. The only thing I don't like about this is when you have multiple configurations from different libraries and frameworks - root of the project becomes messy.

having both `.rc` and `config` in the project is pointless. `.rc` and `config` have same purpose - storing configuration. No need to have two files for storing configuration. If you create `.rc` in the root and config in `config` it does not resolve problem with multiple files in project root. It just makes things more complex - structure, navigation and understandability. And it will be dummy because except for `config: './database/config.js'` it wont contain anything else because everything is already in config file.

Alternative is better:
```json
"typeormConfig": "src/config/typeorm.json"
```

We also need to allow to specify `--config` to cli. Then it may become easier to create npm script and use this option.  So the question is - do we need config option in package.json when we can create npm scripts?

**Comment by NoNameProvided** [comment]
> The only thing I don't like about this is when you have multiple configurations from different libraries and frameworks - root of the project becomes messy.

This is the very same reason what makes me say we dont need two place to store config related options. So I would totally vote against having a `.rc` file.

I am also actually against storing custom config in `package.json` as well as it feels unnatural to me. (This one is totally a subjective thought of my own.)

So I still think we should stick with only adding a `--config` option to specify a different config file when the default location is not desirable. 

Anyway it is a good thing to install the CLI alongside with the project (and since the cli is in the same repo it happens by default here) The only paid off is to we need to wrap important scripts in npm scripts like 

```json
"scripts": {
  "migrate": "typeorm migrations:run"
}
```
and then we we have to call via `npm run migrate`, which is not that longer than `typeorm migrate`. 

Also since the implementation of migration abstracted away the underlying tools can be swapped. (Eg: this is what will happen when we will move to use typeorm by default, all dev will still run `npm run migrate` and they don't have to learn new commands.)

Npm scripts also supports custom params, so we can still add a rule like this:

```json
"scripts": {
  "typeorm": "typeorm --config config/typeorm.json"
}
```

and we can run any command with it: `npm run typeorm -- migrations:run`. (Everything after the double dash will be passed to the called script as parameters so the actual command which will run in this case is `typeorm --config config/typeorm.json migrations:run`)

So my opinion is to leverage the tooling we already have.

**Comment by slavafomin** [comment]
Well, the example of @NoNameProvided makes sense. If additional arguments could be passed to the typeorm CLI through `npm run` then I have no objections.

However, on the other side, it will make commands longer to type, i.e.: `npm run typeorm -- arguments` instead of just `typeorm arguments`. I would personally prefer the second form. I see no harm in adding RC file or adding a section to `package.json` as far as it's not mandatory. This way everyone could be happy — just use the way you think is better for your project.

**Comment by pleerock** [comment]
As per discussion lets use suggestion @NoNameProvided provided. Maybe in the future we will implement some additional sugar things, but for now I'll close it.

**Comment by KyleRAnderson** [comment]
Does the `--config` option actually exist? I'm getting errors trying it, and neither this ticket nor the documentation actually clarify if it was ever added.

**Comment by vincilbishop** [comment]
For anyone that finds themselves here: https://stackoverflow.com/questions/52187328/how-to-specify-ormconfig-ts-for-typeorm
