### ISSUE TITLE
OneToMany relationship joined on possibly two columns

### ISSUE THREAD

**Issue by macdonaldr93** [typeorm/typeorm#4198]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm trying to figure out how to express a relationship through entities. This is essentially it:

```typescript
@Entity()
export class Game {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('int')
  homeTeamId: number;

  @ManyToOne(type => Team, team => team.games)
  @JoinColumn({ name: 'homeTeamId' })
  homeTeam: Team;

  @Column('int')
  awayTeamId: number;

  @ManyToOne(type => Team, team => team.games)
  @JoinColumn({ name: 'awayTeamId' })
  awayTeam: Team;
}
```

```typescript
@Entity()
export class Team {
  @PrimaryGeneratedColumn()
  id: number;

  // this is where I'm unsure what to do
  @OneToMany(type => Game, game => game.homeTeam || game.awayTeam, {
    cascade: true,
  })
  games: Game[];
}
```

I want to express that games can be either from a home team or an away team. If this isn't possible in the Entity. Where could I add this? Is there any concept of virtual fields?

**Comment by imnotjames** [comment]
Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

Though - reading the question, I'm not sure I understand what you're trying to do.  If you're still having trouble, please clarify on the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
