### ISSUE TITLE
[Typescript] Does save() need to be typed with generic ?

### ISSUE THREAD

**Issue by taboulot** [typeorm/typeorm#4242]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.16` (or put your version here)

**The problem :**

Recently we introduced a bug during a refactoring. We `save()` an entity in the wrong repository which raised an error.

*Example :*

```ts
class CustomerEntity {
 public id: number;
 public name: string;
} 

class AddressEntity {
 public id: number;
 public address: string;
}

const address: AddressEntity = {id: 3, address: 'myAddress'}
const customerRepo = this.entityManager.getRepository(Customer);

customerRepo.save(address); 
// No typescript script error even if the transaction failed in my DB
```

**Potential cause :**

`save()`typing is that :
```ts
save<T extends DeepPartial<Entity>>(entity: T, options: SaveOptions & {
        reload: false;
    }): Promise<T>;
```

It means that the `entity` can have additional properties, because of `extends DeepPartial<Entity>`. I thing it's an error.

**Question :**

I think the right type is :
```ts
save(entity: DeepPartial<Entity>, options: SaveOptions & {
        reload: false;
    }): Promise<DeepPartial<Entity>>;
```

It's more safe.

Am I right or there is a reason for `T` to `extends DeepPartial<Entity>` ? Am I missing something ?

**Comment by Kononnable** [comment]
Take a look at [this example](https://www.typescriptlang.org/play/#src=type%20BasicType%20%3D%20%7B%20id%3A%20number%20%7D%0D%0A%0D%0Afunction%20fnc(arg%3A%20BasicType)%20%7B%0D%0A%20%20%20%20console.log(arg.id)%0D%0A%7D%0D%0A%0D%0Aconst%20A%3A%20BasicType%20%3D%20%7B%0D%0A%20%20%20%20id%3A1%0D%0A%7D%0D%0Aconst%20B%20%3D%20%7B%0D%0A%20%20%20%20id%3A%202%2C%0D%0A%20%20%20%20name%3A%20%20%22x%22%0D%0A%7D%0D%0A%0D%0Afnc(A)%0D%0Afnc(B)%0D%0A). It works because typescript uses [structural subtyping](https://www.typescriptlang.org/docs/handbook/type-compatibility.html) - it will always allow you to pass additional properties(unless you're using object literal).

As for type which you thought was correct - you still would need to use generic parameter. Otherwise typescript wouldn't know that Entity type in first argument is same type that is returned - i.e. you would pass `DeepPartial<CustomerEntity>` and return type would still be `Promise<DeepPartial<Entity>>`.

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
