### ISSUE TITLE
QueryFailedError: relation "users_id_seq" already exists

### ISSUE THREAD

**Issue by darioielardi** [typeorm/typeorm#4256]
**Issue type:**

[X] question
[X] bug report ?
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**The problem**

I got a simple project using TypeORM with a bunch of entities. Every entity has an id column defined as the docs suggest:

```
@PrimaryGeneratedColumn()
id: number;
```

Now, the problem is that if I set `synchronize: true` or try to sync the schema from the CLI, it tries to recreate the id sequence every time, which throws an error:

`QueryFailedError: relation "users_id_seq" already exists`

How am I supposed to handle this behavior?

Thanks and congratulations for the great work with this project.

**Comment by Kononnable** [comment]
Can you provide some reproduction example? I think this is something specific, because we doesn't have more of such reports and this is basic use of schema sync functionality.

**Comment by veraldo** [comment]
I had this problem, I've noticed that the sequences were duplicated at some point, and the `column_default` value was like `nextval('user_id_seq1'::regclass)`. Changing it to `nextval('user_id_seq'::regclass)` made the synchronization work. Mind that it will mess up with the current id in the sequence

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by Jekahome** [comment]
DROP SEQUENCE "user_id_seq";

**Comment by codecrusher84** [comment]
I had the same problem and deleting the database completely and creating it again fixed the issue...
