### ISSUE TITLE
Root Id query

### ISSUE THREAD

**Issue by ibox4real** [typeorm/typeorm#4265]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

So for limit, offset and order to work correctly when there is an one-to-many or many-to-many relation, TypeOrm first selects the id-s of the root element and then limits the second query to those id-s. 

This is currenlty being done with two queries. Would inner joining the root id query to the final query not give better performance instead of looping over the ids and using WHERE IN ([ids])   in the second query?

**Comment by Kononnable** [comment]
I think this was done to make a distinction between `limit`,`offset` and `skip`, `take`. What you would choose depends on what effect do you want to achieve - take 5 elements from main table and all data related to it or take 5 elements at all(if relation is 1:many you would take e.g. just 2 rows from main table).

**Comment by imnotjames** [comment]
Hope this answered your question, but since it's been about a year since you asked the question and there was any activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
