### ISSUE TITLE
Not stable CI tests for @next version of TypeORM

### ISSUE THREAD

**Issue by YegorZaremba** [typeorm/typeorm#4316]
**Issue type:**

- [x] bug report

**TypeORM version:**

- [x] `@next`

Not stable CI tests

**Comment by vlapo** [comment]
This is a known issue. @Kononnable works on this continuously

**Comment by YegorZaremba** [comment]
@Kononnable Hi, should I close PR #4311 for this issue? (and close issue too?)

**Comment by vlapo** [comment]
@YegorZaremba I think the best is fix bugs for now. Check issues here and pick one ;)

**Comment by Kononnable** [comment]
Skipping failing test is a bad idea(in general). We would forget about them in the future and they wouldn't be tested(or fixed) at all. In local development I sometimes skip broken tests and enable just before pushing the branch(or skip entire db driver if most of tests are failing).

As for 0.3.0 - it's a tricky subject. It is alive for a year now but there are still some changes there to be made and for some of them we have not agreed on implementation(yet). So if you've got a time and doesn't have to implement a specific feature it might be better to avoid it. It is mostly completed by there is a chance you would spend a day of two on understanding the code which would be changed a day later.

When fixing bugs in 0.2 you could check if they're not working on 0.3(if it's just a matter of quick look) and prioritize those not running in both versions. I would advice you to start in one area(issue label) and pick bugs from there. It's much easier to fix a bug when you're already familiar with code of that fragment of typeorm.
If you'd like you can also review PRs. It can save a lot of time if someone a bit familiar with our codebase and contributing guidelines reviews PRs before @pleerock checks if it can be merged. Often only tiny problems are blocking PRs, but they have to wait 2-3 more weeks because @pleerock doesn't have enough time to check them on a daily basis(so if he is the only one reviewing them this process may take some time).

**Comment by YegorZaremba** [comment]
Thank you for the detailed answers, they are very helpful for newcomers
