### ISSUE TITLE
It returns error when running find (Repository) with relation when a pivot table is created (2 many-to-one)

### ISSUE THREAD

**Issue by shajeeck** [typeorm/typeorm#4338]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce:**

It returns error when running find (Repository) with relation when a pivot table is created (2 many-to-one)

> eg from MySQL sample database  'sakila'

Consider 3 tables: `actor`, `film`, `film_actor`

**Actor**

```
export class Actor {

    @PrimaryGeneratedColumn()
    actor_id: number;

    @Column()
    first_name: string;

    @Column()
    last_name: string;

    @OneToMany(type => FilmActor, filmActor => filmActor.film)
    filmActors: FilmActor[];

}
```

**Film**

```
export class Film {

    @PrimaryGeneratedColumn()
    film_id: number;

    @Column()
    title: string;

    @OneToMany(type => FilmActor, filmActor => filmActor.actor)
    filmActors: FilmActor[];
    
}
```

**FilmActor**

```
export class FilmActor {

    @ManyToOne(type => Actor, actor => actor.filmActors, { primary: true })
    @JoinColumn({ name: 'actor_id', referencedColumnName: 'actor_id' })
    actor: Actor;

    @ManyToOne(type => Film, film => film.filmActors, { primary: true })
    @JoinColumn({ name: 'film_id', referencedColumnName: 'film_id' })
    film: Film;

    @UpdateDateColumn()
    last_update: Timestamp;
}
```

When running `filmRepository.find({ relations: [ "filmActors" ]});` it gives an error

> ER_BAD_FIELD_ERROR: Unknown column 'Film.actor_id' in 'on clause'

Am i doing anything wrong here?

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by Kononnable** [comment]
Try to define primary columns more explicitly:
https://github.com/typeorm/typeorm/issues/3701#issuecomment-475915733

**Comment by shajeeck** [comment]
Thanks for your reply, i tried explicitly defining the primary keys, but still it gives same error.

> ER_BAD_FIELD_ERROR: Unknown column 'Film.actor_id' in 'on clause'

Now my FilmActor is like this

```
export class FilmActor {

    @PrimaryColumn()
    actor_id: number;

    @PrimaryColumn()
    film_id: number;

    @ManyToOne(type => Actor, actor => actor.filmActors)
    @JoinColumn({ name: 'actor_id' })
    actor: Actor;

    @ManyToOne(type => Film, film => film.filmActors)
    @JoinColumn({ name: 'film_id' })
    film: Film;

    @UpdateDateColumn()
    last_update: Timestamp;

}
```

Any help will be appreciated...

**Comment by shajeeck** [comment]
@pleerock any help?

**Comment by imnotjames** [comment]
This does not look to be an issue with TypeORM but instead how you're using it.

We'll need more information to locally replicate this problem.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
