### ISSUE TITLE
how to know migrationRun finish?

### ISSUE THREAD

**Issue by fatfatson** [typeorm/typeorm#4357]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

is there any event for (auto )migration finish?
I have to make some query at the program starting, but if there's a break migration, the query will fail, so I'd like to wait for the finish of migration, but i don't know how to get it.

also want to know: is there any API to check the migration status?

**Comment by Kononnable** [comment]
You can disable automigration in connection options and call migrations manually -`await connection.runMigrations()`. This way you will have full control over when it is executed and if db is already up-to-date.

**Comment by imnotjames** [comment]
Hope this was an answer to your question.  Since it's been about a year since you asked the question and there was no other activity I'm gonna close it out.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
