### ISSUE TITLE
Generated Migration Recapitulates Entire Schema

### ISSUE THREAD

**Issue by SethGreylyn** [typeorm/typeorm#4362]
**Issue type:**

[x] bug report

**Database system/driver:**

[x] `mysql` / `mariadb`

**TypeORM version:**

[x ] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a project with the following `.env` environment variables:

```
TYPEORM_CONNECTION=mysql
TYPEORM_HOST=localhost
TYPEORM_PORT=3306
TYPEORM_USERNAME=<username>
TYPEORM_PASSWORD=<password>
TYPEORM_DATABASE=<database>
TYPEORM_ENTITIES=<entities glob>
TYPEORM_ENTITIES_DIR=<entities dir>
TYPEORM_MIGRATIONS=<migrations glob>
TYPEORM_MIGRATIONS_DIR=<migrations dir>
```

My development environment is Windows 10, whereas my colleagues develop on Mac OSX and Debian.

When I run `typeorm migration:generate -n newMigration`, TypeORM always generates a migration file (regardless of whether the entities have been changed), and this migration is a single-migration setup of the entire database schema (including any new additions).

My colleagues can run the same command and either have it error out if it didn't detect any schema changes, or have slim migrations that only take not of those changes made for the new migration. I found [this issue](https://stackoverflow.com/questions/52800204/typeorms-migrationgenerate-regenerates-the-whole-database-schema) with no answers, which seems to be an instance of the same problem.

I've made sure to have run the latest migrations before attempting to generate a new one; I've even dropped the schema entirely and rebuilt it from previous migrations. The result is always the same.

**Comment by wallopthecat** [comment]
I have the same issue on Windows 10, typeorm `0.2.18`, postgresql via docker on windows. Driving me absolutely crazy, and I stumbled across the same unanswered stackoverflow, which incidentally seems to have a bounty right now

**Comment by Kononnable** [comment]
Could you provide some reproduction data? Right now we only knows that this happens on Win10. I guess something else(come configuration settings) is required for the bug to appear.

**Comment by wallopthecat** [comment]
For me this was solved (on Win10) by removing `schema: public` from models
https://github.com/typeorm/typeorm/issues/4632#issuecomment-529714706

**Comment by mdawsondev** [comment]
I'm having this same issue on MySQL. I'm not using `@Entity({ schema: "public"})` anywhere in my code but every time I try to generate a new migration, TypeORM generates an entire replica which is attempting to pointlessly alter every table in the database.

**Comment by wallopthecat** [comment]
Compare your db with what is in with your `build/server/entity/*` files. The difference between the 2 is what is generated

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
