### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by mhabsaoui** [typeorm/typeorm#4377]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Hi,
I am trying to make [NestJs web-app](https://github.com/lujakob/nestjs-realworld-example-app) (with TypeOrmModule => ^6.0.0) connect to a Mysql DB running in a docker container.

_ormconfig.json :_

```
{
  "type": "mysql",
  "host": "nest-mysql",
  "port": 3306,
  "username": "root",
  "password": "rootpass",
  "database": "nestjsrealworld",
  "entities": ["src/**/**.entity{.ts,.js}"],
  "synchronize": true
}
```
_The docker command I am using to run mysql container instance :_
`docker run --rm --name nest-mysql -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_DATABASE=nestjsrealworld -d mysql`

The problem I get is it cannot connect to DB :/

```
[Nest] 22388   - 2019-06-30 1:40 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +527ms
Error: getaddrinfo ENOTFOUND nest-mysql nest-mysql:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
```

I have checked on the Mysql container logs it is ready for connections...

What am I doing wrong ?

Thanks.

**Comment by Tukimitu** [comment]
are you sure your database host is like 'nest-mysql'? my db host is '127.0.0.1','localhost'...eg

**Comment by mhabsaoui** [comment]
> are you sure your database host is like 'nest-mysql'? my db host is '127.0.0.1','localhost'...eg

Yes, when using docker Mysql, you have to use the container name (nest-mysql) instead of localhost...

**Comment by ValeriyDevPro** [comment]
`docker run --rm --name nest-mysql -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_DATABASE=nestjsrealworld -d mysql`

If this is the exact command you are executing, then I see the issue that there is no `port` declaration.

try to use
`docker run --rm --name nest-mysql -p3306:3306 -e MYSQL_ROOT_PASSWORD=rootpass -e MYSQL_DATABASE=nestjsrealworld -d mysql`

>>> Yes, when using docker Mysql, you have to use the container name (nest-mysql) instead of localhost...

This is valid for the situation when you are running both mysql and an application inside containers, but if your application is running by host then you have to set a port in your docker command and for your application use `localhost` instead of `nest-mysql`

I think you are trying to implement some tutorial, if I'm right then I think it will be fair to post a link to this tutorial.

Cheer.

**Comment by mhabsaoui** [comment]
@ValeriyDevPro  OK Thanks for your tips, that helped.
