### ISSUE TITLE
How to set default value for datetime in nest ORM column for mysql

### ISSUE THREAD

**Issue by mymmoonoa** [typeorm/typeorm#4386]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Does anyone know how to set default value of datetime type for nest ORM mysql
I tried 
```
@Column({ type: 'datetime', default: () => new Date()}) .
@Column({ type: 'datetime', default: () => '2019-06-29'})
@Column({ type: 'datetime', default: 'CURRENT_TIMESTAMP'})
@Column({ type: 'datetime', default: 'now()'})
```
All failed.

I will be very appreciated for any help.

**Comment by rmainseas** [comment]
Try swapping `datetime` for `timestamp`

**Comment by mymmoonoa** [comment]
> Try swapping `datetime` for `timestamp`

Now I use `{type: 'bigint', unsigned: true, default: 0}` instead. 
But Still I want to figure out what the default value can it be for `datetime` as [orm official document](https://typeorm.io/#/entities) `# Column types for mysql / mariadb` part has this type

**Comment by robertmain** [comment]
`bigint` will give you an integer. `TIMESATMP` (counter-intuitively) will give you an ISO8601 date string.

**Comment by mymmoonoa** [comment]
> `bigint` will give you an integer. `TIMESATMP` (counter-intuitively) will give you an ISO8601 date string.

Thanks @robertmain , looks TIMESTAMP is quite good. Now I use bigint to store javascript `new Date().getTime()` value.

**Comment by robertmain** [comment]
Fair enough. Just be aware of the fact that you may run into weird timezone issues storing unix timestamps.

**Comment by billyjov** [comment]
@robertmain i tried it with `timestamp`, but still get an mysql error for the Date object.

my column looks like this: 

```
 @Column({
        nullable: false,
        default: () => moment().add(2, 'hours').toDate(),
        type: 'timestamp',
    })
```

**Comment by robertmain** [comment]
Yeah, you probably don't want to do that, because that `default` value is evaluated only when the migration is run. So what you're effectively doing is snapshotting the current time when the migration is being run, then telling MySQL to *always* use that value as the default value. So what you're effectively running is this:

```typescript
@Column({
  nullable: false,
  default: () => new Date(2020, 1, 18, 17, 00), 
  type: 'timestamp',
})
```


Which will produce something like the following SQL:


```sql
ADD COLUMN `mycolumnname` TIMESTAMP NOT NULL DEFAULT '2020-02-18 17:00:00-05:00'
```


What you _probably_ want to do is have MySQL re-calculate that value every time, so you want to shoot for the following SQL:

```sql
ADD COLUMN `mycolumnname` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
```

I'm guessing at this point because I've migrated most of my apps to postgres, but you probably want something like this in your column definition:

```typescript
@Column({
  nullable: false,
  default: () => 'CURRENT_TIMESTAMP' 
  type: 'timestamp',
})
```

**Comment by billyjov** [comment]
Yes you are right. 
 But i dont want to have each time the current TIMESTAMP but two hours later.

i tried following without any success


```
@Column({
  nullable: false,
  default: () => 'DATE_ADD(NOW(), INTERVAL 2 HOUR)' 
  type: 'timestamp',
})

```

or 

```
@Column({
  nullable: false,
  default: () => 'DATE_ADD(CURRENT_TIMESTAMP), INTERVAL 2 HOUR)' 
  type: 'timestamp',
})

```
 TypeORM/MySQL does'nt support all these SQL expressions

**Comment by robertmain** [comment]
MySQL _does_...but TypeORM's integration with MySQL may not. It's hard to say, but I ended up switching to postgres (for a variety of reasons). I know that "jUSt SwITch tO PosTGrES" isn't _really_ a solution, but if you can it tends to be a much better developer experience all round :)

**Comment by billyjov** [comment]
@robertmain thanks for your analyse. @pleerock is there a plan to support this ? or a workaround to deal with it ?

**Comment by robertmain** [comment]
@billyjov np. I think part of the issue is that TypeORM takes whatever you enter into `default` and just treats that as a string value. So if you enter `CURRENT_TIMESTAMP`, it doesn't pass

```sql
DEFAULT CURRENT_TYPESTAMP
``

to your RDBMS....instead it passes:

```sql
DEFAULT 'CURRENT_TIMESTAMP'
```
Thinking about this some more - have you tried getting rid of `default` and using `asExpression` instead in your `Colum()` option?

So, this:


```ts
@Column({
  asExpression: 'ADD COLUMN `mycolumnname` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
'
})
```

Again, hardly a fix - but it might allow you to continue with your project.

**Comment by Aadmaa** [comment]
See @pleerock answer here: https://github.com/typeorm/typeorm/issues/877

You can do like this: 
@Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP'})

Or like this if for example you want to match Date.now() from Javascript:
@Column({type: "bigint", default: () => "cast(date_part('epoch', CURRENT_TIMESTAMP)*1000 as bigint)"})

If you generate a migration with the CLI you can see it is interpreted correctly. 
```typescript
 await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "created" SET DEFAULT cast(date_part('epoch', CURRENT_TIMESTAMP)*1000 as bigint)`, undefined);
```

**Comment by gentunian** [comment]
none worked for me with mongodb, this worked:
```typescript
@Column() createdAt: string = DateTime.now().toISO();
```

**Comment by PRossetti** [comment]
For PostgreSQL at least you can do

@Column({ type: "timestamp", default: () => "now()" })
time: Date;
Have in mind this is not the same as doing:

@Column({ type: "timestamp", default: "now()" })
time: Date;
This last option in my case at least throw error in CI because it wasn't doing what it looks, so try going with the first alternative I mentioned.
