### ISSUE TITLE
Shortening of aliases in query generation.

### ISSUE THREAD

**Issue by davidsheckler** [typeorm/typeorm#4425]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I believe there is a bug in the shortening of aliases (at least for the oracle driver as it limits the size of an alias to 30 characters)

From driver/DriverUtils.ts : In the function buildColumnAlias():

```
    static buildColumnAlias({ maxAliasLength }: Driver, alias: string, column: string): string {
        const columnAliasName = alias + "_" + column;

        if (maxAliasLength && maxAliasLength > 0 && columnAliasName.length > maxAliasLength)
            return alias.length > column.length
                ? `${shorten(alias)}_${column}`
                : `${alias}_${shorten(column)}`;

        return columnAliasName;
    }
```

Should you have a table with a large number of large columns, that are also larger than the alias; you can have collisions on the shortened names of the columns.

Example of generated SQL below (Sorry it's somewhat large) There are multiple aliases of TA_TRANSACTIONS_br, TA_TRANSACTIONS_fr, TA_TRANSACTIONS_de etc.. 

I suggest an easy fix is to shorten the table name first, and see if the result is less than the maxAliasLength.

 If you have to shorten columns I would suggest a check for uniqueness.

Thanks!

```
SELECT "TA_TRANSACTIONS"."sunburst_id" AS "TA_TRANSACTIONS_sunburst_id", 
"TA_TRANSACTIONS"."carrier_tcsi_office_id" AS "TA_TRANSACTIONS_ca", 
"TA_TRANSACTIONS"."broker_tcsi_customer_id" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_tcsi_office_id" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_credit_score" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_transcredit_dtp" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_contact_first_name" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_contact_last_name" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_contact_phone" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_contact_fax" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."broker_email_address" AS "TA_TRANSACTIONS_br", 
"TA_TRANSACTIONS"."freight_bill_number" AS "TA_TRANSACTIONS_fr", 
"TA_TRANSACTIONS"."freight_bill_amount" AS "TA_TRANSACTIONS_fr", 
"TA_TRANSACTIONS"."status" AS "TA_TRANSACTIONS_status", 
"TA_TRANSACTIONS"."credit_amount" AS "TA_TRANSACTIONS_credit_amount", 
"TA_TRANSACTIONS"."external_comment" AS "TA_TRANSACTIONS_ex", 
"TA_TRANSACTIONS"."rate" AS "TA_TRANSACTIONS_rate", "TA_TRANSACTIONS"."rate_type" 
AS "TA_TRANSACTIONS_rate_type", "TA_TRANSACTIONS"."mileage" AS 
"TA_TRANSACTIONS_mileage", "TA_TRANSACTIONS"."equipment_type" AS 
"TA_TRANSACTIONS_eq", "TA_TRANSACTIONS"."origin_city" AS 
"TA_TRANSACTIONS_origin_city", "TA_TRANSACTIONS"."origin_state" AS 
"TA_TRANSACTIONS_origin_state", "TA_TRANSACTIONS"."origin_postal_code" AS 
"TA_TRANSACTIONS_or", "TA_TRANSACTIONS"."destination_city" AS 
"TA_TRANSACTIONS_de", "TA_TRANSACTIONS"."destination_state" AS 
"TA_TRANSACTIONS_de", "TA_TRANSACTIONS"."destination_postal_code" AS 
"TA_TRANSACTIONS_de", "TA_TRANSACTIONS"."last_update" AS 
"TA_TRANSACTIONS_last_update", "TA_TRANSACTIONS"."inserted" AS 
"TA_TRANSACTIONS_inserted", "TA_TRANSACTIONS"."date_in_collection" AS 
"TA_TRANSACTIONS_da", "TA_TRANSACTIONS"."date_collected" AS 
"TA_TRANSACTIONS_da", "TA_TRANSACTIONS"."date_dispersed" AS 
"TA_TRANSACTIONS_da", "TA_TRANSACTIONS"."date_closed" AS 
"TA_TRANSACTIONS_date_closed", "TA_TRANSACTIONS"."amount_collected" AS 
"TA_TRANSACTIONS_am", "TA_TRANSACTIONS"."insert_product_id" AS 
"TA_TRANSACTIONS_in", "TA_TRANSACTIONS"."update_product_id" AS 
"TA_TRANSACTIONS_up", "TA_TRANSACTIONS"."update_product_user_id" AS 
"TA_TRANSACTIONS_up", "TA_TRANSACTIONS"."fme_id" AS "TA_TRANSACTIONS_fme_id" 
FROM "TA_TRANSACTIONS"
```

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by dpmallinger** [comment]
you may be interested in:
https://github.com/typeorm/typeorm/issues/6229

if your using an up to date oracle client/server ( > 12.2 ) the max alias length should be 128 not 30.

**Comment by imnotjames** [comment]
Fixed a few cases of this.  If it's still an issue in 0.2.28 please open a new issue with detailed reproduction example instructions.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by kelmore5** [comment]
Glad this issue was resolved, but want to ask. Is a hash on the field names the best way to handle this? I feel like if you're going to swap out aliases, the names should be reversible somehow. Unless there's a way to get the original alias back from the hash that I missed.

PS: This feature was especially confusing while using `SelectQueryBuilder.getRawMany` and my field names were changed without any documentation or warning. It'd also be nice to get some sort of warning message about it.

Thanks

**Comment by imnotjames** [comment]
> Is a hash on the field names the best way to handle this? I

Unique & Consistency - worked well for this and beat any other alternatives proposed at the time.

> I feel like if you're going to swap out aliases, the names should be reversible somehow.

A mapping is kept internally.  Perhaps `getRawMany` should still translate them back?  I think this would be reasonable because `getRawMany` isn't for debugging TypeORM internals, it's for bypassing the hydration operations.

> It'd also be nice to get some sort of warning message about it.

Where?  Why?

---

Instead of commenting on a resolved issue which won't get much attention I suggest making a new one with a feature request.

**Comment by kelmore5** [comment]
Hey James (or not James?), thanks for the reply.

> A mapping is kept internally. Perhaps getRawMany should still translate them back? I think this would be reasonable because getRawMany isn't for debugging TypeORM internals, it's for bypassing the hydration operations.

That would be _ideal_. At least I think so / that's really what I want here.

> Where? Why?

Valid questions! Mainly because I spent a couple hours wondering about this until I found the one issue about it lol. But it'd probably be more annoying than helpful

> Instead of commenting on a resolved issue which won't get much attention I suggest making a new one with a feature request.

Wasn't sure if I should open a feature request or comment on the previous thread. I'll do that, thank you!
