### ISSUE TITLE
Unable to fetch records by using where clause for a date type field in postgres using typeorm

### ISSUE THREAD

**Issue by sauravpharmeasy** [typeorm/typeorm#4465]
I am using @nestjs/typeorm to fetch records from postgres.I want to fetch all the rows for given particular date and time using where clause.The table test has data for given date and time but unable to fetch it.

**test.entity.ts:**

@Column("timestamp with time zone",{ 
        nullable:false,
        name:"updated_on"
        })
    updated_on:Date;

**test.service.ts:**

let result = await this.testRepositiory.find({
	where: {
		updated_on: new Date(2019,6,6,0,44,43)
	}
})

**Typeorm generates below query and gives empty response as result:**

select * from test where updated_on = $1 -- PARAMETERS: ["2019-07-05T19:14:43.000Z"]
result: []

**Comment by Kononnable** [comment]
By the look of it JS Date object is using another timezone then is passed to db query.
Please provide a reproduction repo and time zones information, it would be hard to if this is a bug without them.

**Comment by imnotjames** [comment]
It's been over a year without any feedback here.  Without information to replicate this isn't an actionable issue and won't help us solve the issue you're having.  Help us to help you :)

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
If this is MSSQL this is a problem with v6 of node-mssql.  #3202
