### ISSUE TITLE
Error during migration:run - SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by bhaidar** [typeorm/typeorm#4467]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have created this migration:
```typescript
import { MigrationInterface, QueryRunner, getRepository } from 'typeorm';
import { MovieEntity } from '@movietracker/entity/movie.entity';
import { AddMovieDto } from '@movietracker/dto/movie.create.dto';

export class SeedMovies1563616871091 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    const movies = [
      {
        title: 'The Shawshank Redemption',
        watchedOn: new Date('2016-11-4'),
        genre: 'Drama',
        rating: 4
      },
      {
        title: 'The Godfather',
        watchedOn: new Date('2017-10-2'),
        genre: 'Drama',
        rating: 2
      },
      {
        title: 'The Dark Knight',
        watchedOn: new Date('2018-12-1'),
        genre: 'Drama, Action',
        rating: 3
      },
      {
        title: 'The Godfather: Part II ',
        watchedOn: new Date('2019-2-4'),
        genre: 'Drama',
        rating: 1
      },
      {
        title: 'The Lord of the Rings: The Return of the King',
        watchedOn: new Date('2019-4-2'),
        genre: 'Adventure, Drama, Fantasy',
        rating: 5
      },
      {
        title: 'Pulp Fiction',
        watchedOn: new Date('2019-3-27'),
        genre: 'Crime, Drama',
        rating: 3
      }
    ];

    const moviesCreated = await getRepository(MovieEntity).create(movies);
    await getRepository(MovieEntity).save(moviesCreated);
  }

  public async down(queryRunner: QueryRunner): Promise<any> {}
}
```

I have the following NPM scripts:

```json
"typeorm:cli": "ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js -f ormconfig.json",
    "db:migrate": "npm-run-all -s -l clean build:server && yarn typeorm:cli migration:run",
```

When I run the `yarn db:migrate` I get this error:

```bash
Error during migration run:
/Users/bilalhaidar/Projects/thisdotmedia/movie-tracker/apps/api/src/app/movietracker/entity/movie.entity.ts:1
(function (exports, require, module, __filename, __dirname) { import * as tslib_1 from "tslib";
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module.m._compile (/.../.../ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/bilalhaidar/Projects/thisdotmedia/movie-tracker/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

If I remove the code inside the `up()` it runs without errors!

**Comment by Kononnable** [comment]
Can you paste your `tsconfig.json` file? It looks like something isn't transpiled correctly.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
