### ISSUE TITLE
blob column only saves string (how to save and load blob)

### ISSUE THREAD

**Issue by StefanWolf-tp** [typeorm/typeorm#4488]
**Issue type:**

[x] question
[x]? bug report
[ ] feature request
[x]? documentation issue

**Database system/driver:**

[x] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x ] `0.2.5` (also tried with 0.2.18)

**Generaly**: 
can someone just give an example how to save a Blob object like in my example 
> Blob {size:1996683, type: "image/png"}  
> size: 1996683 type: "image/png"  
> proto: Blob  

can be saved in a cordova typeorm database (with the data content)? Inital if i get the Blob i can work with it fine and can display the image direclty without any converting or something else.

**Long version of my problem:**  
im currently building an ionic app with cordova and angular. for the database im using the typeorm module.  which i initialize like this:

    await createConnection({
    	type: 'cordova',
    	database: 'test.db',
    	location: 'default',
    	logging: false,
    	synchronize: true,
    	entities: [
    	  User,
    	  QrCode,
    	  QrFile,
    	  QrOrder,
    	  SubItem,
    	  Property,
      ]
    })

my qrFile entity which contains the blob column looks like:

    @Entity('qrfile')
    export class QrFile{
    
    ...
    
      @Column("blob", { nullable: true })
      content: Blob;

Here i tried a lot of other types instead of Blob e.g. Buffer, ArrayBuffer and so on...

I added a few debug console logs in the "main" method which is managing the entity content:

``` lang-js
public async getFileContent(qrFile: QrFile) {
    if(!qrFile.content){
      console.log("getFileBase64Content -> no content so load from server")
      let result  = await this.loadContentFromServer(qrFile).catch(reject => {
        return null;
      });
      qrFile.content = result;//await new Response(result).arrayBuffer()//new Buffer(result);
      qrFile = await this.saveQrFileToDB(qrFile);
    }else{
      console.log("getFileBase64Content -> content found!")
    }
    console.log("IMPORTANT!!! content which will be used:")
    console.log(qrFile.content)

    return qrFile.content;
  }
```

Now i'm loading the file from a server as octet stream (so the first if check is true and i have to load and then set the content) the content is a real Blob the first time, when i loaded it from the server: 

console output:

> IMPORTANT!!! content which will be used: main.js:6217  
> Blob {size:1996683, type: "image/png"}  
> size: 1996683 type: "image/png"  
> proto: Blob  

but the second time this method is called i have something in the content of the qrFile but it isn't a Blob...

console output

> IMPORTANT!!! content which will be used: main.js:6217  
> [object Object]

**It's pretty strange, cause the saveToDB method is returning the "new/updated" entity and i ALWAYS use the content of that entity.**

Like i wrote i tried already a lot. like make different buffers out of the first Blob and set this as content. and then after loading out of the database convert the Buffer back to a Blob but nothing worked. i have always just the object Object with which a can't really work it seems like. 

ionic info:

> cli packages: (C:\Users\#####\AppData\Roaming\npm\node_modules)
> 
>     @ionic/cli-utils  : 1.19.3
>     ionic (Ionic CLI) : 3.20.1
> 
> global packages:
> 
>     cordova (Cordova CLI) : not installed
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.9
>     Cordova Platforms  : android 7.0.0
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     Android SDK Tools : 26.1.1
>     Node              : v10.15.3
>     npm               : 6.4.1
>     OS                : Windows 10
> 
> Environment Variables:
> 
>     ANDROID_HOME : D:\android_sdk
> 
> Misc:
> 
>     backend : pro

And package.json entry for typeorm:

> "typeorm": "^0.2.5",

**Edit**:
i now activated the logging for typeORM and did some more console logs:
the update query is:

    query: UPDATE "qrfile" SET "content" = ? WHERE "id" = ? -- PARAMETERS: [{"size":1996683,"type":"image/png"},1]

and a direct query after the save on the qrFile results in:

> content: "[object Object]"

so there is a simple String with just [object Object] saved in the db?!

so one more update from my side:
created an extra method which updates the content value directly via a query:
with this method i get as db select result "content: "[object Blob]" still a string it seems. also strange is that the parameter.
to be honest i don't really like to convert the image to base64 and save it as string or something like that. i mean the doc of typeorm (https://github.com/typeorm/typeorm/blob/master/docs/entities.md) says that blob is a valid entity type - so it should work somehow.

maybe i just make a silly misstake. but i can't find any example with blob. hope someone can help

**Comment by imnotjames** [comment]
Can you include a simple way to replicate this issue? The snippets you included can't be used to attempt to replicate.  Perhaps a repository?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
