### ISSUE TITLE
timestamp and postgresql

### ISSUE THREAD

**Issue by GreyFoxRU** [typeorm/typeorm#4519]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ x ] `0.2.18`

Good day!
 
I want to work with the 'UTC' time zone using the timestamp type.  
As I planned, the date should be sending from the server to the database in the 'UTC' time zone, and vice versa, from the database it is necessary that the dates comes in the 'UTC' time zone.

Here is an example where you can reproduce the problem [test.zip](https://github.com/typeorm/typeorm/files/3451685/test.zip)

```typescript
import { Entity, PrimaryGeneratedColumn, BaseEntity, Column } from 'typeorm';

@Entity('users')
export class User extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('timestamp', { name: 'date', default: (): string => 'LOCALTIMESTAMP' })
  date?: Date;

}
```
---
```typescript
/* Postgres Driver */
import pg from 'pg';
/* TypeORM */
import { createConnection, Connection, EntityManager } from 'typeorm';
/* moment */
import moment from 'moment';
// Local
import ormconfig = require('./ormconfig');
import { User } from './entities/users.entity';

enum PgTypes {
  TIMESTAMP = 1114
}

function users(): User[] {
  return [
    User.create({
      id: '7227817A-BD1D-48A8-BFAC-DC85B4BD52F4',
      date: "2018-07-12T11:42:00.644377Z"
    }),
    User.create({
      id: '14F5DC79-9392-4129-8B09-5124F043523F'
    })
  ]
};

(async () => {
  pg.types.setTypeParser(PgTypes.TIMESTAMP, (stringValue) => moment.utc(stringValue));

  const connection: Connection = await createConnection(ormconfig);
  await connection.synchronize(true);

  await connection.transaction(async (em: EntityManager) => {
    await em.query(`ALTER DATABASE ${ormconfig.database} SET timezone TO 'UTC'`);
    await em.save(users());
  });
  const getUsers: User[] = await connection.createQueryBuilder(User, 'user')
    .getMany()
  console.log(getUsers);
})();
```
---
The time zone that is set in my operating system is GMT + 03
Despite the fact that I executed the query `ALTER DATABASE ${ormconfig.database} SET timezone TO 'UTC'`, and fact that in the logs `ormlog.log` it says that the date is transmitted 2018-07-12T11: 42: 00.644Z, if you look at the postgres logs, you can see that the sended date  
is different, in my case is 2018-07-12T14: 42: 00.644Z.  
How it can be that the difference in the logs is there? Am I doing something wrong?

**Comment by Destreyf** [comment]
@GreyFoxRU 

I just dealt with this myself, the short answer is that this is an issue caused by node-postgres, it's not specific to TypeORM but it is specific to wanting to store dates in UTC.

<detail><summary>If you'd like a more detailed explanation of what's happening, open this<summary>
Here's what's happening, step by step, when you try to insert/update dates.

1. TypeORM performs a [preparePersistentValue](https://github.com/typeorm/typeorm/blob/1047989796e441a084001570f1656d49e44a9a07/src/driver/postgres/PostgresDriver.ts#L397-L464)` to ensure that it's in a format that's compatible with the storage engine, each driver has their own version of this.
2. preparePersistentValue determines that the column is a timestamp and attempts to format as needed by calling [DateUtils.mixedDateToDate](https://github.com/typeorm/typeorm/blob/1047989796e441a084001570f1656d49e44a9a07/src/driver/postgres/PostgresDriver.ts#L418)
3. DateUtils.mixedDateToDate ensures that a Date object is returned, **_you'll notice there is an option already on it for toUtc, but this doesn't appear to be used anywhere in the code._**  Although ultimately toUtc still wouldn't solve the problem, you'll see why in a few more steps.
4. TypeORM logs the query and params and then passes them off to node-postgres (pg), a couple steps happen internally, but ultimately you end up in Query.prototype.prepare, and it calls a [map on all of the passed in values](https://github.com/brianc/node-postgres/blob/1b5f3e33c45bb6d2e2084b00840fbe58035f6db7/packages/pg/lib/query.js#L201) in order to clean them by running the [prepareValue](https://github.com/brianc/node-postgres/blob/1b5f3e33c45bb6d2e2084b00840fbe58035f6db7/packages/pg/lib/utils.js#L49-L77) function.
5. node-pg determines that the field is a [Date type](https://github.com/brianc/node-postgres/blob/1b5f3e33c45bb6d2e2084b00840fbe58035f6db7/packages/pg/lib/utils.js#L60-L64).  And proceeds to format the date into a postgres compatible string.  This is where the trouble starts, you'll also notice in there that there's a `defaults.parseInputDatesAsUTC` option, it's default `false`, i'm not sure how to change these defaults, but doing so would result in all dates being in UTC even if you wanted them to store the timezone info, this is not an acceptable compromise for my project.
6. _At this point, i actually am lost on what happens next, all i know is that eventually the `setTypeParser` functions can get called, but the string passed to them lacks any timezone information, somehow, it's as if it got truncated, i verified the result of `dateToString` should at least return a string that looks like a valid date, but alas, this is where the error happens._  Debugging an async app is actually a nightmare. (atleast for me in webstorm)
</detail>
Here's how i'm getting around it, i made a new `Column` Decorator called `UTCDateColumn` which automatically does 2 things, 1) it sets the type to 'timestmap' and the second is that it sets up the `transformer`.

```typescript
import { Column, ColumnOptions, ColumnType } from 'typeorm';
import { ColumnEmbeddedOptions } from 'typeorm/decorator/options/ColumnEmbeddedOptions';
import { ValueTransformer } from 'typeorm/decorator/options/ValueTransformer';

// Custom decorator to automatically set column type to 'timestamp' and the transformer to our UTCDateTransformer
export function UTCDateColumn(typeOrOptions?: ((type?: any) => Function) | ColumnType | (ColumnOptions & ColumnEmbeddedOptions), options?: (ColumnOptions & ColumnEmbeddedOptions)): Function {
  return function(object: Object, propertyName: string) {
    // normalize parameters
    let type: ColumnType | undefined;
    if (typeof typeOrOptions === 'string' || typeOrOptions instanceof Function) {
      type = <ColumnType>typeOrOptions || 'timestamp';
    } else if (typeOrOptions) {
      options = <ColumnOptions>typeOrOptions;
      type = typeOrOptions.type || 'timestamp';
    }
    if (!options) options = {} as ColumnOptions;
    options.transformer = UTCDateTransformer;

    return Column(<any>type, options)(object, propertyName);
  };
}

// Transformer used to make sure that everything stays happy.
export const UTCDateTransformer: ValueTransformer = {
  to(value: any): any {
    // I remove the Z because this is what causes DateUtils.mixedDateToDate to recognize that it's UTC and convert it to local time
    // by doing this, it assumes that the date MUST be in our local time, this can have some side effects if mistakenly used.
    return (typeof value !== 'string' ? (<Date>value).toISOString() : value).replace('Z', '');
  },
  from(value: any): any {
    // This is just a sanity thing, it should be coming back from the database as a date object, but just to be safe,
    // this could probably be better, but i haven't run into issues with it yet. 
    return (typeof value === 'string' ? new Date(value.indexOf('Z') !== -1 ? value : value + 'Z') : value);
  }
};
```
So to use it with your example code, it'd look like this:

```typescript
import { Entity, PrimaryGeneratedColumn, BaseEntity, Column } from 'typeorm';
import { UTCDateColumn } from './utc-date.decorator.ts';

@Entity('users')
export class User extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  // Note, you could also do: @UTCDateColumn('timestamp', {default: (): string => 'LOCALTIMESTAMP' })
  @UTCDateColumn({default: (): string => 'LOCALTIMESTAMP' })
  date?: Date;
}
```

I am using this UTC date field in several places now and am happy with the results so far.

The real magic in getting this to work is the transformers to/from.  You don't need a custom decorator or the pre-defined transformer, but because you're likely to re-use the logic i have it setup that way, here's a bare bones way to do it without the custom decoratoro.

```typescript
import { Entity, PrimaryGeneratedColumn, BaseEntity, Column } from 'typeorm';

@Entity('users')
export class User extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('timestamp', { 
    name: 'date', 
    default: (): string => 'LOCALTIMESTAMP',
    transformer: {
      to: (typeof value !== 'string' ? (<Date>value).toISOString() : value).replace('Z', ''),
      from: (typeof value === 'string' ? new Date(value.indexOf('Z') !== -1 ? value : value + 'Z') : value)
    }
  })
  date?: Date;
}
```

Hopefully this helps someone out in the future as they stumble along this, i learned a great deal about the internal workings on TypeORM, node-postgres, and even the postgres connection/data protocols.

**Comment by korniychuk** [comment]
Thank you very much for your solution, @Destreyf ! It works but not for all cases.
* I had some problems with summer and wintertime.
* It doesn't work with `returning('*')` construction, just because of a bug in TypeORM. The result of INSERT/UPDATE queries with `RETURNING *` doesn't move through `prepareHydratedValue()` and as a result value transformers don't execute for this case.

I found another solution on `pg` level without custom decorators and transformers for TypeORM. We can adjust `pg` package default configuration like next way:

```typescript
import * as pg from 'pg';

/**
 * @see https://github.com/brianc/node-postgres/issues/2141
 * Other links that can be helpful:
 *  - https://github.com/typeorm/typeorm/issues/4519
 *  - https://github.com/brianc/node-postgres/issues/1746
 *  - https://github.com/typeorm/typeorm/issues/2390
 */
pg.defaults.parseInputDatesAsUTC = true;
/**
 * @see https://github.com/brianc/node-postgres/issues/993#issuecomment-267684417
 * @see https://jdbc.postgresql.org/development/privateapi/constant-values.html to find 1114 number
 */
pg.types.setTypeParser(1114, (stringValue: string) => new Date(`${ stringValue }Z`));
```

Notice: I'm not sure that it works correctly for column types with time zones like `timestamp with time zone`.

cc @GreyFoxRU

**Comment by rstrand** [comment]
I'd use `timestamp with time zone` if possible. The postgres wiki provides a good explainer for this: https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29

**Comment by imnotjames** [comment]
Looks like this has been answered.

**Comment by neumartin** [comment]
Can I set a global timezone for PostgreSQL sessions?

**Comment by flmuel** [comment]
If thats a node-postgres issue, I still dont understand why this is not fixed...
Nevertheless, you can also use "timestamp" for saving UTC time but you have to set the node timezone variable in your environment (.env file):

`TZ=UTC`

**Comment by zlooun** [comment]
@flmuel i use transformer for this.
Just delete Z in date string and it works.
A crutch, but it works as you expect.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/50909481/229333481-026a43a5-6cf6-4ced-9a95-127cc36aece2.png">
