### ISSUE TITLE
Option to remove dashes (-) in UUID

### ISSUE THREAD

**Issue by kateile** [typeorm/typeorm#4556]
**Issue type:**

[x] question
[x] feature request

**Database system/driver:**
[X] `mysql` / `mariadb`

**TypeORM version:**
[x] `latest`

**Steps to reproduce or a small repository showing the problem:**
```ts
@Entity('apps')
export class App {
    @PrimaryGeneratedColumn('uuid')
    readonly id: string;


    @Column({transformer: new ColumnEncryptionTransformer(config.get('keys.app_secret'))})
    secret: string;
}
```
I didn't find a way to use transformer in **PrimaryGeneratedColumn** so that I can strip those dashes!  is there a simple way UUID to be saved in database without dashes?
now id are saved as **8e5365f4-3d42-4274-bafc-93b97bd6e3f2** 36 characters

what I wish is just **8e5365f43d424274bafc93b97bd6e3f2** 32 characters

**Comment by johannesschobel** [comment]
Hey @kateile , i guess you could use a `Transformer` for this.
Please see this here: https://typeorm.io/#/decorator-reference/column (and scroll a bit down).

Basically - a `Transformer` is a method that is applied when writing to the database and reading from the database. You can define 2 separate methods. In your case, this would only be required when writing to the database - simply remove all `-`..

Another option would be to use use a `BeforeInsert` hook ( https://typeorm.io/#/decorator-reference/beforeinsert )

However, in any case - i guess you would need to remove the `uuid` type, because this is propagated to the database as well (at least it is for postgres)

**Comment by kateile** [comment]
@johannesschobel thanks, I will go with `BeforeInsert `

**Comment by dhritzkiv** [comment]
To clarify something: the UUID type in Postgres is always stored as 16 bytes. The database's output format (what gets sent to the client) is always in the UUID standard form (the 36 character length string with dashes). Postgresql is very lenient about how you pass in UUIDs, however: you can pass in the standard form, in the condensed form, in all caps, etc. But at the end of the day, it's always stored the same way.

It would be nice, however, to be able to set a global option to retrieve UUIDs in the dashes-stripped 32 character form, automatically, without using transformers to provide a `from` converter.
