### ISSUE TITLE
Case of table and field names not preserved

### ISSUE THREAD

**Issue by tjme** [typeorm/typeorm#458]
Is it possible to preserve the case specified for table and field names when creating or syncing the schema (as they appear to be converted to camel case (with lower case initial letter)?

Driver: mssql

**Comment by pleerock** [comment]
you can specify custom names in decorators. e.g. `@Entity("my-table-name")` or `@Column({ name: "my-column-name" })`

**Comment by pleerock** [comment]
I hope I answered your question.

**Comment by kanatkubash** [comment]
Maybe add a field to ormconfig.json to hint column names handing?
Something like 
```javascript
{
columnHint:'snakeCase'|'camelCase'|'uppercase'|'lowercase'
}
```

**Comment by chriszrc** [comment]
Is there any way to only have custom names for query output? Like formatting the columns in json output for display?

**Comment by srishti-dev** [comment]
@pleerock my problem is not solved even after doing it this way .

**Comment by nebkat** [comment]
@srishti-dev you must specify what your problem is if you would like help.

This issue is now mostly solved using custom naming strategies (see https://github.com/tonivj5/typeorm-naming-strategies).

You can use the community [Slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) for general issues.

**Comment by RSocaG** [comment]
I have the same issue, I need to preserve the case table name cause the typeorm create a new table "student" intead of detect the table "Student" which already exist.
