### ISSUE TITLE
Very long query generated when loading relation ids of a relation that has a foreign key to itsels

### ISSUE THREAD

**Issue by eyalhakim** [typeorm/typeorm#4642]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[X] `0.2.17` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
When using `loadRelationIdAndMap` on a relation that has a foreign key to the same table, a very long recursive query is generated:

`"SELECT "product_categories_rid"."productId" AS "productId", "product_categories_rid"."productCategoryId" AS "productCategoryId" FROM "default"."product_category" "product_category" INNER JOIN "default"."products_categories" "product_categories_rid" ON ("product_categories_rid"."productId" = $1 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $2 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $3 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $4 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $5 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $6 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $7 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $8 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $9 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $10 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $11 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $12 AND "product_categories_rid"."productCategoryId" = "product_category"."id") OR ("product_categories_rid"."productId" = $13 AND 
...(~1000 times)
"product_categories_rid"."productCategoryId" = "product_category"."id") ORDER BY "product_categories_rid"."productCategoryId" ASC, "product_categories_rid"."productId" ASC"`

This also happens when using the `@Relation` decorator.

**Comment by Kononnable** [comment]
Could you provide some reproduction data? Right now we don't even know yours exact entity definition.

**Comment by eyalhakim** [comment]
Hi @Kononnable I think the info above should be enough to understand and reproduce the issue. Not sure why my specific business related data model is needed but here is the relevant snippet:

`@Entity()
export class ProductCategory {

    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: 'int', nullable: true })
    parentCategoryId: number;

    @ManyToOne(() => ProductCategory)
    @JoinColumn({ name: 'parentCategoryId' })
    parentCategory: ProductCategory;

    @ManyToMany(() => Product, product => product.categories)
    products: Product[]
}`

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
