### ISSUE TITLE
create and update time should not use node server's time

### ISSUE THREAD

**Issue by Diluka** [typeorm/typeorm#466]
this cause timezone problems.
see https://github.com/sequelize/sequelize/issues/7204

**Comment by pleerock** [comment]
they should use utc time, I'll check if they are not.

**Comment by Diluka** [comment]
also node servers' time maybe is different. use database's time is better

**Comment by jwclark** [comment]
Not sure if this is related, but I'm also having timezone issues. DB and Node are running on a system -6 from UTC. Writing and Reading the time appears to show the correct time in UTC: e.g. 2017-05-19T04:07:36.000Z

When stored in postgres w/o timezone then same date is saved(without the 'Z'). However, when stored in postgres with timezone enabled, it shows the UTC time with the local server timezone: 2017-05-19 04:07:36-06.

As mentioned before, read and writes appear to work just fine, but when I query based using on time using builder.where(someEntity.date <= queryEndDate), I have to add 6 hours to queryEndDate in order to get the correct results back. The behavior is the same whether or not I use { timezone: true } on the datetime column.

**Comment by jwclark** [comment]
Date comparison queries appear to work just fine if { localTimezone: true } is set. But not if UTC is used.

**Comment by jwclark** [comment]
As a followup, simply passing in a Date object to the query doesn't work unless localTimezone: true is specified. But passing the date in as a string in the "yyyy-mm-dd hh:mm:ss" format worked better.

**Comment by pleerock** [comment]
> it shows the UTC time with the local server timezone: 2017-05-19 04:07:36-06.

please be aware how dates in javascript work - they always give you date (including when you console.log them) in local server's time. If you want to get UTC date of it you need to use special methods in Date object. Its javascript date object specifics which you should learn to understand how to handle date problems

**Comment by pleerock** [comment]
@Diluka there is one problem with this feature request. If we make `createDate` and `updateDate` to be set by database, we have to query them from the database right after insertion because we should set `createDate` and `updateDate` values. But we don't know `createDate` and `updateDate` values because database sets them. Not sure if its a good idea to perform extra query after insertion.

**Comment by jwclark** [comment]
@pleerock - Yes, however that is not the issue here. As I stated before:

> However, when stored in postgres with timezone enabled, it shows the UTC time with the local server timezone: 2017-05-19 04:07:36-06.

In other words, the UTC time of 04:07:36 was getting stored with the INCORRECT time zone information of -06. The actual time in javascript could have been represented either by 04:07:36-00 OR 22:07:36-06. The time and timezone were mixed incorrectly.

**Comment by jwclark** [comment]
I'm still having issues related to this in postgres. If a UTC date/time is stored without timezone, e.g. 2017-04-26 00:00:00, on read(QueryBuilder.findOne()) a Date object is returned by TypeORM with the incorrect time: "2017-04-26T06:00:00.000Z". It's as if TypeORM is assuming that the date is in server time instead of UTC, and so it adds 6 hours. Should TypeORM assume that the date is UTC or server time?

**Comment by jwclark** [comment]
It looks like my issue on read was resolved a few weeks ago: https://github.com/typeorm/typeorm/commit/f810328ac04f7eb963fae24b0e07dd8023ff7b40#diff-a2a8f77fc79655011d9d2b94ebc610bd. Updating to the latest version on npm resolved the issue.

**Comment by pleerock** [comment]
I have completely refactored persistence system and how dates are generated on database side. Please try a new version (npm i typeorm@next) and let me know if your issue is not resolved in new versions too.

**Comment by jwclark** [comment]
My tests are all still passing after updating to version 0.1.2. Is that the version with your changes?

**Comment by pleerock** [comment]
no, its 0.2.0-alpha.1
