### ISSUE TITLE
Revert migrations running in reverse order

### ISSUE THREAD

**Issue by RecuencoJones** [typeorm/typeorm#4697]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.18` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I created two migrations, one on August and the other today. After running this last migration I wanted to check that the `down` would be applied correctly. However I run into the following:

Before running revert:
```
> db.migrations.find()
{ "_id" : ObjectId("5d7118c2bfc3a0f771f3ea4a"), "timestamp" : 1566560354098, "name" : "UpdateContacts1566560354098" }
{ "_id" : ObjectId("5d7118c2bfc3a0f771f3ea4b"), "timestamp" : 1567689639607, "name" : "MergeConfigs1567689639607" }
```

Running revert:
```
2 migrations are already loaded in the database.
UpdateContacts1566560354098 is the last executed migration. It was executed on Fri Aug 23 2019 13:39:14 GMT+0200 (Central European Summer Time).
Now reverting it...
Migration UpdateContacts1566560354098 has been reverted successfully.
```

After running revert:
```
> db.migrations.find()
{ "_id" : ObjectId("5d7118c2bfc3a0f771f3ea4b"), "timestamp" : 1567689639607, "name" : "MergeConfigs1567689639607" }
```

Is this a known issue of some sort? Is there any flag or anything which I might be missing?

**Comment by DimaIT** [comment]
@RecuencoJones, just checked migrations in `0.2.18` and they applied and reverted in propper order for me.

But what you described can happen in certain conditions:
If file with migration `MergeConfigs1567689639607` was deleted in filesystem, then typeorm can't revert this migration, and will revert latest present in fs, despite the contents of `migrations` table.

Please try to clean up database and try to apply and revert migrations again. If issue still present please provide more details, otherwise issue can be closed.

**Comment by RecuencoJones** [comment]
Hi @DimaIT, thanks for this explanation, I will try such steps and will come back with my feedback.

**Comment by RecuencoJones** [comment]
@DimaIT, I have just tried this in a separate environment and still observe migrations running unexpectedly in reverse order.

I created [this repository](https://github.com/RecuencoJones/typeorm-4697) to reproduce the issue.

**Comment by RecuencoJones** [comment]
I think I might have found the issue...

https://github.com/typeorm/typeorm/blob/4d2fa0774ef0a0e05407c5271ff6df190fa45dc4/src/migration/MigrationExecutor.ts#L341
![image](https://user-images.githubusercontent.com/7302877/64412034-d345a100-d08e-11e9-890d-4acea5c871e4.png)

Shouldn't migrations be sorted by timestamp instead?

**Comment by DimaIT** [comment]
@RecuencoJones, was able to reproduce issue with your repo, thanks.

Sorting by `id` instead of `timestamp` was made for a reason. Check #1315 for more details.

As I can see issue is here:
https://github.com/typeorm/typeorm/blob/4d2fa0774ef0a0e05407c5271ff6df190fa45dc4/src/migration/MigrationExecutor.ts#L299

We are loading migrations from mongo and use them as is, while mongo contains `_id` field, bot not `id`. So sorting by id is not working cause `id` is `indefined`.

**Comment by RecuencoJones** [comment]
@DimaIT, I see, if that's the case maybe we should modify the implementation of `getLatestExecutedMigration`:
https://github.com/typeorm/typeorm/blob/4d2fa0774ef0a0e05407c5271ff6df190fa45dc4/src/migration/MigrationExecutor.ts#L340

I'd suggest that, instead of sorting in JavaScript, we query the db and let it sort by ID, i.e:

```typescript
    protected async getLatestExecutedMigration(queryRunner: QueryRunner): Promise<Migration|undefined> {
        let migrations: Array<Migration>;

        if (this.connection.driver instanceof MongoDriver) {
            const mongoRunner = queryRunner as MongoQueryRunner;
            migrations = await mongoRunner.databaseConnection
            .db(this.connection.driver.database!)
            .collection(this.migrationsTableName)
            .find()
            .sort("_id", -1)
            .toArray();
        } else {
            const migrationsRaw: ObjectLiteral[] = await this.connection.manager
            .createQueryBuilder(queryRunner)
            .select()
            .from(this.migrationsTable, this.migrationsTableName)
            .orderBy("id", "DESC")
            .getRawMany();
            migrations = migrationsRaw.map(migrationRaw => {
                return new Migration(parseInt(migrationRaw["id"]), parseInt(migrationRaw["timestamp"]), migrationRaw["name"]);
            });
        }

        return migrations.length > 0 ? migrations[0] : undefined;
    }
```

I have tried this particular implementation and all tests seem to be passing

**Comment by DimaIT** [comment]
@RecuencoJones, yes, this should fix current issue.
But I see two issues with such solution:

1. One extra call to database added. I suppose it's not critical, but not needed.
2. Current code is quite simple and working fine for all databases except of mongo. I think it's better not to change it much, if possible.

My proposal is to fix `loadExecutedMigrations` for mongo. And keep `getLatestExecutedMigration` unchanged.
https://github.com/typeorm/typeorm/blob/4d2fa0774ef0a0e05407c5271ff6df190fa45dc4/src/migration/MigrationExecutor.ts#L299

We just need to wrap database response data into `Migration` class mapping `_id` properly.

```typescript
    protected async loadExecutedMigrations(queryRunner: QueryRunner): Promise<Migration[]> {
        if (this.connection.driver instanceof MongoDriver) {
            const mongoRunner = queryRunner as MongoQueryRunner;
            const migrationsRaw = await mongoRunner.databaseConnection.db(this.connection.driver.database!)
.               .collection(this.migrationsTableName)
                .find()
                .toArray();
            return migrationsRaw.map(migrationRaw => {
                return new Migration(parseInt(migrationRaw["_id"]), parseInt(migrationRaw["timestamp"]), migrationRaw["name"]);
            });
        } else {
            const migrationsRaw: ObjectLiteral[] = await this.connection.manager
            .createQueryBuilder(queryRunner)
            .select()
            .from(this.migrationsTable, this.migrationsTableName)
            .getRawMany();
            return migrationsRaw.map(migrationRaw => {
                return new Migration(parseInt(migrationRaw["id"]), parseInt(migrationRaw["timestamp"]), migrationRaw["name"]);
            });
        }
    }
```

@RecuencoJones if you like my code, it would super nice if you update your pull request with it, since you've already created it.

**Comment by RecuencoJones** [comment]
@DimaIT, I actually thought about the extra DB call and spent some time looking for different approaches from JS side. 

There's just one problem with that particular implementation, MongoDB uses ObjectIDs which cannot be trivially parsed to number nor be sorted as such.

This StackOverflow answer provides a bit more context on how ObjectIDs are assigned: https://stackoverflow.com/a/12100023

**Comment by DimaIT** [comment]
@RecuencoJones, thanks for clarification. 
Now your solution looks much more reasonable to me. I think it's makes sense to add comment describing situation with mongo ids to your code.

> We could probably try to parse the timestamp or the incremental part and sort by it, but not sure if that's the right way to fix this. 

That may work, but seems kind of tricky. 

I have couple more ideas: 
1. We can sort migrations by `id` in `loadExecutedMigrations`. Than `getLatestExecutedMigration` needs just peek the last one.
2. Or if we want to keep logic related to relational databases untouched, than we can only sort migrations for mongo by `_id` in reverse order. `getLatestExecutedMigration` will pick the first migration, wich will be the latest one. I think it's the simpliest fix that can be made.
