### ISSUE TITLE
ManyToMany without Junction Table

### ISSUE THREAD

**Issue by RShadowhand** [typeorm/typeorm#4748]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I've got two tables: `users`, and `projects`. There's `ManyToMany` relation, but I don't want to use a junction table. Both tables have a `domain` column:

Users
|-------
id
username
pass
domain

Projects
|--------
id
name
path
domain

How would I go about using `@ManyToMany` to add relations ***WITHOUT*** using a junction table?

EDIT: I essentially want `... FROM users u LEFT JOIN projects p ON u.domain = p.domain` instead of `... FROM users u LEFT JOIN users_projects_projects up ON u.id = up.id LEFT JOIN ...`

**Comment by jbjhjm** [comment]
It's not exactly a ManyToMany relation I think.
To me it looks like a User <ManyToOne> Domain <OneToMany> Relation, but you want domain to be string-based instead of being a full entity. I don't think TypeORM provides this out of the box so you'd need to build your joins manually.
Or think about adding a table for domains so that you have a domainEntity which links a list of users to a list of projects.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
