### ISSUE TITLE
How to use @CreateDateColumn and @UpDateColumn in mssql

### ISSUE THREAD

**Issue by tanapolTan** [typeorm/typeorm#4838]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.19` (or put your version here)

```  @PrimaryGeneratedColumn() id: number;
  @CreateDateColumn({ name: 'created_at' }) 'created_at': Date;
  @UpdateDateColumn({ name: 'updated_at' }) 'updated_at': Date;
```

How to use @CreateDateColumn and @UpDateColumn in mssql
it was not update date correctly.

**Comment by silentroach** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/entities.md#special-columns

**Comment by tanapolTan** [comment]
> https://github.com/typeorm/typeorm/blob/master/docs/entities.md#special-columns

i already read this document but it is not work.

```
@Entity('purchases')
export class Purchase {

  @PrimaryGeneratedColumn() id: number;
  @CreateDateColumn({ name: 'created_at' }) 'created_at': Date;
  @UpdateDateColumn({ name: 'updated_at' }) 'updated_at': Date;
```

**Comment by tanapolTan** [comment]
now i try to typeorm-next@1.0.0 it doesn't work too.

**Comment by karlos1337** [comment]
Was searching about using `@Column({ default: new Date()})` in ms sql server but have found this issue and using `@CreateDateColumn() created?: Date;` works as charm.
![imagen](https://user-images.githubusercontent.com/1143362/66044124-28a38f80-e521-11e9-8ccb-92cc241367e7.png)

**Comment by leonardootoni** [comment]
Definitely this problem is also happening on Postgresql using typeorm 0.2.19.
Created a table having two columns (created_at and updated_at) through migrations as follows:

`{
            name: 'created_at',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'updated_at',
            type: 'timestamp',
            isNullable: true,
          },`

And defined my Entity class as:

`
enum Blocked {
    true = 'true',
    false = 'false',
  }

@Entity({ name: 'users' })
@Unique(['email'])
export default class User extends BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @Column({ length: 50 })
  name!: string;

  @Column({ length: 50 })
  email!: string;

  @Column({ length: 150 })
  hash!: string;

  @Column({ type: 'enum', enum: Blocked, default: Blocked.false })
  blocked!: boolean;

  @CreateDateColumn({ name: 'created_at'})
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at'})
  UpdatedAt!: Date;

  @VersionColumn()
  version!: number;

}

`
trying to save an User object, the following query runs:

`
query: START TRANSACTION
query: INSERT INTO "users"("name", "email", "hash", "blocked", "created_at", "updated_at", "version") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, 1) RETURNING "id", "blocked", "created_at", "updated_at", "version" -- PARAMETERS: ["someUserName","someEmail@email.com","somePassword"]
query failed: INSERT INTO "users"("name", "email", "hash", "blocked", "created_at", "updated_at", "version") VALUES ($1, $2, $3, DEFAULT, DEFAULT, DEFAULT, 1) RETURNING "id", "blocked", "created_at", "updated_at", "version" -- PARAMETERS: ["someUserName","someEmail@email.com","somePassword"]
error: error: null value in column "created_at" violates not-null constraint
    at Connection.parseE (/home/wallup1/dev/tests/typscript_test/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/home/wallup1/dev/tests/typscript_test/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/home/wallup1/dev/tests/typscript_test/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:209:13)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:286:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 246,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (1, someUserName, someEmail@email.com, somePassword, f, null, null, 1).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'users',
  column: 'created_at',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '2042',
  routine: 'ExecConstraints'
}
query: ROLLBACK
[2019-10-09T13:46:06.410] [ERROR] QueryFailedError: null value in column "created_at" violates not-null constraint
`

Trying to read more regards to this issue, I found [here](https://github.com/typeorm/typeorm/issues/2080#issuecomment-386788009) where @pleerock informs that is necessary to set a default value to these columns. My understanding is that it is necessary to set in the database directly. In fact, doing this the issue has a work around. However, It means that the Database will manage for you the generation of the date. Not the ORM. 

This way, I am concluding that there is a bug regards to the decorators @CreateDateColumn and @UpdateDateColumn that not set a date automatically during the insert or update operations.

P.S: I realised that @VersionColumn() decorator is working fine.

**Comment by leonardootoni** [comment]
Just to say, I found a work around that worked fine but is far to be elegant. I changed the decorators **@CreateDateColumn** and **@UpdateDateColumn** to **@Column**. However, I created two listeners

```
@BeforeInsert()
  private setCreateDate(): void {
    this.createdAt = new Date();
  }

  @BeforeUpdate()
  public setUpdateDate(): void {
    this.updatedAt = new Date();
  }
```
This worked fine as a work around.

**Comment by tanapolTan** [comment]
thankyou, i will try update typeorm again next month.

**Comment by leonardootoni** [comment]
Just to put more information on this thread, I checked that actually the bug is present with @CreateDateColumn Decorator. I changed my abstract class as down below and the update operations set  **CURRENT_TIMESTAMP** automatically. So, this operation is working fine.
`
import {
  VersionColumn, BeforeInsert, BeforeUpdate, UpdateDateColumn, Column,
} from 'typeorm';
import { validateOrReject } from 'class-validator';

export default abstract class AbstractEntity {
  @Column({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;

  @VersionColumn()
  private version!: number;

  @BeforeInsert()
  private beforeInsert(): void {
    // Workaround to solve a bug from 0.2.19 version
    this.createdAt = new Date();
  }

  @BeforeInsert()
  @BeforeUpdate()
  private async validateEntity(): Promise<void> {
    await validateOrReject(this);
  }
}
`

`query: UPDATE "users" SET "name" = $2, "email" = $3, "blocked" = $4, "version" = "version" + 1, "updated_at" = CURRENT_TIMESTAMP WHERE "id" IN ($1) -- PARAMETERS: [1,"Leonardo Otoni de Assis","leonardootoni@gmail.com","true"]`

However, the @CreateDateColumn decorator does not set the **CURRENT_TIMESTAMP** automatically when persisting a new record, unfortunately. I tried different configurations with this decorator without any success. P.S: I discovered this issue because I set the create_at column as not null in the database.

**Comment by basicBrogrammer** [comment]
I'm having the same issue with postgres. I think we need some docs around how to use it properly

**Comment by tarasrudyy** [comment]
Looks like this is why https://github.com/typeorm/typeorm/issues/2020

https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#020

```
now created date and update date columns is set on the database level, not by ORM anymore (e.g. using CURRENT_TIMESTAMP as a default value)
```

**Comment by maatthc** [comment]
It works fine to me (using Mysql) if I don't define a type for the column:

`@PrimaryGeneratedColumn()
  uid: number

  @CreateDateColumn()
  updateDate

  @Column()
  titleText: string`

**Comment by lucafaggianelli** [comment]
you can use them like this (change `type` as per your preference):
```ts
@CreateDateColumn({ type: 'timestamp' })
createdAt: Date;

@UpdateDateColumn({ type: 'timestamp' })
updatedAt: Date;
```

**Comment by naddison36** [comment]
Thanks @lucafaggianelli.
Setting the `type` to `timestamp` worked for me as well against a Postgres database

**Comment by dan-klasson** [comment]
`CreateDateColumn` and `UpdateDateColumn` gave me the exact same migration in MySQL.

I ended up doing this instead:

```javascript
  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
  createdAt: Date;

  @Column({ type: 'timestamp', onUpdate: 'CURRENT_TIMESTAMP', nullable: true })
  updatedAt: Date
```
