### ISSUE TITLE
getSql() returns query with parameters not substituted

### ISSUE THREAD

**Issue by dankochetov** [typeorm/typeorm#4855]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`

**Steps to reproduce or a small repository showing the problem:**

I'm trying to use PostgreSQL `WITH` syntax. As I understand, there's no built-in functionality in TypeORM for this (at least googling didn't get me anywhere), so I'm trying to build a raw query. Part of this raw query is a TypeORM-generated INSERT query. So, the code looks like this:

```ts
const insertQuery = manager.createQueryBuilder(Entity, 'entity')
  .insert()
  .values(works)
  .onConflict(`DO NOTHING`)
  .returning('status')
  .getSql();

await manager.query(`
  WITH "rows" AS (
    ${insertQuery}
  ) SELECT count(*) as "count", "status" FROM "rows" GROUP BY "status"
`);
```

When I'm trying to execute this code, this is the resulting query I'm getting from the logs:
```sql
WITH "rows" AS (
INSERT INTO "xxx"("field1", "field2", "field3", "field4", "field5", "field6", "field7", "field8", "field9", "field10", "field11") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, DEFAULT, DEFAULT) ON CONFLICT DO NOTHING RETURNING status
) SELECT count(*) as "count", "status" FROM "rows" GROUP BY "status"
```
Which fails with an error:
```
there is no parameter $1
```
As you can see, query returned by `getSql()` contains not substituted parameters. Is there a way to get a query with parameters properly substituted? Not sure if it's me or the libary doing something wrong.

**Comment by garlou** [comment]
Did you find a solution for this? I'm having the same problem

**Comment by dankochetov** [comment]
@garlou 
No, I'm currently using the raw query instead.

**Comment by garlou** [comment]
I kind of found a workaround but not 100% sure about it: 
```
const string = query.getSql();
const count = (string.match(/\$\d?/g) || []).length;
const params = filter ? Object.values(filter).splice(0, count) : [];
await getConnection().query(
  `SELECT * FROM (${string}) t ORDER BY RANDOM() LIMIT ${take};`,
  params
);
```

Hope it helps

**Comment by JClackett** [comment]
Also getting the same thing where using getSql() 
It seems to not be passing the parameters

```js
    const userQuery = User.getRepository()
      .createQueryBuilder("user")

    const requestQuery = Document.createQueryBuilder("document")
      .where("document.someId = :someId", { someId })
      .select("document.userId")
      .getSql()

    return userQuery.andWhere("user.id NOT IN (" + requestQuery + ")").getMany()
```

end of the sql query
```
..."document" WHERE "document"."someId" = $1)',
  parameters: []
}
```

QueryFailedError: there is no parameter $1

**Comment by JustBeYou** [comment]
I see that no one solved this, so I dived a little bit in the code and I think the problem is here.
https://github.com/typeorm/typeorm/blob/b99b4ad869cbf482ae9a5558acf64084157cbedd/src/query-builder/QueryBuilder.ts#L407

It simply returns the first element returned by `getQueryAndParameters`. 

Could anyone point me to where are the parameters replaced?

**Comment by dankochetov** [comment]
@JustBeYou yes, this is done by the driver - in my case, by `pg`. So perhaps the solution here would be to allow extracting the variables used in a query to be able to add them to the final query later.

**Comment by juanfernandoe** [comment]
In my opinion, there should be a way to get the final query to be able to execute it manually. You'll be able to do optimisations on the database side or debug if something is wrong.

**Comment by JustBeYou** [comment]
Could a maintainer tell us if a third party solution would be preferred (using a SQL library to obtain the prepared query) or a custom handmade one? After that, we could do a PR and fix it as it got really old.

**Comment by imnotjames** [comment]
To the initial request - the get sql just returns the query string.  There is no such thing as a query that we create with substituted parameters.  That's because we never substitute them in nearly every driver - the server doesn't exactly, either.  The variables are sent separately from the query and the server uses them after it has parsed the query.

That's how prepared statements work.  A nice stack overflow response with more info: https://stackoverflow.com/questions/8263371/how-can-prepared-statements-protect-from-sql-injection-attacks

If you manually replace the parameters with strings like in the code snippets included here you are opening yourself up to SQL injection & exploitation.

I'm going to hide those examples as they are very, very unsafe to use.

What you want is `getQueryAndParameters()` & to pass the parameters to your queries as the values of a prepared statement.

I think it bears explicitly saying: There will not be a function in TypeORM that will emit a SQL statement with the parameters replaced BECAUSE this would open you up to SQL injection and would be full of edge cases, bugs, and security issues from day one.

If you believe I misunderstood, though, let's chat on the typeorm slack :) [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) !

**Comment by juanfernandoe** [comment]
Hi @imnotjames,

I understand your point but then what would be the way to get the final sentence which
is going to the database server in order to be able to optimize/debug the final SQL with real values, not placeholders?

**Comment by imnotjames** [comment]
The final SQL that is sent to the database can be retrieved with `getSQL`.  If there are differences between the two that's a bit of a bug - but generally they should be the same.

What is sent to the database server are the placeholders in one packet, and a separate packet with the parameters.  That's a bit of a simplification, but the sentiment remains - there is no actual query with the placeholders replaced. It does not exist in typeorm or in the client.

In most cases on the server it also does not exist.  Most servers do not try to execute the SQL directly.  They parse it and craft and abstract syntax tree and when they hit a parameter location it looks up the parameter value we sent.

If you want to execute the code directly it highly depends on the way you're connecting to the server.  For example, datagrip supports these parameters & will prompt you to give it the appropriate values to send along with the parameterized query.

**Comment by imnotjames** [comment]
And yes - in some cases the values used in the query - not just columns - could affect the query execution planner and the performance of the query.

While technically we could do a string replace of the parameters to include the values there's two reasons why we shouldn't -

1. It would encourage people to use an inherently unsafe attempt to create a representation for debugging in ways that would open them up to SQL injection
2. It won't actually give you exactly what's sent to the server anyway and could actually give you incorrect query planner results

**Comment by Lardpower** [comment]
@gkbrk7 , thank you for this workaround! It works even when using the nested queries via getQuery(), just need to call setParameter or setParameters to the top-level query, not the nested one (where these parameters are used).
