### ISSUE TITLE
onUpdate: 'CASCADE' doesn't work on many-to-many relation

### ISSUE THREAD

**Issue by stepanh** [typeorm/typeorm#4980]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[x] `0.2.20`

**Steps to reproduce or a small repository showing the problem:**

`onUpdate: 'CASCADE',` works well on `many-to-one` relations, however, on `many-to-many` it seems to have no effect.
```ts
export const SampleEntity = new EntitySchema<Sample>({
  name: 'sample',
  columns: {
    ...BaseColumns,
    id: {
      type: String,
      primary: true,
    },
  },
  relations: {
    company: {
      type: 'many-to-one',
      target: 'company',
      onUpdate: 'CASCADE', // works, foreign key shows "ON UPDATE CASCADE"
    },
    owners: {
      type: 'many-to-many',
      target: 'user',
      joinTable: true,
      cascade: true,
      onUpdate: 'CASCADE', // doesn't work, junction table foreign key shows "ON UPDATE NO ACTION"
    },
  }
});

```

**Comment by michaelbazos** [comment]
Encountered the same issue.

```ts
  @JoinTable()
  @ManyToMany(type => Employee, {
    onUpdate: 'CASCADE',        // query log shows "ON UPDATE NO ACTION" no matter the value
    onDelete: 'CASCADE'          // property is correctly picked up
  })
  employees: Employee[];
```

**Comment by DiCrEn** [comment]
Same here with mysql too

**Comment by AndresSp** [comment]
Same here... Someone could attend this?

**Comment by fan-tom** [comment]
Is this because of here https://github.com/typeorm/typeorm/blob/master/src/metadata-builder/JunctionEntityMetadataBuilder.ts#L146
`onUpdate: relation.unUpdate || 'CASCADE'` is missed?

**Comment by fan-tom** [comment]
I just tried to fix this issue, but realized that currently when you set `onDelete` option in ManyToMany decorator it affects both sides of relation (applied to both created foreign keys from junction table to entity tables), which is nonsense for me, because when you use `OneToOne` and `ManyToOne` decorators, you set on delete / on update actions for foreign keys pointing to OPPOSITE entity, not to entity you use them in. Seems that it is because in that cases only one foreign key is created and so relation options on both sides must be the same, so we can just take one of them, but why then both `OneToMany` and `ManyToOne` allow to set relation properties?

**Comment by winay39** [comment]
I am facing the same problem. Please have a look at this asap :)

**Comment by Cris21395** [comment]
I am also dealing with this problem. I have used the approach proposed by @fan-tom and works well. I think this feature should be added in the next release.

**Comment by dneelapareddy** [comment]
Any update on this fix?

**Comment by hakimio** [comment]
@dneelapareddy see https://github.com/typeorm/typeorm/pull/7105

**Comment by dneelapareddy** [comment]
@hakimio Thanks for the response, but I am looking at `ON CASCADE UPDATE` for `manyTomany` relation
