### ISSUE TITLE
migrations:generate : Incorrect column type comparison if the column is enum. (should not be lowercase for a custom name)

### ISSUE THREAD

**Issue by korniychuk** [typeorm/typeorm#5000]
**Issue type:**

[ ] question
[x ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.20` (or put your version here)

**Description:**

Enum's with a custom name in Pascal Case (`EExchangeCode` in my example) handled incorrectly by the `migration:generate`.  

**Steps to reproduce or a small repository showing the problem:**

I prepared [a repository](https://github.com/korniychuk/typeorm-migraion-enum-bug-demo) to demonstrate the problem with better description in `README.md` (with screenshots).

```bash
# preparation
git clone git@github.com:korniychuk/typeorm-migraion-enum-bug-demo.git
cd typeorm-migraion-enum-bug-demo
npm install
npm run db:docker:dev   # requires docker and docker-compose
npm run migrations:run

# demo of the problem
npm run migrations:diff test
```

**Comment by zaro** [comment]
Same here. The core of the problem is that when migration is generated  this is the comparison to detect change:

```js
                    return tableColumn.name === column.databaseName
                        && tableColumn.type === this.connection.driver.normalizeType(column)
                        && tableColumn.isNullable === column.isNullable
                        && tableColumn.isUnique === this.connection.driver.normalizeIsUnique(column);
```

and more specifically `tableColumn.type === this.connection.driver.normalizeType(column)`
`tableColumn.type` will be whatever the enum type name is, and `this.connection.driver.normalizeType(column)` will always be simply enum.

I think this is Postgres specific bug, as postgres doesn't have column type enum, but instead creates a new column type for each enum.

**Comment by korniychuk** [comment]
This issue looks like related https://github.com/typeorm/typeorm/issues/5421
