### ISSUE TITLE
Missing import/export in 0.1.0-alpha.3

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typeorm/typeorm#501]
Hello
After installing the 0.1.0-alpha.3 I've noticed I cannot build the project anymore.
Looks like export is missing in find-options/JoinOptions and import of JoinOptions is missing in FindOneOptions

The error says:
`node_modules/typeorm/find-options/FindOneOptions.d.ts(12,12): error TS2304: Cannot find name 'JoinOptions'.`

**Comment by booradleys** [comment]
When i do import { FindOneOptions } from "typeorm";

Class FindOneOptions imported is into: node_modules\typeorm\driver\mongodb\typings.d.ts
But this should be found into node_modules\typeorm\find-options\FindOneOptions.d.ts

I don't know if it's because of this missing JoinOptions.

**Comment by bartlomiej-korpus** [comment]
Looks like there is a name conflict.

**Comment by alfaproject** [comment]
I had to rollback because of this, but I actually need the new locking stuff for my next release. Thank you for fixing!

**Comment by auser** [comment]
+1 @alfaproject I _hate_ to use the +1, but in this case, I can't say it any better.

**Comment by infedelcastro** [comment]
This was fixed by [this commit](https://github.com/typeorm/typeorm/commit/e7d2f4f302fb10a093d9a232f74d8f14857c7ef7) but there hasn't been a new alpha build published to npm yet. When can we expect an update to get published to NPM?

**Comment by infedelcastro** [comment]
If you are like me and need to get this package working in a CI environment where packages are downloaded every build, you can fix the missing import, then create a .tar.gz archive of the typeorm folder in node_modules and point your package.json at that tar.gz file instead of specifying a version number. I included the tar.gz file I used for if you don't know how/can't make one yourself.
[typeorm.tar.gz](https://github.com/typeorm/typeorm/files/1050711/typeorm.tar.gz)

**Comment by eyalhakim** [comment]
@infedelcastro or better yet, simply run `npm install https://github.com/typeorm/typeorm/files/1050711/typeorm.tar.gz --save`

**Comment by pleerock** [comment]
fix is published in `typeorm@0.1.0-alpha.4`
