### ISSUE TITLE
TypeORM changes native query and loses parameters

### ISSUE THREAD

**Issue by WeekendMan** [typeorm/typeorm#5058]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Why this
```ts
getConnection().query('DROP TABLE IF EXISTS public.user CASCADE');
```
executes this
```SQL
'TRUNCATE TABLE "public"."user"'
```
???

Query was taken from error returned by TypeORM. The error is thrown when there is no "user" table. I've got service function in dev environment that removes all tables to let TypeORM create them from the very start, execute migrations, etc. "IF EXISTS" should solve the case, but as I can see DROP becomes to TRUNCATE and CASCADE is lost.
Correct me if I'm wrong, the .query method should execute exactly the query that was given in.

If that's an CASCADE side effect, take a look at the first comment, there is the further issue.

```ts
QueryFailedError {
    message: 'relation "public.user" does not exist',
    name: 'QueryFailedError',
    length: 109,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'namespace.c',
    line: '421',
    routine: 'RangeVarGetRelidExtended',
    query: 'TRUNCATE TABLE "public"."user"',
    parameters: []
}

**Comment by WeekendMan** [comment]
Also
Table B depends on table A.
```ts
await connection.query(`TRUNCATE TABLE public.b CASCADE;`);
```
> Error: 'Table "B" references "A".'
Now
```ts
await connection.query(`TRUNCATE TABLE public.a CASCADE;`);
```
> Error: 'Table "B" references "A".'
What am I doing wrong here?

**Comment by imnotjames** [comment]
Cannot replicate.

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
