### ISSUE TITLE
Add a subdocument to an Object field

### ISSUE THREAD

**Issue by taksumaki** [typeorm/typeorm#5092]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[x] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
I want to publish subdocuments in a field called "Comments" but I don't know how to do it with typeorm.

For example:
A **publication is published but a user wants to comment**, the publications have the following **fields**:

```
{
    "title": "title",
    "author": "author",
    "comments": [
                {
                  "author": "author",
                  "content": "content 1",
                },{
                  "author": "author",
                  "content": "content 2",
                }, //More comments stored.
                ]
}
```
I want to **store all the comments in that "Comments" field of object type**.

**How can I do it?**

**Comment by taksumaki** [comment]
Is this repository abandoned or because they do not respond to any issue?

**Comment by d337** [comment]
First of all, I guess there are only 3 - 4 full-time working authors of this amazing tool and that's why it's not abandoned yet.

Now, the TypeORM is such a wonderful tool for Relational Database. MongoDB is something which was not aimed at TypeORM in the first vision. That's the main reason why it has a lower interest in MongoDB.

[You can look into this amazing article if you want to dig deeper](https://medium.com/articode/typeorm-mongodb-review-8855903228b1)

P.S.: If you're still in the initial phase then use 
1. [For only TS use Typegoose](https://github.com/typegoose/typegoose)
2. [For only JS use Mongoose](https://github.com/Automattic/mongoose)

**Comment by rustamwin** [comment]
try this:
```js
entity.comments = [...entity.comments, newComment];
```

**Comment by rustamwin** [comment]
@taksumaki Did you resolve your issue?
