### ISSUE TITLE
can't create composite primary key

### ISSUE THREAD

**Issue by elgreatly** [typeorm/typeorm#530]
i want to create composite primary key to match my database these two columns as a foreign key then when i add @PrimaryColumn() on these fields it give me error because these fields won't be unique but it will be unique together 

then i want to create composite primary key to void this exception

**Comment by pleerock** [comment]
you need to create index which indicates that they are unique in pair, like this:

```ts
@Entity()
@Index(["firstColumn", "secondColumn"], { unique: true })
export class Category
```

See [example here](https://github.com/pleerock/typeorm/blob/ad2bc865edb20fa1624b7aa3a92f20b03937614d/test/functional/relations/multiple-primary-keys/multiple-primary-keys-many-to-many/entity/Category.ts#L11-L11).

**Comment by pleerock** [comment]
Did I answer your question?

**Comment by pleerock** [comment]
I guess yes.

**Comment by ShadabFaiz** [comment]
Just for curiosity, This can also be one of the solution:
@Entity()
export class Category {
   @PrimaryColumn("int")
      firstColumn: int;
   @PrimaryColumn("int")
      secondColumn: int;
}
So does either of the solution have any benefits over one another?

**Comment by pleerock** [comment]
@ShadabFaiz this is different. Primary keys are not equal to unique key.

**Comment by faizan1219** [comment]
`
@Entity('association')
@Index(['id1', 'id2'], {unique: true})
export class Association {
  
  @PrimaryColumn()
  id: number;
  
  @Column()
  id1: number;

  @Column()
  id2: number;
  
}
`
i did this to create a composite key... i was successful... but problem happens when i delete some entries and add those entries again it gives me the following error....

`could not execute statement due to a constraint failure (19 UNIQUE constraint failed: cattle_group_cattle_association.cattleGroupId, cattle_group_cattle_association.cattleId)`

i am using deleteQueryBuilder to delete the entry:

`this.associationRepository.createQueryBuilder()
.delete()
.where('id1 IN (:ids)', {:ids})
.execute();`

tell me where i'm going wrong...

**Comment by ShadabFaiz** [comment]
check out [doc]( https://github.com/typeorm/typeorm/blob/master/docs/relations.md)

**Comment by joseSignot** [comment]
@faizan1219  how are you deleting? Probably there is an issue there, are you doing it through typeorm or through mysql?
