### ISSUE TITLE
Polymorphic Relationship

### ISSUE THREAD

**Issue by shirshak55** [typeorm/typeorm#5331]
**Issue type:**

[ ] question
[ ] bug report
[x ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[x ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

Hmm is there any chance for polymorphic relationship. Other Orm like Eloquent, Rails active model etc already supports it.

**Comment by bashleigh** [comment]
I've been implementing a repository which handles polymorphic children and polymorphic parents. I was going to open source it but if I'm honest, I would rather implement it into typeorm! 

```typescript
@Entity()
export class AdvertEntity {

  @PolymorphicParent(() => [UserEntity, MerchantEntity])
  owner: UserEntity | MerchantEntity;

}

@Entity()
export class UserEntity {

  @PolymorphicChildren(() => AdvertEntity)
  adverts: AdvertEntity[];

}
```

These are the available options for the above decorators

```typescript
export interface PolymorphicChildrenDecoratorOptionsInterface {
  primaryColumn?: string;
  hasMany?: boolean;
  cascade?: boolean;
  eager?: boolean;
  deleteBeforeUpdate?: boolean;
}

export interface PolymorphicParentDecoratorOptionsInterface {
  deleteBeforeUpdate?: boolean;
  primaryColumn?: string;
  hasMany?: boolean;
  cascade?: boolean;
  eager?: boolean;
}
```

A downside is I'm not currently using a reverse relationship check?

I've implemented this in a way outside of typeORM so I've just made an abstract repository that handles hydrating on {findOne, find} and saving etc. I'd love to implement this for typeORM! When I'm 100% happy with it, I'll create a repo with it on github :) 

I did however start writing a medium post about it https://medium.com/p/96ad63cb8d0b/edit
I've since reimplemented this entirely although some of the basic logic is the same! 

I've implemented this so you can really customise it! You can have many different parents, many different children AND! Singular + array returns so you can have a parent of 2 types yet return one and the reverse for children. There is no overall difference for how the decorators are handled other than the default values for the options. 

There's only one thing holding me back at the moment and that's whether to implement a race promise for singular relations or find all and determine which to return as we'd only require one entity? Not sure what decision to make! Not sure if to throw an exception if 2 entities are found? Or even just bypass the typing and return an array instead of 1 entity but I don't want to do that!

**Comment by shirshak55** [comment]
@bashleigh i wish it would be like active record /  eloquent style. But it looks like new features are not being added :(
There is bookself which do support polymorphic relationship.
https://github.com/bookshelf/bookshelf

**Comment by Perf** [comment]
hey @bashleigh 
that's an awesome addition to TypeOrm!
Could you please upload these sources somewhere? I am looking for a proper polymorphic relationship implementation in TypeOrm... and your's seems to be the most proper one!

**Comment by bashleigh** [comment]
@Perf I made it public :) https://github.com/bashleigh/typeorm-polymorphic 

We need to colab on this soon!

**Comment by bashleigh** [comment]
I've added my source to npm as `typeorm-polymorphic` if anyone is interested

**Comment by shirshak55** [comment]
I am closing this as @bashleigh solution fixes it.

**Comment by onichandame** [comment]
It is great that a 3rd party package solves the problem. But polymorphic relation is close to the core functions of an ORM in my opinion, would it make sense to merge this function into typeorm itself?

**Comment by bashleigh** [comment]
@onichandame I have suggested it, I would much rather it be apart of ORM than a package myself maintains as I can't dedicate as much time to it I'm affraid. Plus I don't use typeorm as often so I don't get to maintain it sneakily!
