### ISSUE TITLE
@CreateDateColumn() do not set new Date automatically 

### ISSUE THREAD

**Issue by leonardootoni** [typeorm/typeorm#5374]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[X] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[X] `0.2.22`

**Steps to reproduce or a small repository showing the problem:**
All my tables defined in Postgres database have the auditing columns "created_at" , "updated_at" and "version". The created_at and version are by default, set as "NOT NULL".

For some reason, the ORM by default is not setting a new date when inserting a new record, even with the @CreateDateColumn() decorator declared. However, everything works fine regards to the version property with the @VersionColumn() decorator. Both are not null in the Database.

I am using a workaround with @BeforeInsert() to set a new Date. However, it is not elegant at all.

My column declaration:
```
  @CreateDateColumn()
  @Column({ name: 'created_at' })
  createdAt!: Date;

  @UpdateDateColumn()
  @Column({ name: 'updated_at' })
  updatedAt!: Date;

  @VersionColumn()
  @Column()
  private version!: number;
```
Down below, the log the shows evidence that the ORM is not setting the date automatically:
```
query: START TRANSACTION
query: INSERT INTO "contacts"("type", "name", "email", "website", "phone1", "phone1_ext", "phone2", "phone2_ext", "address", "address_compl", "city", "province", "postal_code", "country", "created_at", "updated_at", "version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, DEFAULT, DEFAULT, DEFAULT) RETURNING "id" -- PARAMETERS: ["P","Leonardo","","","6479154312","","34535435345","a","80, Industry St.","Suite 100","Toronto","ON","M9V5E3","CA"]
query failed: INSERT INTO "contacts"("type", "name", "email", "website", "phone1", "phone1_ext", "phone2", "phone2_ext", "address", "address_compl", "city", "province", "postal_code", "country", "created_at", "updated_at", "version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, DEFAULT, DEFAULT, DEFAULT) RETURNING "id" -- PARAMETERS: ["P","Leonardo","","","6479154312","","34535435345","a","80, Industry St.","Suite 100","Toronto","ON","M9V5E3","CA"]
error: error: null value in column "created_at" violates not-null constraint
    at Connection.parseE (/home/wallup1/dev/wallupcms/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/home/wallup1/dev/wallupcms/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/home/wallup1/dev/wallupcms/node_modules/pg/lib/connection.js:123:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 301,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (1, P, Leonardo, , , 6479154312, , 34535435345, a, 80, Industry St., Suite 100, Toronto, ON, M9V5E3, CA, null, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'contacts',
  column: 'created_at',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '2042',
  routine: 'ExecConstraints'
}
```
More details:
```
[2020-01-17T19:11:00.802] [DEBUG] ContactModel.ts QueryFailedError: null value in column "created_at" violates not-null constraint
    at new QueryFailedError (/home/wallup1/dev/wallupcms/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/home/wallup1/dev/wallupcms/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/home/wallup1/dev/wallupcms/node_modules/pg/lib/query.js:145:17)
    at Connection.connectedErrorMessageHandler (/home/wallup1/dev/wallupcms/node_modules/pg/lib/client.js:214:17)
    at Connection.emit (events.js:210:5)
    at Connection.EventEmitter.emit (domain.js:476:20)
    at Socket.<anonymous> (/home/wallup1/dev/wallupcms/node_modules/pg/lib/connection.js:128:12)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12) {
  message: 'null value in column "created_at" violates not-null constraint',
  name: 'QueryFailedError',
  length: 300,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (2, P, Leonardo, , , 6479154312, , 34535435345, a, 876, Maine St., Suite 1456, Toronto, ON, M8T7Y9, CA, null, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'contacts',
  column: 'created_at',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '2042',
  routine: 'ExecConstraints',
  query: 'INSERT INTO "contacts"("type", "name", "email", "website", "phone1", "phone1_ext", "phone2", "phone2_ext", "address", "address_compl", "city", "province", "postal_code", "country", "created_at", "updated_at", "version") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, DEFAULT, DEFAULT, DEFAULT) RETURNING "id"',
  parameters: [
    'P',              'Leonardo',
    '',               '',
    '6479154312',     '',
    '34535435345',    'a',
    '876, Maine St.', 'Suite 1456',
    'Toronto',        'ON',
    'M8T7Y9',         'CA'
  ]
}
```

**Comment by Binaryify** [comment]
same in mongodb, it must be a bug

**Comment by leonardootoni** [comment]
It seems to be a simple bug, considering that the @VersionColumn() is working correctly for a not null DB Column during insert operations without any workaround. Moreover, @UpdateDateColumn() is working fine as well for update operations.

**Comment by artoodeeto** [comment]
I have the same and issue and fixed it with hooks. @leonardootoni lets try to fix this dude I think theyre busy if you want

**Comment by geunyoungno** [comment]
same issue in mysql
UpdateDateColumn works well, but CreateDateColumn doesn't insert date.

**Comment by artoodeeto** [comment]
@leonardootoni @geunyoungno yow my dudes. I just have a workaround. so you can set your migration something like this.

```
createdAt DATETIME      DEFAULT CURRENT_TIMESTAMP
OR
{
   name: 'createdAt',
   type: 'DATETIME',
   isNullable: true,
   default: 'CURRENT_TIMESTAMP'
},
```

**Comment by leonardootoni** [comment]
@artoodeeto your solution is not a valid workaround on situations where a createAt field **must** be a **Not Null** field in the Database. The framework itself should handled it automatically before to persist the transaction.

**Comment by artoodeeto** [comment]
So before creating/persisting a row in the database, it should include the values/parameters of `createdAt` column right?. Even if you set the column constraints to `NOT NULL` it doesn't matter because you already have a default value. Even without a framework, this is how you handle in the database right? even on updating without using a framework, you'll set the row like `updateAt  DATETIME ON UPDATE CURRENT_TIMESTAMP`. 

I'm saying this because when I tried creating my model first, then run the command `migration:generate` the `createdAt` column will have a `DATETIME NOT NULL DEFAULT now()`.

Also I found this out in [issue](https://github.com/typeorm/typeorm/issues/5306#issuecomment-573865514). This is how they handle the createdAt and upadtedAt columns.

**Comment by shivamkss** [comment]
You can use @Column({ insert: true }) in your entity class, it works fine.

**Comment by imnotjames** [comment]
> same in mongodb, it must be a bug

These aren't supported in MongoDB.

---

I cannot replicate this issue.  Can a repository be created that can be used as a reproducible example?

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
