### ISSUE TITLE
Error on update of entity with m2m relationship

### ISSUE THREAD

**Issue by neilshah2000** [typeorm/typeorm#5395]
**Issue type:**

[X] question
[X] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[X] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

https://github.com/neilshah2000/typeorm-m2m-update-error

**I have 2 entities with a many to many relationship between them. When i try and update the related entity using repository.update() method i get the error below**

```
{ QueryFailedError: SQLITE_ERROR: no such column: gfs_application_id at new QueryFailedError (C:\Users\ShahN2\Documents\apollo\typeorm\MyProject\src\error\QueryFailedError.ts:9:9) at handler (C:\Users\ShahN2\Documents\apollo\typeorm\MyProject\src\driver\sqlite\SqliteQueryRunner.ts:53:26) at replacement (C:\Users\ShahN2\Documents\apollo\typeorm\MyProject\node_modules\sqlite3\lib\trace.js:19:31) at Statement.errBack (C:\Users\ShahN2\Documents\apollo\typeorm\MyProject\node_modules\sqlite3\lib\sqlite3.js:16:21) message: 'SQLITE_ERROR: no such column: gfs_application_id', errno: 1, code: 'SQLITE_ERROR', name: 'QueryFailedError', query: 'UPDATE "gfs_application" SET "id" = ?, "name" = ?, "vendor_name" = ?, "gfs_application_id" = ? WHERE "id" IN (?)', parameters: [ 1, 'new-app', 'vend-name', undefined, 1 ] }
```

```
    let appRepository = connection.getRepository(GfsApplication);
    let deviceRepository = connection.getRepository(Device);

    const device = new Device();
    device.name = 'test-device';
    device.macAddress = '2.5.6.7.12'
    const d1 = await deviceRepository.save(device);

    const gfs = new GfsApplication();
    gfs.name = 'new-app'
    gfs.vendorName = 'vend-name';
    gfs.devices = [];
    gfs.devices.push(d1);
    const a1 = await appRepository.save(gfs);

    const devices = await deviceRepository.find();
    const apps = await appRepository.find();
    console.log("Loaded devices: ", devices);
    console.log("Loaded applications: ", apps);

    // an update on an entity with a many-to-many relationship throws an error
    // "message: 'SQLITE_ERROR: no such column: gfs_application_id',"
    await appRepository.update(1, apps[0]);

```

**Comment by ELI7VH** [comment]
I also just got this same thing. 

provided my record with my relation key and an array of records and got this error...

**Comment by imnotjames** [comment]
Looks like an issue with your entity definitions.

If you think it's an issue with typeorm rather than a local problem please open a new more complete issue including a reproducible example.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
