### ISSUE TITLE
Constrain Naming Conventions

### ISSUE THREAD

**Issue by avin-kavish** [typeorm/typeorm#5469]
**Issue type:** question

**Database system/driver:** `postgres`

**TypeORM version:** `latest`

**Steps to reproduce or a small repository showing the problem:**

Uhh... Constraints seems to be created with not very user friendly names. Can't we have a naming convention for that?

![image](https://user-images.githubusercontent.com/48435155/73744828-a26db300-4777-11ea-8018-6b48faf01b73.png)

Edit: I just had a looked at the code, looks like a conventional key is being generated but is being hashed for some reason. It's a SHA1 hash. It's deterministic. I'm not sure why it is in there but collision avoidance cannot be the reason.

**Comment by jjosef** [comment]
The index columns seem to be deterministic, but foreign key name generations are problematic for production database migrations. Having a better way to handle these would be nice.

**Comment by kaykhancheckpoint** [comment]
For those struggling with this, it is possible to explicitly set the name of FK constraints by building a naming strategy.

**CustomNamingStrategy**

I've opted to build something like the following naming convention: `<table1>_<table2>_<table1_column>` then i hash this because it could get long and mysql will throw an identifier too long error.

This method makes the foreign keys deterministic so that i can use the same migrations for both test and production db.

```
import { DefaultNamingStrategy, Table, NamingStrategyInterface } from "typeorm";
import crypto from "crypto";

export class CustomNamingStrategy extends DefaultNamingStrategy implements NamingStrategyInterface {
    foreignKeyName(tableOrName: Table | string, columnNames: string[], referencedTablePath?: string, referencedColumnNames?: string[]): string {
        
        tableOrName =
            typeof tableOrName === "string" ? tableOrName : tableOrName.name;

        const name = columnNames.reduce(
            (name, column) => `${name}_${column}`,
            `${tableOrName}_${referencedTablePath}`,
        );

        return`fk_${crypto.createHash('md5').update(name).digest("hex")}`
    }
}
```


**ormconfig.ts**

Then import the custom naming strategy in your config.

```
module.exports = {
    "type": "mysql",
    "host": process.env.DB_HOST,
    ...
    namingStrategy: new CustomNamingStrategy()
}
```

references:

https://github.com/typeorm/typeorm/tree/master/sample/sample12-custom-naming-strategy
https://github.com/typeorm/typeorm/issues/5286
https://github.com/typeorm/typeorm/pull/4274/files
