### ISSUE TITLE
Unique Index Name on recreation

### ISSUE THREAD

**Issue by raceloop** [typeorm/typeorm#549]
Hi,

When using a unique index like this`@Index({ unique: true })` the column is successfully created but when restarting TORM it throws an error complaining that the index does not exist.

The fix is `@Index("myCol", { unique: true })`

What appears to be happening is that the "ALTER TABLE / DROP INDEX" statement is no recognising the index by it's uid. Instead it tries to drop the index using the column Name for the index name. 

`ALTER TABLE `user` DROP INDEX myCol`

instead of

`ALTER TABLE `user` DROP INDEX ind_705816b51e5f6f664aacaa94a75`

An alternative fix is to simply restart TORM again.

cheers

JT

**Comment by iz-iznogood** [comment]
I can no longer reproduce this in mssql and postgres but it is present in mysql driver.

**Comment by pleerock** [comment]
@iz-iznogood are you able to fix it?

**Comment by iz-iznogood** [comment]
Hi, the problem is not related to indexes.
It happens because the system detects a false difference in the uniqueness of the column and as a result it tries to rebuild the column.

There is no difference between a unique constraint and a unique index on MySQL (AFAIK), so the column is reported as unique in the schema although it is not unique in the metadata. I did not find a way to distinguish between them, but again I am not an expert on MySQL

I believe this check should be pushed to the driver somehow, since it is different in each case.

What is your opinion ? Is there a pattern that you use for such cases ?

**Comment by iz-iznogood** [comment]
One workaround here is that you can just declare the column as unique 
@Column({unique: true})
This way the metadata know that the column is unique and match the database schema
Also if you do this you can remove the index 

This works fine, but the underlying problem remains

**Comment by iz-iznogood** [comment]
Hi @pleerock the only solution for this is to create a method
`normalizeIsUnique(column: ColumnMetadata): boolean `

in each driver
all implementations should 
`return column.isUnique;`

MySQL implementation would also search for a unique index in the column.entityMetadata.indices

Do you agree ? This would solve it for good I believe and push some logic to the driver where it belongs

**Comment by pleerock** [comment]
Is this problem only in mysql? We need to understand why do we have such problem in mysql? Can't we make things same in mysql and other drivers? Why not to use index instead of simple unique constraint in mysql as well?

**Comment by iz-iznogood** [comment]
Yes this is only related to MySQL - MariaDB. 
I will provide a pull request shortly so that you can see the pattern.
It fixes #549, #244, #572 and #221.

If you agree I will add the tests so that you can merge it

**Comment by pleerock** [comment]
@iz-iznogood thank you very much
