### ISSUE TITLE
Here is my JSON object, "Users": [{"ID": 1, "Name": "Joe"}, {"ID": 2, "Name": "Jenny"}, {"ID": 3, "Name": "Dave"}], "Users": [{"ID": 1, "Name": "Joe"}, {"ID": 4, "Name": "John"}], "Users": [{"ID": 4, "Name": "John"}, {"ID": 3, "Name": "Dave"}]. I want to search and return only those array of objects which have ID = 1 inside them i.e. (first and second). Is there any way that I can use to search inside array of objects for specific property using typeorm?

### ISSUE THREAD

**Issue by AkshayPanchal-004** [typeorm/typeorm#5533]
**Issue type:**

[ * ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
!>

**Comment by artoodeeto** [comment]
Hello Im assuming you are new to github. You can add your question under the template.

To answer your question, I'm not sure what you're doing here if your ID has unique constraints or a primary key, but If its an entity you can do 

for EntityManager API:
```
const user = await manager.findOne(User, 1);
const timber = await manager.findOne(User, { firstName: "Timber" });
```

for Repository API:
```
const user = await repository.findOne(1);
const timber = await repository.findOne({ firstName: "Timber" });
```
If your `ID` column is a Primary key.


If those return objects are the current structure you can use `filter`. Example:

```
const usersWithIdOne = [YOUR ARRAY OF OBJECTS HERE].fiter( user => Number(user.id) === 1)
```

**Comment by AkshayPanchal-004** [comment]
@artoodeeto Thank you for your advice.
Yup. I can use filter method on the array of objects directly (as mentioned above), to get the output.
But, my concern is something different. what if I am storing these kind of JSON objects in my MYSQL table.
I want to filter these JSON objects directly from the database (for user.id = 1) without using filter method at code level.
Does typeorm has any approach to do it?

**Comment by artoodeeto** [comment]
@AkshayPanchal-004  yes they do. If the ID column in your table is not unique then you can still query those users with specified ID number by:

Using raw queries:
```
await repository.query(`SELECT * FROM USERS WHERE id = 1`);
```

Using query builder:
```
await getRepository(User)
    .createQueryBuilder("user")
    .where("user.id = :id", { id: 1 })
    .getMany();
```

You can check the [documentation here](https://typeorm.io/#/select-query-builder)

**Comment by AkshayPanchal-004** [comment]
@artoodeeto Sorry for this unpleasant presentation. But, I hope it will help you what i really asking.
USER   GROUP TABLE
------------------------
Group_ID | Members
-------------------------
     1         | [{"ID":   1, "Name": "Joe"}, {"ID": 2, "Name":   "Jenny"}, {"ID": 3, "Name": "Dave"}]
     2         | [{"ID": 1,   "Name": "Joe"}, {"ID": 4, "Name":   "John"}]
     3         | [{"ID": 4, "Name":   "John"}, {"ID": 3, "Name": "Dave"}]
Here is my user group table with two columns in it (first is group_id & second is members).
Now I want to filter those users group id which has ID = 1 associated with it. i.e. I want to search in 'members' column which stores array of objects within it. 
Does TypeORM has any approach to do so through which I can query within these array of JSON objects directly at DB level only.(without using filter method on code level).

**Comment by artoodeeto** [comment]
Hello @AkshayPanchal-004. Let me clarify this.

so the first column is an integer type which is the `1, 2, 3` and a second column which is an `Array of JSON` `[{ID: 1, name: 'foo'}]` which is the USERS table right? So you add the user info in the group's table, instead of user id? Is this your table design?

First, let me ask you this. What is the relationship between these 2 entities? Is it `many to many` or `one to many`? 

From the data you've shared, I'm assuming 1 User can be in multiple groups and 1 Group can have multiple users? So this is `many to many` relationships. I say this because you might get some problems in the long run. See the User `ID:1, name: joe` if `joe` updates its name then you have to update it from the 2 rows now which is inefficient and wasted work. My suggestion is to create a 3rd table that holds both user and group id and make those  IDs unique and primary key. 

Now all the crap that I talked about are just assumptions and I might be wrong, I hope you can forgive me. :smile: 

but if that's really your column type then you can read [mysql](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html) if that's your dbms. Also, I don't think typeorm support JSON functions right now, so I'm suggesting is you'll have to do it with raw queries.

**Comment by AkshayPanchal-004** [comment]
@artoodeeto 
Thank you for your time and suggestion. It surely helped me.
See you in future with many more doubts. Hope you wont mind😅
