### ISSUE TITLE
Repository remove function returns an object with all the primary columns set to undefined

### ISSUE THREAD

**Issue by sacha67** [typeorm/typeorm#5671]
**Issue type:**

[X] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[X] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
Remove an Entity by using `remove()` function of a `Repository`.

Hello, I don't understand why all properties defined as `@PrimaryColumn` on the Entity class are set to `undefined` in the object returned by `remove()`.

**Comment by imnotjames** [comment]
This is because the object has been removed and the PK is no longer relevant nor accurate.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
