### ISSUE TITLE
bug on commit https://github.com/typeorm/typeorm/commit/ceff897

### ISSUE THREAD

**Issue by artoodeeto** [typeorm/typeorm#5699]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

@merceyz hello sir, first of all I want to thank you for your awesome contribution. We the users of typeorm are truly grateful and appreciative of your work and just wanted to report this bug.

Typescript/VScode telling me that the return value is an Array. Though before I upgraded to the latest version It doesn't say any error. I have to add `[0]` after `(req.body)`, like: `const post: PostModel = PostModel.create(req.body)[0];`

Create post route implementation:
```ts
const { id } = req.payload;
    const post: PostModel = PostModel.create(req.body);
    try {
      const user: User = await User.findOneOrFail(id);
      post.user = user;
      const { id: postID, title, body } = await post.save();
      res.status(200).json({
        meta: {},
        payload: {
          post: {
            id: postID,
            title,
            body
          }
        }
      });
    } catch (error) {
      res.status(400).json({ error });
    }
```

I think this was introduced in this commit https://github.com/typeorm/typeorm/commit/ceff897

VSCODE ERROR:

![Screen Shot 2020-03-16 at 7 24 04 PM](https://user-images.githubusercontent.com/19770382/76817971-9850c280-67c1-11ea-8ee2-5478d8f91723.png)

TEST ERROR:

![Screen Shot 2020-03-16 at 7 28 10 PM](https://user-images.githubusercontent.com/19770382/76817986-a1da2a80-67c1-11ea-9e88-0453cf85d069.png)

baseModel:

```ts
import { BaseEntity } from 'typeorm';
import { validateOrReject } from 'class-validator';

export class BaseModel extends BaseEntity {
  async validateModel(): Promise<this | Error> {
    try {
      await validateOrReject(this, { validationError: { target: false } });
      return this;
    } catch (error) {
      throw error;
    }
  }
}
```

Post:
```ts
@Entity({ name: 'posts' })
export class Post extends BaseModel {
  @PrimaryGeneratedColumn()
  id!: number;
}

```

Thank you so much sir. 

PS: the workaround is to put a `// @ts-ignore`

like: 

```ts
// @ts-ignore
    const post: PostModel = PostModel.create(req.body);
```

**UPDATE**

I think I know the reason. 

When I used create a method like: `User.create(req.body)` it uses a different function signature. I think because of this:

```ts
User <---- this User
{
   username: 'new1',
   email: 'new1@gmail.com',
   password: 'password'
}
````
create method assumes that the parameter is like `User, {props}` so it assumes the it uses the function signature with a return type of Array.

To remove this ts error you have to explicitly do this:

```ts
const user: User = User.create({
        email: 'test@gmail.com',
        password: 'password',
        username: 'foo'
      });
```

this one will use the right overload method.

**UPDATE**

you can use like this too: `const user: User = User.create(req.body as User);` then the error goes away.

**Comment by imnotjames** [comment]
Post.user / user.posts doesn't exist.

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
