### ISSUE TITLE
cascade insert not working

### ISSUE THREAD

**Issue by bijeebuss** [typeorm/typeorm#57]
Here is what I have

```
@Table()
export class AccessToken {
  @PrimaryColumn('int',{generated:true})
  primaryKey: number;

  @OneToOne(type => User, user => user.access_token, {cascadeInsert:true, cascadeUpdate:true})
  user:User
}

@Table()
export class User {
  @PrimaryColumn("int", { generated: true })
  primaryKey: number;

  @Column()
  email: string;

  @OneToOne(type => AccessToken, token => token.user, {cascadeInsert:true, cascadeUpdate:true})
  @JoinColumn()
  access_token: AccessToken;
}

var token = new AccessToken();
var user = new User();
user.email = 'mwelnick@test.com'
user.access_token = token;

return connection.getRepository(AccessToken).persist(token).then(token => {
  connection.close();
  return token;
});
```

it is saving the access token fine but not saving the User.

**Comment by pleerock** [comment]
your code is not valid, because you bind token to user, but you don't persist user, but instead you persist a token which does not have reference to user inside it. Thats why he don't know that he needs to save a user by cascades. You need either to save a user, either to set a user to token and save a token.

I have created a test for your case, so it should work at least with `npm i typeorm@next`

**Comment by bijeebuss** [comment]
That makes sense, however the example with photo and photometadata on the readme should have the same issue then.

**Comment by KurtGokhan** [comment]
@pleerock Sorry for reviving this. But if the cascade insert only works on the side where JoinColumn is, shouldn't the option to enable it be inside JoinColumn? Right now it seems like cascade insert is possible on both sides of the relation. 

Also, usually, dependency would be reversed in this case and JoinColumn would be on the AccessToken side. But persisting User would be more plausible, because a User owns an AccessToken. Cascade insert from both sides would really be helpful in this case. Would you consider such a feature? If I am correct, this is only missing in OneToOne relationships.

**Comment by adrianhara** [comment]
Any news on this? I'm having the issue on a OneToMany/ManyToOne relationship when i try to save from the ManyToOne side it tries to insert the ManyToOne object first and it fails because of the foreign key constraint.

**Comment by adrianhara** [comment]
I can confirm this works with alpha-0.2.0, great job!
