### ISSUE TITLE
Call ORACLE stored procedure with "OUT" parameter

### ISSUE THREAD

**Issue by nandigamchandu** [typeorm/typeorm#5706]
**Issue type:**

[ ] question
[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[x] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by dpmallinger** [comment]
if you are asking how here is an example.  

a function that returns a string value would work like this:
```
const sql: string = `
		begin
		  :p0 := foo.function(:p1);
		end;
`;
const result: any = await connection.query(sql,
      [{ dir: oracledb.BIND_OUT, type: oracledb.STRING }, param]
);

```

**Comment by manchuwook** [comment]
> if you are asking how here is an example.
> 
> a function that returns a string value would work like this:
> 
> ```
> const sql: string = `
> 		begin
> 		  :p0 := foo.function(:p1);
> 		end;
> `;
> const result: any = await connection.query(sql,
>       [{ dir: oracledb.BIND_OUT, type: oracledb.STRING }, param]
> );
> ```

Unfortunately, the const SQL only works for functions and does not work for stored procedures.

**Comment by dpmallinger** [comment]
@manchuwook  yes, that example was a function but a stored procedure is very similar. 

```
const sql: string = `
                 begin
                   schema.procedure(:p0, :p1, :p2, :p3, :p4);
                 exception
                   /* exception handling here */
                 end;
                `;

const result: any = await connection.query(sql,[
        { dir: oracleConstant.BIND_OUT, type: oracleConstant.CURSOR },
        param2,
        param3,
        param4
      ]
);

const rs = result[0];
const response: any[] = [];
let row;
while ((row = await rs.getRow())) {
      response.push(row.VALUE);
}

// always close the ResultSet
await rs.close();

```

**Comment by manchuwook** [comment]
I will give that a shot - I'd much rather go through typeorm than directly through oracledb.

**Comment by wfpena** [comment]
> I will give that a shot - I'd much rather go through typeorm than directly through oracledb.

@manchuwook  where you able to get it working?

**Comment by keithics** [comment]
I did it something like this..

```
getConnection().manager.query(`SELECT package.function('VALUE1', 'VALUE2','VALUE3') AS VAL FROM DUAL`)
        .then(async (result)=>{
            console.log(result)
            res.jsonp(result[0].VAL);
        }).catch((err)=>{
            return res.status(422).send({
                 message: ErrorHandlerController.getErrorMessage(err)
             })
        });
```

**Comment by manchuwook** [comment]
> > I will give that a shot - I'd much rather go through typeorm than directly through oracledb.
> 
> @manchuwook where you able to get it working?

Sorry for the late delay - I was not able because the db was expecting a single object and not an array of objects.

**Comment by imnotjames** [comment]
Array of objects is `:...value` when you pass `{ value: [1, 2, 3] }`

Sounds like this was resolved otherwise.

**Comment by FilipeVeber** [comment]
> @manchuwook yes, that example was a function but a stored procedure is very similar.
> 
> ```
> const sql: string = `
>                  begin
>                    schema.procedure(:p0, :p1, :p2, :p3, :p4);
>                  exception
>                    /* exception handling here */
>                  end;
>                 `;
> 
> const result: any = await connection.query(sql,[
>         { dir: oracleConstant.BIND_OUT, type: oracleConstant.CURSOR },
>         param2,
>         param3,
>         param4
>       ]
> );
> 
> const rs = result[0];
> const response: any[] = [];
> let row;
> while ((row = await rs.getRow())) {
>       response.push(row.VALUE);
> }
> 
> // always close the ResultSet
> await rs.close();
> ```

I'm also facing this problem with "out" params.
I tried to do as the answer I mentioned but it just returns the following error:

`
error: { [Error: ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PL/SQL: Statement ignored] errorNum: 6550, offset: 41 }
error: ERRO: QueryFailedError, Message: ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PLS-00306: wrong number or types of arguments in call to 'SAU_CALCULA_PVI_P'
ORA-06550: line 3, column 19:
PL/SQL: Statement ignored - Parameters: [31,01/01/2021,31/01/2021,,10,150,10,1,1,1,83235.98,484947.01,65360.07,0,1,[object Object],[object Object],[object Object],[object Object],[object Object]]
`

I tried to combine this with the DECLARE statement as the following:

`
DECLARE
  v_vl_pvi          NUMBER;
  v_vl_pv_rap_ft    NUMBER;
  v_vl_pv_rap_conc  NUMBER;
  v_vl_pv_rap_engie NUMBER;
  v_erro            VARCHAR2(4000);
BEGIN
  SAU.SAU_CALCULO_PV_PKG.SAU_CALCULA_PVI_P(
	:p0,
	TO_DATE(:p1, 'DD-MM-YYYY'),
	TO_DATE(:p2, 'DD-MM-YYYY'),
	:p3,
	:p4,
	:p5,
	:p6,
	:p7,
	:p8,
	:p9,
	:p10,
	:p11,
	:p12,
	:p13,
	:p14,
	p_vl_pvi => v_vl_pvi,
	p_vl_pv_rap_ft => v_vl_pv_rap_ft,
	p_vl_pv_rap_conc => v_vl_pv_rap_conc,
	p_vl_pv_rap_engie => v_vl_pv_rap_engie,
	p_mensagem => v_erro
  );
END;
`

`ERRO: QueryFailedError, Message: ORA-01036: illegal variable name/number - Parameters: [31,01/01/2021,31/01/2021,,10,150,10,1,1,1,83235.98,484947.01,65360.07,0,1,[object Object],[object Object],[object Object],[object Object],[object Object]]`

And if try to stringify the objects, it turns out this way:

`ERRO: QueryFailedError, Message: ORA-01036: illegal variable name/number - Parameters: [31,01/01/2021,31/01/2021,,10,150,10,1,1,1,83235.98,484947.01,65360.07,0,1,{"dir":3003,"type":2004},{"dir":3003,"type":2004},{"dir":3003,"type":2004},{"dir":3003,"type":2004},{"dir":3003,"type":2004}]`

Did this because I was out of ideas.

Packages:
"oracledb": "^3.1.2"
"typeorm": "^0.2.32"

**Comment by wfpena** [comment]
@FilipeVeber what are the parameters on `SAU.SAU_CALCULO_PV_PKG.SAU_CALCULA_PVI_P`?

I got it working by using node streams, but I'm not sure you want OUT or IN parameters.

**Comment by FilipeVeber** [comment]
> @FilipeVeber what are the parameters on `SAU.SAU_CALCULO_PV_PKG.SAU_CALCULA_PVI_P`?
> 
> I got it working by using node streams, but I'm not sure you want OUT or IN parameters.

Hello @wfpena! Thanks for answering!
Actually, I just pushed my code! I made it work!

I had to use the oracledb connection instead of the a TypeORM approach.

Here's what I had to do:

1 - Get the oracledb: 
`const oracledb = require("oracledb");`

2 - Procedure with IN and OUT parameters:
```
`BEGIN
  SAU.SAU_CALCULO_PV_PKG.SAU_CALCULA_PVI_P(
    :p0,
    .
    .
    .
    :p14,
    :v_vl_pvi,
    :v_vl_pv_rap_ft,
    :v_vl_pv_rap_conc,
    :v_vl_pv_rap_engie,
    :v_erro
  );
END;`
```
3 - Get the connection from the oracledb instead of the TypeORM: 
`const conn = await oracledb.getConnection();`

4 - Build the `bindings` object with the named parameters: 
```
{
      p0: dataObject.id,
      p1: dataObject.name,
      .
      .
      .
      v_vl_pvi: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      .
      .
      .
}
```

5 - Call the procedure using the `execute` function: 
`const result = await conn.execute(procedure, bindings);`

6 - Get the result from `result.outBinds;`

The differences from my code to the above suggested is that I'm using the type NUMBER instead of CURSOR and I'm using the `execute` function from oracledb intead of the `query` function from TypeORM.

**Comment by mritunjayupadhyay** [comment]
> 

What if the package is creating(I mean inserting data in a table).
In this scenario,  you will get the following error
`On create document.\nORA-14551: cannot perform a DML operation inside a query `.

**Comment by alichampion** [comment]
> 

Hi @dpmallinger after this I'm getting `NJS-018 invalid ResultSet` error do you have any idea?

**Comment by amitagarwal-dev** [comment]
Oracle sp with out parameter is working in my case.  
My sp:  

```sql
CREATE OR REPLACE PROCEDURE TEST_GENERATESTANRRN 
(
  P_TRANSACTIONID IN VARCHAR2 
, O_STAN OUT VARCHAR2 
, O_RRN OUT VARCHAR2 
) IS
    JullianDay VARCHAR2(5);
	v_Hour VARCHAR2(3);
	v_Minute VARCHAR2(3);
	v_Year VARCHAR2(4);
	v_STAN VARCHAR2(20);
	v_ID VARCHAR2(12);
    v_RRN varchar2(20);
BEGIN
	SELECT CONCAT ('00', TO_NUMBER(TO_CHAR(SYSTIMESTAMP, 'DDD'))) INTO JullianDay FROM dual;
	SELECT CONCAT ('0', EXTRACT(HOUR FROM SYSTIMESTAMP)) INTO v_Hour FROM dual;
	SELECT CONCAT ('0', EXTRACT(MINUTE FROM SYSTIMESTAMP)) INTO v_Minute FROM dual;
	SELECT EXTRACT(YEAR FROM SYSTIMESTAMP) INTO v_Year FROM dual;

    INSERT INTO test_STANRRNGenration (TransactionID) VALUES (p_TransactionID) returning stan into v_ID;
	v_STAN := CONCAT('000000', v_ID);

	SELECT SUBSTR(v_Year, 4, 1) || SUBSTR(JullianDay, -3) || SUBSTR(v_Hour, -2) ||
	SUBSTR(v_STAN, -6), SUBSTR(v_STAN, -6) INTO O_RRN, O_STAN from dual;
END TEST_GENERATESTANRRN;
```  
`Typeorm Code`  
```js
import { AppDataSource } from "./data-source";
import * as oracledb from "oracledb";

AppDataSource.initialize()
  .then(async () => {
    let ret = await AppDataSource.manager.query(
      "call TEST_GENERATESTANRRN(:txnid,:stan,:rrn)",
      [
        "1234123412",
        { type: oracledb.DB_TYPE_VARCHAR, dir: oracledb.BIND_OUT },
        { type: oracledb.DB_TYPE_VARCHAR, dir: oracledb.BIND_OUT },
      ]
    );
    console.log(ret);
  })
  .catch((error) => console.log(error));
```  
`OUTPUT`  
```
query: SELECT SYS_CONTEXT('USERENV','DB_NAME') AS "db_name" FROM dual
query: SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS "schema_name" FROM dual
query: call TEST_GENERATESTANRRN(:txnid,:stan,:rrn) -- PARAMETERS: ["1234123412",{"type":2001,"dir":3003},{"type":2001,"dir":3003}]
[ '000003', '213807000003' ] //stan rrn output
```
