### ISSUE TITLE
Building to a separate folder causes import problems

### ISSUE THREAD

**Issue by thomasgauvin** [typeorm/typeorm#5743]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
https://github.com/thomasgauvin/typescript-example

1- Indicate build command to compile to a separate folder (ie: tsc to /build) (you can do this from my repo with `npm run build`)
2- Indicate production of serving from the separate build folder (you can do this from my repo with `npm run prod`)

this is the error screenshot:
![image](https://user-images.githubusercontent.com/35609369/77281586-c6407600-6c9d-11ea-8252-ddceb29d14f8.png)

**Comment by phoenisx** [comment]
I had trouble understanding this issue as well.
First I thought this is due to `tsc`, but discussing the issue with TS devs, I got to know `typeorm` actually looks for source files from `ormconfig.json`, properties like `entities` and various others, i.e.:

```json
{
  "entities": ["dist-server/models/**/*.js"],
  "factories": ["dist-server/factories/**/*.factory.js"],
  "migrations": ["dist-server/migrations/**/*.js"],
  "seeds": ["dist-server/seeds/**/*.seed.js"],
  "subscribers": ["dist-server/subscriber/**/*.js"]
}
```

In your `ormconfig.json` you have defined:

```json
  "entities": [
    "src/entity/*.js",
    "src/entity/*.ts"
  ]
```

which includes `src/entity/*.ts` TS files as well, and thus the above error. If you remove the `*ts` lookup, things will work just fine.

The only drawback I see from this approach is that, we have to keep our `build`s or`dist`s up-to-date, before running any typeform commands.

**Comment by imnotjames** [comment]
For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
