### ISSUE TITLE
Typeorm is blocking redux-saga call

### ISSUE THREAD

**Issue by wagnerpvilla** [typeorm/typeorm#5807]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[ ] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[x] react-native
[ ] expo

**TypeORM version:**

[ ] latest
[ ] @next
[x] ^0.2.24

Hi,

I have a problem when I am calling an action by redux-saga.

When I call findOne, it returns when I call it again.

### Connetion options:

```
const dbOption: Typeorm.ConnectionOptions = {
        type: 'react-native',
        database: config.database.name,
        logging: ['error', 'query', 'info', 'log', 'schema', 'warn', 'migration'],
        synchronize: false,
        entities: [
          MobUserSchema,
          MobAccountSchema,
          MobEstablishmentSchema,
          MobOccurrenceTypeSchema,
          MobOccurrenceSchema,
          MobPaymentTermSchema,
          MobEntrySchema,
          MobUserSettingSchema
        ],
        location: 'default'
      };
```

### An Example Model:
```
import { EntitySchema } from 'typeorm';
import { BaseModel, BaseModelSchema } from './BaseModel';

export interface MobUser extends BaseModel {
  idUser: string;
  name: string;
  email: string;
  password: string;
}

export const MobUserSchema = new EntitySchema<MobUser>({
  name: 'mobUser',
  columns: {
    idUser: {
      type: 'bigint',
      primary: true
    },

    name: {
      name: 'nmName',
      type: String,
      length: 250,
      nullable: false
    },
    email: {
      type: String,
      length: 250,
      nullable: false,
      unique: true
    },
    password: {
      type: String,
      nullable: false
    },
    ...BaseModelSchema
  },
  tableName: 'mobUser'
});

```

### Saga:
```
import { call, put, all, takeEvery } from 'redux-saga/effects';

import CustomErrors, { getYupErrors } from '../../../utils/CustomErrors';
import { signInFailure, signInSuccess, signInRequest } from './actions';
import { AuthActions } from './types';
import sessionService, { SignInResponse } from '../../../services/SessionService';

function* signIn({ payload }: ReturnType<typeof signInRequest>) {
  try {
    const response: SignInResponse = yield call([sessionService, sessionService.signIn], payload);

    yield put(signInSuccess({ token: response.token, signed: true, isOnline: response.isOnline }));
  } catch (exSignIn) {
    let message = '';

    if (exSignIn.inner) {
      message = getYupErrors(exSignIn.inner).reduce((a, b) => `${a} - ${b}\n`, '');
    } else if (exSignIn.response) {
      message = exSignIn.response.data?.message;
    }

    if (message) {
      yield put(signInFailure(new CustomErrors(message)));
    } else {
      yield put(signInFailure(new CustomErrors('', exSignIn)));
    }
  }
}

export default all([takeEvery(AuthActions.SIGNIN_REQUEST, signIn)]);
```

### Session class: 
```
import * as Yup from 'yup';
import BaseService from './BaseService';
import databaseHelper from './DatabaseHelper';
import CustomError from '../utils/CustomErrors';
import userService from './dataService/UserService';
import accountService from './dataService/AccountService';
import securityService from './SecurityService';

const schema = Yup.object().shape({
  email: Yup.string()
    .email('Informar um email válido')
    .required('Informar um email válido'),

  password: Yup.string()
    .min(6, 'A senha precisa ter pelo menos 6 caracteres')
    .max(18)
    .required('Informar uma senha')
});

class SessionService extends BaseService {
  resource = 'session';

  needToken = false;

  public async signIn(params: SignInRequest): Promise<SignInResponse> {
    const { email, password } = params;

    **await** schema.validate(params, { abortEarly: false });

    const [isDataBaseReady, isServerOn] = **await** Promise.all([databaseHelper.isDataBaseReady(), this.isServerOn()]);

    if (isServerOn) {
      const {
        data: { user, token }
      } = await this.post(['login'], { email, password });

      return { user, token, isOnline: true };
    }

    if (isDataBaseReady) {
      const ret = await this.localSignIn(email, password);
      return ret;
    }

    throw new CustomError('Não foi possível efetuar o login');
  }

  private async localSignIn(email: string, password: string): Promise<SignInResponse> {
    const user = **await** userService.findOne({ email });

    if (!user) {
      throw new CustomError('Usuário ou senha inválido');
    }

    const isValidPassword = await securityService.compareHash(password, user.password);

    if (!isValidPassword) {
      throw new CustomError('Usuário ou senha inválido');
    }

    const account = (await accountService.findOne({}))!;

    const tokenInfo = {
      id: user.idUser,
      email: user.email,
      name: user.name,
      account: account?.name,
      idAccount: account?.idAccount
    };

    console.log({ tokenInfo });

    return { isOnline: false, user: tokenInfo };
  }
}
```
### Calling Typeorm
```
import {
  EntityManager,
  Repository,
  getManager,
  ObjectType,
  FindConditions,
  FindManyOptions,
  FindOneOptions,
  EntitySchema
} from 'typeorm';

abstract class BaseDataService<T> {
  private manager?: EntityManager;

  private objEntity: EntitySchema<T>;

  constructor(objEntity: EntitySchema<T>) {
    this.objEntity = objEntity;
  }

  protected get getManager(): EntityManager {
    return (this.manager = this.manager ?? getManager());
  }

  protected getRepository(): Repository<T> {
    return this.getManager.getRepository(this.objEntity);
  }

  protected getExternalRepository<E>(entity: ObjectType<E>): Repository<E> {
    return this.getManager.getRepository(entity);
  }

  public async find(options?: FindManyOptions<T>): Promise<T[]> {
    return this.getRepository().find(options);
  }

  public async findCondition(condition: FindConditions<T>): Promise<T[]> {
    return this.getRepository().find(condition);
  }

  public async findOne(condition: FindConditions<T>, options?: FindOneOptions<T> | undefined): Promise<T | undefined> {
    console.log({ findOne: { condition } });
    const ret = await this.getRepository().findOne(condition, options);
    console.log({ findOne: { ret } });
    return ret;
  }
}

export default BaseDataService;

```
When I call the findOne method, it is printted on console the variable condition, but not the ret value. But when I call again this method, the ret value of the first call is printed. And it is printted just the condition of the second call, and the saga keep blocked.

### Reactotron Logs with Sqlite in debug mode

![reactotron2](https://user-images.githubusercontent.com/5511044/78462754-773a0e00-76ab-11ea-88ef-b98f867b327a.PNG)

![reactotron1](https://user-images.githubusercontent.com/5511044/78462755-7a34fe80-76ab-11ea-9834-8d44b65f44ed.PNG)

![reactotron0](https://user-images.githubusercontent.com/5511044/78462758-7c975880-76ab-11ea-9944-49ad382af9f5.PNG)

**Comment by imnotjames** [comment]
Can you create a minimally reproducible example?  As it stands I have no way to reproduce this error and I can't really understand how the screenshots you included map up to the code you wrote.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
