### ISSUE TITLE
Postgres createdAt / updatedAt decorators use tz-aware NOW() as value for tz-unaware timestamp columns

### ISSUE THREAD

**Issue by bengotow** [typeorm/typeorm#5841]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

The TypeORM postgres driver uses the `timestamp` column type with a default value of `NOW()` for createdAt and updatedAt. This is incorrect, because the postgres `NOW()` method returns a timestamp with the server's timezone applied, and applying it to a `timezone` column assumes the value is UTC. If the Postgres server is running in a timezone other than UTC, this shifts the value of every createdAt and updatedAt timestamp.

The correct default value would be:
`now() at time zone 'utc'`

**Comment by bengotow** [comment]
(Related to #2220 and #1717, I think)

**Comment by humbertowoody** [comment]
Hi! I'm running into this exact same error. I created an issue but closed in favor of this one. So, right now the only way to solve it is to set the DB timezone to UTC? Thanks in advance!

**Comment by rstrand** [comment]
I'm not sure this is actually a bug as a timestamp without timezone column in postgres assumes the columns are in the same timezone that the database is configured to use.

I think the cleanest solution would be to use a `timestamp with timezone` column for the createdAt/updatedAt columns (and other Date types) would be the best solution as it means postgresql converts the timestamp to UTC before storing it.

**Comment by montacerdk** [comment]
Having the same issue, any solutions ?

**Comment by vbhakta8** [comment]
I have been trying to create the columns like so:
```
@CreateDateColumn('timestamptz')
createdAt!: Date;

@UpdateDateColumn('timestamptz')
updatedAt!: Date;

@DeleteDateColumn('timestamptz')
deletedAt?: Date;
```

but my migration file uses the regular `timestamp` whenever I go and try to run a migration, the output looks like so:
```
"created_at" TIMESTAMP NOT NULL DEFAULT now(), 
"updated_at" TIMESTAMP NOT NULL DEFAULT now(), 
"deleted_at" TIMESTAMP,
```

Is the `timestamptz` type not supported with postgres when doing a migration?

**Comment by rstrand** [comment]
@vbhakta8 You can use `ts-node ./node_modules/typeorm/cli.js migration:generate -n new-migration` to avoid transpiling the code first.

**Comment by JaosnHsieh** [comment]
```typescript
@CreateDateColumn({
    type: 'timestamp with time zone',
    nullable: false,
  })
  createdAt!: Date;

  @UpdateDateColumn({
    type: 'timestamp with time zone',
    nullable: false,
  })
  updatedAt!: Date;

  @DeleteDateColumn({
    type: 'timestamp with time zone',
    nullable: false,
  })
  deletedAt!: Date;
```

above using node.js client side timezone instead of Postgres database timezone on `"typeorm": "0.2.25"`

**Comment by enote-kane** [comment]
I think I saw the same issue in almost any ORM in any language at some point: false assumptions. And I am missing some reasoning in this discussion.

Just like already said in #2220, dealing with time is pretty complex and impossible if you ignore the time zone. A timestamp without a time zone simply does not make sense, since the reader can never be _sure_ that the creator was using UTC/Zulu, it's always an assumption, never a guarantee.

Also, I disagree with the OP on the following points:
> ... because the postgres NOW() method returns a timestamp with the server's timezone applied ...

Sorry, but this is wrong (also test for yourself in [this fiddle](https://dbfiddle.uk/?rdbms=postgres_13&fiddle=777a907f9a45618ac7a2b284a24ef15e)):
```sql
SELECT now();
-[ RECORD 1 ]----------------------
now | 2021-08-04 01:40:39.007361+03

SET timezone TO 'Asia/Tokyo';
SELECT now();
-[ RECORD 1 ]----------------------
now | 2021-08-04 07:41:03.644949+09

SET timezone TO 'Zulu';
SELECT now();
-[ RECORD 1 ]----------------------
now | 2021-08-03 22:41:09.884997+00
```
The resulting value totally depends on the client session, not on the server. That might be true for other databases, but certainly not for PostgreSQL.

> The correct default value would be:
> `now() at time zone 'utc'`

This is even worse, since that means the application is generating UTC timestamps without anyone telling it to and the developer might have (correctly) assumed to deal with local timestamps.

And although there is a "workaround" by making sure in a controlled environment that all parties are in the same timezone and that also no deviating connection parameters will be used, it is not a solution. There are certainly applications for which local timestamps are totally OK but others for which it is not.

The only solution would be to use `TIMESTAMP WITH TIME ZONE` by default.

From my perspective, the current implementation defaulting to timestamp without time zone is clearly a bug, since it ignores the most important part of a timestamp for correct interpretation.

However, if the assumption (that TypeOrm handles the time zone correctly) does not apply, then there is a completely different issue in this topic.

**Comment by pleerock** [comment]
I added `design issue: create/update date columns` label because this issue demonstrates inflexibility of the current `@CreateDateColumn` and `@UpdateDateColumn` decorators - people want different conflicting behaviors for different purposes. Issue can be easily solved by using more flexible decorator `@Column` - using it you can customize behavior the way you want. Best way for people to prevent this confusion - remove confusing `@CreateDateColumn` and `@UpdateDateColumn` decorators and show people how to do same using `@Column` decorator.

**Comment by neumartin** [comment]
Can I set a global timezone for PostgreSQL sessions?

**Comment by kasir-barati** [comment]
I guess we need a more cleaner way instead of these hacky ways

I mean something like this:
```ts
class EntityName {
  @CreateDateColumn({
    type: 'timestamp with utc time zone',
    name: 'created_at',
  })
  createdAt: Date;

  @UpdateDateColumn({
    type: 'timestamp with utc time zone',
    name: 'updated_at',
  })
  updatedAt: Date;
}
```

Any progress on this?

**Comment by OrjiNuel** [comment]
I am trying to use this as a basemodel that extends other models but when I create an entity, it adds data to the updatedAt and deletedAt column even when I have not done any update or deleted the entity
 
@CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @CreateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  @CreateDateColumn({ type: 'timestamptz' })
  deletedAt: Date;

Please any help to why it is so?

**Comment by neverovski** [comment]
@OrjiNuel you cane use `{ synchronize: false }` option in DataSource

**Comment by kyungseopk1m** [comment]
Is there any way to use `@CreateDateColumn`, `@UpdateDateColumn`, and `@Column` decorators together and use a consistent UTC time?

**Comment by stim371** [comment]
> Is there any way to use `@CreateDateColumn`, `@UpdateDateColumn`, and `@Column` decorators together and use a consistent UTC time?

@kyungseopk1m Please create a new issue or ask in the help channel on the Discord (https://discord.gg/cC9hkmUgNa).

**Comment by kyungseopk1m** [comment]
finally solved the problem by using the timestamp with time zone type instead of the timestamp type. thx ;)
