### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by tontonskie** [typeorm/typeorm#591]
Just want to ask the author @pleerock this. Are you confident with this project to be used in production? and aside from you do you know others that use this project on production?

I love this project and it is great. Just want to know directly from you, a sort of assurance that this project will be maintained longer and somehow if not completely that I can rely on this project I know there will be bugs I know that.

I'm planning to use this on big projects for corporate and startups.

**Comment by pleerock** [comment]
> Are you confident with this project to be used in production?

it really depends on what kind of "production" is it and what kind of team working in this production. For example personally I use it on production in a very HUGE project. I use it there because I know that anytime my team is able to do version updates easily (bugfixes, new features, etc.) and my team is writing a very clean code and they are using typeorm properly, thats why all processes are easy in our production.

>  want to know directly from you, a sort of assurance that this project will be maintained longer

I spent almost two years of my life on this project, I don't know how many hours it is, but this time cost me probably hundreds of thousands dollars. I won't stop.

> I know there will be bugs I know that

yeah, there will be bugs. Some of them critical and will be fixed quickly. There are prioritable bugs and not prioritable. If you faced not prioritable bugs you will have to wait, because there are lot of things to be done. Some of bugs require lot of redesign and refactor and it takes time. Bugs exist always in any complex software. And typeorm is a very complex software. Thats a price of its features.

> I'm planning to use this on big projects for corporate and startups.

This decision is up to you, personally I would use it in any project, especially in startups because nodejs together with typescript do a good job in startups, especially in lean startups. And all my tools (including typeorm) are great if you do lean and productive development.

**Comment by tontonskie** [comment]
@pleerock thanks for the time in attending my concern and I appreciate it. I'm going to use this on startups and plan to contribute also but I'm going to start first with integrating it with a framework.

Again thanks and keep it up.

**Comment by dcworldwide** [comment]
In case it helps, my company is using typeorm and postgres in a production system for ~6 months now.  It's been very solid. Typeorm's use of decorators and strongly typed apis has kept our code simple and robust. 

As typeorm is a growing project, we've deliberately kept things simple. We use transactions, query builder, table CRUD abstractions, migrations and auto-schema sync (this is a killer feature). We've held off on using relations for now as a personal preference largely because we want to keep things simple.

**Comment by avin-kavish** [comment]
@dcworldwide you don't use relations in a relational database using an object-relational mapper?
