### ISSUE TITLE
Different result with query builder and direct query

### ISSUE THREAD

**Issue by ardyfeb** [typeorm/typeorm#5939]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

Different data returned from typeorm with query builder and direct querying to database, i trying to implement pagination. When using typeorm count of returned data is different, here my code
```ts
const orders = await this.orderRepository
      .createQueryBuilder('order')   
      // Typeorm cannot load eager relation when querying through query builder,
      // so we need to load them manually
      .leftJoinAndSelect('order.item', 'item')
      .leftJoinAndSelect('item.product', 'product')
      .leftJoinAndSelect('order.store', 'store')
      .leftJoinAndSelect('store.address', 'storeAddress')
      .leftJoinAndSelect('order.user', 'user')
      .leftJoinAndSelect('order.voucher', 'voucher')
      .leftJoinAndSelect('order.shippingMethod', 'shippingMethod')
      .leftJoinAndSelect('order.shippingAddress', 'shippingAddress')
      .leftJoinAndSelect('order.payment','payment')
      .where(conditions)
      .orderBy(
        {
          'order.created': 'DESC'
        }
      )
      .offset(offset) // 10
      .limit(max) // 50
      .getMany();
    
    console.log("count: ", orders.length)
```
returned 9 rows
![Screenshot_20200423_200203](https://user-images.githubusercontent.com/30074366/80102942-b0281d00-859d-11ea-9727-7c566c5a97dd.png)

then i try copy typeorm output query and run on my database IDE, count of rows returned is different its return 10 orws
![Screenshot_20200423_200254](https://user-images.githubusercontent.com/30074366/80103253-2593ed80-859e-11ea-8bcd-db7a7be48950.png)

**Comment by kimarudg** [comment]
I am also experiencing the same.
When I have enabled database logging, I am able to grab the query that is being run against the database. When I copy that query and run it directly, I am getting 175 records. Typeorm gives me 2500 records for the same query

**Comment by imnotjames** [comment]
Can you include a minimally reproducible example?  There's not enough info here to reproduce the problem you're seeing.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by NarHakobyan** [comment]
same for me when insterting dates

**Comment by imnotjames** [comment]
Without more information we can't replicate / fix this.

**Comment by himalayaahuja** [comment]
@imnotjames Same issue being faced, when executing the raw query generated by query builder against database manually (via script) yields 0 rows and when using `.getMany()` method on the same query builder then it yields 9 rows.

Using "typeorm": "^0.3.16"
DB: Postgres

**Comment by itse4elhaam** [comment]
Facing the same issue, any fix?

**Comment by naorpeled** [comment]
> Facing the same issue, any fix?
> 

Hey,
can you share a reproduction?

I'd love to help with this but need more context 🙏
