### ISSUE TITLE
ORM is wanting to create the table when it already exists 

### ISSUE THREAD

**Issue by metenawy** [typeorm/typeorm#6082]
**Issue type:**
[ x] question

**Database system/driver:**

[ x] `mysql` / `mariadb`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
at the first time the table is created successfuly but after that agot the error the table is already exist , i modified synchronize: false and error was gone but i don't need to set this parameter to false in development stage , and i found some articls showed examples and this parameter was true and working fine .
like this 
[typeorm-migrations-explained](https://medium.com/better-programming/typeorm-migrations-explained-fdb4f27cb1b3)
<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

**Comment by Zuoguangcheng** [comment]
I have the same question,  how to resolve。version: 0.2.24

**Comment by pablo-abc** [comment]
The article linked says this about migrations:
```
To get started with migrations, the first thing you should do is set synchronize: false in ormconfig.json.
```

You shouldn't use `synchronize: true` and migrations together. When using migrations, TypeORM keeps the state of the current migration on a DB table (as far as I understand). If you set synchronize it with `synchronize: true`, the state saved by TypeORM will no longer match the current state of the DB. I do prefer to use migrations over synchronization for production environments since it has a more deterministic outcome.

**Comment by RajanZhan** [comment]
@

> I have the same question, how to resolve。version: 0.2.24

I got the  same question, I set the entity  table  name like this "minitools_dayknow_day**K**nowledge", it is in trouble. but is ok like this "minitools_dayknow_dayknowledge",so I changed the table name. maybe you can try.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
If you add the above information please re-open this issue.

As it stands it's not possible to reproduce your problem with the information provided.
