### ISSUE TITLE
TypeORM not working with WebPack

### ISSUE THREAD

**Issue by mtwzim** [typeorm/typeorm#6225]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[x] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**WebPack version:**
[x] `4.43.0`

## Current Behavior
Hello guys, I'm creating a cli app with typeorm (private), and well, I've been working on this app and I recently added the webpack, however it seems that there are no returns on connections, however when I just compile the cli app everything works.

## Expected Behavior
It was for when I compile with the webpack to work perfectly.

## Steps to Reproduce
Build my app
npm install dependencies
run web pack

## My WebPack config
```
const path = require('path');
const Dotenv = require('dotenv-webpack');

module.exports = {
  entry: './dist/main.js',
  devtool: 'inline-source-map',
  target: 'node',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: [ '.js' ],
  },
  plugins: [
    new Dotenv()
  ],
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
};
```
dist/main.js already compiled ts code

See the differents print, the first is without webpack, and the secont is with webpack:
![image](https://user-images.githubusercontent.com/42474938/83983161-78352900-a902-11ea-81fe-6152efa58231.png)
![image](https://user-images.githubusercontent.com/42474938/83983149-6a7fa380-a902-11ea-8cdd-66467499e3a1.png)

Thank'u

**Comment by imnotjames** [comment]
> Build my app

Where is your app to reproduce this with?

**Comment by imnotjames** [comment]
Without a reproducible example we can't help much.  If you can include it we can confirm if this is a problem with your application or TypeORM.

Looks like this is more of a question & support request than a bug report.

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
