### ISSUE TITLE
Wasm/Rust bindings for compute

### ISSUE THREAD

**Issue by somehowchris** [typeorm/typeorm#6292]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

I'm a huge fan of typeorm but sometimes hate the slowness of node. That's exactly why I created this issue.

I now dug about 3 weeks into rust and it's really fast (list fast af) and with webassembly or ffi you can have some code snippets written in js and some in rust. Me as a mostly relational database user for work would love to see those rust speeds inside compute heavy parts of typeorm.

In the end it would be amazing to integrate webassembly into typeorm.

I know this seems a bit far but I'm really missing typeorm in rust. If there's going to be some rust part in typeorm it would be amazing to have a crate for it and then have it integrated into typeorm or a rust style clone :)

**Comment by Kononnable** [comment]
@somehowchris 
Wasm won't work for connecting to dbs. It is meant to be used by browsers, so no tcp/udp streams because of security concerns. There is a WASI, which will allow I/O to be directly used in some environments where we can use wasm. I'm not aware of status of work on WASI, but it might take some time for it to be usable and for node to support that format.
Anyhow, technically it's not a blocker for node side of things - same idea can be implemented using native modules.

**Comment by UnsolvedCypher** [comment]
If you're using Rust, you should probably use a Rust ORM like [Diesel](http://diesel.rs/). Because of the requirements of the borrow checker and type checker in Rust, it's much easier to improve an existing Rust ORM than to try to use bindings to one written for Node.

**Comment by imnotjames** [comment]
I'm gonna echo to use diesel.  We already have enough trouble with the platforms we support now.  Maintaining official rust bindings (or rewriting?) Is not tenable.
