### ISSUE TITLE
Allow Repositories to be singletons, and still work in transactions

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#6337]
this request is basically to have Repositories mimick Spring Data

**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

In spring you can do something like (written in ts, which spring doesn't support)

```ts
@service
class FooService {
  constructor( private readonly fooRepo: FooRepo, private readonly barRepo: BarRepo ) {}

  @transactional
  doTheNeedful(foo: Foo) {
        await this.barRepo.findOne(foo.bar.id);
        // conditionals/setters/copies
        await this.fooRepo.save(foo);  }
   }
```

I'm not asking that typeorm provide dependency injection, but I'd like to be able to use it with transactions, here's an example using `@aurelia/kernel` `DI`

```ts
@singleton
class FooService {
  constructor( private readonly fooRepo: FooRepo, private readonly barRepo: BarRepo, private readonly txnm: TransactionManager  ) {}

  doTheNeedful(foo: Foo) {
     this.txnm.transaction(() => {
        await this.barRepo.findOne(foo.id);
        // conditionals/setters/copies
        await this.fooRepo.save(foo);
     });
  }
}
```

in order to do this, the Repo itself would have to not be a chained promise, instead Connection, or EntityManager would have to be passed in.

```ts
RepositoryFactory.create( Connection.pool(DataSource), FooRepo );
```

**Comment by imnotjames** [comment]
I don't think this is something that would be solved by a singleton repository - but if you wanted that you said it yourself.  You'd want a DI container to manage that.

Instead, what you're suggesting is that for a specific function you want to wrap all query runner calls in a transaction via a decorator - because that's how spring does it.

Except right there is the deal - the decorator on the function does this and you can too - look at all properties on the decorated functions object when called & if any are repository then start a transaction & afterwards commit or roll back.

Like you said - typeorm isn't a DI container and a singleton repository would have MANY weird side effects and has been requested a few times in the past without movement - so I don't think this is gonna happen.  As such, I'm gonna close this.
