### ISSUE TITLE
Can `merge` merge all fields?

### ISSUE THREAD

**Issue by 0x0ece** [typeorm/typeorm#6422]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Doing some experiments, is seems to me that `merge` only merges fields marked as `@Column`. Is this true? What's the rationale and is there a way to merge all the entities fields? Thank you

**Comment by imnotjames** [comment]
Yes - merge only works for columns because otherwise it could inadvertently merge things.

If you need to merge outside of TypeORM you can always create a helper function that wraps that call - first call merge for columns, then go through the rest of the entities as well and merge the fields you want.

**Comment by imnotjames** [comment]
For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
