### ISSUE TITLE
errors thrown by orm don't have a type

### ISSUE THREAD

**Issue by adnan-kamili** [typeorm/typeorm#643]
Usually all the exceptions are handled in an app at a single place (Exception Middleware). Other ORM's usually provide a type for the error like Sequelize throws errors with type SequelizeError (instance of SequelizeError) so they can be easily identified and converted to validation errors etc. 

Something similar should be provided so that db errors can be easily identified in a systematic manner. Currently, error format is:

```javascript
{
  code:"ER_NO_DEFAULT_FOR_FIELD"
  errno:1364
  index:0
  message:"ER_NO_DEFAULT_FOR_FIELD: Field 'name' doesn't have a default value"
  sqlState:"HY000"
}
```
Currently what I can do is check for `sqlState` property in error, but that's not an elegant solution.

Secondly, the error message is not user-friendly. ER_NO_DEFAULT_FOR_FIELD: is repeated twice which makes the otherwise user-friendly message unpresentable.

**Comment by pleerock** [comment]
>  the error message is not user-friendly. ER_NO_DEFAULT_FOR_FIELD: is repeated twice which makes the otherwise user-friendly message unpresentable.

typeorm returns underlying driver's error. So this issue is specific to node-mysql package. But I don't think its not user-friendly, because "message" is used in error message, which means when error occur it shows in console only message, e.g. no "code" property is shown, but we still want to know code in this error message. That's why it stands there.

I have created `QueryFailedError` error wrapper with additional info. This will be released in next `0.1.0-alpha.33` version.
