### ISSUE TITLE
Question: Event Subscribers and Transactions

### ISSUE THREAD

**Issue by malisetti** [typeorm/typeorm#6436]
**Question**
If a db transaction has 2 different table updates/inserts, will the subscriber action for the first entity be called after the  completion of transaction, i.e Will I get the latest change of second entity that happened in transaction in the subscription function of first entity ?

**Database system/driver:**

`postgres`

**TypeORM version:**

`latest`

**Comment by greenreign** [comment]
Since I've been struggling with this mightily I think I can say almost certainly that you will not.  If you were to re-query using he `EntityManager` passed into the event then you would get the sandboxed data for the uncommitted transaction but all event subscriptions run before the transaction is committed.

**Comment by greenreign** [comment]
See 
https://github.com/typeorm/typeorm/issues/1705
https://github.com/typeorm/typeorm/issues/2816

**Comment by imnotjames** [comment]
Looks like the question was answered.

For other questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
