### ISSUE TITLE
ormconfig file ignored if it's not a json file and explicitly passed with --config option

### ISSUE THREAD

**Issue by develo-pera** [typeorm/typeorm#6441]
**Issue type:**

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have a config file named `ormgconfig.js` with the following configuration:

``` js
const { join } = require('path');

require('dotenv-safe').load({
  allowEmptyValues: false,
  path: join(__dirname, '.env'),
  sample: join(__dirname, '.env.example'),
});

module.exports = {
  entities: ['./build/entities/*.js'],
  logging: 'all',
  migrations: ['./migrations/*.ts'],
  type: 'postgres',
  url: process.env.POSTGRES_URL,
  cli: { migrationsDir: 'migrations' },
};
```

I expect when I run `typeorm migration:create -n Test` that the migration file is created inside `migrations` folder in the root of the project, but instead of that, migration file is created outside of that folder, directly in the root folder.

I tried switching to .ts and also tried to pass both files as arguments with `--config ormconfig.js` and `--config ormconfig.ts` but nothing changed. The only thing that's working like expected and that actually creates a file inside `migrations` folder is when I switch to `ormconfig.json` and explicitly pass `--config ormconfig.js`

**Comment by dmythro** [comment]
Yeah, have this too, don't think it's related to a driver (we use `mysql`).

**Comment by imnotjames** [comment]
I can't replicate but there might be a few cases here that could be happening:

1: You're trying to use `typeorm` globally and only have `dotenv-safe` loaded locally.  The problem here is that TypeORM is operating from a "global" context so it isn't set up to pull modules when running as a CLI from the context of your local project.    We're looking into what can be done for this, but haven't made too much headway.  You end up with an error and TypeORM silently discards your config.

2: You've not installed dotenv-safe` at all.  You just gotta install it.

3: Some other JS error is happening when loading your config and TypeORM silently discards your config.

For all of these, if you'd like further help debugging, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
