### ISSUE TITLE
Connection mysql with typeorm without server?

### ISSUE THREAD

**Issue by juan-rangel** [typeorm/typeorm#6455]
**Issue type:**

[ x ] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ x ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ x ] `react-native`
[ x ] `expo`

**TypeORM version:**

[ x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hi guys, any chance of being able to connect React Native to Mysql with TypeOrm without using the Js Node, Express or other server-side structure?

**Comment by imnotjames** [comment]
The MySQL clients used by TypeORM are explicitly for NodeJS, without support for React-Native.

While you might be able to get it to work with a LOT of work - eg, you'd need to write your own `mysql` client, then set up the bindings for Android & iOS, then get the react native bindings, and only THEN write a driver for `TypeORM` - it's not exactly feasible.

Perhaps look into something like Firebase instead of TypeORM?
