### ISSUE TITLE
can't use order by with take and skip

### ISSUE THREAD

**Issue by xenoterracide** [typeorm/typeorm#6515]
I get this when using QueryBuilder with an `orderBy` and `take/skip` the exception itself is terrible

```
      at src/query-builder/SelectQueryBuilder.ts:1943:145
              at Array.map (<anonymous>)
      at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.createOrderByCombinedWithSelectExpression (src/query-builder/SelectQueryBuilder.ts:1938:14)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:1855:46)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.next (node_modules/tslib/tslib.js:122:57)
      at node_modules/tslib/tslib.js:115:75
      at Object.__awaiter (node_modules/tslib/tslib.js:111:16)
      at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.executeEntitiesAndRawResults (node_modules/typeorm/query-builder/SelectQueryBuilder.js:1382:24)
      at SelectQueryBuilder.<anonymous> (src/query-builder/SelectQueryBuilder.ts:1056:40)
      at step (node_modules/tslib/tslib.js:141:27)
      at Object.next (node_modules/tslib/tslib.js:122:57)
      at node_modules/tslib/tslib.js:115:75
      at Object.__awaiter (node_modules/tslib/tslib.js:111:16) {
            [stack]: "TypeError: Cannot read property 'databaseName' of undefined\n" +
      '    at /Users/calebcushing/IdeaProjects/service-graph/src/query-builder/SelectQueryBuilder.ts:1943:145\n' +
              '    at Array.map (<anonymous>)\n' +
      '    at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/Users/calebcushing/IdeaProjects/service-graph/src/query-builder/SelectQueryBuilder.ts:1938:14)\n' +
      '    at SelectQueryBuilder.<anonymous> (/Users/calebcushing/IdeaProjects/service-graph/src/query-builder/SelectQueryBuilder.ts:1855:46)\n' +
      '    at step (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:141:27)\n' +
      '    at Object.next (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:122:57)\n' +
      '    at /Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:115:75\n' +
              '    at new Promise (<anonymous>)\n' +
      '    at Object.__awaiter (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:111:16)\n' +
      '    at SelectQueryBuilder.Object.<anonymous>.SelectQueryBuilder.executeEntitiesAndRawResults (/Users/calebcushing/IdeaProjects/service-graph/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1382:24)\n' +
      '    at SelectQueryBuilder.<anonymous> (/Users/calebcushing/IdeaProjects/service-graph/src/query-builder/SelectQueryBuilder.ts:1056:40)\n' +
      '    at step (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:141:27)\n' +
      '    at Object.next (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:122:57)\n' +
      '    at /Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:115:75\n' +
              '    at new Promise (<anonymous>)\n' +
      '    at Object.__awaiter (/Users/calebcushing/IdeaProjects/service-graph/node_modules/tslib/tslib.js:111:16)',
            [message]: "Cannot read property 'databaseName' of undefined"
          },
          extensions: { code: 'INTERNAL_SERVER_ERROR' }
        },
        [length]: 1
      ]
```

**Comment by imnotjames** [comment]
Please include a minimally reproducible example.  A stack trace is nice but we don't get the whole picture.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by xenoterracide** [comment]
closing for now because I've switched projects and never had a chance to create a minimal reproduction.
