### ISSUE TITLE
`.andWhere` is having a side effect on original QueryBuilder instance

### ISSUE THREAD

**Issue by dadooda** [typeorm/typeorm#6658]
**Issue type:**

[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.25` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

```typescript
let qb = this.postRepo.createQueryBuilder("post")
qb.andWhere(`post.boardId = :boardId`, { boardId: 5 })  // Not a `qb = qb.andWhere`!
qb.andWhere(`post.boardId = :boardId`, { boardId: 5 })
qb.andWhere(`post.boardId = :boardId`, { boardId: 5 })
qb.getCount()
// See `[5,5,5]` in SQL query despite the fact I'm using the original `qb`.
```

In the example above **I don't fetch** an updated instance of `qb`, just discard the value silently. Nevertheless, original `qb` gets modified. If this side effect is by design, it must be documented appropriately.

Needless to say this issue **is causing enormous pain,** esp. when you have to fire a few dozen slightly varying queries, e.g. to produce a stats report. In a functional language we shouldn't expect original `qb` to be modified, but expect a derived value instead. But, if that's by current design, it should be stated ALL CAPS in the docs.

Thank you authors for a great library.

**Comment by jgburet** [comment]
This hasn't been written in a FP way, otherwise it would have been stated. I don't see any lack in the documentation here.
Having this functionality not working the way you wanted is not the documentation's fault. It never said you could use it the way you did.

As of today, a query builder is an instance that you build progressively. The first `qb` you get is the same as the one you get on the following calls as all these methods return the same instance, `this`.
If all you want is to have similar builders, clone them. (nope, there's no `clone` method...)

**Comment by RobertSandiford** [comment]
Just here to say that I was also surprised by this.

I think I tend to expect functional behaviour, as it's more common than not in javascript.

Mozilla documentation states whether a function has side effects or not in the first statement: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

I would favour the same approach here, making this clear at the earliest opportunity in the docs.

As a best practice - what you actually do is up to you
