### ISSUE TITLE
Create pagination in a relationship

### ISSUE THREAD

**Issue by fera765** [typeorm/typeorm#6691]
**Issue type:**

[ ] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [ ]  `mysql`
    [x] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

I would like to paginate a relationship

I am currently using .left Join And Select

**Comment by kateile** [comment]
It will be much easier for you to get help if you include some codes

**Comment by fera765** [comment]
```js
    const findPost = await this.ormRepository
      .createQueryBuilder('posts')
      .where('posts.user_id IN (:...ids)', { ids: users_id })
      .leftJoin('posts.likes', 'likes')
      .loadRelationCountAndMap('likes.countLikes', 'posts.likes')
      .leftJoinAndSelect('posts.user', 'user')
      .leftJoinAndSelect('posts.comments', 'comments')
      .orderBy('posts.created_at', 'DESC')
      .take(per_page)
      .skip(page)
      .getMany();
```

So I would like to make a pagination or put a limit on the comments relationship, would there be any way to do that?

**Comment by kateile** [comment]
Why don't you create 2 separate methods for **fetching post** and **fetching comment**? Because if you succeed in what you are trying to archive, you will be fetching the same post every time pagination occurs, so fetching **the same post will occur over and over** which is wastage of resources. I would recommend for you to create a separate methods, something like
```
fetchComments(postId:number) {
//here fetch only comments and do pagination
}
```
That would be a good arc practice.
Sorry I haven't answer would you real asked, but this way it will be much easier and efficient

**Comment by fera765** [comment]
Yes, I created a service that only returns comments for a given post., more thanks for the comment
