### ISSUE TITLE
How this shit to use?!

### ISSUE THREAD

**Issue by vrg-success** [typeorm/typeorm#6702]
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x ] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)
I just want write this query to queryBuilder
```sql
SELECT 
    DISTINCT ON (cu."conversationId") cu."conversationId",
    conversations."createdDateTime",
    messages.id "messageId",
    messages."sentDateTime" "messageSentDateTime",
    messages.message "messageText",
    (
        SELECT COUNT(messages."receiverRead") "unreadMessages" FROM messages
        WHERE 
            messages."conversationId" = cu."conversationId" 
            AND messages."senderUserId" != '69e56a68-edbd-4f8b-8ccd-cb8031c5c865'
            AND messages."receiverRead" = false
            AND messages.id NOT IN (
                SELECT messages_deleted."messageId" FROM messages_deleted
                WHERE messages_deleted."userId" = '69e56a68-edbd-4f8b-8ccd-cb8031c5c865'
            )
    )
FROM conversations_users cu 
INNER JOIN conversations ON conversations.id = cu."conversationId" AND conversations.status = 'active'
LEFT JOIN messages ON messages."conversationId" = conversations.id
WHERE 
    cu."userId" = '69e56a68-edbd-4f8b-8ccd-cb8031c5c865' AND cu."isDeleted" = false
    AND
    messages.id NOT IN (
        SELECT messages_deleted."messageId" FROM messages_deleted
        WHERE messages_deleted."userId" = '69e56a68-edbd-4f8b-8ccd-cb8031c5c865'
    ) 
ORDER BY cu."conversationId", messages."sentDateTime" DESC;
```
When I tried do that, I started cursing the orm, I got million issue, I got problem with select, I got problem with Distinct, It's absolutly trash ORM. The ORM good for trivial task, but if I have difficult query - I will get a issues....

**Comment by pleerock** [comment]
dear Rustamjon, if you have million issues, most probably you don't understand ideas behind ORM and use it inproperly. 

It's hard to organize pagination properly, simply because non of RDBMS support this functionality out of the box. They don't support it because of specifics database results being returned in a **rows**.

ORM tries to help you organize a pagination, just to **help** you as much as it can, and does sacrifice in some cases in order to support other cases. So yes, not your every query is supported. In cases, when it doesn't support your query - it's your responsibility to implement pagination without using `skip` and `take` properties of TypeORM.

If you think it's a trash, then use something that is not a trash. Toxic behaviour isn't welcomed in this repository.
