### ISSUE TITLE
🐛 Redis parser throwing an error every 1 hour

### ISSUE THREAD

**Issue by AdelUnito** [typeorm/typeorm#6716]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.2.x`

**PG version:**

[x] `7.x`

**Steps to reproduce or a small repository showing the problem:**

I'm getting the following error every 1 hour in production and I wasn't able to reproduce it locally

```bash
{ AbortError: Fatal error encountered. Command aborted. It might have been processed.
    at RedisClient.flush_and_error (/.../node_modules/redis/index.js:297:23)
    at JavascriptRedisParser.returnFatalError (/.../node_modules/redis/index.js:148:18)
    at handleError (/.../node_modules/redis-parser/lib/parser.js:196:10)
    at parseType (/.../node_modules/redis-parser/lib/parser.js:304:14)
    at JavascriptRedisParser.execute (/.../node_modules/redis-parser/lib/parser.js:533:24)
    at Socket.<anonymous> (/.../node_modules/redis/index.js:218:27)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
  code: 'NR_FATAL',
  command: 'INFO',
  origin:
   { ParserError: Protocol error, got "\u0015" as reply type byte. Please report this.
       at handleError (/.../node_modules/redis-parser/lib/parser.js:190:15)
       at parseType (/.../node_modules/redis-parser/lib/parser.js:304:14)
     offset: 1,
     buffer: '{"type":"Buffer","data":[21,0,0,0,2,1,0]}' } }
```

My ormconfig file:

```js
require('dotenv').config();
let ormConfig = {
  "name": "default",
  "type": process.env.ORM_DATABASE_TYPE,
  "host": process.env.ORM_DATABASE_HOST,
  "port": process.env.ORM_DATABASE_PORT,
  "username": process.env.ORM_DATABASE_USERNAME,
  "password": process.env.ORM_DATABASE_PASSWORD,
  "database":  process.env.ORM_DATABASE_NAME,
  // synchronize ensures entities are synced with the database, every time the app is run
  "synchronize": true,
  // This code will log all queries which run more then 1 second
  "maxQueryExecutionTime": 1000,
  "entities": [
    "dist/src/entity/**/*.js"
  ],
  "migrations": [
    "dist/src/migration/**/*.js"
  ],
  "subscribers": [
    "dist/src/subscriber/**/*.js"
  ],
  "cli": {
    "entitiesDir": "src/entity",
    "migrationsDir": "src/migration",
    "subscribersDir": "src/subscriber"
  }
};


const ormLogLevels = process.env.ORM_LOG_LEVEL ? process.env.ORM_LOG_LEVEL.split(',') : ['all'];
ormConfig = {
  ...ormConfig,
  "logging": ormLogLevels,
};


if (process.env.REDIS_HOST && process.env.REDIS_PORT) {
  ormConfig = {
    ...ormConfig,
    "cache": {
      "type": "redis",
      "options": {
        "host": process.env.REDIS_HOST,
        "port": process.env.REDIS_PORT
      }
    }
  }
}

module.exports = ormConfig;
```

My Redis is on AWS elasticach redis cluster.

**Comment by imnotjames** [comment]
That looks to be a problem with either node-redis or elasticache - not TypeORM.

What version of `node-redis` do you have installed

**Comment by AdelUnito** [comment]
> node-redis

@imnotjames I don't have `node-redis` installed, I have [redis](https://www.npmjs.com/package/redis) v3.0.2 installed

**Comment by imnotjames** [comment]
This does not look like an issue with TypeORM (and might have to do with the redis instances you've spun up, but who knows) - but if you think it's an issue with how TypeORM is using the redis library please create a reprodicible example separate from your environment which replicates this issue.  I suggest docker instances to accomplish that.

If you do, we'll reopen this issue & dig into it further.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
