### ISSUE TITLE
adding jwt authguard throws unauthorized error

### ISSUE THREAD

**Issue by shanipasr** [typeorm/typeorm#6756]
**Issue type:**

[ ] bug report

**Database system/driver:**

[ ] `mysql`

**TypeORM version:**

[ ] `latest`

I have written the following login module with the nesjts 'typeorm'.

```
@Post('login')  
public async login(@Body() data) {            
return await this.authService.login( data);  
}
```
It works fine and send me the desired result (contains the jwt token).

But when I add `@UseGuards(AuthGuard('jwt'))` at the top of this service, I get the error` 401, unauthorized.`

I don't understand why it gives this error, because when I login I will protect it.

**Comment by moontai0724** [comment]
I think it’s not a bug of typeorm.
Did you put your JWT into headers, or where you desired to receive?
Please take a look to documentation.

**Comment by imnotjames** [comment]
This sounds unrelated to TypeORM and more if an issue with nestjs.  None of these aspects of you're code directly map up to TypeORM.

Please open an issue against nestjs and if the actual issue is found to be somewhere with TypeORM with some reproducible code please reopen an issue.

**Comment by nrayburn-tech** [comment]
This is an issue with how you have configured nestjs, definitely is not a TypeORM issue.

Your login route is being protected by the jwt guard.  Because it is protected, you can never access it to get a valid jwt.  The login route should be protected by a different guard, or not protected at all.
Here is a link to the docs, https://docs.nestjs.com/techniques/authentication.  There are also one or two good issues in the nestjs github issues that may help you.
