### ISSUE TITLE
Identity Map

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm#677]
Hello!

The TypeORM is not utilizing the **identity map** pattern, often found in enterprise ORMs. Could you please share the reasoning behind this design decision or exact problems you've faced when trying to implement it?

Right now, this approach makes event-driven decoupled systems very difficult to implement, because different parts of application is not aware of entities already fetched and modified (but not yet persisted) in other parts of application, and there is no guarantees about order of events. Does it mean, that TypeORM is not suitable for such decoupled code, or are you planning to address this issue in the future somehow?

Thank you!

**Comment by pleerock** [comment]
I don't see any relation between identity map and decoupling. I don't know how you design `event-driven decoupled systems` but when you say `different parts of application is not aware of entities` it already smells like different part of application are coupled on shared state of entities. But they shouldn't be, right? They must use events instead of sharing state.

I don't see identity map as good fit in TypeORM. TypeORM has its own way and have some difference with other ORMs. Plus TypeORM uses different environment and language - JavaScript which is more functional then Java, PHP and others. 

The fact they use identity map does not necessary mean its better, sometimes they force to use such patterns because of platform specifics/limitations they have.

Identity map has its own pros and cons and at the moment I don't think TypeORM needs it. If I introduce it in TypeORM there will be lot of new unpleasant problems we'll need to design, implement and fix. There are few problems it will solve as well however.
