### ISSUE TITLE
The number of idle connections is too high. How typeorm handles idle connections? 

### ISSUE THREAD

**Issue by sontd-0882** [typeorm/typeorm#6793]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[ ] `latest`
[ ] `@next`
[x] `0.x.x` (v0.2.24)

**Steps to reproduce or a small repository showing the problem:**
Can you tell me how typeorm handles idle connections? 

I'm running into a problem that the number of idle connections is too high, meanwhile, the number of active connections is really small.

I'm not sure but those idle connections keep CPU and RAM, that cause the performance slows down.

This is DB session charts from PG Admin.
 
![a9f30208eaeb7051075f99bc8eb9ad9c](https://user-images.githubusercontent.com/49388081/94382845-69e87280-0168-11eb-894f-cb19d5aea2ba.png)

![image_2020_9_28](https://user-images.githubusercontent.com/49388081/94382849-6fde5380-0168-11eb-8b74-7c8b218bea9e.png)

**Comment by imnotjames** [comment]
How are you configuring the Postgres driver?

**Comment by sontd-0882** [comment]
@imnotjames Thanks for replying.

This is my `ormconfig.js` file. `idleTimeoutMillis` must be `30000` by default, I guess.

```js
{
...
production: {
    type: 'postgres',
    host: process.env.DATABASE_HOST,
    port: process.env.DATABASE_PORT,
    username: process.env.DATABASE_USERNAME,
    password: process.env.DATABASE_PASSWORD,
    database: process.env.DATABASE_PRODUCTION_NAME,
    synchronize: false,
    logging: true,
    entities: ['dist/**/*.entity.js'],
    migrations: ['dist/database/migrations/*.js'],
    cli: { migrationsDir: 'src/database/migrations' },
    migrationsTableName: 'migrations',
  }
}

**Comment by imnotjames** [comment]
Do you have multiple node processes?  By default there should only be max 10 connections to Postgres in the pool.

**Comment by imnotjames** [comment]
I know replication a server under stress can be difficult but that's be the ideal scenario - a way for is to replicate this behavior.

**Comment by sontd-0882** [comment]
> Do you have multiple node processes?
My application is deployed on k8s. There were 30 pods then.

> And you're sure that this is typeorm making all these connections? Is there any way we can verify that?
Yes! There is only one other connection from my pgAdmin, all over 100+ connections are from the node application.

**Comment by imnotjames** [comment]
Perhaps sets the idle timeout & max connections per pool to be lower.  I don't think this is exactly a typeorm issue, it's an issue you'd run into with any language and any framework.

Thing is - that's only about 3 per pod so you'll be running into this problem under load @ 10 per pod.. pretty much no matter what.  If all of them exhaust their connection pools you'll have a worst case of 300 connections 

And even 300 idle connections should be fine memory-wise but I think it's above the limit normally available through their docker container.

If you need to cut down on connections but can't change any settings you might want to look into setting up read replicas or configuring a reverse proxy for Postgres.  That's a bit outside the scope of this project though.

**Comment by Alynva** [comment]
@imnotjames shouldn't be an configurable way to say that connections with inactivity should be closed? If later, another connection is requested, so it will be created/connected again.

I'm running into a problem where I think that the pool references just gone, maybe because its created inside a worker, child process or something (but the connection still open), and in the next request, the pool is empty and it creates another connection, but the others that is already connected never closes, so the connection count on the database goes up very easily. I'm running the API with `sls offline` to run aws lambda functions locally, I don't think that it would happen after deploy, because in the cloud the functions will never share the same resource, process or anything that `sls offline` does.

**Comment by imnotjames** [comment]
That feature is available with many of the drivers when configuring their underlying pool implementations.  For example, with postgres it's `idleTimeoutMillis`.

**Comment by Alynva** [comment]
I'm using mysql, didn't find that config

**Comment by alfonsogarza** [comment]
@Alynva I'm having similar issues but running on Postgres, did you find a solution or the root problem?

**Comment by vlad-healthhelper** [comment]
Hi guys. I also have this issue running `queryRunner.manager.query` to use SQL on a complex query instead of typeorm. Every request a new session is created and it is never released.
You can see me making 10 requests one after another, each request creates a new session. 11th request never returns and the NestJS application just hangs and no calls can be made to the DB. You can the see me shutting down the service and the sessions are released at that point
<img width="693" alt="Screen Shot 2022-10-19 at 4 39 26 PM" src="https://user-images.githubusercontent.com/101212640/196824522-3efcf6f3-6605-40d4-b1d7-543d71c7fe89.png">

**Comment by vlad-healthhelper** [comment]
Just realized that I needed to call `.release()` manually
```
try {
      const records = await queryRunner.manager.query(<QUERY HERE>, params)
      return records
    } catch (e) {
      this.logger.error(e)
      throw new BadRequestException('Unable to get the data')
    } finally {
      await queryRunner.release()
    }
```
