### ISSUE TITLE
TypeScript compilation fails with version v0.2.27 : error TS2611

### ISSUE THREAD

**Issue by rbutera** [typeorm/typeorm#6805]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[x] `latest`
[x] `0.2.27` 

**Steps to reproduce or a small repository showing the problem:**

The issue appears to be related to `MongoEntityManager.d.ts`:

```shell
[node_modules/typeorm/entity-manager/MongoEntityManager.d.ts:27:9 - error TS2611: 'queryRunner' is defined as a property in class 'EntityManager', but is overridden here in 'MongoEntityManager' as an accessor.

27     get queryRunner(): MongoQueryRunner;
           ~~~~~~~~~~~

Found 1 error(s).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I manually installed 0.2.26 and compilation succeeded.

**Comment by Cristiandi** [comment]
I'm using the version 4.0.3 of typescript, same problem.

**Comment by anhphantien** [comment]
I also ran into the same problem as @Cristiandi. Please fix this.

**Comment by kayotimoteo** [comment]
Same problem here TypeScript version 4.0.3.

**Comment by imnotjames** [comment]
We aren't currently using 4.0 yet - perhaps there's a compatibility feature we didn't enable for the latest release?

**Comment by imnotjames** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#properties-overriding-accessors-and-vice-versa-is-an-error

Looks like the issue was introduced in the type definitions as of Typescript 3.7 - https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html - because there's a problem with overriding properties with accessors.

And for some reason our build wasn't using this until 0.2.27 - not sure the cause there, as we should have been updating over time.

If we drop to Typescript 3.6.0 it should fix this issue - but it does mean that TypeORM as a project is stuck on that until whenever we can create a breaking change.  What a pain. :|

**Comment by imnotjames** [comment]
This should be fixed as of 0.2.28

**Comment by Cristiandi** [comment]
@imnotjames everything working for me with 0.2.28 TY!

**Comment by anhphantien** [comment]
@imnotjames Thank you so much, bro! :)

**Comment by ahrasel** [comment]
after update dependency typeorm to v0.2.28. it's work for me
