### ISSUE TITLE
problem when implementing order by random

### ISSUE THREAD

**Issue by fera765** [typeorm/typeorm#6840]
**Issue type:**

[x] bug report
[ ] feature request
[x] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[x] `@next`
[x] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

<!--
    To answer those questions you need to put "x" inside the square brackets, for example:
    [x] `mysql`
    [ ] `postgres`

    Also, please format your code properly (by taking code blocks into ```ts .... ```)
--!>

This apparently deals with a bug, because when I try to make a query using a raw query it works normal.

when I use order By ('rand ()'), I have this problem >   message: 'function rand() does not exist',

when I use order By ('random()'), I have this problem >  message: 'for SELECT DISTINCT, ORDER BY expressions must appear in select list',

**Comment by imnotjames** [comment]
Could you include a way to replicate your issue?

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by fera765** [comment]
> Você poderia incluir uma forma de replicar o seu problema?
> 
> Quando a abertura de um problema, as pessoas serão mais capazes de oferecer ajuda, se você fornecer o código que eles possam facilmente entender e usar para reproduzir o problema. Isto resume-se a assegurar o seu código reproduz o problema segue as seguintes diretrizes:
> 
> * Mínimo – Usar o mínimo de código possível que ainda produz o mesmo problema
> * Completa – Fornecer todas as partes alguém precisa para reproduzir o seu problema em questão em si
> * Reproduzível – Teste o código que você está prestes a fornecer para certificar-se de que reproduz o problema
> 
> ## O mínimo de
> O código mais há para percorrer, a menos provável que as pessoas podem encontrar o seu problema. Simplificar o seu exemplo de duas maneiras:
> 
> 1. Recomeçar do zero. Criar um novo programa, adicionando-se apenas o que é necessário para ver o problema. De uso simples, nomes descritivos para variáveis e funções – não copie os nomes que você está usando no seu código existente.
> 2. Dividir e conquistar. Se você não tiver certeza de que a origem do problema é, começar a remoção de código um pouco de cada vez até que o problema desaparece – em seguida, acrescente a última parte de trás.
> 
> Não sacrifique a clareza para fins de brevidade, quando a criação de um mínimo exemplo. O uso consistente de nomenclatura e de recuo, e incluem comentários de código se necessário. Use o seu editor de código de atalho para formatação de código.
> 
> Não incluem quaisquer senhas ou credenciais que devem ser mantidos em segredo.
> 
> ## Completo
> Certifique-se de que todas as informações necessárias para reproduzir o problema está incluída no problema em si.
> 
> Se o problema requer algum código, bem como algumas baseado em XML de configuração, incluir o código para ambos. O problema pode não estar no código que você acha que ele se encontra.
> 
> Uso individual de blocos de código para cada arquivo ou trecho que você incluir. Fornecer uma descrição do propósito de cada bloco.
> 
> **NÃO** use imagens de código. Copie o texto real do seu editor de código, cole-o isso e, em seguida, formate-a como código. Isso ajuda os outros mais facilmente ler e testar seu código.
> 
> ## Reproduzível
> Para ajudá-lo a resolver o seu problema, outros precisarão verificar se ela existe.
> 
> Descrever o problema. "Não trabalho" não é suficientemente descritivo para ajudar as pessoas a entender o seu problema. Em vez disso, diga a outros leitores que o comportamento esperado deve ser. Conte para os outros leitores que o texto exato da mensagem de erro é, e qual a linha de código é a produzi-lo. Use uma breve, mas descritivo resumo do seu problema como o título da sua pergunta.
> 
> Eliminar quaisquer problemas que não são relevantes para o problema. Se a sua pergunta não se trata de um erro do compilador, certifique-se de que não existem erros de tempo de compilação.
> 
> Verifique que o seu exemplo reproduz o problema! Se você inadvertidamente corrigido o problema ao compor o exemplo, mas não testá-lo novamente, você iria querer saber que antes de pedir a alguém para ajudar.


```js
    const findAllPosts = await this.ormRepository
      .createQueryBuilder('posts')
      .where('posts.user_id IN (:...ids)', { ids: users_id })
      .loadRelationCountAndMap('likes.count_likes', 'posts.likes')
      .loadRelationCountAndMap('comments.count_comments', 'posts.comments')
      .leftJoinAndSelect('posts.user', 'user')
      .leftJoinAndSelect('posts.files', 'files')
      .orderBy('random()')
      .take(per_page)
      .skip(page)
      .getMany();

    return findAllPosts;
```

**Comment by imnotjames** [comment]
This looks like an issue with how you're writing the query and not a bug in typeorm.

For support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by brunolcarlos** [comment]
How to use RAND in TypeORM ?
