### ISSUE TITLE
Load a relation in property of entity class with find*() method

### ISSUE THREAD

**Issue by devistar** [typeorm/typeorm#6849]
[x] bug report
[ ] feature request
[x] documentation issue

**Issue type:**

I want to retrieve an entity and one relation. I'm using a custom repository that extends Repository< T >.

```typescript
    async findById(id: string): Promise<T> {
        const pattern = await this.repository.findOne(id, { relations: ['patternCategory'] });
        console.log("pattern", pattern);

        if (!pattern) {
            throw new NotFoundException(`${this.tableName} with "${id}" not found`);
        }

        return pattern;
    }

```

I can see the query with relation in console but it doesn't load patternCategory property.

```
pattern PatternEntity {
  id: 'adcbd7be-248a-4966-ad0a-98684c491cc0',
  name: 'Basic Inside Turn',
  abbreviation: null,
  description: null,
  leaderExplanations: null,
  followExplanations: null,
  patternCategoryId: null,
  patternCategory: null
}
```

```typescript
Entity class

export class PatternEntity {
    @PrimaryColumn()
    id: string;

    @Column({
        unique: true,
    })
    name: string;

    @Column({
        nullable: true,
    })
    abbreviation: string;

    @Column({
        nullable: true,
    })
    description: string;

    @Column({
        nullable: true,
    })
    patternCategoryId: string;

    @ManyToOne(type => PatternCategoryEntity, patternCategory => patternCategory.patterns)
    patternCategory: PatternCategoryEntity;
}
```

How can I do to load patternCategory property with relation query ?
Is it a bug or I did it wrong ?

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[x] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[] `latest`
[ ] `@next`
[x] `0.2.26

**Comment by imnotjames** [comment]
This looks like an issue somewhere in the code you've implemented that's causing it to not work as expected.

I'd suggest trying some of our support systems for questions first before opening this as a bug report - as I can't tell from here that it's a bug or not.

If it turns out that it's a bug, then we can get an issue open.  If you do open a new issue please make sure you include everything needed for a minimally reproducible example - as it stands, you omitted a number of entities.  Something that can be made into a test case without much effort would be optimal.  Self-contained, you know?

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
