### ISSUE TITLE
Embedded entity with mana-to-many relation can not been remove

### ISSUE THREAD

**Issue by lichnow** [typeorm/typeorm#6878]
**Issue type:**

[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**
The user entity
```ts
@Entity('security_users')
export class User extends BaseEntity {
   ...
   @Column((type) => CustomerMixin)
    customer?: CustomerMixin;
}
```
CustomerMixin class
```ts
export class CustomerMixin {
      @ManyToMany((type) => Sea, (sea) => sea.users, { cascade: true })
      seas!: Sea[];
}
```
sea entity
```ts
@Entity('customer_seas')
export class Sea {
   ...
   @ManyToMany((type) => User, (user) => user.customer && user.customer.seas)
   @JoinTable()
    users!: User[];
}
```

After I call method `userRepository->remove(user)`

Get error
`Cannot set property 'seas' of undefined`

**Comment by imnotjames** [comment]
I believe there's an issue with your implementation, here, instead of an issue with TypeORM core.  I'm not sure what, but it looks like the `CustomerMixin` is not an entity but you're treating it like one 

For support on this, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support).

If you've found that it's indeed a problem with TypeORM let's reopen the issue then.

Cheers!
