### ISSUE TITLE
Emit ECMAScript Modules alongside CommonJS

### ISSUE THREAD

**Issue by imnotjames** [typeorm/typeorm#6974]
### The Problem

We do not emit ECMAScript modules - only CommonJS.  As the support for ESM becomes larger
it will be more and more common to need to use features from ESM like named exports.

### The Solution

As part of the process for building the CommonJS modules we should also emit a separate set of ECMAScript Modules.

This does not have to be a breaking change and [is described in the NodeJS documention.](https://nodejs.org/api/packages.html#packages_writing_dual_packages_while_avoiding_or_minimizing_hazards)

Adding something similar to this to the `package.json` could get us support for both:

```json
{
  "type": "module",
  "main": "./index.js",
  "exports": {
    "import": "./esm/index.js",
    "require": "./index.js"
  }
}
```

### Considered Alternatives

This could instead just be done as a breaking change - support only Node 12+ (or wherever ESM support started)
and just start emitting ESM.  That's a pretty difficult set of changes and could break code for a number of people.

### Additional Context

This came out of #6941

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tomasvvv** [comment]
any updates regarding this so far?

**Comment by Sti2nd** [comment]
TypeORM does not support ECMAScript Modules!
Just wanted to write it explicitly for others to see as I spent some hours trying to get it to work, then I finally found this issue.

**Comment by robogeek** [comment]
I'm sorry .. but today, this attitude is no longer useful:  "_ As the support for ESM becomes larger
it will be more and more common to need to use features from ESM like named exports._"  As the author of books on Node.js programming, I started encouraging my readers to fully adopt ESM modules a long time ago.

I'm in the middle of updating one of my books, and have the intention of demonstrating full ESM adoption from TypeScript code, but have run into this problem when trying to use TypeORM.

In order to load the TypeORM decorators, I've tried this:

```js
import * as TypeORM from "typeorm";
const Entity = TypeORM.Entity;
const Column = TypeORM.Column;
const PrimaryColumn = TypeORM.PrimaryColumn;
const ManyToMany = TypeORM.ManyToMany;
console.log(Entity);
console.log(TypeORM);
/* const { 
    Entity, 
    Column, 
    PrimaryColumn, 
    ManyToMany
} = TypeORM.default; */
```

But I get an error: `TypeError: PrimaryColumn is not a function`

The `console.log` statements show that `TypeORM.default.PrimaryColumn` does exist, but if I try to use that field from TypeScript, the compiler tells me there's no field named `default`.  

I don't see a route forward.  It seems the only solution is to inform my readers that TypeORM doesn't support use from ESM modules, despite ESM modules being the future.

JavaScript programmers will never get to enjoy the advantages of ESM modules if we don't take the steps necessary to get there.  At this stage that means learning how to generate hybrid modules that support both ESM and CommonJS use.
