### ISSUE TITLE
ManyToMany with private field

### ISSUE THREAD

**Issue by mbayou** [typeorm/typeorm#699]
Hi,

I try to create entity with relation many to many, but I want it on private field, so I created a getter. 

```typescript
/**     
 * User's circles     
 */     
@ManyToMany((type) => ActivityCircle, (activityCircle) => activityCircle.getUsers, {lazy: true})     
 private circles: ActivityCircle[];     
```

```typescript
/**
   * Circle's users
   */
  @ManyToMany((type) => User, (user) => user.getCircles, {lazy: true})
  @JoinTable()
  private users: User[];
```

When I tried it an error occurred 

``` {"message":"JoinTable is missing on User#circles many-to-many relationship. You need to put JoinTable decorator on it.","stack":"MissingJoinTableError: JoinTable is missing on User#circles many-to-many relationship. You need to put JoinTable decorator on it....```

Do you have any solution to fix it ? 

Thanks you.

**Comment by pleerock** [comment]
no, you can't use getter. Just do:

```ts
  @ManyToMany((type) => User, "circles", {lazy: true})
  @JoinTable()
  private users: User[];
```

But first think if you really need getters (mistake \#1 of users who come from java-like languages thinking they must use getters here as well).

Also instead of doing `{lazy: true}` here you should do `private users: Promise<User[]>` and note lazy relations is a very specific feature.

**Comment by mbayou** [comment]
Thank you, it works ! I know the element of getter and setter but I have some constraints, however, really thank you for your quick response. :)
