### ISSUE TITLE
Creating a relation with a join table

### ISSUE THREAD

**Issue by BrainMaestro** [typeorm/typeorm#700]
Hey, This is a great project. Really well done.

I have a  a many to many relationship between two entities (ex: `Vendor` and `Material`) which creates a join table. I have a separate entity `Quote` that I would like to relate to the join table of the previous relationship. How would I go about achieving that?

Thanks

**Comment by pleerock** [comment]
instead of using `@ManyToMany` relation you create a new entity called like `VendorMaterialQuote` with proper many-to-one/one-to-many relations inside to `Vendor`, `Material` and `Quote`. Its not possible to add something to the table generated by `@ManyToMany` decorator - because it is used only to generate basic relationship. If you need something more you just create your own entity with proper relations.

**Comment by BrainMaestro** [comment]
Alright, I guess that works. Thanks!
