### ISSUE TITLE
TYPEORM will support Oracle Database with oracledb

### ISSUE THREAD

**Issue by kotapatikk** [typeorm/typeorm#702]
Hi TYPEORM Team,

while am working with Oracle Database getting below error.  installed npm install oracledb --save and it's available under node_modules and also \node_modules\typeorm\driver\oracle.

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): DriverPackageNotInstalledError: Oracle package has not been found installed.

But whereas it's work for me MySQL.

Please give me the solution any steps to be install / included.

**Comment by pleerock** [comment]
Check if oracle was REALLY installed. Try to remove node modules and reinstall everything again. If nothing works for you - simply try to do `require("oracledb")` in your code and check if it works.

**Comment by kotapatikk** [comment]
thanks peelrock

Again same issue facing all the times.

**Comment by pleerock** [comment]
make sure you have installed oracle without errors. Plus as I told try to do require("oracledb") in your code and check if it works.

**Comment by rajancherma** [comment]
Hello pleerock,
I have been facing similar connectivity issues as mentioned in the issue opened. Meanwhile, it is also being claimed in some online community that typeorm-oracle connectivity and DB operations like loading, inserting are experimental.

And, upon searching for various sources on the Internet for a sample project which uses Oracle DB connectivity, I couldn't find any. 

It'd be helpful if you can provide a github link to a sample working project(if any exists already!)  which uses Oracle DB instead of mysql with at least two DB operations like select, insert, update.  It'll also provide an assurance or a green signal that it is safe to proceed using typeorm for Oracle DB. 

Thanks.

**Comment by pleerock** [comment]
@rajancherma oracle is supported, but not completely, there are several issues not yet fixed in the latest version. We already have some progress on resolving those issues and we are planning to release complete oracle support with all issues fixed in next 0.2.0 version (planned for release probably end of feb, beginning of march).
