### ISSUE TITLE
 syntax error at or near "AND"

### ISSUE THREAD

**Issue by gegham1** [typeorm/typeorm#7034]
### Expected Behavior

Get address object in query result

### Actual Behavior

I have a relation between Adress and Order, foreign key is carAddressId in Order entity

```
 syntax error at or near "AND"
```

```typescript

await getRepository(Order).createQueryBuilder('order')
      .innerJoinAndSelect("order.address", "address", "address.id = order.carAddressId")
      .where("order.userId = :userId", { userId })
      .orderBy('order.createDate', 'DESC')
      .getOne();

@Entity({
  name: 'address',
})
export class Address extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  address: string;

  @Column({ type: "float" })
  latitude: number;

  @Column({ type: "float" })
  longitude: number;

  @Column()
  userId: string;

  @CreateDateColumn({
    type: "timestamptz",
  })
  createDate: Date;

  @DeleteDateColumn()
  deleteDate?: Date;

  @ManyToOne(type => User, user => user.addressUser)
  addressUser: User;

  @OneToOne(type => Order, order => order.address)
  order: Order;
}

@Entity({
  name: 'orders',
})
export class Order extends CommonEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('uuid')
  userId: string;

  @Column('uuid')
  updateByUserId: string;

  @Column('uuid')
  carId: string;

  @Column('uuid')
  carAddressId: string;

  @Column({
    type: "timestamptz"
  })
  todoDate: Date;

  @Column()
  comment: string;

  @Column({
    type: "simple-json",
    nullable: true,
  })
  imageArrayId: string[];

  @CreateDateColumn({
    type: "timestamptz"
  })
  updateDate: Date;

  @CreateDateColumn({
    type: "timestamptz"
  })
  createDate: Date;

  @Column({
    enum: PaymentType,
    type: 'enum'
  })
  paymentType: PaymentType;

  @Column({
    enum: OrderStatus,
    type: 'enum',
    default: OrderStatus.WAITING,
  })
  status: OrderStatus;

  @Column({ default: false })
  isOpen: boolean;

  @Column({ default: false })
  accessible: boolean;

  @Column({
    nullable: true,
    type: 'uuid',
  })
  operatorImageId: string;

  @ManyToOne(() => User, user => user.orders)
  user: User;

  @OneToOne(() => Address, address => address.order)
  address: Address;

  @OneToMany(() => OrderChangeHistory, orderChangeHistory => orderChangeHistory.orderId)
  orderChangeHistory: OrderChangeHistory[];

  @OneToMany(() => File, file => file.orders)
  files: File[];
}

```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| TypeORM version     | 0.2.28 |

### Relevant Database Driver(s)
  - [x] `postgres`

**Comment by nebkat** [comment]
Could you try turn on the query log (see https://typeorm.io/#/logging/) so we can see exactly what the broken query looks like?

**Comment by imnotjames** [comment]
This isn't a complete example.  `CommonEntity`, `PaymentType`, `OrderStatus`, etc are all missing - in the future, please create a minimally reproducible example & include the actual queries being generated.

However, I made a much smaller version of what you've got:

https://github.com/imnotjames/typeorm/commit/2b7a17721e2a07d29be92ee055364e56f52b7a89

You need to specify a `@JoinColumn()` on your relationships - and specifying them to the values you'd expect them to be.

You're seeing this failure because we always expect a default join condition.

https://github.com/imnotjames/typeorm/blob/920e7812cd9d405df921f9ae9ce52ba0a9743bea/src/query-builder/SelectQueryBuilder.ts#L1491

The query that is generated is as such:

```sql
SELECT "order"."id" AS "order_id", "order"."carAddressId" AS "order_carAddressId", "address"."id" AS "address_id" FROM "order" "order" INNER JOIN "address" "address" ON  AND ("address"."id" = "order"."carAddressId")
```

I'm going to open a separate issue to tackle the condition-less join after I confirm there are no other issues similar to that - but I am pretty sure this issue is an error in how you've configured your entities.

**Comment by DoubleOTheven** [comment]
Adding `@JoinColumn()` worked for me as well
