### ISSUE TITLE
Allow to specify transaction property for individual migrations.

### ISSUE THREAD

**Issue by pedrolcn** [typeorm/typeorm#7087]
## Feature Description
Allow each individual migration to specify if it should be ran inside a transaction or not.

### The Problem
Some operations cannot be ran inside a transaction (eg. `CREATE INDEX CONCURRENTLY` on postgresql). While the typeorm CLI does allow to specify a `transaction` argument on the `migration:run` command, this argument applies globally. This poses a problem when migrations are ran in a CI pipeline where we don't want to completely abandon the guarantees that wrapping a migration in a transaction gives us (safe rollback if something shall go wrong) and leaves no other resource other than running some migrations manually

### The Solution

When running a migration the `MigrationExecutor` checks if the migration class defines a value for the transaction property in order to decide if this particular migration should be wrapped in a transaction or not. This value should take precedence over the `transaction` property of the `MigrationExecutor`.

There is an issue if the transaction argument is `'all'` ie. all migrations should be executed within a single transaction, as there is no clear cut way to conciliate it with some migrations wanting to be ran outside transactions, so maybe the `Migration`'s transaction property should only be honored if the `MigrationExecutor`'s transaction is either `'each'` in which case if a migration has `transaction = false` it is not wrapped in a migration, or `MigrationExecutor`'s transaction is `'none'` in which case only migrations which explicitly state it are wrapped in transactions.

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by kjb085** [comment]
@pedrolcn Has any progress been made on this?

**Comment by wu-json** [comment]
Also interested in this!

**Comment by JDaoMothership** [comment]
Also very interested in this functionality!!

**Comment by erikwlarsen** [comment]
would also love to see this!

**Comment by alielkhateeb** [comment]
Would love to see that too

**Comment by TimBeyer** [comment]
I feel like this should be a relatively easy fix in general, however there's one concern I have:

If we keep `"each" | "all" | "none"`, and proceed as suggested with the default being `false` in `"none"` and `true` in `"each"` and a failure in `"all"`, that causes a state where the defaults do fundamentally opposite things based on the overall transaction setting.
If you set an explicit value in the migration, it really should behave the same no matter what.

Another more general issue is the existence of `"all"` in the first place.  
Once a single transaction overrides its setting to `false`, `"all"` is forever broken.  
That makes it sort of a poor default as well given that a single default override on a migration breaks the overall default.

Any large production system eventually needs to run a migration outside of a transaction, so once you hit that point, you need to switch the default from what it has been all the time until then to `each` or `none` which leaves you with uncertainty about the impact of such change.

As such, in my opinion, `"all"` should never be a default and should be discouraged so that all solutions are engineered with that in mind from the start.

So for me the issue here is less of a "can we build this" and more of a "how can we build this in a way to not create even more confusing possibilities".

We could enable it only in `"each"` mode, but then you would expect a default of `true` for all cases where `transaction` is `undefined` which is also somewhat confusing.

We could also create a new mode `"custom"` and enforce that every single override is set.
That would probably be the most clear version, but creates one more option in the confusing constellation we already have.
It would also make it so that autogenerated migrations by default do not work in `"custom"` mode.

Does anyone have a good plan for this? We also really need the ability to skip transactions, but I don't just want to add even more tech debt to this part of the library.

**Comment by TimBeyer** [comment]
Actually thinking about it again, if I have 
`transaction: "each"` on the overall config,
then I have `transaction: true` as a default
and `transaction: false` would override that.

If I have
`transaction: "none"` on the overall config,
then I have `transaction: false` as a default
and `transaction: true` would override that. 

That would be somewhat confusing, but not a lot more confusing than what we have currently.  
It also would preserve the current logic.

I think I'll go ahead and try to open a PR for this to see how it feels.

**Comment by RezaRahmati** [comment]
hi 
to be able to run transaction concurrently we did this way, is there any issue running this way and we haven't consider it?

We wanted only these script to be run in non transactional and rest of scripts be in default transaction behavior

```
const { MigrationInterface, QueryRunner } = require('typeorm');

module.exports = class transactionIndex1675570965163 {
    name = 'transactionIndex1675570965163';

    async up(queryRunner) {
        const nonTransactionalQueryRunner =
            queryRunner.manager.connection.createQueryRunner();
        try {
            await nonTransactionalQueryRunner.connect();

            await nonTransactionalQueryRunner.query(
                `CREATE INDEX concurrently IF NOT EXISTS "IDX_CARD_TRANSACTION_CARD_TRANSACTION_TYPE_RESPONSE_CODE" ON "CARD"."TRANSACTION" ("CARD_NUMBER", "TRANSACTION_TYPE_CODE_REF", "RESPONSE_CODE_REF") `
            );
        } catch (err) {
            console.error(err);
        } finally {
            await nonTransactionalQueryRunner.release();
        }
    }

    async down(queryRunner) {
        await queryRunner.query(
            `DROP INDEX IF EXISTS "CARD"."IDX_CARD_TRANSACTION_CARD_TRANSACTION_TYPE_RESPONSE_CODE"`
        );
    }
};

```

**Comment by moulinraphael** [comment]
It seems that the mechanism to revert a migration is always using a transaction even if `transaction = false` is specified in the migration and `migrationsTransactionMode: 'each'` is specified in the DataSource configuration. 

<img width="938" alt="image" src="https://github.com/typeorm/typeorm/assets/4943583/aa340b23-3814-4279-953c-ef24b9566dcd">

<img width="631" alt="image" src="https://github.com/typeorm/typeorm/assets/4943583/a91d4903-00e2-4937-8fd3-898d2cbb8d40">

**Comment by bashovski** [comment]
This is still broken. Any plans on fixing this?
