### ISSUE TITLE
Wrong method performance getCount in QueryBuilder

### ISSUE THREAD

**Issue by webafra** [typeorm/typeorm#7160]
hi.

I checked the following code and the output of the first variable is empty and the value of the second variable shows the number 4!

```

const catQb = await this.category
      .createQueryBuilder('cat')
      .skip(5)
      .take(5);

    const categories = await catQb.getMany();
    const count = await catQb.getCount();

   console.log(categories)
   console.log(count)

```

It seems that the conditions are not considered in the second variable.

out
count

**Comment by nebkat** [comment]
https://github.com/typeorm/typeorm/blob/f27622daf9784d06496975bbbcacdb0938fd2c82/src/query-builder/SelectQueryBuilder.ts#L1858-L1876

Using `getCount()` ignores some options, such as skip and take, since they don't really make sense for counting. If you still want to do this your answer would be `max(4 - 5, 0)` i.e. `0`.
