### ISSUE TITLE
Entity mapping very slow when using @RelationId

### ISSUE THREAD

**Issue by some-user123** [typeorm/typeorm#7194]
### Expected Behavior

Entitiy mapping (i.e. `getMany()`) shouId not take significantly more time than the raw query (i.e. `getRawMany()`) even if there is a field decorated with `@RelationId`.

### Actual Behavior

`getMany()` is slower by a factor of 100 than `getRawMany()` if there is a field decorated with `@RelationId`. Leading to >20s for 5000 rows/entities.

### Steps to Reproduce

I'm storing time series in a postgresql database. There is a timeseries table and a timeseries_values table containing the actual values (created using a generated migration), see below.

(If you're wondering about the naming differences, I'm using `SnakeNamingStrategy` from `typeorm-naming-strategies`).

The table:
```
              Table "public.timeseries_values"
     Column    |     Type      | Collation | Nullable | Default
---------------+---------------+-----------+----------+---------
 timeseries_id | integer       |           | not null |
 date          | date          |           | not null |
 value         | numeric(12,6) |           | not null |
Indexes:
    "PK_..." PRIMARY KEY, btree (timeseries_id, date)
Foreign-key constraints:
    "FK_..." FOREIGN KEY (timeseries_id) REFERENCES timeseries(id) ON DELETE CASCADE
```

My entity definition:
```typescript
@Entity('timeseries_values')
export class TimeSeriesValue {
  @ManyToOne(() => TimeSeries, (ts: TimeSeries) => ts.values, {
    nullable: false,
    onDelete: 'CASCADE',
  })
  timeseries: TimeSeries

  @PrimaryColumn({ nullable: false })
  @RelationId((value: TimeServiesValue) => value.timeseries)
  timeseriesId: number

  @PrimaryColumn('date', {
    nullable: false,
  })
  date: string

  @Column('decimal', {
    nullable: false,
    precision: 12,
    scale: 6,
  })
  value: string
}
```

The raw query is pretty fast:
```
  console.time('query')

  await getRepository(TimeSeriesValue)
    .createQueryBuilder('values')
    .where({
      timeseries: { id: 33 },
    })
    .getRawMany()

  console.timeEnd('query')
```
takes 110-190ms for ~5000 rows.

Switching from `getRawMany` to `getMany` slows it down to ~22s for the same number of rows!

It seems to be caused by this column:
```
  @PrimaryColumn({ nullable: false })
  @RelationId((value: TimeServiesValue) => value.timeseries)
  timeseriesId: number
```

If I comment it out (which works for this query, but not for generating the migration, etc.), the time goes down to 200-300ms, which seems reasonable.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |          |
| Node.js version     | v14.5.0 | 
| Typescript version  | v4.1.2 | 
| TypeORM version     | v0.2.29 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nebkat** [comment]
For this particular example you shouldn't need `@RelationId` at all. It makes sense with One-to-Many where you are loading a large number of related entities for a single entity, but with Many-to-One you already have the ID you need so the extra queries are unnecessary.

**Comment by some-user123** [comment]
Thanks for your comment, although I'm not sure I understand it completely.
I followed the [documentation](https://github.com/typeorm/typeorm/blob/master/docs/decorator-reference.md#relationid).

How could I have the id in the entity (when not joining the related table) and the related entity (when joining the table) without using `@RelationId`?
Maybe above example was oversimplified, I have more complex tables with multiple ManyToOne relations and `@RelationId`s. Depending on the situation I need different combinations of entities and id.

**Comment by nebkat** [comment]
When you define a Many-to-One relation, the primary column(s) of the related entity is created as a foreign key in your own entity. In this case I presume `TimeSeries` contains an `id` column, so if you were to just define the `@ManyToOne` and nothing else, a `timeseriesId` column would be created in the table, it just wouldn't show up when you load the entity.

If you also manually define `timeseriesId`, as you have done in the example, the `@ManyToOne` will realize that the foreign key column already exists and use that instead of creating a duplicate column. Then whenever you request the entity you will also be given the value of `timeseriesId` because it is defined as a standard column.

`@RelationId` then becomes useless because the relation ID is already stored in the entity. That is not the case for OneToMany or ManyToMany, where it is more useful. I am not actually sure why the Many-to-One example is given in the documentation, although note that the relation ID column there isn't annotated as an ordinary column so it technically has more of a use. What I described above is in the documentation [here](https://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation).

**Comment by phil294** [comment]
This is probably the same as  #3507 (?)

**Comment by some-user123** [comment]
Thanks, will close this issue. I no longer use typeorm anyway.
