### ISSUE TITLE
MSSQL - Query fast with literals but slow with parameters

### ISSUE THREAD

**Issue by shemama2** [typeorm/typeorm#7209]
When i pass the native query like connection.query(select * from user where id=1), the performance is really good and it less that 0.5 seconds. If we use the findone or QueryBuilder method, it is taking around 5 seconds to repsond.

On further debugging, we found that passing value directly to query like this, 

``` return getConnection("vehicle").createQueryBuilder() .select("vehicle").from(Vehicle, "vehicle") .where("vehicle.id='" + id + "'").getOne(); ```

is faster than

```return getConnection("vehicle").createQueryBuilder() .select("vehicle").from(Vehicle, "vehicle") .where("vehicle.id =:id", {id:id}).getOne();```

is there any optimization we can do to fix the issue with parameterized query?

**Comment by nebkat** [comment]
Currently the parameter replacement algorithm is quite inefficient. 

https://github.com/typeorm/typeorm/blob/f27622daf9784d06496975bbbcacdb0938fd2c82/src/driver/mysql/MysqlDriver.ts#L397

If you use `where({id: id})` it should be a lot quicker because it uses the driver's native parameter system rather than text replacing within TypeORM.

**Comment by shemama2** [comment]
It is working fine now.. Thanks your respnose.
