### ISSUE TITLE
Sometimes wont start

### ISSUE THREAD

**Issue by kristianstroka** [typeorm/typeorm#7240]
## Issue Description
Cannot start sometimes 

### Expected Behavior
Start server without issues

### Actual Behavior
Almost always start as expected, but in some cases (1-2 from 20 starts) it wont start ... CPU is increased to 100% with node process, but nothing happened, no output to console, nothing to show, just this: 

`> ts-node-dev --respawn --transpile-only ./src/index.ts

[INFO] 12:03:00 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)`

### Steps to Reproduce
I'm using nodejs with typeorm also with react in concurently, so root package.json is like this: 

```
"scripts": {
    "server": "cd server && npm run prod",
    "server-dev": "cd server && npm run dev",
    "client": "cd client && npm start",
    "client-build": "cd client && serve -s build",
    "dev": "concurrently --kill-others \"npm run server-dev\" \"npm run client -FAST_REFRESH=true\"",
    "prod": "concurrently --kill-others \"npm run server\" \"npm run client-build\""
  },
```

Then server package is like this: 
```
"scripts": {
      "dev": "ts-node-dev --respawn --transpile-only ./src/index.ts",
      "prod": "tsc && node ./build/index.js",
      "migration:run": "ts-node ./node_modules/typeorm/cli.js migration:run",
      "migration:revert": "ts-node ./node_modules/typeorm/cli.js migration:revert",
      "typeorm": "node --require ts-node/register ./node_modules/typeorm/cli.js",
      "typeorm-generate-migrations": "node --require ts-node/register ./node_modules/typeorm/cli.js migration:generate",
      "tsc": "tsc"
   }
```

In my index.ts file inside src I have this code: 
```
import "reflect-metadata";
import { createConnection, getConnectionOptions } from "typeorm";
import * as express from "express";
import * as bodyParser from "body-parser";
import * as helmet from "helmet";
import * as cors from "cors";
import routes from './routes/index';

console.log('Starting server')

getConnectionOptions()
    .then(async connectionOptions => {

        Object.assign(connectionOptions, { connectionTimeout: 5 });

        createConnection(connectionOptions)
            
            .then(async connection => {
                console.log('Successfully connected')
                
                await connection.runMigrations()

                const app = express()
        
                let allowedOrigins = (typeof process.env.CLIENT_ROOT !== 'undefined') ? process.env.CLIENT_ROOT.split(',') : [];

                app.use(cors({
                    origin: function (origin, callback) {
                        if (typeof origin === 'undefined') {
                            callback(null, true)
                        } else if (allowedOrigins.indexOf(origin) !== -1) {
                            callback(null, true)
                        } else {
                            callback(new Error('Not allowed by CORS'))
                        }
                    },
                    credentials: true
                }))
                app.use(helmet())
                app.use(bodyParser.json())

                app.use("/", routes)
        
                app.listen(process.env.PORT_SERVER, () => {
                    console.log("Server started on port " + process.env.PORT_SERVER + "!")
                })
                
            })
            .catch(error => console.log(error));
    }).catch(error => console.log(error))

```
### Relevant Database Driver(s)

- [x] `mysql`

**Comment by imnotjames** [comment]
Cannot replicate.  If you can provide more information that'd be stellar.  Without being able to replicate this I can't do a whole lot.

---

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by Ginden** [comment]
Closing - no response from reporter for over 3 months.
