### ISSUE TITLE
Add doker from OracleDb

### ISSUE THREAD

**Issue by jzonta** [typeorm/typeorm#7281]
## Feature Description
This proposal is to implement the Oracle database of the docker container.

### The Problem

Unlike the other databases, oracle does not have an image, you need to create a git repository download, download the Oracle installation and then do the manual process, in addition, to download the oracle installation you must be logged in and accept the terms. This makes automation difficult.

### The Solution

My proposal is to create a docker image with all the installation ready, make it available on the dockerhub and then add the data at https://github.com/typeorm/typeorm/blob/master/src/commands/InitCommand.ts

I have already started development to do this. Does anyone have another idea?

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
Most of the oracle database ages have received takedowns.

I've set one up and it's been fine so far.

However, this issue is not really related to typeorm, is it?

---

For questions, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!
