### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by denismaxim0v** [typeorm/typeorm#7322]
## Feature Description
Better error messages
### The Problem
Right now the error messages are very unclear and don't point to an actual problem in the codebase. For example: you are reworking your entities, and you by not paying enough attention have somewhere a OneToOne relation and on the other side ManyToOne, this should be clearly pointed in the error instead of right now
```
UnhandledPromiseRejectionWarning: QueryFailedError: syntax error at or near "("
```
Like what does it mean?

### The Solution
I want do ideally see a backtrace of where an error has been thrown.

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
`QueryFailedError: syntax error at or near "("` just means that the query we generated was incorrect.

We don't know at this time that it's because you made a mistake in your schema.

However, what you're suggesting as the solution:

The backtrace not being there has to do with your environment.  We don't control what you print out with your errors.

You need to use a `.catch` somewhere because it's bubbling up your promises and failing _somewhere_ and you aren't catching it / logging it / etc.
