### ISSUE TITLE
object literal in where clause not working properly

### ISSUE THREAD

**Issue by soodakshay** [typeorm/typeorm#7337]
Issue type:

[ ] question
[x] bug report
[ ] feature request
[ ] documentation issue

Database system/driver:

[ ] cordova
[ ] mongodb
[ ] mssql
[ ] mysql / mariadb
[ ] oracle
[x ] postgres
[ ] cockroachdb
[ ] sqlite
[ ] sqljs
[ ] react-native
[ ] expo

TypeORM version:

[ ] latest
[ ] @next
[x] 0.2.25

NodeJS: v10.22.0

I am trying to query the table and in the query, the object literal when passed in the where clause does not return all the records but instead it returns only a single record.  When I directly specify the parameter instead of passing the object literal, it returns multiple records. 

I am using typeorm with NestJS

The below is an example that returns only a single record instead of multiple records:

```
async queryAssetBySerialPart(req: QueryAssetsBySerialPartReqBody): Promise<[Asset[], number]> {
    const query = getRepository(Asset)
      .createQueryBuilder('assets')
      .leftJoinAndMapOne('assets.logistic', Logistic, 'logistic', 'assets.id = logistic.assetId')
      .leftJoinAndMapOne('assets.status', Status, 'status', 'assets.id = status.assetId');

    req.query.forEach((queryData, idx) => {
        if (idx === 0) {
            query.where(
              new Brackets(qb => {
                qb.where(`"assets"."serial" = :serial`, {
                  serial: queryData.serial,
                }).andWhere(`"assets"."part" = :part`, {
                  part: queryData.part,
                });
              }),
            );
          } else {
            query.orWhere(
              new Brackets(qb => {
                qb.where(`"assets"."serial" = :serial`, {
                  serial: queryData.serial,
                }).andWhere(`"assets"."part" = :part`, {
                  part: queryData.part,
                });
              }),
            );
          }
    });

    const [assets, totalCount] = await query.getManyAndCount();

    return [assets, totalCount];
  }
```

Below is an example that works fine and returns multiple records:

```
async queryAssetBySerialPart(req: QueryAssetsBySerialPartReqBody): Promise<[Asset[], number]> {
    const query = getRepository(Asset)
      .createQueryBuilder('assets')
      .leftJoinAndMapOne('assets.logistic', Logistic, 'logistic', 'assets.id = logistic.assetId')
      .leftJoinAndMapOne('assets.status', Status, 'status', 'assets.id = status.assetId');

    req.query.forEach((queryData, idx) => {
      if (idx === 0) {
        query.where(
          new Brackets(qb => {
            qb.where(`"assets"."serial" = '${queryData.serial}'`).andWhere(`"assets"."part" = '${queryData.part}'`);
          }),
        );
      } else {
        query.orWhere(
          new Brackets(qb => {
            qb.where(`"assets"."serial" = '${queryData.serial}'`).andWhere(`"assets"."part" = '${queryData.part}'`);
          }),
        );
      }
    });

    const [assets, totalCount] = await query.getManyAndCount();

    return [assets, totalCount];
  }
```

Unfortunately, I can not share the complete file/code and structure because of confidentiality

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
(though I'm guessing it's #1568, #3428 but that's just a guess)
