### ISSUE TITLE
Both null and undefined find option value should generate IS NULL query

### ISSUE THREAD

**Issue by yujiahaol68** [typeorm/typeorm#737]
I found that when use find function with option. If I want to find a column's value that is null. I will get the right result. But if `tslint` prefer changing `null` into `undefined`, it won't work great because it didn't map both null and undefined value to generate the `IS NULL` sql query.

It cause a big problem and it will take a long time to debug if my project use `tslint` very late.

**Comment by NoNameProvided** [comment]
This has been discussed multiple times across multiple projects of @pleerock . In short this is the correct behavior.

In JS `null` and `undefined` means different things. A `null` value is an explicit way to express that nothing should be there. In the other hand `undefined` means a non-existing value. With `undefined` TypeORM wouldn't be able to make a difference why it isn't there. You just forgot to put the value there? Or was it intentional? With `undefined` there is no way to tell the difference.

For the above reason it's unlikely that this will be changed. I advice you to turn of that particular TSLint rule.

**Comment by yujiahaol68** [comment]
However some teams have set this `no-null-keyword` rule. Maybe the lib should give the right to the team to choose instead of insisting all the team should obey the rules of lib. What do you think?

**Comment by pleerock** [comment]
@NoNameProvided you are absolutely right. I recommend to turn off that tslint rule as well

**Comment by binki** [comment]
I used to use `null` a lot before I started using TypeScript. With TypeScript, it’s a lot easier to only use `undefined` instead. Using `null` in TypeScript requires checking for more conditions and being more explicit because you can’t take advantage of the default value of variables being `undefined`.

Additionally, TypeScript itself’s own “optional class property” behavior favors `undefined` over `null`. This is because it is easier for an object to end up with a property access returning `undefined` than it is to get `null` as `null` will only be returned if the property is initialized.

Regarding `undefined` as a property value, you already can use `Object.hasOwnProperty.call(o, propertyName)` to determine if the property is defined on an object. If the value shouldn’t be on the object, it can be removed by using `delete` instead of overwriting it with `undefined`.

What I think I care about more than **how** TypeORM chooses to handle `undefined`/`null` is that there is consistent behavior and documentation. If I have time later I may open a new docs issue, but just dumping this here for now. Here is what I am seeing with postgresql backend currently (typeorm-0.2.7):

```ts
const o = await manager.findOne(MyEntity, {
  col1: 'asdf',
  col2: undefined,
  col3: null,
});
```

generates SQL like this:

```sql
SELECT "MyEntity"."id" AS MyEntity_id",
  "MyEntity"."col1" AS MyEntity_col1",
  "MyEntity"."col2" AS MyEntity_col2",
  "MyEntity"."col3" AS MyEntity_col3"
FROM "my_entity" "MyEntity"
WHERE "MyEntity"."col1" = $1
AND "MyEntity"."col2" = $2
AND "MyEntity"."col3" IS NULL
-- PARAMETERS: ["asdf",null]
```

So TypeORM isn’t ignoring the `undefined`—it’s passing it as `NULL` but as a parameterized value and uses `=` instead of `IS NULL`. This is good in some cases—this way, you can ensure that no rows will be returned if you have a variable accidentally left set to undefined. If TypeORM actually ignored `undefined`, then I would expect the `AND "MyEntity"."col2" = $2` to be omitted and then the query would suddenly start matching rows when I expect it not to.

@yujiahaol68 You might be able to use `IsNull()` instead of `null` in `find()`’s where conditions to work around your tslint issue. Alternatively, it might be acceptible to use [`// tslint:disable-next-line:no-null-keyword`](https://palantir.github.io/tslint/usage/rule-flags/) when checking/assigning data on nullable columns. Though I also wonder about the merits of that rule in the first place. If you are trying to write TypeScript, I feel like it is actually *harder* to write code that uses `null` than to accidentally add `null` to places—so that tslint rule may not actually have much benefit.

**Comment by blitzmann** [comment]
Our team just ran into this issue. While I understand there's a difference between undefined and null, when it's applied to the find method typeorm will break the query by generating a `column = null` as mentioned by @binki.

I think typeorm needs to be consistent: either it ignores undefined values completely, or throws an error when encountering them because it doesn't know what exactly to do with it (this would be my preference). But I don't think anyone would expect it to do `col = null`

**Comment by NoNameProvided** [comment]
Hi @blitzmann! 

This is a 3 years old closed issue, I suggest you open a new issue with your feedback.
