### ISSUE TITLE
On create not use default value

### ISSUE THREAD

**Issue by sigmagf** [typeorm/typeorm#7469]
## Issue Description

I'm trying to create an entry in my database, but the typeorm is not using the default values.

```typescript
// Users.ts
@Entity('users')
export class User implements IUser {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column('varchar')
  name: string;

  @Column('varchar')
  email: string;

  @Column('varchar')
  username: string;

  @Column('varchar')
  password: string;

  @Column('varchar', { name: 'pwd_reset_token' })
  pwdResetToken?: string;

  @Column('varchar', { name: 'pwd_reset_expires' })
  pwdResetExpires?: Date;

  @CreateDateColumn({ name: 'created_at', type: 'timestamp' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamp' })
  updatedAt: Date;
}


// Create Method
async create(data: UsersRepositoryCraeteOrUpdateData, withPassword: boolean): Promise<IUser> {
  const user = getManager().create(User, data);
  const dbData = await getManager().save(user);

  return dbData;
}
```

```
QueryFailedError: null value in column "id" of relation "users" violates not-null constraint
    at new QueryFailedError (/home/joao/Projects/myapp/myapp-server/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/home/joao/Projects/myapp/myapp-server/src/driver/postgres/PostgresQueryRunner.ts:228:19)
    at step (/home/joao/Projects/myapp/myapp-server/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/home/joao/Projects/myapp/myapp-server/node_modules/tslib/tslib.js:122:57)
    at rejected (/home/joao/Projects/myapp/myapp-server/node_modules/tslib/tslib.js:113:69)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  length: 271,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (null, Testado da silva, testado.silva@mail.com, testado, 12345678, null, null, null, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'users',
  column: 'id',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1965',
  routine: 'ExecConstraints',
  query: 'INSERT INTO "users"("id", "name", "email", "username", "password", "pwd_reset_token", "pwd_reset_expires", "created_at", "updated_at") VALUES (DEFAULT, $1, $2, $3, $4, DEFAULT, DEFAULT, DEFAULT, DEFAULT) RETURNING "id", "created_at", "updated_at"',
  parameters: [
    'Testado da silva',
    'testado.silva@mail.com',
    'testado',
    '12345678'
  ]
}
```

### My Environment

| Dependency | Version |
| --- | --- |
| Operating System | ubuntu 20.04 |
| Node.js version | 12.19.0 |
| Typescript version  | 4.2.3 |
| TypeORM version     | 0.2.31 |

### Relevant Database Driver(s)

- [ ] `mongodb`
- [ ] `mysql`
- [x] `postgres (in docker)`
- [ ] `sqlite`
- [ ] `sqlserver`

**Comment by imnotjames** [comment]
Cannot replicate.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by imnotjames** [comment]
If you can provide more information that helps to reproduce the issue you're having please re-open this issue and add that information.

**Comment by sigmagf** [comment]
All the information is there, the "@PrimaryGeneratedColumn('uuid')" is not generating any uuid, not even if I use some code that defaults to using the v4 function of the "uuid" package

To generate a user, I am required to generate it as follows:
```
import {v4} from 'uuid'
...
const user = getManager().create(User, {
  id: v4(),
  name: 'blablabla',
  email: 'blablabla',
  username: 'blablabla',
  password: 'blablabla',
});
const dbData = await getManager().save(user);
...
```

**Comment by imnotjames** [comment]
What is the schema that was generated for this table?

**Comment by sigmagf** [comment]
The table in database?

**Comment by imnotjames** [comment]
Yes - the query is attempting to use the default.  If you generated it using TypeORM it should be using the UUID function that's part of postgres.

**Comment by sigmagf** [comment]
Ok, my database doesn't really have the uuid generator, but I've tried to do it with the "default" option with "@primaryColum({ default: v4() })" and it still doesn't work

**Comment by imnotjames** [comment]
If you're not using the schema as generated by TypeORM this is definitely outside the scope of what this issue tracker is for.

---

For questions & general support, please check out the [community slack](https://join.slack.com/t/typeorm/shared_invite/zt-gej3gc00-hR~L~DqGUJ7qOpGy4SSq3g) or check [TypeORM's documentation page on other support avenues](https://typeorm.io/#/support) - cheers!

**Comment by imnotjames** [comment]
My suggestion is to update your database schema - or to use a `@BeforeInsert` or a subscriber & set the `@PrimaryColumn("uuid")`.

If you'd like to use the UUID generation then this is a duplicate issue of #6761
