### ISSUE TITLE
Disable synchronization for function-based index is not working

### ISSUE THREAD

**Issue by bengchet** [typeorm/typeorm#7487]
## Issue Description
Typeorm attempts to drop index and related column when running next schema sync even though I haved disabled synchronization on that particular index.

### Expected Behavior

When I have run synchronization, Typeorm should ignore the function-based index that I have declared not to be synchronized, aka @Index('index_name', { synchronize: false })

### Actual Behavior

Typeorm attempts to drop both index and the related column (for my case the column doesn't not exist because it is function based index)

Note: I am using Oracle.

Table
![usertable](https://user-images.githubusercontent.com/13192939/111949454-ba3efc80-8b1b-11eb-953e-90f5b6e4c441.PNG)

Typeorm attempts to drop index and column during next schema sync
![dropindex](https://user-images.githubusercontent.com/13192939/111949468-be6b1a00-8b1b-11eb-979e-0356751e5a74.PNG)

```
// include the output in code tags like these!
```

### Steps to Reproduce

1. Create a user table with column id and username;
2. Create function based index with 
```sql
create index "user_username" on "user" (upper("username"));
```
3. Run Schema Synchronization. If the index exists, error will appear. If the index doesn't exist or deleted, error will not appear.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    | Windows 10 |
| Node.js version     | v14.16.0 | 
| Typescript version  | v4.2.2| 
| TypeORM version     | v0.2.31 | 

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [x] `oracle`
- [ ] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by imnotjames** [comment]
`synchronize` is not an option for indices. You can check `IndexOptions` to confirm.  If you'd like this as a feature please open a separate issue.

**Comment by kjleitz** [comment]
@imnotjames `synchronize` has been an option for indices for at least 5 years:

Documentation blame: https://github.com/typeorm/typeorm/blame/d4607a86723eef07e62e6d7321a07f3ae5ed1f90/docs/indices.md#L142

Code blame: https://github.com/typeorm/typeorm/blame/874e5736776cb94635e4d6e2486aade4d797ed10/src/decorator/Index.ts#L23

It's part of the function signature when only a name is specified. The linked implementation looks like this:

```ts
export function Index(name: string, options: { synchronize: false }): Function;
```

...but currently it looks like this:

```ts
export declare function Index(name: string, options: {
    synchronize: false;
}): ClassDecorator & PropertyDecorator;
```

Same effect. It's not part of `IndexOptions` because it exists outside of it. Yet it's documented, and it seems to be the only way to use a non-basic index in your database. My use-case, for example, is a GIN index. Unfortunately, it is broken in that every subsequently-generated migration removes the index despite using this option as documented.

Note: I **do not use** `synchronize: true` in my application.

I believe this issue should be re-opened.

**Comment by kareldonk** [comment]
Also having the same issue. Using `synchronization: false` with `@Index` does not ignore the index when creating migrations as per the documentation. Please reopen and fix.
![image](https://github.com/typeorm/typeorm/assets/12107205/98f52842-8d38-4814-848b-25bad9c81ffa)
