### ISSUE TITLE
Mongodb support

### ISSUE THREAD

**Issue by xfg** [typeorm/typeorm#75]
I would be wanted to see mongodb as one of supported databases in future. At the present for mongodb exists only Mongoose orm but it uses Active Record pattern but would be great have orm which realizes a data mapper pattern for mongodb.

Is it in the plans? Mongodb very popular in nodejs community.

**Comment by pleerock** [comment]
Hi, there is a separate project called [typeodm](https://github.com/pleerock/typeodm) however Im not working on it since all my time is spending on typeorm. Once I finish all planned features and typeorm will stabilize I'll switch to typeodm development. You can try typeodm, its generally working good. There is no docs for it yet, however there are [good samples](https://github.com/pleerock/typeodm/tree/master/sample) you can try.
