### ISSUE TITLE
Upgrading 0.2.20 to 0.2.31 gives error

### ISSUE THREAD

**Issue by thellimist** [typeorm/typeorm#7512]
Only thing I did was change the package json, and do npm install again. Once I revert the version, it works correctly. 

Below is the error

```
[0] Error: Package exports for '/app/node_modules/typeorm/node_modules/tslib' do not define a valid '.' target
[0]     at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
[0]     at applyExports (internal/modules/cjs/loader.js:459:14)
[0]     at resolveExports (internal/modules/cjs/loader.js:508:12)
[0]     at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:785:27)
[0]     at Module.require (internal/modules/cjs/loader.js:956:19)
[0]     at require (internal/modules/cjs/helpers.js:74:18)
[0]     at Object.<anonymous> (/app/node_modules/typeorm/index.js:3:15)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[0]     at Module.load (internal/modules/cjs/loader.js:914:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
[0]     at Module.require (internal/modules/cjs/loader.js:956:19)
[0]     at require (internal/modules/cjs/helpers.js:74:18)
[0]     at Object.<anonymous> (/app/src/database/entity/User.ts:1:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:439:23)
[0]     at Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
[0]     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:442:12)
[0]     at Module.load (internal/modules/cjs/loader.js:914:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:822:14)
```

Command I run `TS_NODE_TRANSPILE_ONLY=true node -r ts-node/register ./src/server.ts`

**Comment by carlocorradini** [comment]
@thellimist 

Why are you using "pure" node with typescript files?
I suggest you to use [ts-node-dev](https://github.com/wclr/ts-node-dev) with the following script: 
```bash
ts-node-dev --prefer-ts true --no-notify --quiet --exit-child -r tsconfig-paths/register --transpile-only src/server.ts
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "lib": [
      "ESNext",
      "ESNext.asynciterable"
    ],
    "allowJs": true,
    "checkJs": true,
    "declaration": true,
    "declarationMap": false,
    "sourceMap": false,
    "baseUrl": ".",
    "outDir": "build",
    "removeComments": false,
    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "typeRoots": [
      "node_modules/@types",
      "src/typings"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "emitDeclarationOnly": false,
    "forceConsistentCasingInFileNames": true,
    "paths": {
      "@app/*": [
        "src/*"
      ]
    }
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules/**/*", "build/**/*", "tests/**/*"]
}
```

The full project is available at the following link: <https://github.com/carlocorradini/graphmarket>

PS: You have to install *[tsconfig-paths](https://github.com/dividab/tsconfig-paths)*

**Comment by pleerock** [comment]
I need more details, error you sent doesn't tell anything about where problem can be.

**Comment by thellimist** [comment]
Will checkout @carlocorradini !

@pleerock that's the error message. Nothing else is printed.

**Comment by imnotjames** [comment]
Cannot replicate.  Can you include more information?

**Comment by imnotjames** [comment]
If you can create a reproducible example please re-open this issue.

---


When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
