### ISSUE TITLE
Column of type "enum" throws missing properties error

### ISSUE THREAD

**Issue by martingmoreno** [typeorm/typeorm#7541]
Hello there!

## Issue Description

The version of TypeORM was updated to the latest release, while starting up the NestJS server it started throwing this enum error. As of my understanding the required properties are in the decorator.

### Expected Behavior

To start correctly the TypeOrmCoreModule 

### Actual Behavior

```zsh
Error: Column "type" of Entity "StandardSet" is defined as enum, but missing "enum" or "enumName" properties.
```

### Steps to Reproduce

This code worked in version ```0.2.31```, once it was upgraded to ```0.2.32``` this error started appearing. 

```typescript
enum StandardSetType {
  AcademicStandard = 'AcademicStandard',
  FoundationalKnowledge = 'FoundationalKnowledge',
  AchievementDescriptor = 'AchievementDescriptor',
}

@Column('enum', { enum: StandardSetType, name: 'type' })
type: StandardSetType;
```

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |   Ubuntu       |
| Node.js version     | v14.15.5 | 
| Typescript version  | 3.9.9 | 
| TypeORM version     | 0.2.32 | 
| NestJS  | 7.6.13 |
| nestJS/TypeORM | 7.1.5 |

### Relevant Database Driver(s)

- [ ] `aurora-data-api`
- [ ] `aurora-data-api-pg`
- [ ] `better-sqlite3`
- [ ] `cockroachdb`
- [ ] `cordova`
- [ ] `expo`
- [ ] `mongodb`
- [ ] `mysql`
- [ ] `nativescript`
- [ ] `oracle`
- [x] `postgres`
- [ ] `react-native`
- [ ] `sap`
- [ ] `sqlite`
- [ ] `sqlite-abstract`
- [ ] `sqljs`
- [ ] `sqlserver`

### Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [x] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by iamdeit** [comment]
+1

**Comment by GabrielLaPorta** [comment]
+1

**Comment by kevin-lindsay-1** [comment]
I happen to use the `{ type: 'enum', enum: StandardSetType }` syntax. Does that work for you?

**Comment by martingmoreno** [comment]
> I happen to use the `{ type: 'enum', enum: StandardSetType }` syntax. Does that work for you?
I used that syntax, it didn't worked. It produces the same error.

**Comment by 2Kable** [comment]
I could reproduce this issue, when the same enum was used by 2 different entities

**Comment by AlexMesser** [comment]
@martingmoreno i've added a test with a different cases and can't reproduce the issue. Can you please create a reproduction repo showing this issue?

**Comment by martingmoreno** [comment]
@AlexMesser Yes, I will try to do it this weekend if there's no problem with the timing of that? Thanks in advance :smile:

**Comment by MrPontas** [comment]
> I happen to use the `{ type: 'enum', enum: StandardSetType }` syntax. Does that work for you?

It worked for me, thanks!

**Comment by imnotjames** [comment]
Cannot replicate. 

When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

**Comment by auragit** [comment]
> I could reproduce this issue, when the same enum was used by 2 different entities

saved my day

**Comment by H6LS1S** [comment]
Can't remember where this thread first appeared, but in short - use a function call

```ts
export enum StatusEnum {
  DEACTIVATED = 'DEACTIVATED',
  ACTIVATED = 'ACTIVATED',
  PENDING = 'PENDING',
}

@Entity('users')
export class UserEntity {
  
  ...

  @Column({ type: 'enum', enum: () => StatusEnum })
  public readonly status: StatusEnum;

  ...

}

@Entity('tips')
export class TipEntity {
  
  ...

  @Column({ type: 'enum', enum: () => StatusEnum })
  public readonly status: StatusEnum;

  ...

}
```

**Comment by kevinmelo** [comment]
The problem still persist on version `0.2.31`.

If you try use an Enum from other Entity, he will throw the error

**Comment by Ginden** [comment]
> The problem still persist on version 0.2.31.

Version `0.2.*` isn't supported.

**Comment by kevinmelo** [comment]
> > The problem still persist on version 0.2.31.
> 
> Version `0.2.*` isn't supported.

I Got working, setting the `enumName` as the name of my enum that was created on database, and the `default` only worket as string

**Comment by socjalis** [comment]
Same issue on 0.3.6 + postgres, moving my Enum and Entity to the same file resolves the problem for some reason.

**Comment by edunse** [comment]
I faced the problem and mine was all about circular dependency. I had two files of my entities:
```typescript
// EntityA.ts
import { EntityB } from './EntityB' 

export enum SomeEnum {
  ONE = 'one',
  TWO = 'two',
}

export class EntityA {
  @ManyToOne(() => EntityB)
  @JoinColumn()
  entityB: EntityB;
}
```

```typescript
// EntityB.ts
import { SomeEnum } from './EntityA' 

console.log(SomeEnum); // PROBLEM! SomeEnum is undefined 
export class EntityB {
  @Column({ type: 'enum', enum: SomeEnum })
  enumColumn: SomeEnum;
}
```

The solution is to move your enum into separate file. Maybe will help someone

**Comment by StefanZivkovic** [comment]
After switching typeorm version from 0.2.31 -> 0.2.45.
i had case of getting error (but in large codebase): `TypeORMError: Column "x" of Entity "y" is defined as enum, but missing "enum" or "enumName" properties.`.

In one of the comments it was mentioned that issue is in enum defined in one entity file, but used in some other entities (in other entity files). After extracting that enum in separate file, and adding `enum` attribute inside @Column decorator, migrations were successfully executed.

**Comment by matt-bader** [comment]
The only thing that fixed the issue for me was to extract the enum into a separate file.

**Comment by krishna-404** [comment]
> The only thing that fixed the issue for me was to extract the enum into a separate file.

This worked for me. Thanks!

**Comment by vicradon** [comment]
> I faced the problem and mine was all about circular dependency and load order. I had two files of my entities:
> 
> // EntityA.ts
> import { EntityB } from './EntityB' 
> 
> export enum SomeEnum {
>   ONE = 'one',
>   TWO = 'two',
> }
> 
> export class EntityA {
>   @ManyToOne(() => EntityB)
>   @JoinColumn()
>   entityB: EntityB;
> }
> // EntityB.ts
> import { SomeEnum } from './EntityA' 
> 
> console.log(SomeEnum); // PROBLEM! SomeEnum is undefined 
> export class EntityB {
>   @Column({ type: 'enum', enum: SomeEnum })
>   enumColumn: SomeEnum;
> }
> One of the solutions to move your enum into separate file. Maybe this will help someone

This worked for me too, thank you

**Comment by joachimbulow** [comment]
I am facing this for a `string` type column - which makes it super weird - but same error code

`ERROR [ExceptionHandler] Column "userId" of Entity "ChatUser" is defined as enum, but missing "enum" or "enumName" properties.`

For the following entity

```typescript
@Entity()
export class ChatUser {
  // @PrimaryGeneratedColumn('rowid')
  // public id!: string;

  @Column({
    type: 'enum',
    enum: Region,
    primary: true,
  })
  userRegion: Region;

  @OneToOne(() => Profile, (profile) => profile.userId)
  @JoinColumn({ name: 'user_id' })
  public user!: Relation<Profile>;

  @Column({ primary: true })
  public userId: string;
```

Isn't that totally crazy?

**Comment by lookto** [comment]
> The only thing that fixed the issue for me was to extract the enum into a separate file.

This seems to be the solution. TypeORM might have a problem with module resolution if in the same file as the entity.
