### ISSUE TITLE
Nullable @Embedded inside @Embedded

### ISSUE THREAD

**Issue by Urigo** [typeorm/typeorm#762]
Hi, looks like the following use case doesn't work for me on Postgres:

```
class Foo {
    @Column()
    name: string
    @Embedded(type => FooMetadata)
    metadata?: FooMetadata
}
@EmbeddableEntity()
class FooMetadata {
    @Column({ nullable: true })
    bar: number

    @Embedded(type => FooChildMetadata)
    child?: FooChildMetadata
}
@EmbeddableEntity()
class FooChildMetadata {
    @Column({ nullable: true })
    something: number

    @Column({ nullable: true })
    somethingElse: number
}
```

The error I get is `Error:  TypeError: Cannot read property 'child' of undefined`

Thank you

**Comment by pleerock** [comment]
what typeorm version are you using?

**Comment by pleerock** [comment]
I don't see primary column in your code example, do you have it?

**Comment by pleerock** [comment]
Okay I added tests and it seems a bug. This is fixed and released in `0.1.0-alpha.35`

**Comment by pleerock** [comment]
BTW in latest versions `@EmbeddedEntity` and `@Embedded` decorators are deprecated. Instead of `@EmbeddedEntity` you simply don't use anything - no need to decorate embedded entity anymore. And instead of `@Embedded` you use `@Column` decorator with same syntax: `@Column(type => FooChildMetadata)`. You can see how exactly it looks like in a commit I made

**Comment by Urigo** [comment]
Thank you so much @pleerock !
