### ISSUE TITLE
How to do a RIGHT JOIN and SELECT

### ISSUE THREAD

**Issue by StickNitro** [typeorm/typeorm#766]
How does one do the following query using typeorm please

```sql
SELECT *
FROM "UserStrength"
RIGHT JOIN "Strength" ON "Strength"."id" = "UserStrength"."strengthId"
```

Where the UserStrengthEntity is defined as:

```typescript
@Entity("UserStrength")
export class UserStrengthEntity extends BaseEntity implements IUserStrength {
    @Column({default: false}) isCompleted: boolean;

    @ManyToOne(type => UserEntity, user => user.userStrengthArray, {
        cascadeAll: true
    })
    @JoinColumn({name: "userId"})
    user: UserEntity;

    @OneToMany(type => UserStrengthItemEntity, userStrengthItem => userStrengthItem.userStrength, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    userStrengthItemArray?: UserStrengthItemEntity[];

    @ManyToOne(type => StrengthEntity, strength => strength.userStrengthArray, {
        cascadeAll: true
    })
    @JoinColumn({name: "strengthId"})
    strength: StrengthEntity;
}
```

and the StrengthEntity is:

```typescript
@Entity("Strength")
export class StrengthEntity extends BaseEntity implements IStrength {
    @Column({length: 50}) name: string;
    @Column({length: 100}) title: string;
    @Column() strengthType: StrengthType;
    @Column({length: 10, nullable: true}) titleColor: string;
    @Column({nullable: true}) titleIcon: string;

    @ManyToOne(type => ClientEntity, clientEntity => clientEntity.strengthArray, {
        cascadeAll: true
    })
    @JoinColumn({name: "clientId"}) client: ClientEntity

    @OneToMany(type => StrengthItemEntity, strengthItem => strengthItem.strength, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    strengthItemArray: StrengthItemEntity[];

    @OneToMany(type => UserStrengthEntity, userStrength => userStrength.strength, {
        cascadeInsert: true,
        cascadeUpdate: true
    })
    userStrengthArray: UserStrengthEntity[];
}
```

I want to load a UserStrength which may or may not exist along with the Strength with a given strengthType (I would also need to RIGHT JOIN to the UserEntity to further filter by UserEntity.id)

Could anyone explain how this is accomplished with typeorm please?

**Comment by pleerock** [comment]
Its not possible to do right joins in concept of such ORMs and I'll try to explain why.

Lets say we have `Post` and `Category` entities. 
If we do left or inner joins we just select posts and all their categories and query builder it returns you posts with or without categories.

If we do a right join we start with posts and return posts with categories and just categories without posts. Since query builder selects and returns `Post[]` where do we insert categories without posts? We can't afford to return separate list of posts and categories it will break current query builder design.

I suggest you to revisit sql you want to write with only left and inner joins, or maybe use subselects, or in worth case scenario you can write raw sql query, execute it and transform to entity manually.
