### ISSUE TITLE
Joins are only pulling some data, but not all?!

### ISSUE THREAD

**Issue by twigs67** [typeorm/typeorm#7713]
URGENT PLEASE HELP! Will pay for your time. 

For whatever reason, my inner joins have decided to only pull the first row with complete information. As you can see here, my `roles` pulls ORG_ADMIN and all the information for that record, but then every other role it only pulls the `created_at`, `updated_at` and `id` for subsequent rows.

It's also only happening in my production environment?

Any help would be greatly appreciated.

<img width="416" alt="Screen Shot 2021-06-06 at 6 08 21 PM" src="https://user-images.githubusercontent.com/15682296/120943051-30520900-c6f2-11eb-9db1-3c0702c673c5.png">

**Comment by twigs67** [comment]
Ok, I ran .getQuery() to see the call TypeOrm was making and it is making the correct call and grabbing all of the correct information. Now the question is, why is it stripping fields for everything after the first call? 

This is really weird, because this JUST started happening and only on prod. I'm running:
```
 "@nestjs/typeorm": "^7.1.5",
 "typeorm": "^0.2.30",
```

**Comment by twigs67** [comment]
I can show my entities too if anyone feels that would help, but I haven't touched my entities in almost a year.

**Comment by twigs67** [comment]
I have tried adding `getMany`, but it didn't work.

**Comment by twigs67** [comment]
I'm absolutely stumped right now. I'm resorting to create a raw query for now. So if anyone can help me, I'd be willing to pay for your time. Thanks

**Comment by marcusadolfi** [comment]
@twigs67 same here!! 

Don't know exactly which version is causing this issue but i downgraded to version 0.2.29 and solve it.

**Comment by imnotjames** [comment]
When opening an issue, people will be better able to provide help if you provide code that they can easily understand and use to reproduce the problem. This boils down to ensuring your code that reproduces the problem follows the following guidelines:

* Minimal – Use as little code as possible that still produces the same problem
* Complete – Provide all parts someone else needs to reproduce your problem in the question itself
* Reproducible – Test the code you're about to provide to make sure it reproduces the problem

## Minimal
The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:

1. Restart from scratch. Create a new program, adding in only what is needed to see the problem. Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
2. Divide and conquer. If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Don't sacrifice clarity for brevity when creating a minimal example. Use consistent naming and indentation, and include code comments if needed. Use your code editor’s shortcut for formatting code.

Don't include any passwords or credentials that must be kept secret.

## Complete

Make sure all information necessary to reproduce the problem is included in the issue itself.

If the problem requires some code as well as some XML-based configuration, include code for both. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

**DO NOT** use images of code. Copy the actual text from your code editor, paste it into the issus, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists.

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.
