### ISSUE TITLE
Question - What does @JoinTable in @ManyToMany does?

### ISSUE THREAD

**Issue by Urigo** [typeorm/typeorm#794]
Hi and sorry for the stupid question:

What is the difference between the two connected entities with @ManyToMany ?
What does the `owner side` means?

**Comment by pleerock** [comment]
Let's start with `one-to-one` relation.
Let's say we have two entities: `User` and `Photo`:

```typescript
@Entity()
export class User {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    name: string;
    
    @OneToOne()
    photo: Photo;
    
}
```

```typescript
@Entity()
export class Photo {
    
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    url: string;
    
    @OneToOne()
    user: User;
    
}
```

This example does not have `@JoinColumn` decorator which is not correct.
Why? Because to make a real relation we need to create a column in the database.
We need to create a column `userId` in `photo` table or `photoId` in `user` table.
But which exactly column should be created - `userId` or `photoId`?
ORM cannot decide it for you. 
To make a decision you must `@JoinColumn` decorator on one of the side.
If you put `@JoinColumn` in `Photo` entity then `userId` column will be created in `photo` table.
If you put `@JoinColumn` in `User` entity then `photoId` column will be created in `user` table.
Where you put `@JoinColumn` decorator that side will be called "owner side of the relationship".
Other side of relation, without `@JoinColumn` decorator is called "inverse (non-owner) side of relationship".

Same in `@ManyToMany` relation you use `@JoinTable` decorator to show owner side of relation.

In `@ManyToOne` or `@OneToMany` relations `@JoinColumn` decorator is not necessary because 
both decorators are different and where you put `@ManyToOne` decorator that table will have relational column. 

`@JoinColumn` and `@JoinTable` decorators are also can be used to specify additional
join column / junction table settings, like join column name or junction table name.

**Comment by Urigo** [comment]
@pleerock thank you for the detailed answer.

So in case of `@ManyToMany`, it will create a separate table that will have two columns - `photoId` and `UserId`.  
so no need for a column on the `Photo` table nor the `User` table (and creating that with TypeORM I also see that behaviour).
So where does `@JoinTable` owner comes into play?
I mean, does it change anything in the implementation?
If so, what if there is no owner, they are both just connected to each other and each side can create the other side with connection as well?

Thanks

**Comment by pleerock** [comment]
I don't remember all places where it does matter, but it does. For example naming thing. It names table like this: `user_photos`. ORM makes decision to name it `user_photos` or `photo_users` based on which side is owning. Same with columns order inside this table.

Also having join table on one side prevents it to create two tables and makes it really bi-directional.

If you are confused where to put join table decorator, just try to think about data side. What is "original" side of relation. For example if user has photos and photos cannot exist without users then probably join table must be set on user side.

**Comment by Urigo** [comment]
@pleerock what if both sides are really "equal" also in the logical sense?

**Comment by pleerock** [comment]
Its all about decision. If you think both sides are equal then put jointable/joincolumn decorator on any side you want.

**Comment by pleerock** [comment]
I think this can be closed

**Comment by lefebvresam** [comment]
Putting joincolumn on a ManyToMany has no effect.

**Comment by pleerock** [comment]
@lefebvresam ManyToMany uses JoinTable instead of JoinColumn

**Comment by chetanchougle** [comment]
@pleerock   But can we use just JoinColumn to get granchildren data . 
Fore example -  table A has foreign key from table B & table B has foreign key from table C  .
How do you get data from table C as well . Does Typeorm support this ?
