### ISSUE TITLE
default value of column [type] is not constant

### ISSUE THREAD

**Issue by chiaramaya** [typeorm/typeorm#7963]
## Issue Description

typeorm version: 0.2.32
Sqlite and dropColumn: default value of column [type] is not constant

### Expected Behavior

function dropColumn with queryRunner: I have to remove a column 

### Actual Behavior

when I use "dropColumn" with queryRunner on a table that have a column ("type" in my example) with default, I have this error "default value of column [type] is not constant"

```
// code
 const connection = getConnection(connectionName);
 const queryRunner = connection.createQueryRunner();
 await queryRunner.dropColumn('vat', 'name');


// error
QueryFailedError: SQLITE_ERROR: default value of column [type] is not constant
 query: `CREATE TABLE "temporary_vat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(32) NOT NULL, "type" varchar(12) DEFAULT ("good")`,
      parameters: []
    } QueryFailedError: SQLITE_ERROR: default value of column [type] is not constant
```

I found an error in a query generator:  "type" varchar(12) DEFAULT ("good")
The correct query is without brackets in default value - "type" varchar(12) DEFAULT "good":

```
CREATE TABLE "temporary_vat" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(32) NOT NULL, "type" varchar(12) DEFAULT "good"
```

**Comment by fieteboerner** [comment]
I have encountered the same issue in SQLite by just creating a table using a migration. The error occurres by setting a string default value to a text/varchar column. I get no errors by setting numeric values to numeric columns.

Perhaps my test repo can help to reproduce the Issue more easily.

# Issue Description

typeorm version: 0.2.41
`QueryFailedError: SQLITE_ERROR: default value of column [column_name] is not constant`

## Expected Behavior
The migration creates a table with the defined two columns. 
The column `column_with_default` should have a default value `'x'`.

The generated query should look like `CREATE TABLE "test" ("id" integer NOT NULL, "text_with_default" varchar NOT NULL DEFAULT "x", CONSTRAINT "UQ_5417af0062cf987495b611b59c7" UNIQUE ("id"))` (Default value with quotes and without parentheses)


## Actual Behavior
By running the migration the process stops with the following error.

```
query failed: CREATE TABLE "test" ("id" integer NOT NULL, "text_with_default" varchar NOT NULL DEFAULT (x), CONSTRAINT "UQ_5417af0062cf987495b611b59c7" UNIQUE ("id"))
error: [Error: SQLITE_ERROR: default value of column [text_with_default] is not constant] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
``` 

## Steps To Reproduce

1. `git clone https://github.com/fieteboerner/typeorm-bug`
2. `npm install`
3. `npm run typeorm migration:run`
4. > The migration fails

> Important file: `src/migration/1643131543733-TestSqlite.ts`

**Comment by Ginden** [comment]
@fieteboerner @chiaramaya It's working as intended.

String value from `default` field is inserted as-is into query.

To achieve your expected result, use:

```
{default: `'x'`}

**Comment by fieteboerner** [comment]
@Ginden oh, ok. Thanks for the explanation. 

It is also very important to use single quotes and no double quotes because of the parentheses. 
- \`'x'\` -> ('x') - valid
- \`"x"\` -> ("x") - invalid, but "x" would be valid 

This definitively should be documented because it isn't straight forward to deal with.

But I think it is still a Problem for @chiaramaya.  He is just dropping a column and has no control over the default value, because the create table query gets generated by typeorm itself, based of the current schema.
