### ISSUE TITLE
Set @Column() default db type for string properties to 'text' instead of 'varchar'

### ISSUE THREAD

**Issue by Xzas22** [typeorm/typeorm#7979]
## Documentation Issue
Set @Column() default db type for string properties to 'text' instead of 'varchar'

### What was unclear or otherwise insufficient?
Is is possible to change the TypeOrm default db types for string properties? The documentation makes no mention but I assume each driver has its own definitions of what primitive types match what db types.

**Comment by amittal-quot** [comment]
you can use `@column({type:"text"})`

**Comment by Xzas22** [comment]
I know I can for individual columns but I have 45 tables, some with 20+ columns. 

I want to change the typeorm setting that makes decorating a string property with a normal @Column() decorator default to ‘text’

**Comment by blazmrak** [comment]
@Xzas22 You can have that done in an hour, maybe two and it is a one time job.

If you want you can modify the driver locally [here](https://github.com/typeorm/typeorm/blob/f7eb46dee0766581b6b182724051746e5d8d1b8b/src/driver/postgres/PostgresDriver.ts#L733) and then use it, but you will have to maintain it. Keep in mind that there is no guarantee that something else won't break because of this.

**Comment by pleerock** [comment]
If you asking about changing default behavior - no, we can't do that because using `text` is limiting your strings in a number of ways and you'll have different performance problems with this approach.

If you asking about providing a special configuration for such purpose - then answer is no, we can't do that because it is too specific request.

@blazmrak provided a good solution for your request. You can also create your "own column decorator" that simply calls default "Column" decorator, but with type set to `text`.

**Comment by AlissonRS** [comment]
@pleerock I'm afraid they were not asking to change it in the library itself, but rather an option for devs to configure what should be the default db type for string (or even number?) in their own project.

You say `text` has limitations, and I say `varchar` has limitations too. I'd like all string columns to be `nvarchar` by default as it avoids a lot of pain when dealing with unicode characters, please check the most upvoted answer here for the rationale: https://stackoverflow.com/questions/144283/what-is-the-difference-between-varchar-and-nvarchar

I do think `nvarchar` should be default in the library itself for the reasons explained in that SO answer, but I get that changing that now would be a breaking change, but would it be possible to at least provide an option for us to override that? Yeah we could create custom decorators, but I wanted new devs joining the team to have a smoother onboarding and use TypeORM as it is without having to think about custom decorators, and coming from Entity Framework for C# I really miss this feature.

Thanks and I appreciate this great library!!!
