### ISSUE TITLE
TypeScript's primitive number type doesn't match the nullable true option in decorator

### ISSUE THREAD

**Issue by piyushchauhan2011** [typeorm/typeorm#7997]
## Documentation Issue

I was going through the FAQ section and noticed that the type defined for `profileId` doesn't have `null`. Is it automatically inferred because assigning `null` to `number` field gives error

Link for the section: https://github.com/typeorm/typeorm/blob/master/docs/relations-faq.md

<img width="1215" alt="Screen Shot 2564-08-01 at 07 42 21" src="https://user-images.githubusercontent.com/693487/127755666-5fb46943-efa8-4460-9a0f-803c84cb065c.png">

### What was unclear or otherwise insufficient?

It looks like it's missing `null` in the type of `profileId` or I might be unclear on how to handle nullable option properly

### Recommended Fix

Add `null` in the type of `profileId`

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✅ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by pleerock** [comment]
The reason why documentation misses `| null` is simplicity. Since TypeScript is configurable, in order to have "errors" with `null` you need to enable `strict` mode. By default this mode is disabled to improve understanding for newcomers to TypeScript. We are following same way - simpler entity definitions to reduce understanding complexity for newcomers. Otherwise putting `| null` isn't the only change we need to bring (also for example, "!" for class properties).

**Comment by piyushchauhan2011** [comment]
Thanks @pleerock this answers my doubt

**Comment by vith** [comment]
Improper type definitions around nullability easily leads to a mess of runtime errors later on, of the precise kind that typescript was created to solve. I'm not sure it's a good idea to send people down this path.
