### ISSUE TITLE
Query not properly escaped with parameter keys containing a "." (dot) character in them

### ISSUE THREAD

**Issue by sylvain-bouchard** [typeorm/typeorm#8015]
## Issue Description

Following #7821, it seems that we are no longer able to specify a parameter key having a "." character in it.

For instance, in my application, I have a parameter key referring to the table name and field as follows: "selectionRoom.id". For such a key, the regex `/:(\.\.\.)?([A-Za-z0-9_]+)/g` in `escapeQueryWithParameters` does not capture the ".", and so the parameter key is left as ":selectionRoom.id" in the resulting SQL statement, which is wrongly interpreted by the database.

### Expected Behavior

Parameters with a key containing a "." should be properly escaped.

### Actual Behavior

Parameters with a key containing a "." are left in the form that starts with a ":" prefix.

### My Environment

| Dependency          | Version  |
| ---                 | ---      |
| Operating System    |  MacOS 10.14.6  |
| Node.js version     | 14.17.0  | 
| Typescript version  | 4.1.6  | 
| TypeORM version     | 0.2.36  | 

### Relevant Database Driver(s)

| DB Type              | Reproducible  |
| ---                  | ---           |
| `aurora-data-api`    | no            |
| `aurora-data-api-pg` | no            |
| `better-sqlite3`     | no            |
| `cockroachdb`        | no            |
| `cordova`            | no            |
| `expo`               | no            |
| `mongodb`            | no            |
| `mysql`              | no            |
| `nativescript`       | no            |
| `oracle`             | no            |
| `postgres`           | yes            |
| `react-native`       | no            |
| `sap`                | no            |
| `sqlite`             | no            |
| `sqlite-abstract`    | no            |
| `sqljs`              | no            |
| `sqlserver`          | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✅ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✖️ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by imnotjames** [comment]
I'm hesitant to completely fix this - parameters used to allow spaces, colons, null bytes, etc - not just periods.  This means that in many cases we had bugs that were caused by parameters overlapping with non-parameter characters.

Instead, I think preventing invalid characters from being used as part of the parameter key would be the better path forward.

I'll add periods to the parameters (though this is not supported in any SQL dialect..) and limit the incoming characters otherwise.

**Comment by pleerock** [comment]
> I'll add periods to the parameters (though this is not supported in any SQL dialect..) and limit the incoming characters otherwise.

wait, if we go with:

> I think preventing invalid characters from being used as part of the parameter key would be the better path forward.

we don't need to add exceptions. Let's decide first what is the best approach. I also think we should have a strategy for straightforward parameter names.

**Comment by imnotjames** [comment]
> we don't need to add exceptions. Let's decide first what is the best approach. I also think we should have a strategy for straightforward parameter names.

The issue is that the regular expression needs to match between the two locations.  Right now what happens is that you can add whatever you'd like as a parameter name (which is difficult to match against if it includes every possible character) but the regex used to replace these is more limited so as to not mistakenly pull in other things as parameters.

This was done because the previous implementation was causing problems with running out of memory, running out of matching groups, etc.  I had pulled what was used and in documentation as the character set allowed - but it seems there's a number of places that use periods as part of their character set for parameter names.

**Comment by pleerock** [comment]
> but it seems there's a number of places that use periods as part of their character set for parameter names.

what do you mean by "number of places"? You mean number of different users who use TypeORM? If yes, who else?

**Comment by imnotjames** [comment]
This came up through https://github.com/nestjsx/crud & anyone that uses the `@nestjsx/typeorm-crud` side of things

**Comment by pleerock** [comment]
ah okay got it. Because of popularity of this package lets add an exception.

**Comment by Leithal3** [comment]
Sorry to jump on this late, but I was hoping to get your thoughts. 

In order to prevent parameter clashing in a generic way (when required) - we use uuidv4 parameters. These contain hyphen (-) characters which would now cause an error to be thrown. 

Previously we had no issues with hyphens in the parameters, but I'm wondering if that was due to some translation occurring under the hood or if hyphens are actually fine in the parameters.

@pleerock 
@imnotjames
