### ISSUE TITLE
How to set options when using better-sqlite3 with sqlcipher?

### ISSUE THREAD

**Issue by yolopunk** [typeorm/typeorm#8475]
Issue type:

- [x] question
- [x] bug report
- [ ] feature request
- [ ] documentation issue

Database system/driver:

- [ ] cordova
- [ ] mongodb
- [ ] mssql
- [ ] mysql / mariadb
- [ ] oracle
- [ ] postgres
- [x] sqlite / better-sqlite3-multiple-ciphers
- [ ] sqljs
- [ ] react-native
- [ ] expo

TypeORM version:

[x] 0.2.41
[ ] @next
[ ] 0.x.x (or put your version here)

better-sqlite3-multiple-ciphers version: 7.4.5

* The following method is in effect （using `better-sqlite3-multiple-ciphers`)

```js
// encrypt db
const db = require('better-sqlite3-multiple-ciphers')('foobar.db', { verbose: console.log })
db.pragma("cipher='sqlcipher'")
db.pragma(`rekey='secret-key'`)
db.prepare(`CREATE TABLE "post" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar NOT NULL, "text" varchar NOT NULL)`).run()
const stmt = db.prepare('INSERT INTO post (title, text) VALUES (?, ?)')
const info = stmt.run('Joey', 'my homie')
db.close()

// decrypt db
const db = require('better-sqlite3-multiple-ciphers')('foobar.db', { verbose: console.log });

db.pragma(`cipher='sqlcipher'`)
db.pragma("key='secret-key'");
const stmt = db.prepare("SELECT * FROM post")
console.log(stmt.get()); // { id: 1, title: 'Joey', text: 'my homie' }
```
* The following method is not valid （using `typeorm`)

```typescript
import { createConnection } from 'typeorm'
import { BetterSqlite3ConnectionOptions } from 'typeorm/driver/better-sqlite3/BetterSqlite3ConnectionOptions'
import { Post } from './entity/post'

const config: BetterSqlite3ConnectionOptions = {
  type: 'better-sqlite3',
  key: 'secret-key',
  database: 'foobar.db',
  driver: require('better-sqlite3-multiple-ciphers'),
  entities: ['entity/*.ts'],
  logging: true,
  verbose: console.log,
  prepareDatabase: db => {
    db.pragma(`cipher='sqlcipher'`)
  }
}

const start = async () => {
  const conn = await createConnection(config)
  const posts = await conn.manager.find(Post)
  console.log(posts)
}

start()  // SqliteError: file is not a database
```

I don’t know what’s wrong with my options for `typeorm`.

Related to issue: https://github.com/m4heshd/better-sqlite3-multiple-ciphers/issues/4

The reproducible repo: https://github.com/yolopunk/typeorm-better-sqlite-sqlcipher

**Comment by m4heshd** [comment]
The issue is `typeorm` tries to run [`PRAGMA foreign_keys = ON`](https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/driver/better-sqlite3/BetterSqlite3Driver.ts#L106) before executing `prepareDatabase()` which leads to file not being recognized as a DB since it's already encrypted.

In my opinion this execution order is not effective or helpful at all when coupled with custom implementations of the library which in this case is an encryption extension. Current method of initialization also goes against the practices of official [SQLite Encryption Extension](https://www.sqlite.org/see/doc/release/www/readme.wiki) which has identical usage and behavior to `better-sqlite3-multiple-ciphers`.

> You must invoke this pragma before trying to do any other interaction with the database. - SEE documentation

There are two possible solutions for this.

1. Bring the execution of `prepareDatabase()` to the top
2. Introduce a new functional config that runs right after [initializing the DB](https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/driver/better-sqlite3/BetterSqlite3Driver.ts#L102)

**Comment by yolopunk** [comment]
@m4heshd 

https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/driver/better-sqlite3/BetterSqlite3Driver.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L102-L120

Here is the related code. I don't see anything wrong with the logical order. 

Please review it, maybe you can focus on some problems.

**Comment by m4heshd** [comment]
@yolopunk That's the same block of code which I linked above.

https://github.com/typeorm/typeorm/blob/cefddd95c550191d6a18cb53c8ea4995d0c219ca/src/driver/better-sqlite3/BetterSqlite3Driver.ts#L106

This line should not execute before `prepareDatabase()` does.

**Comment by yolopunk** [comment]
Awesome! That is worked by verification. I could commit a pull request for fixed the bug!

**Comment by m4heshd** [comment]
@yolopunk I wouldn't jump into that because that could be a breaking change for the existing users. Introducing something new would be the best option here.

**Comment by pleerock** [comment]
Thank you guys!
