### ISSUE TITLE
Major version

### ISSUE THREAD

**Issue by ioncreature** [typeorm/typeorm#8775]
## Feature Description

Please name any next version as a major version

### The Problem

Last 0.3 release has a list of breaking changes.

Dependency update bots like `dependabot` and `renovate` use simple rules - if the version number is second then it means this is a minor update, without breaking changes. I understand that semver allows this, but anyway. Release 0.3 broke all microservices I'm owning.

To avoid such problems in the future please make any next release a major release, like `1.0`

### The Solution

Please make a major release 1.0 as soon as possible.

**Comment by pleerock** [comment]
> I understand that semver allows this, but anyway. Release 0.3 broke all microservices I'm owning.

You just answered your question. You need to follow semver as well in order to prevent your code breaking. If dependency bots do not follow it, I'm not sure why they work this way.

We are planning to bring more improvements and breaking changes in the future 0.4+ versions, so I don't really want to release 1.0 at the moment. Sorry if it bring inconveniences.

**Comment by acSpock** [comment]
@pleerock that's the point that @ioncreature is making. This package has been in development for over 6 years and still has no major version. Semver says that anything 0.x.z can be breaking and is unstable.

typeorm is one of the most widely used orm's for nodejs applications and yet developers are still expected breaking changes with minor version bumps. I understand that this is an open source project but the life of long projects that decided to use typeorm, even years ago, are still expected breaking changes as they try to keep up with package releases. Perhaps the dev teams that decided to use typeorm in their projects should have known the consequences of choosing a pre major release a package. Also, perhaps the typeorm maintainers should consider moving toward a major and stable release version so that dev shops can be more prepared to deal with backward compatibility.

**Comment by ramblingenzyme** [comment]
@pleerock Even just an understanding of what the maintainers think is left before deciding to release 1.0 would be amazing.
