### ISSUE TITLE
Entity Metadata not found - Works in production, but fails for integration tests

### ISSUE THREAD

**Issue by wsdt** [typeorm/typeorm#8798]
For me the string path entities: ['dist/entity/**/*.entity.js'], works in production code, but for the integration tests this and all above solutions fail. I always need to define the entities explictly by adding them one by one.

This can't be the solution as that's not scalable, you always need to manually add the entities. Did anyone have the same problem for integration tests only?

**Comment by pleerock** [comment]
You have a configuration issue. Debug how integration tests are running and how it differs from production execution context.

Also I recommend to stop using string entity paths because this feature is going to be removed in the next `0.4.0` version. This was discussed multiple times across the repo, but shortly 3 main reasons:

* problems like you currently have
* unexpected user-facing DX issues due to removed entities persisted in the `outDir`
* we want to make entities explicitly defined to introduce new type-safety features in the future versions

**Comment by Jo-Chris** [comment]
To me that sounds like an unnecessary additional thing to keep track of.

**Comment by pleerock** [comment]
You answer the questions and deserve 👎 . Great 🚀 

> To me that sounds like an unnecessary additional thing to keep track of.

yes, software engineering is full of pros and cons and you have to leverage.

Sometimes it's better to have additional thing to keep track of rather than spend hours or days on weird bugs because of the cool features.

Sometimes you have to choose between one cool feature and another more cool feature, because they cannot live together.

Simply said:

* unnecessary additional thing to keep track of **<** problems like you currently have
* unnecessary additional thing to keep track of **<** unexpected user-facing DX issues due to removed entities persisted in the outDir
* unnecessary additional thing to keep track of **<** new type-safety features in the future versions

**<** means "less valuable".

**Comment by wsdt** [comment]
Completely understandable, but other frameworks are capable of that feature too. 

But thank you for the reply :)

**Comment by pleerock** [comment]
> Completely understandable, but other frameworks are capable of that feature too.

I have a simple answer to this statement.

If you mean "other frameworks in other languages" - then yes, they do, because they have a different language and different platform/language specifics. And of course they do not have cool features like JavaScript / TypeScript have.

If you mean "other frameworks in JavaScript / TypeScript" - then all these frameworks has following problems:

- problems like you currently have
- unexpected user-facing DX issues due to removed entities persisted in the outDir
- missing cool type-safety features
