### ISSUE TITLE
Relations and limit

### ISSUE THREAD

**Issue by xfg** [typeorm/typeorm#89]
Suppose `Post` and `Comment` have relation one to many.
How to select post only with 10 comments? I don't found answer at this question in the documentation.

**Comment by pleerock** [comment]
the only way you can do it is to create and execute separate queries:

```typescript
const posts = await getEntityManager()
    .createQueryBuilder(Post, "post")
    .getResults();

const promises = posts.map(async post => {
    post.comments = await getEntityManager()
        .createQueryBuilder(Comment, "comment")
        .where("comment.post=:postId", { postId: post.id })
        .getResults();
});

await Promise.all(promises);
```

The problem with using single query builder is that if you use leftJoinAndSelect it will join all comments and there is no way to limit it. If you use limit for selected data with joins - you'll fail because limit only truncates number of returned results, which includes duplications because of joined data. Its a problem of design of relational databases.

But maybe in the future we can add some helper methods to query builder which may allow to select a data from different table with limit and without joins and map this data into some object property.

Btw alternatively you can try subqueries, but this is maybe more advanced and complicated.

**Comment by xfg** [comment]
> But maybe in the future we can add some helper methods to query builder which may allow to select a data from different table with limit and without joins and map this data into some object property.

I would want to see this. Many ORM in other programming languages do the relations without joins. I have complex relations as `a.b.c.d` and I want to load only 10 entries from `a` then for each entry from `a` I want to load only 10 entries from `b` and so on.

**Comment by pleerock** [comment]
> Many ORM in other programming languages do the relations without joins

even without joins... Can you link me orm which supports loading of relations with limitation? I want to see design and maybe take some of its best practices?

**Comment by xfg** [comment]
Sorry, I don't know orm which supports loading of relations with limitation. I only know orm which loads relations without joins, by separate queries through `SELECT * FROM ... WHERE IN ...`.  For example [here](http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#lazy-eager-loading). One additional query for each relation.

I think that limitation possibly do for mongodb because field contains all relations ids and we can simply select several ids from them and then do query with [$in](https://docs.mongodb.com/manual/reference/operator/query/in/) to database. But for relational databases it do more difficult.

**Comment by pleerock** [comment]
I also haven't seen any orm with support of loading relations with limitation.
How yui's orm is implemented is their own way, I would argue if this approach is better then joins.
Also you should not compare relational database orms with document database orms. Anyway, the issue here is about limitation in relation and I'll investigate this question later once I finish more priority tasks

**Comment by apezel** [comment]
Hibernate or EclipseLink support this by selecting first the collection (without join) and then selecting relations. A first work around would be to lazy load relations.

**Comment by apezel** [comment]
I think this could be achieved by adding a ```defferSelect``` option on join methods wich would result in : 

```sql
select * from my_table limit 10;
```
And then : 

```sql
select t.* from my_relation t where t.join_id in (ids from request 1)
```

**Comment by apezel** [comment]
A work around is to inner join a subquery with the limit and where clauses (don't know if it works in every case) : 

```javascript
let q = conn.getRepository(Model).createQueryBuilder("model");
q.andWhere("model.field = :param", {param: value});
q.setOffset(off);
q.setLimit(limit);

let q2 = conn.getRepository(Model).createQueryBuilder("model");
q.select("model.id");
q2.innerJoin(`(${q.getGeneratedQuery()})`, "intermediate_table", "ON", "model.id = intermediate_table.id");
q2.setParameters(q.getParameters());
q2.leftJoinAndSelect("relation", "realtion_alias");
q2.getResults();
```

Don't know if it could be included as a real solution but it works. But it may cause problem when trying to add a where clause on the left joined relation.

I don't have many times these days but i can contribute if needed.

**Comment by pleerock** [comment]
@apezel very nice that you could get subqueries done without any examples provided by me! I think we can introduce extra `limit` option to `leftJoin/innerJoin`. But need to think about signature of this method and how to pass it, because there also possible to send parameters which may bring conflict.  After that need to check in the query builder if limit is set then perform subquery with limitation set instead of join.

**Comment by xfg** [comment]
@apezel yes, your solution (without joins) is a typical for many ORM, but exist use case which will not properly work, e.g. if we need to select 10 posts and 3 comments to each post. The similar use cases is a problem for all ORM which I saw.

**Comment by apezel** [comment]
@xfg do you mean to apply a limit on the relation itself ?

**Comment by xfg** [comment]
@apezel yes, I want to apply the limit on the relation when I select several entities from database which have one to many relation. See http://stackoverflow.com/questions/1442527/how-to-select-the-newest-four-items-per-category

**Comment by apezel** [comment]
@xfg Ok i was answering to a different problem : apply a limit on a model that has relations fetched with a join. For example : 
```javascript
let q = conn.getRepository(Model).createQueryBuilder("model");
q.leftJoinAndSelect("relation", "realtion_alias");
q.setOffset(0);
q.setLimit(10);
```
will result in the following sql : 
```sql
select model.* from model model left join relation relation_alias limit 0 offset 10
```
It works if relation is a onetoone but it doesn't if the relation si a onetomany because the limit will be applied on everything and not just on model. That's the purpose of my joined subquery : apply the limit and the where clauses on model and then joining the result to the final query : 

```sql
select model.*, relation.*
  from model model
    inner join (select id from model limit 0 offset 10) intermediate on model.id = intermediate.id
    left join relation r;
```

@pleerock @xfg By the way, i'm not sure that allowing to apply a limit on the relation itself is a good idea because it may cause unwanted removes during save : 

```javascript
let q = conn.getRepository(Model).createQueryBuilder("model");
q.leftJoinAndSelect("relation", "realtion_alias", {limit: 10});
let fetchedModel = await q.getSingleResult();
await conn.getRepository(Model).persist(fetchedModel);
// <-- problem : some relations have been removed because of the limit
```

**Comment by pleerock** [comment]
@apezel right, such fetched models should only be used for representation, and should not be persisted

**Comment by pleerock** [comment]
It's not possible to implement "limit" for joins. The only way to query relations separately is to use another query, or subquery.

As of `0.1.0-alpha.23` there are lot of useful methods to create subqueries using elegant api. See [there](https://github.com/typeorm/typeorm/blob/0b4e3ff5eb52ca05f0fe9e9fe5d7b6e1b575863a/test/functional/query-builder/subquery/query-builder-subquery.ts#L74) how to use subqueries. Some of examples are:

```ts

        const posts = await connection.getRepository(Post)
            .createQueryBuilder("post")
            .where(qb => {
                const subQuery = qb.subQuery()
                    .select("user.name")
                    .from(User, "user")
                    .where("user.registered = :registered")
                    .getQuery();
                return "post.title IN " + subQuery;
            })
            .setParameter("registered", true)
            .getMany();
```

```ts
const posts = await connection
            .createQueryBuilder()
            .select("user.name", "name")
            .from(subQuery => {
                return subQuery
                    .select("user.name", "name")
                    .from(User, "user")
                    .where("user.registered = :registered", { registered: true });
            }, "user")
            .setParameters(userQb.getParameters())
            .getRawMany();
```

**Comment by atonamy** [comment]
@pleerock

> > Many ORM in other programming languages do the relations without joins
> 
> even without joins... Can you link me orm which supports loading of relations with limitation? I want to see design and maybe take some of its best practices?

Please have a look this [solution](https://github.com/typeorm/typeorm/issues/4255) it seems is possible to load relations with limitations.
Another way is to use [LATERAL joins](https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html) which currently not supported by TypeOrm, but it only works in MySql version 8.0.14 and above.

Could be really nice if you can implement wrappers that has such support without using hacking approach.

**Comment by ezze** [comment]
This issue is five years old, and I can't believe it's not solved but closed. As already told above, selection algorithm should be splitted into several separate queries.

@pleerock This kind of functionality exists in Yii framework and in [Sequelize](https://sequelize.org/) (see `separate` option of `findAll` method in a [model](https://sequelize.org/master/class/lib/model.js~Model.html)).

Unfortunately, lack of this kind of functionality makes TypeORM almost useless in many daily scenarios during working with relational database.

**Comment by spotykatch** [comment]
Oh, seems fun.
@ezze, Could you please make an example of how the call should look for a separate `a.b.c.d` relation?
So we do have
```ts
@Enity()
export class Post {
  @OneToMany(() => Comment, comment => comment.post)
  comments: Comment[]
}

@Enity()
export class Comment {
  @ManyToOne(() => Post, post => post.comments)
  post: Post

  @OneToMany(() => Coment, comment => comment.subComments)
  subComments: Comment[]
}
```
How the query for `a(limit: 10) -> b(limit: 5) -> c(limit: 3) -> d(limit: 1)` should be called. I just don't really get that. That seems ok for `a.b` relation, but if we make it more complicated, then it looks like a callback hell.

**Comment by kkkasio** [comment]
> 
Did you have an answer of a way to do?

**Comment by ezze** [comment]
@kkkasio I ended up quering `id`s of entities without `left join`s (but with `inner join`s if required) including filtering (`where`) and `limit`. This way you I get proper `count` of entities first. After that I can `left join` relations in a separate query providing received `ids` in `where` clause. But this approach may be not suitable for you if you want to filter by properties of left joined relations.

**Comment by kkkasio** [comment]
> @kkkasio I ended up quering `id`s of entities without `left join`s (but with `inner join`s if required) including filtering (`where`) and `limit`. This way I get proper `count` of entities first. After that I can `left join` relations in a separate query providing received `id` in `where` clause. But this approach may be not suitable for you if you want to filter by properties of left joined relations.

Thanks for your reply, it's really an annoying problem but it's workable.
I just wouldn't want to explicitly deal with the joins.

**Comment by apudiu** [comment]
Why TypeORM doesn't look into the source code of Larave's Eloquent? I'm sure TypeORM can learn from that.

**Comment by osmanyz** [comment]
This issue is almost 8 years old. I still cannot believe how they can closed unsolved issue.
