### ISSUE TITLE
Repository: differents between .save() and .persist() and would a .insert() be possible?

### ISSUE THREAD

**Issue by daniel-lang** [typeorm/typeorm#899]
The title more or less says it all, what is the difference right know (or the difference planed) between `.save()` and `.persist()` of a repository? Since looking at the source code, would suggest, that they do the same.
And is there a way to just insert the entities without the check beforehand? Because when I try to insert 700 entities at once a select statement is executed for each one of them, which isn't neccesary in every use case. Mine for example is, inserting entities that have been loaded from an api where I can be certain, that they do not exist in the table.

**Comment by pleerock** [comment]
> .save() and .persist()

`persist` is just old name of `save`. It just calls save method right now and there is zero difference, just naming. persist method is deprecated and will be removed in the future. Its there only because of old users who use persist when there was not save method.

> And is there a way to just insert the entities without the check beforehand?

Yes, using insert functionality of `QueryBuilder`. Example:

```ts
        await connection.createQueryBuilder()
            .insert()
            .into(User)
            .values([
                { name: "Umed Khudoiberdiev" }, // or your entities
                { name: "Bakhrom Baubekov" },
                { name: "Bakhodur Kandikov" },
            ])
            .execute();
```

**Comment by daniel-lang** [comment]
Okay, thanks for clearing that up for me!
