### ISSUE TITLE
How to export connection

### ISSUE THREAD

**Issue by raducostea** [typeorm/typeorm#91]
My project structure looks something like

```
models/
models/connection.ts
models/post/post.ts
models/post/post.service.ts
```

Inside the connection i have the createConnection() command

Inside post.ts i have the entity
Inside post.service.ts i have the repository

The issue is that if i use
```
let postService = Container.get(PostRepository);
export {postService }

```
inside the post.service.ts file i get this error

> " Error: Cannot get connection "default" from the connection manager. Make sure you have created such connection. Also make sure you have called useContainer(Container) in your application before you established a connection and importing any entity."

My guess is that createConnection() command needs to execute first?

If i use
`let postService = Container.get(PostRepository); `
inside the createConnection() promise function it works fine.

What should i do? I want to be able to easily import and use post service in multiple files like

```
import {postService} from 'models/post/post.service.ts'
postService.findAll()....
```

I am using https://github.com/typeorm/typeorm-typedi-extensions inside my post.service.ts in order to access the connection object inside the service.

**Comment by pleerock** [comment]
try to checkout https://github.com/typeorm/typescript-example and check if it work for you and you can change it to fit your needs.

The problem is that you are accessing repository without connection established which is wrong. I have removed this check in latest version. Try to install `npm i typeorm@next` (it should be `0.0.3-alpha.6`) and check if you still have issues.

**Comment by pleerock** [comment]
feel free to reopen it if you still have something to add here
