### ISSUE TITLE
specify length for postgres array

### ISSUE THREAD

**Issue by vrachels** [typeorm/typeorm#939]
In postgres, it is possible to specify the array length when creating the table.  

This is implied by ColumnOptions.d.ts, as well:
```
    /**
     * Indicates if this column is an array.
     * Can be simply set to true or array length can be specified.
     * Supported only by postgres.
     */
     isArray?: boolean;
```

however, setting the length in the options results is the PostgresDriver::createFullType string being built improperly, resulting in an invalid command.

> "Error: Column <> of Entity <> does not support length property."

There's currently no type checking for the optional params, so either should have a new array length entry, or should be something like 
```
if (column.length && !column.isArray) {
  type += "(" + column.length + ")";
}
```

```
if (column.isArray) {
  type += " array";
  if (column.length) {
    type += `[${column.length}]}`;
}
```

Currently postgres doesn't actually use the array length value, but it would be nice to not be intentionally confusing or broken - and even nicer to be ready for future implementation.

**Comment by pleerock** [comment]
Its not that simple. If its not used by postgres anyway then I don't think we shall implement it in orm yet. Because there is a multidimensional array support in postgres, and if we support that too we'll have issue with this design - column.length will not work anymore since each dimension will have its own length, so we'll be needed to pass an array of length. What if user simply want to make it multidimensional without applying a length? We'll need option for that as well.

I don't remember currently what was an issue with multidimensional arrays, but I think it was that postgres does not expose information about column type - if its multidimensional or not, thats why typeorm couldn't use it in schema sync.

**Comment by vrachels** [comment]
that is a good point, and an argument for creating a new config entry.
ie:  ```arrayDims: undefined | number | number[];```
   Any undefined/null would be [].  defined would be [#].

[array fn docs](https://www.postgresql.org/docs/current/static/functions-array.html) for details, but looks like array_ndims and array_dims might be the exposed info you need to rebuild the schema from an existing table.

**Comment by pleerock** [comment]
This feature has potential problems and is not in priority right now, so I'll close it for now.

**Comment by aman1205** [comment]
@Column('simple-array')
  options: string[];
  
 How we fixed length of array  , like i want to fix the length of array to 4
