### ISSUE TITLE
Please refund all the donations

### ISSUE THREAD

**Issue by secretjshero** [typeorm/typeorm#9555]
[Sequelize](https://github.com/sequelize/sequelize) and [Prisma](https://github.com/prisma/prisma) getting better with their new contributors and the issues is managed well, yet TypeORM looks like slowly rotten, the amount of your open source donation is not equal to what you have done started from [this issue](#3267).

Other ORMs deserves more donation.

Please fix this:
https://github.com/typeorm/typeorm/issues/2815
https://github.com/typeorm/typeorm/issues/1601
https://github.com/typeorm/typeorm/issues/2821
https://github.com/typeorm/typeorm/issues/2158
https://github.com/typeorm/typeorm/issues/3251 (???)
https://github.com/typeorm/typeorm/issues/2256 
https://github.com/typeorm/typeorm/issues/4270
https://github.com/typeorm/typeorm/issues/7086
https://github.com/typeorm/typeorm/issues/3136
https://github.com/typeorm/typeorm/issues/9096
https://github.com/typeorm/typeorm/issues/3051
https://github.com/typeorm/typeorm/issues/6123
https://github.com/typeorm/typeorm/issues/2440 (Documentation is outdated)
https://github.com/typeorm/typeorm/issues/2530
https://github.com/typeorm/typeorm/issues/4569

- Everyone will findout using decorators `@@@@@@@@@@@` in TypeORM with hacks workaround to achieve goals is bad.
- In transactions, many inserts generate an error
- Confuses Classes with Types
- In transactions when it throws an error, it doesn't roll back all operations within transactions
- The first stable 1.0.0 version release was planned for autumn of 2018, today on 2022/11, they have an unstable 0.3.10 version
- Confusing/obscure/unpredictable/broken parts. Sometimes glorious, sometimes goofy. Devs almost abandoned the project. Feels like driving a luxury car with flat tires. (stop donating this open source)

**Comment by pleerock** [comment]
Very funny. This library authors provided personal support to the most of the significant donations this project had. And of course countless hours of development and maintenance that obviously you can't understand. If you want to use alternative - go ahead and use Prisma, it will work for you until it's back-funded. Or go ahead and use other open source libraries until they get abandoned because of users like you @secretjshero (also you don't have to create fake accounts). 

In my daily job I use many different open source libraries, both popular and unpopular, backed by both communities and companies, and I can surely say that TypeORM is maintained better than 90% of them. This is state of open source, and thoughtless opinions can't really help here.
