### ISSUE TITLE
Alternate Migration Strategy

### ISSUE THREAD

**Issue by jacfra** [typeorm/typeorm#9573]
### The Problem

`typeorm` generates it's migrations in defiance of `git`.

Why exactly is there a migration history inside of the version control software?

Shouldn't the migration generation tool be written to take advantage of `git`?

### The Solution

Allow for an alternate migration strategy to generate migration files on a per table basis with a relationship file at the end to create the relationships after everything has been created. 

### Additional Context

None

### Relevant Database Driver(s)

| DB Type           | Relevant      |
|-------------------| ---           |
| `aurora-mysql`    | no            |
| `aurora-postgres` | no            |
| `better-sqlite3`  | no            |
| `cockroachdb`     | no            |
| `cordova`         | no            |
| `expo`            | no            |
| `mongodb`         | no            |
| `mysql`           | no            |
| `nativescript`    | no            |
| `oracle`          | no            |
| `postgres`        | no            |
| `react-native`    | no            |
| `sap`             | no            |
| `spanner`         | no            |
| `sqlite`          | no            |
| `sqlite-abstract` | no            |
| `sqljs`           | no            |
| `sqlserver`       | no            |

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ Yes, I have the time, and I know how to start.
 - ✖️ Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️ No, I don’t have the time, but I can support (using donations) development.
 - ✅ No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by luca-nardelli** [comment]
I'm not a contributor to TypeORM, but I cannot completely understand your proposed solution, and I assume that's the case for the typeorm developers as well. I'd say some examples and more detailed use cases would be very useful.

Regarding your question "Why exactly is there a migration history inside of the version control software?": To me, having the full history in git is a very useful feature, since it shows all transformations that happened to the database and also any custom SQL that might have been added to perform non trivial data migrations during the lifetime of the project.

**Comment by TimBeyer** [comment]
Migrations aren't necessarily just pure schema definition changes.  
Sometimes they perform backfilling or transforming of data in order to support a new schema for example.  
Additionally, not every setup has just a single DB or multiple DBs that are always at the same version of the schema.  
So in the end, you do often need the in between states since getting to the desired schema state is only part of the story when you're working in environments where you need to roll out changes with zero downtime.

Thus it's difficult in practice to only have a single schema declaration file which is being maintained.

What would be great though is a feature where you can easily create a schema dump as a migration file so that eventually you could squash all the previous migrations into one when you know that none of the old in-between steps are needed anymore.

What makes it tricky is that the migration runner only tracks the migrations it has to run based on a table containing the names of the past migrations. It isn't really aware that a dump of the schema would result in the same state as the DB is in right now, and thus it should skip this new migration on databases that have existed before the squashing of migrations.

One option could be to find a way to create a consistent hash over the entire schema, and use that to also track the state of migrations on the DB. You could recursively hash over all the tables so that you also know which specific tables are behind.
This isn't exactly trivial though, especially if the DB is somehow in a different state due to manual changes done during experimentation. If the hash somehow didn't add up, you would have no way to go forward anymore.

**Comment by jacfra** [comment]
@luca-nardelli 

Check out this example:

Given these `tables`

```
EntityA:
- id
// etc
- createdAt

EntityB:
- id
// etc
- EntityAId
```

Currently, the `typeorm` `cli` would create one `migration` file with all of the `tables`, `columns`, `relationships` and `indexes` (etc) between the `tables`.

i.e.

```
import {MigrationInterface, QueryRunner} from "typeorm"; 

export class Migration-2 implements MigrationInterface { 

   public async up(queryRunner: QueryRunner): Promise<any> { 
       await queryRunner.query(`CREATE TABLE entity_a ...`);
       await queryRunner.query(`CREATE TABLE entity_b ...`);
       // etc
   } 
   public async down(queryRunner: QueryRunner): Promise<any> { 
   } 
}

```

Then if you add a column to `EntityA` another `migration` file get generated to your `migrations` folder:

```
import {MigrationInterface, QueryRunner} from "typeorm"; 

export class Migration-2 implements MigrationInterface { 

   public async up(queryRunner: QueryRunner): Promise<any> { 
       await queryRunner.query(`ALTER TABLE entity_a ...`);
   } 
   public async down(queryRunner: QueryRunner): Promise<any> { 
   } 
}

```

So you end up with two `migration` files.

```
/project-root/migrations
- Migration-1.ts
- Migration-2.ts
```

I'm suggesting writing a `--table-state` flag so you can have one file for each `table` that changes based upon your `entities`. The history of the change of those `entities` is tracked with `git`, like the rest of the code in your codebase. If you have to back up to a previous state of your code base you can revert back to that state with `git`. And (@TimBeyer) if you have to transform, backfill or have multiple different databases on different schema versions you can write a `typescript` script to handle it.

One caveat being that because the `tables` have to exist first for `relationships` and `indexes`, etc to exist you should have separate `relationship` and `index` files  (if they exist) that are run after to show the history of changes to the `indexes` and `relationships`.

You could also have additional functions (like what `typeorm` currently has) to take the current state of the `database` into account and create `migrations` that take the differences between the `database` and `entities` into account.

Additionally, `typeorm` should generate its `migrations` as strongly typed `typescript` not strings. 

```
/project-root/migrations
- EntityAMigration.ts
- EntityBMigration.ts
- RelationshipMigration.ts
- IndexMigration.ts
```

**Comment by Lewiscowles1986** [comment]
You can always dump your DDL or DML if you want a copy of the schema locally. If that isn't what you are asking for then I think this is unclear.

**Comment by jacfra** [comment]
After writing through a few different iterations of the beginning stages of an app this wasn't as useful as I thought it might be.

i.e. having a magic to wave at any version of a database and get to the latest version is too useful of a feature to split up over multiple `git` versions. Especially, if you include data seeding/transforming functionality in the appropriate migration file.

My preference for strongly typed type script migrations remains the same.
