### ISSUE TITLE
Performance decrease when comparing to Bookshelf.js

### ISSUE THREAD

**Issue by vesse** [typeorm/typeorm#974]
I've been switching from [bookshelf.js](http://bookshelfjs.org/) to TypeORM since it looks better and supports joins whereas using `withRelated` of Bookshelf does `WHERE id IN (.....)` queries. 

After having implemented the same API that lists about 5000 items from our Postgres database I was surprised to find that the HTTP request handling takes about 1000ms with TypeORM whereas the Bookshelf implementation does it in less than 600ms even though it performs 3 additional `WHERE IN` queries.

I use `createConnection` before initialising the Koa application, and then `getConnection` in all route handlers. I tried the query also with the connection received in `createConnection` (just to see that getting a connection in the route handler would not be the cause), and the query took 890ms.

Bookshelf.js implementation:

```typescript
const bookshelfList: IMiddleware = async(ctx: IRouterContext) => 
  (new MainEntry())
    .query((qb) => {
      qb
        .leftJoin('second_entry', 'main_entry.id', 'second_entry.main_entry_id')
        .leftJoin('third_entry', 'second_entry.id', 'third_entry.second_entry_id')
        .leftJoin('fourth_entry', 'third_entry.fourth_entry_id', 'fourth_entry.id')
        .where({ owner_id: ctx.params.owner_id });
    })
    .fetchAll({
      withRelated: ['second_entry.third_entry.fourth_entry'],
      columns: [ 'main_entry.id', 'third_entry.a_column', 'fourth_entry.name' ]
    })
    .then((entries) => entries.toJSON())
    .then((entries: any) => ctx.body = entries)
    .catch(errorHandler);
```

TypeORM implementation:

```typescript
const typeormList: IMiddleware = async(ctx: IRouterContext) => 
  getConnection()
    .manager
    .createQueryBuilder(MainEntry, 'main_entry')
    .select([ 'main_entry.id', 'third_entry.a_column', 'fourth_entry.name' ])
    .leftJoin('main_entry.second_entry', 'second_entry')
    .leftJoin('second_entry.third_entry', 'third_entry')
    .leftJoin('third_entry.fourth_entry', 'fourth_entry')
    .where('main_entry.owner_id = :ownerId', {
      ownerId: ctx.params.owner_id
    })
    .getMany()
    .then((entries: any) => ctx.body = result)
    .catch(errorHandler);
```

Unfortunately I don't have really useful information on this, just reporting what I see. I am willing to debug this in case you have ideas on where to start looking.

There are 13M main entries in the database, 5000 of which match the query. Both implementations create similar SQL with the JOINs (since we use Knex QueryBuilder to construct the query), but as mentioned Bookshelf.js does 3 `WHERE IN` queries then to get second, third, and fourth level entries. We are actually going to be limiting the amount of items to fetch in single query so the impact will not be that much if any.

**Comment by pleerock** [comment]
You should not count `createConnection` at all since its not just creates a connection, it initialilzes the whole ORM. You must create a connection only once, during your app bootstrap and use created connection everywhere in your app during application lifecycle.  

Also TypeORM has much much more features then knex and its not just a query builder. QueryBuilder consider lot of other things including listeners, subscribers, caching, proper pagination, locking, etc.. But of course there are lot of room for optimizations, and Im sure we can improve this speed.

Now, specific to your problem. You told knex is doing 3 extra requests to get the data which should be slower as you believe. But in fact it maybe NOT slower. Why? Because as more nested joins you have and as more database data you have in nested rows as much data database will return you. Thats how relational databases work - they cannot return you an object, they return you data in a table format. But in table format to include nestings it uses duplication and multiple rows. Simple object may take you to return 100k rows if it has deep joins!!! 100k rows means more memory and time to transfer and parse the data. In most of times when you have nested joins its much more efficient to perform multiple requests instead of one. TBH I don't recommend you to use more then few levels of joins at all. And note, if you don't select the joined data it wont return you 100k rows lets say and won't work so slow.

To confirm what Im talking just run SQL query ORM generates for you - you'll see how many rows will be returned. Then execute 3 separate queries and see how many rows they will return and count them all. You'll see how huge difference is. More data is return to the client - more time it takes to send it to the client, parse it and store in the memory - yeah it may be a very consumptive process.

**Comment by vesse** [comment]
Yes, I only create the connection once and then use `getConnection` in the route handlers. I am under the assumption that `getConnection` does not initialise a new connection.

But, the left joins may indeed play a role here. Of the 5000 main entries all have a matching second entry, but only 900 have a matching row in third entry table.

The SQL query generated by TypeORM matches that of Knex:

```sql
SELECT 
  "main_entry"."id" AS "main_entry_id", 
  "third_entry"."a_column" AS "third_entry_a_column", 
  "fourth_entry"."name" AS "fourth_entry_name", 
FROM "main_entry" "main_entry" 
LEFT JOIN "second_entry" "second_entry" ON "second_entry"."main_entry_id"="main_entry"."id"  
LEFT JOIN "third_entry" "third_entry" ON "third_entry"."second_entry_id"="second_entry"."id"  
LEFT JOIN "fourth_entry" "fourth_entry" ON "fourth_entry"."id"="third_entry"."fourth_entry_id" 
WHERE "main_entry"."owner_id" = $1 ```

vs.

```sql
select
  "main_entry"."id",
  "a_column",
  "name" 
from "main_entry" 
left join "second_entry" on "main_entry"."id" = "second_entry"."main_entry_id" 
left join "third_entry" on "second_entry"."id" = "third_entry"."second_entry_id" 
left join "fourth_entry" on "third_entry"."fourth_entry_id" = "fourth_entry"."id" 
where "owner_id" = ?
```

which is the main reason I was not expecting this outcome. That is, Knex too receives the 5000 row result table and Bookshelf then performs the three additional `WHERE IN` queries.

**Comment by pleerock** [comment]
Okay, are you comparing timings of exactly same SQL query and difference with knex isnt small, then my answer is in orm complexity and other things that knex does not have. But of course there is a room for optimization.

One question, does knex transform your selecting data into some models? Or it just returns what it has selected from the database? Can you try to use `getRawMany()` instead of `getMany()` and compare timings ?

**Comment by vesse** [comment]
Yes, Bookshelf too converts the results to models (`Bookshelf.Collection<T extends Bookshelf.Model>)`, and I then call `toJSON` on the results when serialising to JSON response. 

With `getRawMany` the route handler execution time is only 56ms.

**Comment by pleerock** [comment]
> With getRawMany the route handler execution time is between 50 and 200ms.

we probably need a more precision numbers and what is exact execution time with knex? 600ms? If yes, then looks like we have 200ms with raw results vs 600ms with knex? 

are you able to contribute to improve orm performance? If yes, then it will be great if you debug execution times and find a bottleneck. If getRawMany works fast compared to getMany then problem may be inside `RawSqlResultsToEntityTransformer` class, however I don't see any high costly operation in there...

**Comment by vesse** [comment]
The 200ms raw result happens occasionally, generally the raw result of TypeORM is 50-80ms when repeating the request. I'm testing now with Postman application in Chrome so there's some HTTP server overhead too.

The 600ms was not with Knex raw result but when used with Bookshelf, ie. converted to models in between. I haven't tried with using raw Knex but based on previous experience I would expect it to perform somewhat similarly than TypeORM with raw result.

I will be going on a business trip and then a vacation, thus it's unlikely that I could debug this further in the next couple of weeks but I'll try to find time to do that once back. Thanks for suggesting to use `getRawMany`, in this case it is a working solution for us as the results are just passed on the the browser for rendering.

**Comment by pleerock** [comment]
Okay, but be careful - it may work for you, but it disables lot of useful typeorm features.

**Comment by pleerock** [comment]
I'll close this issue and please let me know if you have something to add. Btw we made a huge performance optimizations of `save` and `insert` methods in recent 0.2.0-alpha versions. You can see more details in #1115
