### ISSUE TITLE
Add SurrealDB support

### ISSUE THREAD

**Issue by John-H-Smith** [typeorm/typeorm#9953]
### Feature Description

I would highly appreciate if [SurrealDB](https://github.com/surrealdb/surrealdb) could be a supported DBMS as it is a really high scalable and performant database system.

### The Solution

Add SurrealDB as supported DBMS.

### Considered Alternatives

Currently, only native implementation is working as far as I know.

### Relevant Database Driver(s)

- [ ] aurora-mysql
- [ ] aurora-postgres
- [ ] better-sqlite3
- [ ] cockroachdb
- [ ] cordova
- [ ] expo
- [ ] mongodb
- [ ] mysql
- [ ] nativescript
- [ ] oracle
- [ ] postgres
- [ ] react-native
- [ ] sap
- [ ] spanner
- [ ] sqlite
- [ ] sqlite-abstract
- [ ] sqljs
- [ ] sqlserver
- [X] surrealDB

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by timyourivh** [comment]
I believe the Surreal team is willing to make this happen as they display a "Coming soon" entry for [NestJs](https://github.com/nestjs/nest) in their SDK section ([here](https://surrealdb.com/docs/integration/sdks) and [here](https://surrealdb.com/docs/integration/sdks/nestjs)). This may be related since [NestJs uses TypeOrm](https://docs.nestjs.com/techniques/database#typeorm-integration) to communicate with data sources.

**Comment by ibilux** [comment]
+1

**Comment by pawanrana1992** [comment]
+1

**Comment by marsenzakirov** [comment]
+1

**Comment by webtimo-de** [comment]
+1

**Comment by stim371** [comment]
Thank you for the request.

As we bring TypeORM back into active development, we have decided not to accept any new driver requests at this time. This allows us to focus on improving and supporting the core platform.

This issue will be closed for now, but will be labeled with "new driver" so it is easily findable in the future.
